### ISSUE TITLE
Typo in opf_parser.py

### ISSUE THREAD

**Issue by wrCisco** [Sigil-Ebook/Sigil#100]
Hi to all, I was wandering in the plugin system of Sigil and I found that in the opf_parser.py at the line 120 there is written "self.spine_ppd = tattr.get("page-progession-direction", None)". That missing "r" in progression makes the bk.getspine_ppd() return always None.
Also, in the ebook Sigil_plugin_framework is documented the function bk.setspine_ppd(), but in the bookcontainer.py the function is named setspineppd.
Thanks for the work you're doing.

**Comment by kevinhendricks** [comment]
Hi wrCisco,

Thanks!  If you want to create a pull request on github with your fixes, I would be happy to merge it so that you get credit.  OW. let me know and I'll make those fixes by hand.

KevinH

**Comment by wrCisco** [comment]
I made the pull request for the first correction. But I don't know how to do with the epub.

**Comment by kevinhendricks** [comment]
Hi,
No problems.  I actually want to change the code to match the documentation so that it is parallel in name to the getspine_ppd but I can do that in the wrapper.py and the bookcontainer.py

Thanks

Kevin

**Comment by wrCisco** [comment]
Ok, seems better to me too.
