### ISSUE TITLE
Cannot extract file: images/ epub seems valid.

### ISSUE THREAD

**Issue by HenningJW** [Sigil-Ebook/Sigil#104]
Hello,
I have a specific .epub file that I can't open with Sigil. I get the translated "Cannot extract file: images/" error message. However I can safely open the file with Winrar, SumatraPDF and Calibre epub viewer. After manually extracting the file, packing it as a zip with Winrar again and renaming the extension to .epub I can open the file without problems in Sigil. The Winrar test reports no errors in the epub. This problem exists on both, the latest version (0.8.7) and 0.7.4.

As I can't reproduce the error with a self generated file and the file has copyrighted contents I will edit the file out, once you have it. Please shoot me a message/answer here once you downloaded the file.

http://www26.zippyshare.com/v/zlOhxd6r/file.html

Thanks.

**Comment by kevinhendricks** [comment]
Downloaded it but the epub is simply bad.  

Here is what unzip -t (to test it) reports:

KevinsiMac:Desktop kbhend$ unzip -t Riley*.epub
Archive:  Riley, Lucinda - Die Mitternachtsrose.epub
    testing: content.opf              OK
    testing: cover.jpeg               OK
images/:  ucsize 816 <> csize 0 for STORED entry
         continuing with "compressed" size value
    testing: images/                  OK
    testing: images/00001.jpeg        OK
...
    testing: images/00022.jpeg        OK
META-INF/:  ucsize 102 <> csize 0 for STORED entry
         continuing with "compressed" size value
    testing: META-INF/                OK
    testing: META-INF/container.xml   OK
    testing: mimetype                 OK
    testing: page_styles.css          OK
    testing: stylesheet.css           OK
text/:  ucsize 2550 <> csize 0 for STORED entry
         continuing with "compressed" size value
    testing: text/                    OK
    testing: text/part0000.html       OK
    testing: text/part0001.html       OK
    testing: text/part0002.html       OK
…
    testing: text/part0072.html       OK
    testing: titlepage.xhtml          OK
    testing: toc.ncx                  OK
At least one warning-error was detected in Riley, Lucinda - Die Mitternachtsrose.epub.

So this is a won’t fix.

Kevin
