### ISSUE TITLE
Sort function

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#106]
Often I would like to sort a css file. Is a sort function something that could be easily added to Sigil?

**Comment by kevinhendricks** [comment]
Hi,

Sounds like something that could be easily implemented in a plugin.  If you are familiar with Sigil python plugin interface, it should be quite easy to do.  If not, you can ask on Sigil’s  Mobileread.com Forum and there are a number of plugin developers/authors that might be able to help.

Kevin

**Comment by mrprobert** [comment]
Cool. Thanks!
