### ISSUE TITLE
Better copy/paste support

### ISSUE THREAD

**Issue by agabrielluz** [Sigil-Ebook/Sigil#110]
Hi, there. I love this impressive tool. It's a lot better than most EPUB tools and I really appreciate your job. As for my issue, I'd like to be able to paste images (jpeg, png) directly on Sigil so that images are automatically imported on the Images section on the left menu.

**Comment by kevinhendricks** [comment]
Is there something wrong with using the File menu to add existing files like images.  AFAIK, the Qt browser widgets are not drag and drop aware.  This is not high priority but I will look at it after epub 3  support has been added.

Thanks

**Comment by kevinhendricks** [comment]
There is now a Sigil plugin which does this nicely for you that works with all clipboardson all os.  So closing this.
