### ISSUE TITLE
Cursor not showing correct form

### ISSUE THREAD

**Issue by CaptainOfTheTitanic** [Sigil-Ebook/Sigil#111]
In version 0.8.7 64 bit Windows 7 64bit the cursor does not show as an arrow on the scrollbar for the Book View although it is correct in the code view. The cursor shows as the text input I bar.

**Comment by kevinhendricks** [comment]
This is a Qt bug so please file a bug report there, but don't hold your breath as I have filed 4 different bugs reports with code to replicate them and no action after months and months.

Thanks,
