### ISSUE TITLE
Is there "Insert Table" function in Sigil?

### ISSUE THREAD

**Issue by benluo** [Sigil-Ebook/Sigil#122]
Some times, I want to insert a table in the document. It's really painful to edit table in raw html code.

**Comment by kevinhendricks** [comment]
Sorry,  Given not all ebook readers render tables well (or even properly on small size screens) creating a table so complicated it is hard to edit is probably not a good idea to begin with.

So this is not a new feature that is high on my priority list now.

Thank you for your interest in Sigil.

**Comment by ZehHa** [comment]
Well, more than one year later may be a bit late . But my suggestion: Just get any html wysiswig editor (my swiss knife tool is SeaMonkey), build your table, and copy the html code right into sigil. All the td and tr tags are on the right places.

Different approach to the problem: Create a jpg from your table and get this included into your ebook.

The best android ebook reader for tables in epub seems to be Moon+ reader so far.
