### ISSUE TITLE
Undo(Redo) is useless on BookView when I toggle the viewstate from BookView to Codeview and toggle back.

### ISSUE THREAD

**Issue by snolkmg** [Sigil-Ebook/Sigil#131]
Undo(Redo) is useless on BookView when I toggle the viewstate from BookView to Codeview and toggle back.
I'm sorry, I can't speak English well.

**Comment by kevinhendricks** [comment]
That is not a bug.  BookView has to copy its contents back to CodeView so that CodeView has any current changes.  Those two do not share a clipboard history as they store things in different formats, plain text vs html.  Once you are in Codeview, and invoke BookView, the reverse happens.

Sorry.

**Comment by snolkmg** [comment]
@kevinhendricks Thanks for your explanation ,I understand.
