### ISSUE TITLE
no longer possible to use system hunspell

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#132]
So, since 48ac7a67aacfd99b4b6a2e00bc6550ae7eaa178c I need to use the bundled hunspell.
I don't like it.

The commit message says `Install hunspell and gumbo shared libraries to <INSTALL_PREFIX>/lib/sigil so that they can be found by the plugin launchers via QCoreApplication::applicationDirPath()`.

Umh... Is there any chance to get it accomplished in some other way?

**Comment by kevinhendricks** [comment]
Hi,
Not really.  Sigil develops for Mac and Windows as primary platforms which both need and use the hunspell shared library.  Linux is a secondary platform we try to keep working. On Linux you can build without it (ie use your system hunspell with a few changes to the cmake process but most probably none of the plugins will be able to do spellchecking without some way for python ctypes code in the plugin to find where on your system your libhunspell.so is located.  Just check out the Linux build docs for more info on what cmake settings exist.  If you are a linux packager, why don't you just add a symlink to point where ever you normally keep libhunspell.so?

No code duplication and it all should work.

Kevin

**Comment by mapreri** [comment]
On Sat, Oct 10, 2015 at 12:39:30PM -0700, Kevin Hendricks wrote:
> Hi,

Hi Kevin!

> Not really.  Sigil develops for Mac and Windows as primary platforms
> which both need and use the hunspell shared library.  Linux is a
> secondary platform we try to keep working.

Yeah, nowadays I got this.  Though as you can guess we are really
interested in having a working sigil, but it's sometimes quite hard due
to the costraints we place on ourself, like avoiding bundled code
copies.

> On Linux you can build without it (ie use your system hunspell with
> a few changes to the cmake process but most probably none of the
> plugins will be able to do spellchecking without some way for python
> ctypes code in the plugin to find where on your system your
> libhunspell.so is located.

I figured.  It's just that the "you can build without it" requires local
patching ;)

> If you are a linux packager, why don't you just add a symlink to point
> where ever you normally keep libhunspell.so?
> 
> No code duplication and it all should work.

I'm a linux packager (for debian/ubuntu), indeed.
This can work indeed.  It's quite ugly but I can live with it.
Just it'll be funny since we do multiarch, and libhunspell.so is just a
symlink to a versioned lib...
lrwxrwxrwx 1 root root 18 Aug  4 22:20 /usr/lib/x86_64-linux-gnu/libhunspell.so -> libhunspell-1.3.so


I believe I'll go down this way I did not think about, I'll kindly ask
cmake to stop wanting so badly a local hunspell and do the symlinking.


Thanks for your support anyway! :)
-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by kevinhendricks** [comment]
Hi,

One other thing.  I am not sure how python 3 ctypes finds its locations to search for shared libraries, but have you tried it to see if it all just works as-is (after building against a system hunspell?  If you put your hunspell library in a standard location, ctypes findLibrary in python may in fact be able to find it just fine.

Just a thought?

Kevin

**Comment by mapreri** [comment]
I've yet to try doing something after I filed this bug, I'll tell you
once I have a chance to look at it.

**Comment by kevinhendricks** [comment]
ps...  to allow system hunspell again simply uncomment a few lines in the 3rdparty/CMakeLists.txt file and make sure you have USE_SYSTEM_LIBS set during cmake.  If it turns out python 3 ctypes findLibrary is smart enough to do the job, we can modify that CMakeLists.txt back to make things work for you out of the box.

**Comment by mapreri** [comment]
On Mon, Oct 12, 2015 at 01:01:36PM -0700, Kevin Hendricks wrote:
> One other thing.  I am not sure how python 3 ctypes finds its
> locations to search for shared libraries, but have you tried it to
> see if it all just works as-is (after building against a system
> hunspell?  If you put your hunspell library in a standard location,
> ctypes findLibrary in python may in fact be able to find it just fine.

Well, I don't know how to try it out in sigil (maybe you have a plugin
to suggest me trying out?), but if I spawn a python shell it works just
fine:

```
mattia@chase ~ % python3
Python 3.4.3+ (default, Oct 10 2015, 09:15:38) 
[GCC 5.2.1 20151003] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('hunspell')
'libhunspell-1.3.so.0'
>>> 
```

Note that in linux using the full path to a lib is usually not that
good since we do dynamic linking with everything possible.

-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-
