### ISSUE TITLE
allow configuring a directory from which load hunspell dictionaries

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#134]
In Debian we have a role to do not embed anything that is in another package.  This is true for hunspell dictionaries too.
Till the current stable there was a env variable usable to tell sigil where to look for hunspell dictionaries, and I added https://anonscm.debian.org/cgit/collab-maint/sigil.git/commit/?id=eef2181af4fe87fdd11f0c87a8cddddd092f250e to achive it nicely.

For now (still in a experimental branch) the only thing I could do is to add a symlink to that directory (which is imho less nice).

Would it be possible to re-add that "feature", or any other mean to specify a directory from where to look for dictionaries?  I'm ok also with build-time flags, and willing to write a patch for that if you tell me what you'd prefer.

**Comment by kevinhendricks** [comment]
Well, you will note that Sigil has its own highly modified version of google's gumbo parser (modified to support xhtml parsing, more tags recognized, and editing), and our own highly modified version of the BeautifulSoup4 python package (modified to fix bugs in builder/_lxml.py, add in real prettyprint, and rework the entire package to work under both python 2, and python 3, at the same time).  If you try to replace either of these with official versions Sigil will fail to work.

And no, neither project will want to upstream our changes as they are specific to mainly ebooks.

I will ask DiapDealer (he does all of the Linux dev work for Linux).  I know he pulled a bunch of build related stuff out to greatly simplify things.  To many linux distributions use too many different conventions, to make things work, disks are cheap, and embedding you own prevents breakage from updating shared libraies and things.  Too bad Linux does not have a true, sandboxed app container and some standard conventions to work with them.

We'll get back to you on the Linux front.

Thanks,

KevinH

**Comment by mapreri** [comment]
On Tue, Oct 13, 2015 at 04:00:02PM -0700, Kevin Hendricks wrote:
> Well, you will note that Sigil has its own highly modified version of
> google's gumbo parser (modified to support xhtml parsing, more tags
> recognized, and editing), and our own highly modified version of the
> BeautifulSoup4 python package (modified to fix bugs in
> builder/_lxml.py, add in real prettyprint, and rework the entire
> package to work under both python 2, and python 3, at the same time).
> If you try to replace either of these with official versions Sigil
> will fail to work.

yeah, I'm very well aware of this, sadly.  But I'm already happy enough
all the stuff in 3rdparty can be replaced by system/vendor provided
ones.
Please continue to work like this, because the tred you follow was:
1) actually reduce bundling
2) actually improving sigil
:)

> I will ask DiapDealer (he does all of the Linux dev work for Linux).
> I know he pulled a bunch of build related stuff out to greatly
> simplify things.

And I'm actually happy about this.  Indirectly thanks to all those
semplification I could drop most of our patches to get it build & work.

> To many linux distributions use too many different conventions, to
> make things work, disks are cheap, and embedding you own prevents
> breakage from updating shared libraies and things.

I fully understand your point.
Updating libraries is never easy.  We have our own way to do libraries
updates, with rebuilding everything, etc, but not always is easy, and
quite often stuff breaks.

> Too bad Linux does not have a true, sandboxed app container and some
> standard conventions to work with them.

Not sure I'd happy.  Having up-to-date libraries which are used by all
applications is also nice some times.  Just think what would happen if
every qt app embeds a full QT stack.
Anyway, they're coming too!

> We'll get back to you on the Linux front.

I'm not asking to rewrite your entire build system or something, and I'm
fully open to compromises :)

Thanks you for keeping sigil a living thing!
-- 
regards,
                        Mattia Rizzolo

GPG Key: 66AE 2B4A FCCF 3F52 DA18  4D18 4B04 3FCD B944 4540      .''`.
more about me:  http://mapreri.org                              : :'  :
Launchpad user: https://launchpad.net/~mapreri                  `. `'`
Debian QA page: https://qa.debian.org/developer.php?login=mattia  `-

**Comment by dougmassay** [comment]
Hey Kevin and mapreri,

I see where/when the SIGIL_DICTIONARIES env var went by the wayside. It wasn't my doing, but I'll see what I can do to put the functionality back. There's an additional new twist with plugins that can access those same dictionaries that may have to be accommodated as well.

Thanks for the heads up on this,
Doug

**Comment by dougmassay** [comment]
mapreri,

Please let me know if the changes in [this recent commit](https://github.com/Sigil-Ebook/Sigil/commit/fcd8cb1b261fbe1be97ce9820780a178eae40594) restores the functionality you requested (RE the environment vairiable SIGIL_DICTIONARIES). If so, I'll close the issue.

Thanks,
Doug

**Comment by mapreri** [comment]
On Thu, Oct 15, 2015 at 04:37:20AM -0700, Doug Massay wrote:
> Please let me know if the changes in [this recent commit]
> (https://github.com/Sigil-Ebook/Sigil/commit/fcd8cb1b261fbe1be97ce9820780a178eae40594)
> restores the functionality you requested (RE the environment vairiable
> SIGIL_DICTIONARIES). If so, I'll close the issue.

Yeah, it does pretty well :)
I tested it and it works fine.

Thanks for everything!

**Comment by dougmassay** [comment]
No problem. Happy to help! I'll be closing this issue then
