### ISSUE TITLE
Date picker uses two digit year

### ISSUE THREAD

**Issue by marcuserronius** [Sigil-Ebook/Sigil#136]
It is impossible to enter certain dates in the metadata window, since the date picker uses a two-digit year. For example, when changing a publishing date to 1940, you enter 1/1/40, and when you look at the "content.opf" file, it says "2040-01-01".

This could solved by switching to a four-digit year, or by allowing the user to input a raw value, like "1940-01-01"

**Comment by kevinhendricks** [comment]
The whole metadata gui will have to be reworked anyway to enable epub3 metadata.  Until then, please simply edit that metadata item by opening the content.opf in a tab, and correcting it there.

Thanks for the head's up.

KevinH

**Comment by kevinhendricks** [comment]
New metadata editor gui just added.  Closing this issue as fixed.  The fix will appear in the next release of Sigil.
