### ISSUE TITLE
Date picker in metadata window requires month and day

### ISSUE THREAD

**Issue by marcuserronius** [Sigil-Ebook/Sigil#137]
The date picker in the metadata window requires specificity in days. The actual metadata supports granularity options, allowing one to specify only a year ("2015") or the month ("2015-07"). This is especially useful for older works where we don't know the exact publishing date, just the year (and possibly the month).

The easiest way of fixing this might be to allow editing the date as an unparsed string, but I don't know.

**Comment by kevinhendricks** [comment]
Simply edit the date directly in the fontent.opf tab, until a full gui redesign is done to support epub3 new metadata.

Thanks,

Kevin

**Comment by kevinhendricks** [comment]
New metadata editor just added.  Closing this issue.  The new editor will appear in the next Sigil release.
