### ISSUE TITLE
Menu bar disappeared

### ISSUE THREAD

**Issue by capiscuas** [Sigil-Ebook/Sigil#146]
Version: 0.8.2-1~trusty+1
I realized that my Sigil has no Menu bar and I can't find a way to show, no shortcut key to Preferences or anything to check how to get it back. Thanks for any feedback!
![image](https://cloud.githubusercontent.com/assets/515154/10838818/924a46a0-7efe-11e5-9436-288e4ac96874.png)

**Comment by capiscuas** [comment]
I tried to remove the Sigil data configuration files.
$HOME/.local/share/sigil-ebook/sigil

but the menu bar still not appearing.

**Comment by capiscuas** [comment]
New discovery: If I run sigil as sudo user the menu bar appears(not sure if my default user is using a wront qt version, not 5, don't know how to check).

In the about window of Sigil I can see root mode uses:
Loaded Qt: 5.2.1

**Comment by kevinhendricks** [comment]
Hi,
FYI, that build of Sigil quite old now and is not an official release of ours so there is not mch we can do to help.   The current Sigil release is Sigil-0.8.901 and it uses an official  Qt 5.4.2 binary.   I have never seen the behaviour you describe, but if changing the user impacts things, then there are probably Qt or Desktop related environment variables impacting things.  What Desktop are you using, KDE? and what version?  What theme?  Does the issue go away if you try a different Desktop or a different theme?  You could try unsetting your Desktop and Qt related environment variables until you see what causes the issue and then report your findings to your internal package maintainer.

KevinH

**Comment by kevinhendricks** [comment]
Closing this as I can not recreate this at all.  If you can figure anything out about its cause, please re-open and post it here for others to find if needed.

**Comment by eli-schwartz** [comment]
I think your problem is that you are using the entirely disgusting Unity desktop by Ubuntu. :wink:
The "issue" you encountered is a "feature" of your distribution.
The same feature FWIW that finally sent me screaming away from anything Canonical Inc.

Like OSX, it uses a global menubar.
Which hides itself unless you are hovering over it.
Although I heard they recently moved the menubar back to where it belongs -- the application window -- it's still hidden unless you hover over it.


One possible solution is to switch desktops -- I suggest Linux Mint/Cinnamon. :+1:
Or resign yourself to an interface that tries to imitate a Macbook (I will refrain from sharing my **personal** feelings about OSX interface design), and then does it badly.

**Comment by toddcarnes** [comment]
You are exaggerating.

Lubuntu doesn't use unity and works just fine. Same thing with Xubuntu,
Kubuntu, etc.

While I agree that Unity sucks, you certainly don't have to leave Ubuntu,
just to get away from it.

**Comment by eli-schwartz** [comment]
And you can use Linux Mint's Cinnamon on Ubuntu. Yes, I know that too. :smile:

As for me, it was the straw that broke the camel's back. I don't want to use anything that Canonical had to do with. It was one of the factors that encouraged me to move to ArchLinux, which for a variety of reasons made me happier.
I'm not saying anyone else has to make the same decision...

**Comment by capiscuas** [comment]
Thanks for the comments. Actually is quite extrange. My default desktop in Ubuntu was Metacity (the one not showing the menu bar in sigil), so I came back to the default Ubuntu desktop unity and now it works. :+1:  , so it's probably not sigil related but desktop related. Nevertheless I missed some debug options in sigil to find out faster what happened, for example:

- a shortcut key to the About menu of sigil to findout what QT and desktop am I using.
- some --about or --version or --debug parameter in the sigil executable to be able to get environment info in the commandlne before the qt interfaces appear.


![image](https://cloud.githubusercontent.com/assets/515154/10877940/2dbd008e-817d-11e5-9149-425c0df5992a.png)

**Comment by eli-schwartz** [comment]
You can modify the launcher script to call **gdb** /usr/lib/sigil/sigil if you need debugging info.

Sigil AFAIK has no idea what desktop you are running, but that should be evident anyway.
If you are using the distro-packaged version of sigil, you are using the distro-packaged version of Qt5 as well.
