### ISSUE TITLE
BookView hooks for CTRL+V (Shift+Insert) vs. Context Menu -> Paste

### ISSUE THREAD

**Issue by calaba** [Sigil-Ebook/Sigil#149]
In BookView -> there is the functionality that in case HTML code is being pasted from clipboard you will get a popup asking whether you wanna paste this as plain text instead of HTML (to remove incompatible HTML formatting). This extension was proposed by me few years back - see https://code.google.com/p/sigil/issues/detail?id=2423 (or https://github.com/calaba/Sigil/commit/2ad11820bd7b70e990531d3c70b15fa0d8d6da33 ).

I just realized that this feature is not working in both current releases - MacOS X and Windows .

How to reproduce:

1) Copy to clipboard some part of HTML formatted text (i.e. from internet browser)
2) Switch to Book View in Sigil
3) Try to paste the clipboard text from Step 1 - if you use paste keyboard shortcut in Book View (CTRL+V or COMMAND+V) it pastes the HTML code without asking you(without showing the decisinion dialog box)  - but if you use the context menu (Right Click -> Paste) or Application menu Edit->Paste then it is working correctly and dialog window is shown to make a decision whether you wanna paste just the text (default) or the entire HTML formatted content.

**Comment by kevinhendricks** [comment]
Sorry this works just fine for me on Mac OS X.  Try copying a piece from CodeView and then pasting it into the BookView window using the menus.  It shows the changes you requested long ago (i.e. the message box asking if you want to paste as plain text).

Then try the same thing with your key sequences for paste and it still does what you expect.  If the former works and the latter does not, please make sure your Keyboard assignments in Sigil Preferences are set properly.

Kevin

**Comment by kevinhendricks** [comment]
Hi,

I take that back.  It seems to be inconsistent.  It worked for me just fine and now does not seem to be working (this is Mac OS X), then it started working again then it stopped.  It seems there is some issue with Qt 5.4.2 as this code has not changed at all since user_none modified and merged your pull request.

I will search the Qt bug database to see if anyone else has reported this.  Your code is still there, but some times the shortcuts are being recognized and sometimes not.

**Comment by calaba** [comment]
For me - on both Windows 7 64-bit and MacOS X 10.10.5 - Control/Command+V never shows the dialog ...

**Comment by kevinhendricks** [comment]
Hi,
I added some qDebug() output and it shows that the QShortCuts created for paste (and PageUp/PageDown) never seem to fire consistently under Qt 5.4.2 and even earlier versions of Qt 5.  I can work around this with a keyPressEvent handler in BookViewEditor.cpp/.h but the bug appears to be in Qt.  I will search the Qt archives to see if this has already been reported.

Thanks for your report.

Kevin

**Comment by calaba** [comment]
You are welcome, thanks for debugging the problem.

**Comment by kevinhendricks** [comment]
Just committed a workaround into master for the Qt5 bug in QShortCut never activating
This bug fix will appear in the next Sigil release.
Closing this.

Thank you for your bug report.
