### ISSUE TITLE
Metadata editor in 0.8.901 doesn't handle <>& properly

### ISSUE THREAD

**Issue by chrisridd** [Sigil-Ebook/Sigil#150]
Starting with a new document:

* Using the metadata editor to set a title `Foo & Bar` results in an OPF with `<dc:title>Foo & Bar</dc:title>`

* Using the metadata editor to then set the description to `<p>Baz</p>` results in an OPF with `    <dc:description><p>Baz</p></dc:description>`. Also the title is now `Foo  Bar` with 2 spaces.

**Comment by dougmassay** [comment]
The metadata editor doesn't automatically convert stuff to entities for
you. Perhaps we can look into it for the future, but for now, you'll need
to enter that sort of thing the same way as if you were manually editing
the opf. Meaning you can't enter ampersands and html tags for metadata.
Only xml safe entities can be used. You'll need to enter "Foo &amp; Bar"
and &lt;p&gt;Baz&lt;/p&gt;

Perhaps we'll look into automatically xml-escaping things when we get EPUB3
metadata editing working, but for now, you'll have to make sure metadata is
xml-safe yourself--weather you use the editor or you edit the OPF manually.

**Comment by chrisridd** [comment]
I'm almost certain older Sigils (before your big recent rewrite) automatically managed entities in the metadata editor - I don't have many authors etc with ampersands (I noticed this just now with a publisher value of `Simon & Schuster`) but certainly HTML markup in the description value was escaped automatically.

This seems like a regression. As you say there's a workaround.

**Comment by dougmassay** [comment]
It definitely could be a regression. I'm not certain. I don't use the metadata editor to be perfectly honest. I'm just saying we have to overhaul the metadata editing process to accommodate epub3 anyway, so it's not likely to be addressed before that happens.

We'll definitely keep this issue open to remind us about it, though. Thanks for the report.

**Comment by chrisridd** [comment]
Thanks Doug!

**Comment by kevinhendricks** [comment]
Closing, as a fix for this was committed to master yesterday and will be in the next release.
Thank you for your bug report!
