### ISSUE TITLE
Support for EPUB 3 Media Overlays metas in OPF

### ISSUE THREAD

**Issue by pettarin** [Sigil-Ebook/Sigil#162]
(Just opening this issue as it seems to me that it is not addressed in 0.9.0, feel free to correct me.)

In addition to what discussed in #148 w.r.t. the relative paths of XHTML, SMIL and audio files, I would like to mention that if an EPUB 3 has Media Overlays, some metas in the OPF file are mandatory, e.g.:

```
<meta property="media:duration" refines="#s001">00:15:07.260</meta>
<meta property="media:duration" refines="#s002">00:01:00.000</meta>
<meta property="media:duration" refines="#s003">00:01:00.000</meta>
<meta property="media:duration">00:17:07.260</meta>
```

where the "refined" metas point to the `id` attributes of the manifest `<item>`s representing the SMIL files, while the "unrefined" meta is the sum of the refined one.

Moreover, usually the OPF also has the following optional metas:

```
<meta property="media:narrator">Narr Ator</meta>
<meta property="media:active-class">css-class-name</meta>
<meta property="media:playback-active-class">css-another-class-name</meta>
```

**Comment by kevinhendricks** [comment]
Sigil 0.9.0 is not epub3 capable yet.  It is our **goal** for the future.  Only the most basic epub3 will survive simple editing in Sigil-0.9.0 at this point.   We will slowly evolve to add more and more epub3 support without hurting epub2 editing.   Our planned next step is to support epub3 metadata editing via a gui.  Closing this
