### ISSUE TITLE
Just a feature request

### ISSUE THREAD

**Issue by beautebook** [Sigil-Ebook/Sigil#168]
Hi there, thank you for the great work, Sigil is an awesome tool.
I would like to suggest that the spellchecker window indicated the total number of errors. It would be nice too that it identified words that are not mispelled but split (with a space somewhere inside).
Thank you!

**Comment by kevinhendricks** [comment]
Spellchecking is designed to run in the background and so total errors at any one point in time do not make much sense in that they have no meaning.  Also, I do not understand your second request.  
You actually want the spellchecker to identify correct words?  

FYI, the use of a space to separate words that are valid with or without the space is language determined.  If hunspell affix file determines which characters should be considered parts of words for each language and what characters should be inserted to attempt to generate suggestions.
