### ISSUE TITLE
serialize_xhtml() and empty elements: Book View complains about malformed XHTML

### ISSUE THREAD

**Issue by pettarin** [Sigil-Ebook/Sigil#169]
I am running Sigil 0.9.1 (official release) and building a custom edit plugin.

I have a problem with switching from Code to Book View on a XHTML file, after my plugin changed its source. The edit has been done by `gumbo_bs4` (as in ePub3-itizer), and the data bytes were obtained by `soup.serialize_xhtml()`. (The same issue occurs with `soup.prettyprint_xhtml()`.)

XHTML source before calling the plugin:

```
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <link href="../Styles/Style0001.css" type="text/css" rel="stylesheet" />
</head>

<body><p>Some text</p></body>
</html>
```

Calling the plugin (hence, `soup.serialize_xhtml()`), I get an "Incorrect XHTML/XML Detected. Are You Sure You Want to Continue?" warning. Answering Yes yields the following:

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
 "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <link href="../Styles/Style0001.css" rel="stylesheet" type="text/css"></link>
</head>
<body>
  <p class="mo" id="f000001">Some text</p>
</body>
</html>
```

Note the `<link ...></link>`. Now, if I switch to Book View, I get the "The operation you requested cannot be performed because p001.xhtml is not a well-formed XML document" etc.

Changing `<link ...></link>` to `<link .../>` fixes the issue.

The issue can be reproduced with other empty elements, like `<br/>`. (BTW, it even gets worse in this case, since the `<br></br>` is changed (by "Fix automatically") into a `<br/><br/>` instead of a single `<br/>`.)

I see in the changelog that in v0.9.2 you modified `serialize_xhtml()` and `prettyprint_xhtml()`: is this issue still standing?

**Comment by pettarin** [comment]
Compiled from source v0.9.2, the issue seems solved. Closing.

**Comment by dougmassay** [comment]
Are you sure? I'm still seeing the issue with serialize_xhtml(), although not with prettyprint_xhtml() using 0.9.2's code.

**Comment by pettarin** [comment]
You are right, in v0.9.2 the issue is still present using `serialize_xhtml()`, but not with `prettyprint_xhtml()`. Reopening.

**Comment by kevinhendricks** [comment]
Just committed the fix to sigil_bs4 serialize_xhtml that I had done for prettyprint_xhtml to use VOID_TAGS to classify if element is supposed to be serialized as void (self-closing).
You should be good to go.

**Comment by kevinhendricks** [comment]
Closing this as fix is in place for the next release.

**Comment by pettarin** [comment]
Apologies, I could fetch and compile only today. I confirm the issue seems solved. Thank you.
