### ISSUE TITLE
EPub Won't Open in Newest Kindle Previewer

### ISSUE THREAD

**Issue by donnabet** [Sigil-Ebook/Sigil#172]
The new previewer was just updated today.

I tried to open a finished book into the previewer and it failed to compile.

Error message below:

Kindle preveiwer failed to compile ebook.

*************************************************************
 Amazon kindlegen(Windows) V2.9 build 1029-0897292 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2014 
*************************************************************

Info:I9026:option: (hidden) amazon creator tool or pipeline

Info:I9014:option: -verbose: Verbose output

Info(prcgen):I1048: Unpacking ePub file

**Comment by dougmassay** [comment]
There is no guarantee that you can't create an epub that Kindlegen won't like. Did the exact same unmodified epub compile OK in the older version of Kindle Previewer?

**Comment by donnabet** [comment]
I tool it into Calibre and converted to a mobi file.  At least I got it to work.  Great program Sigil.  I love it.


Thanks for the quick response.


TechsChoice and WizardVisions


________________________________

**Comment by dougmassay** [comment]
It occurs to me that there was an issue with the third-party Epubcheck Sigil plugin that may have caused some structural  problems with epubs saved after using it. Do you, by any chance, use that plugin?

http://www.mobileread.com/forums/showpost.php?p=3233358&postcount=76

**Comment by donnabet** [comment]
I do not have it.  I am new to Sigil, but I can tell you that I have tried every combination of ebook publishing InDesign, Word, OpenOffice, GoogleDocs, KindleGen, etc and the first thing that has actually worked the way I need it to is Sigil.  Except, of course, for the last little bit of getting the epub to compile on the kindle previewer.


I am aware that there are plugins, but I have not looked into them yet.  Where do I find the plugin?  I looked on the github page again and did not see where to get plugins.


Thanks.


TechsChoice and WizardVisions


________________________________

**Comment by arthurattwell** [comment]
@donnabet Apologies if this is a silly suggestion: sometimes when I get that error on Kindle Previewer, simply retrying works (that is, drop the epub into Previewer again). I've not investigated why this is the case.

(Incidentally, I've also found that the Pagina EPUB-Checker sometimes finds problems in my epub files that Sigil's validation doesn't find, though I've not found any connection between those issues and errors with Kindle Previewer.)

**Comment by kevinhendricks** [comment]
This really is not an bug unless Sigil has somehow introduced the breakage and flightCrew and epubcheck show the epub as valid.  Sigil, like any editor, will not prevent you from creating a non-valid epub, that is up to the author to validate their own epub using the validation plugins or external validation tools.    If you have not used plugins with Sigil that means you have not validated with FlightCrew or EpubCheck plugins.  So I am closing this issue.  Please re-open it if you can provide a sample epub 2 that  you have created that passes epubcheck and flightcrew that KindlePreviewer will not accept.

**Comment by donnabet** [comment]
I am not aware of plugins.  Where do I get the plugins?  Thanks for your response.



TechsChoice and WizardVisions


________________________________

**Comment by kevinhendricks** [comment]
The link to the flightcrew validation plugin can be found under releases in this very github site.  Links to it also appear on sigil-ebook.com.  See our ReadMe on this site. (Where exactly did you download Sigil from?  If you have not downloaded from an official site or in case of Linux an official distribution site, you have probably downloaded more than you bargained for!).  The link to other plugins can be found on our Mobileread support site here.  

http://www.mobileread.com/forums/showthread.php?t=247431
