### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#175]
sigil uses Python 3.4 for external plugins, and it expects it in quite some places.
Now, the first stable release of Python 3.5(.0) has been around since September 2015, and the major linux distributions are migrating to it.  Debian already did the default switch and Ubuntu is near it.

I tried to build sigil against libpython 3.5 but my test build segfault on start (didn't investigate further).
I'm also worried about how plugins could move on to the next python versions (which change fairly often).

Do you have plans on supporting python 3.5?

**Comment by dougmassay** [comment]
No plans to support Python 3.5 until such time as Qt5 has a pre-compiled
version built with VS2015 (since Python 3.5 for Windows is built with
VS2015). But having said that, I see no reason why it wouldn't successfully
build/run against 3.5 on Linux.

**Comment by kevinhendricks** [comment]
Hi,
At one point in Sigil we had commits and had run on python3.5 briefly, but not for a release build.  I will look to see if the commits are still in the history to give you some idea of simple it should be on Linux and MacOSX.  Windows compiler versions, as DiapDealer has pointed out are what are holding us back.  For Windows, we need both Qt, and Python, and of course Sigil all built with the same compiler.

As I remember, the changes are minor and everything should work.

KevinH

**Comment by eli-schwartz** [comment]
As an Arch Linux user, I want to know what I am doing wrong, if Sigil works fine for me on python3.5 even though you say it shouldn't. :confused: 

Arch Linux has only been on python3.5 since about October I think... :grinning:

**Comment by mapreri** [comment]
Indeed it works.  I should stop doing this things in the middle of the night... sorry.
I was running it inside a chroot, and there it segfaults, but I'm going to guess that's not a real problem, and I'm not going to nag about it :)

Anyway, do you have a pointer about those commits?  a quick `git log --oneline|grep -i python` didn't reveal anything relevant.

And OK about windows.  I hope Qt people will release a build soon....

Thanks for you quick replies.

**Comment by kevinhendricks** [comment]
Hit commits and this site and go back to September 16 of 2015.  You will see a sequence of commits that moved from Python 3.4 to Python 3.5 and then back to Python 3.4.  Most of them are Windows and Mac OS X specific but at least you can see what all was touched.  Not much fundamentally.

**Comment by mapreri** [comment]
Ok, I found them.
Most of the changes are doc-related, the rest are not relevant on linux indeed.
Actually the change
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -73,8 +73,8 @@ if (USE_SYSTEM_LIBS)
         pkg_check_modules( PCRE libpcre16 )
     endif()
 endif()
-find_package(PythonInterp 3.4)
-find_package (PythonLibs 3.4)
+find_package(PythonInterp 3.5)
+find_package (PythonLibs 3.5)
 
 # gumbo-parser it is our main xhtml/html5 parser.
 # We have an internal version because it diverges from Google's and GitHub's
```
should be relevant, but seems like it picks 3.5 by itself anyway..

I can consider this closed.  Thank you very much for your support.
