### ISSUE TITLE
Feature Request: Hotkeys and Accelerators for File/Add Blank <type> File

### ISSUE THREAD

**Issue by kyanha** [Sigil-Ebook/Sigil#177]
I'm trying to create workable ePub files of books that were distributed as single HTML files (and, in one case, as a single XHTML file within an ePub, with no chapter links indexed).

I'd like to be able to organize these into more professional forms, if only for my own perusal.  Sigil provides a means of doing so, so thank you for creating and maintaining it.

However, it's rather annoying to have to take my hands off the keyboard or do longer, complicated chords (alt+f, d, down, enter) to be able to create a new HTML file within the book's structure.  (If I wanted to learn Emacs-like keybindings and chordings and key progressions, I'd probably be using Emacs.)

So, I'd like to suggest the following accelerators be added to the File/Add/ menu:

X for Existing Files
H for HTML File
S for Stylesheet
I for SVG Image

In addition, I would like to suggest the following hotkeys be added to the menu options on that menu:

Alt+Shift+X for Existing Files
Alt+Shift+H for HTML File
Alt+Shift+S for Stylesheet
Alt+Shift+I for SVG Image

I understand that these menu options are likely not on your perception/conception of the most common uses of Sigil, and thus probably intentionally didn't have hotkeys assigned to them.  However, I do think that Sigil is the best option available for editing monolithic HTML into multi-chapter epub, and this would make the use of Sigil that much easier by those who use it for such.  (At the risk of sounding selfish, it would certainly make it easier for me to use it for such. :))

Thanks for the time you've already spent creating and improving Sigil, and for your time and consideration of this request!

**Comment by kevinhendricks** [comment]
Hi,

You do know that there is a simple way to add split markers (either in  CodeView or BookView) that once set, will split the file into many pieces **automatically** updating all of the internal links properly including the NCX.  There are also tools for creating an html table of contents, setting semantics on file, renaming and renumber ing files, etc.

So if you are going about these tasks manually, you are probably missing the whole point of Sigil.

Kevin

**Comment by kevinhendricks** [comment]
Also you can use the preferences to assign accelerator keys to most menu functions.  Your use case should really be using the split markers and splitting the files instead of repetively adding empty xhtml files and copy/pasting sections from other xhtml content in it.

Closing this issue.  I may rebisit it in the future but given other Sigil tools can do what you want more effectively, this is not a priority for Sigil.
