### ISSUE TITLE
Compilation issue with latest 0.9.3 release

### ISSUE THREAD

**Issue by david-geiger** [Sigil-Ebook/Sigil#178]
Hi,

When I tried to compile sigil-0.9.3 I get an error from %install section:

Compiling /home/david/mgarepo/sigil/BUILDROOT/sigil-0.9.3-1.mga6.x86_64/usr/share/sigil/python3lib/updatechecker.py ...
  File "/usr/share/sigil/python3lib/updatechecker.py", line 2
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by dougmassay** [comment]
I can't begin to understand what's going on there. First of:f the "from future" imports ARE at the beginning of that script. Second: Sigil's build/install process doesn't check the syntax of Python scripts. It just copies them to their destination. At what exact point do you get that error?

What instructions are you following to build, and what are building on?

**Comment by david-geiger** [comment]
Oh sorry my bad !!!

I used a wrong macro in %install section from spec file: 

find %{buildroot} -name '*.py' -exec sed -i -e 's|#!/usr/bin/env python||g' {} \;

This has deleted "#!/usr/bin/env python3" and replace for "3" in python files :(

**Comment by dougmassay** [comment]
Closing

**Comment by eli-schwartz** [comment]
**Don't** use macros to "fix" the shebang lines for packaging purity.

From what I can see Sigil already has the appropriate shebangs on all its *.py files (`/usr/bin/env python` for py2&3 modules, `/usr/bin/env python3` for py3-only modules).
