### ISSUE TITLE
EPUB3-Support?

### ISSUE THREAD

**Issue by ITfee** [Sigil-Ebook/Sigil#181]
In an old FAQ (see http://web.sigil.googlecode.com/git/files/OEBPS/Text/faq.html) I found this:

> Does Sigil Support EPUB 3?
> 
> Sigil is an EPUB 2 editor and does not currently support all the features of EPUB 3. However it does support audio and video files which are the most often requested parts of EPUB 3, and does allow you to preserve EPUB 3 tags. A future version may support EPUB 3, but EPUB 3 ereaders are not common yet, even though some ereaders support certain parts of EPUB 3.

Is this still up-to-date for the current version (0.9.3)? If yes, when will Sigil fully support EPUB3?

**Comment by kevinhendricks** [comment]
That website is old and not under my control.  All information about Sigil and what parts of epub3 Sigil-0.9.3 now supports is posted in the release notes here and on sigil-ebook.com.
