### ISSUE TITLE
(Corrupted?) otf fonts crash Sigil without an error message.

### ISSUE THREAD

**Issue by HenningJW** [Sigil-Ebook/Sigil#183]
I have a file that crashes Sigil when it is opened. I narrowed the problem down to what I believe are corrupted otf fonts. Once I remove the fonts everything is opened fine. It would be nice if Sigil could just ignore the broken fonts and display an error message (or at least display a relevant error message and not open the file).

I stripped all text and uploaded the file, so it should be even fine from a copyright point of view: http://www82.zippyshare.com/v/754cOiNr/file.html

edit: Apparently this also happens when I replace the fonts with non broken fonts from http://www.linuxlibertine.org/index.php?id=91&L=1 here is the file with replaced fonts: http://www95.zippyshare.com/v/AoqkkOPp/file.html

**Comment by kevinhendricks** [comment]
Broken fonts will crash Qt the main gui application that Sigil is built with.  Improperly obfuscated fonts are a particular problem.  Short of adding our own font-validator to check each font, this is not something we can deal with.  If you set Sigil to open in CodeView (and not BookView) and turn off Preview, you should be able to open the epub enough to remove those bad font files as only BookView and Preview should load the font resources.  Please file a bug with the software that created the broken font files.

**Comment by HenningJW** [comment]
I am not sure if you have read my edit, I did not expect you are that fast. This happens also with the linuxlibertine font downloaded from the official site, I don't except that to be broken (although I am not sure). Opening it in CodeView doesn't help, it still crashes, but deleting fonts out of the zip works.

Thanks for your answer.

**Comment by kevinhendricks** [comment]
Fonts are not corrupted.  They are fine.  But whomever created that epub messed up.  There is an encryption.xml file in the META-INF folder that specifies that the fonts are obfuscated using the Adobe font obfuscation method.  That obfuscation method (and the IDPF method) both are based on the book unique-identifier as specified in the content.opf in the package tag.

Your package tag in the content.opf shows the following:
 unique-identifier="uuid_id"

but if you go to that metadata entry you will see that no proper uuid is provided:
```
<dc:identifier id="uuid_id" opf:scheme="uuid">urn:uuid:</dc:identifier>
```

This causes a problem in Sigil as it sees the prefix of the urn:uuid: key but no actual uuid value is there with which to unobfuscate the fonts.  The right way to handle this is to start with unobfuscated fonts.  Then add them using calibre or Sigil and they will properly create a uuid unique-identifier and will use that to properly obfuscate the fonts.

I can try to make sure that Sigil does not barf when when the identifier is present but broken.  We handle the missing case just fine.

**Comment by kevinhendricks** [comment]
Just committed a fix to prevent the crash from improper/missing obfuscation keys.  The fix will appear in the next release.  Closing this issue.
