### ISSUE TITLE
MARC relator list update/refresh

### ISSUE THREAD

**Issue by mihailim** [Sigil-Ebook/Sigil#185]
Now that the MARC relator list has been factored out into a separate class, it might be a good time to update it so that it conforms to the current authoritative list maintained by the LOC.

The canonical URL for the complete list is: http://www.loc.gov/marc/relators/relaterm.html

This refers to both the codes and terms as such (for example, the current MARC list no longer has a "Recipient" term and mentions that one should use the "Addressee" term instead but using the same code, `rcp`) as well as the descriptions. There are also missing terms, for example "Appellant", "Appellee", etc.

`MarcRelators::SetRelatorsMap()` mentions `    // These descriptions fixed, standard EPUB descriptions and should not be changed` , but that's misleading. The descriptions seem to come from the OPF 2 spec at http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.2.6 , but that section explicitly states (emphasis mine):

> For convenience, **some** relator code values are listed here **as examples**. Consult the MARC code list cited above for the complete list.

The spec-listed descriptions themselves are in no way normative; instead, the MARC relator list definitions are. The examples aren't even being listed any more in the 3.0.1 spec: http://www.idpf.org/epub/301/spec/epub-publications.html#sec-meta-elem

The existing descriptions (i.e., term definitions) also all start with "Use for ", which is redundant in this context. The definitions on the MARC site have evolved as well to cover more use cases--for example, some list "family" in addition to "person or organization".

I am aware that changing the descriptions has implications for the translations, though. If that's undesirable for the moment, we could leave the existing ones be and just add missing relator terms using the definition from the MARC site, and see how it goes.

I volunteer to write, test and submit a patch for this (it's fairly trivial), but wanted to first sound people out on whether it would be welcome :)

**Comment by kevinhendricks** [comment]
closed since your pull was merged.
