### ISSUE TITLE
No separating lines between code

### ISSUE THREAD

**Issue by jafprrr** [Sigil-Ebook/Sigil#188]
In previous versions of Sigil, there were separating lines between most lines of code, which made the code easier to read.

Now all the code is smooshed up together.

Is there a workaround that automatically separates those lines of code?

**Comment by dougmassay** [comment]
The feature is still there, Sigil just doesn't automatically make code "pretty" any more (over and over and over). You have to ask Sigil to do it. Tools->Reformat HTML->Mend and Prettify (I forget the exact wording offhand) to prettify all HTML files. Tou can right-click on Code View to do the same for individual Files if you choose.

**Comment by kevinhendricks** [comment]
closing this as not a bug
