### ISSUE TITLE
Well-Formed Check doesn't notice redundant images

### ISSUE THREAD

**Issue by jafprrr** [Sigil-Ebook/Sigil#189]
When you do the Well-Formed Check, it doesn't pick up images that aren't being used in the ePub.

**Comment by dougmassay** [comment]
It's not intended to. The Well-Formed check is just that: a check that the HTML is well formed. Use a validator (there's a Flightcrew plugin as well as an EpubCheck plugin) if you want to check check an epub's compliance with standards. 

Also ... use the "Unused Media" feature to detect images that are not being used in the epub.
