### ISSUE TITLE
Problem Compilig on Windows 10 x64

### ISSUE THREAD

**Issue by Quaturn** [Sigil-Ebook/Sigil#190]
Lately I have problem to compile the installer from the source code.
There was no problem 1 or 2 months ago, but now it is always showing this error.

`[ 94%] Building CXX object src/CMakeFiles/Sigil.dir/MainUI/MainApplication.cpp.obj
MainApplication.cpp

[ 94%] Building CXX object src/CMakeFiles/Sigil.dir/MainUI/MainWindow.cpp.obj
MainWindow.cpp

E:\git\Sigil\src\MainUI\MainWindow.cpp(3283) : error C2146: syntax error : missing ')' before identifier 'and'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3283) : error C2065: 'and' : undeclared identifier

E:\git\Sigil\src\MainUI\MainWindow.cpp(3283) : error C2146: syntax error : missing ';' before identifier 'nav_resource'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3283) : error C2059: syntax error : ')'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3284) : error C2143: syntax error : missing '}' before ';'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3284) : error C2064: term does not evaluate to a function taking 1 arguments

E:\git\Sigil\src\MainUI\MainWindow.cpp(3288) : error C2065: 'm_Book' : undeclared identifier

E:\git\Sigil\src\MainUI\MainWindow.cpp(3288) : error C2227: left of 
'->CreateSectionBreakOriginalResource' must point to class/struct/union/generic type
        type is 'unknown-type'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3288) : error C2065: 'content' : undeclared identifier

E:\git\Sigil\src\MainUI\MainWindow.cpp(3288) : error C2065: 'originating_resource' : undeclared identifier

E:\git\Sigil\src\MainUI\MainWindow.cpp(3289) : error C2143: syntax error : missing ';' before '->'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3289) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

E:\git\Sigil\src\MainUI\MainWindow.cpp(3292) : error C2065: 'm_ViewState' : undeclared identifier

E:\git\Sigil\src\MainUI\MainWindow.cpp(3292) : error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

E:\git\Sigil\src\MainUI\MainWindow.cpp(3292) : error C2078: too many initializers

E:\git\Sigil\src\MainUI\MainWindow.cpp(3293) : error C3861: 'GetCurrentFlowTab': identifier not found

E:\git\Sigil\src\MainUI\MainWindow.cpp(3296) : error C2059: syntax error : 'if'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3296) : error C2143: syntax error : missing ';' before '{'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3296) : error C2447: '{' : missing function header (old-style 
formal list?)

E:\git\Sigil\src\MainUI\MainWindow.cpp(3301) : error C3861: 'tr': identifier not found

E:\git\Sigil\src\MainUI\MainWindow.cpp(3301) : error C4430: missing type specifier - int assumed. 
Note: C++ does not support default-int

E:\git\Sigil\src\MainUI\MainWindow.cpp(3302) : error C2059: syntax error : '}'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3302) : error C2143: syntax error : missing ';' before '}'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3305) : error C2143: syntax error : missing ';' before '{'

E:\git\Sigil\src\MainUI\MainWindow.cpp(3305) : error C2447: '{' : missing function header (old-style 
formal list?)

NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\X86_AM~1\cl.exe' : return code '0x2'
Stop.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.`

Does anyone have any idea what may be causing this?

**Comment by dougmassay** [comment]
I'm experiencing the same thing you are. I haven't built on Windows for a bit, so I assume one of our fairly recent changes has temporarily broken something on Windows. We'll track it down and get it fixed.

Thanks for the report.

**Comment by dougmassay** [comment]
The issue should be resolved on Windows now. Please let me know if it still doesn't work for you.

**Comment by kevinhendricks** [comment]
FWIW, you might want to wait until all of the new translations are updated and added to the tree sometime later this week before building.

Thanks for your bug report!

**Comment by Quaturn** [comment]
Thank you now it is compiling without any problems. 
You can close this issue. :-D

**Comment by dougmassay** [comment]
Glad to hear it! Thanks again for bringing it to our attention.
