### ISSUE TITLE
New Errors

### ISSUE THREAD

**Issue by jafprrr** [Sigil-Ebook/Sigil#191]
Uploading ePubs for the first time with epub3.0, I received the following errors in each of my uploads that I did not have previously. Some of them (such as the language) are clearly related to the Metadata Editor not having been implemented yet, but others are a little harder to work out:

assertion failed:   Exactly one manifest item must declare the 'nav' property (number of 'nav' items: 0).
attribute "opf:role" not allowed here; expected attribute "dir", "id" or "xml:lang"
attribute "opf:scheme" not allowed here; expected attribute "id"
element "metadata" incomplete; missing required element "dc:language"
value of attribute "width" is invalid; must be an integer

**Comment by dougmassay** [comment]
Please take usage problems or questions about how Sigil works to the MobileRead forum dedicated to Sigil users: http://www.mobileread.com/forums/forumdisplay.php?f=203

The github Issue tracker should be used for Sigil code-related problems and bugs. Not usage questions or EPUB validation questions. We (or someone) will be happy to help you with questions of this nature over there.

Thanks

**Comment by kevinhendricks** [comment]
Yes, agreed,  the mobileread forums are the better place to ask these questions.  The correct answers depend on how you generated this epub3 to begin with?  epub3-itizer should have handled all of these issues if run properly on a valid epub2?  If generated in some other way you need to add a nav, fix the metadata in the content.opf to be valid epub3, and update the manifest properties, at the very minimum.  See the epub3 tools menu.  Please ask any followups on Mobileread in the Sigil forum.
