### ISSUE TITLE
compiler error error: ‘QConditional’ in namespace ‘QtPrivate’ does not name a type @src/sigil_constants.cpp:1:

### ISSUE THREAD

**Issue by sarrow104** [Sigil-Ebook/Sigil#193]
My Environment:
     ubuntu 14.04
     gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
     Qt5.5.1

error msg:

> Scanning dependencies of target sigil
> [ 45%] Building CXX object src/CMakeFiles/sigil.dir/sigil_constants.cpp.o
> In file included from /home/sarrow/Qt5.5.1/5.5/gcc_64/include/QtCore/QString:1:0,
>                  from /home/sarrow/Sources/Sigil/src/sigil_constants.cpp:1:
> /home/sarrow/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h: In static member function ‘static T QString::toIntegral_helper(const QChar*, int, bool*, int)’:
> /home/sarrow/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h:828:37: error: ‘QConditional’ in namespace ‘QtPrivate’ does not name a type
>          typedef typename QtPrivate::QConditional<isUnsigned, qulonglong, qlonglong>::Type Int64;
>                                      ^
> /home/sarrow/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h:828:49: error: expected unqualified-id before ‘<’ token
>          typedef typename QtPrivate::QConditional<isUnsigned, qulonglong, qlonglong>::Type Int64;
>                                                  ^
> /home/sarrow/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h:829:37: error: ‘QConditional’ in namespace ‘QtPrivate’ does not name a type
>          typedef typename QtPrivate::QConditional<isUnsigned, uint, int>::Type Int32;

blah, blah ....

**Comment by kevinhendricks** [comment]
That is a bug in an internal Qt header, not in Sigil.  Do you by chance have multiple versions of Qt or Qt headers installed?  Such as having both Qt 4 and Qt 5 on the same system?

**Comment by kevinhendricks** [comment]
Ah, your system must define Int32 and Int64 as macros per this bug report at Qt:
https://bugreports.qt.io/browse/QTBUG-39192
Defining them as macros will break this Qt internal code.  Sorry but this is not a Sigil issue.  You might try adding undefining those macros or finding which headers on your system are defining them.

**Comment by kevinhendricks** [comment]
Closing this issue as it is not Sigil related.
