### ISSUE TITLE
Issue running from latest source on Windows 10 64-bit

### ISSUE THREAD

**Issue by Quaturn** [Sigil-Ebook/Sigil#196]
Hello guys. This is this is the issue.
After compiling from source (latest git revision) and installing the program I tried to run it but I can't because it is always showing error containing this.
`Traceback (most recent call last):

  File "C:/Program Files/Sigil/python3lib\xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "C:/Program Files/Sigil/plugin_launchers/python\sigil_bs4\builder\_lxml.py", line 26, in <module>
    from lxml import etree

ImportError: No module named 'lxml'
`

**Comment by dougmassay** [comment]
If you'll just give me some time to get some documentation for building on windows together, this will go much easier. But for now, look to the instructions for Linux/Mac to see which extra Python modules are required for building Sigil.

**Comment by Quaturn** [comment]
ok thanks

**Comment by dougmassay** [comment]
Building the lxml module for Windows from scratch is a daunting task. Do yourself a favor and get one of the precompiled binaries for it from Chris Gohlke's excellent repository.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

The 3.4.4-cp34 version for your architecture (win32 or amd64) is the one to go with. Pip should be sufficient for installing the rest.

**Comment by Quaturn** [comment]
ok irony of the thing is that it was sufficient to reinstall python on my computer (first I uninstalled it) 
Sorry for raising this issue you can close it :-D

**Comment by dougmassay** [comment]
Will do. Glad you had some success. Thanks for the update.
