### ISSUE TITLE
opf:scheme="marc:relators"

### ISSUE THREAD

**Issue by jafprrr** [Sigil-Ebook/Sigil#197]
When I add authors through the Metadata Editor, it defaults by including opf:scheme="marc:relators"

Yet when I run FlightCrew, it tells me that the opf:scheme attribute is not allowable.

**Comment by dougmassay** [comment]
This was pointed out in the Mobileread forums and has been taken care of in the master branch. There was one more reversion bug that was fixed and we hope to release 0.9.5  this weekend.

Thank you for the report.
