### ISSUE TITLE
<rudy><rt> mend and prettify code wrong

### ISSUE THREAD

**Issue by o3067179** [Sigil-Ebook/Sigil#199]
<img src="http://i1050.photobucket.com/albums/s411/o3067179/_zps787vnnq1.png">
not prettify code to same line.
sigil ver 0.9.4

**Comment by kevinhendricks** [comment]
There is no such thing as a standard for orettifying html5 code.  So it is not incorrect, it simply does not match your expectations.  So please clearly illustrate by example how you think this particular piece of code should be pretty printed.

Kevin

**Comment by o3067179** [comment]
@kevinhendricks 
if not prettify code to same line, the output in epub reader (e.g. google play books) or sigil preview will display blank space before and after the word.

<img src="http://i1050.photobucket.com/albums/s411/o3067179/_zps2ndpkkg4.png">

pretty printed example: \<p\>初めての\<ruby\>仲間\<rt\>なかま\</rt\>\</ruby\>。\</p\>

**Comment by kevinhendricks** [comment]
I should treat both ruby and rt tags as if they are inline tags and not block tags.  Is that correct?  If so, I should be able to change that in time for the next release hopefully this weekend.

**Comment by o3067179** [comment]
Yes, that's right. they are inline element.
Thank you for your understanding.

**Comment by kevinhendricks** [comment]
Just now committed the fix.  It will appear in our next release which should happen this weekend.
I am closing this as fixed in master.  If you still have issues after the upcoming Sigil-0.9.5 please re-open this issue.

Thank you for your bug report!
