### ISSUE TITLE
typo s/specifiy/specify/

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#202]
an automated tool found this typo in the sigil binary.

Just by grepping I found two instances of it in `src/Dialogs/MetaEditor.cpp` and `docs/Install.md`.

**Comment by dougmassay** [comment]
I'm not seeing the typo in your message. Did some markup mess something up?

**Comment by mapreri** [comment]
it's in the title :)

**Comment by dougmassay** [comment]
Oh, well there we go! Thanks for the report.

**Comment by dougmassay** [comment]
Corrected in master: https://github.com/Sigil-Ebook/Sigil/commit/2f0182eb1ce2f51e16d1c80548cd342e588888d5

Though that typo is the least of the work that needs done to the Install.md document. It needs overhauled or eliminated at this point (the only thing that hasn't been supplanted by other, more complete, documents are the Windows compilation guidelines).

Thanks again.

**Comment by mapreri** [comment]
Thank you! :smiley:
