### ISSUE TITLE
[Enhancement] Files Reports

### ISSUE THREAD

**Issue by nonentity1001** [Sigil-Ebook/Sigil#203]
For HTML files add column for Semantic Type

Provide a means of ordering the files the same as they appear in Book Browser - 'spine order' ?

See discussion here on down ==>> http://www.mobileread.com/forums/showpost.php?p=3288287&postcount=18

BR

**Comment by kevinhendricks** [comment]
All of this is provided in the opf and quite clearly too.  Instead, our plan to add a new dockable window / tool that will allow the user to see all spine entries,  any associated semantics, position in the spine, any manifest properties (epub3), and any page spread properties (fixed format epub) and let the user edit/change them as they see fit.

**Comment by nonentity1001** [comment]
For EPUB2 the opf file will tell me, **directly**, which files have a Semantic Tag - but it does not tell me, **directly**, which files don't have a Semantic Tag - I have to do it via subtracting sets in my head. The absence of something is just as important as the presence of something - and sometimes more so.  I'm yet to look at any EPUB3 opf files

The new tool sounds good, Will I be able add and delete semantic tags there.  And will I be able to bring up a file in code view by double clicking on it, as I can from the Report->HTML Files feature.

**Comment by nonentity1001** [comment]
I inadvertently clicked close

**Comment by nonentity1001** [comment]
Having read subsequent posts at MR about the new tool I'll close this
