### ISSUE TITLE
Dialog "Opening this EPUB ..." does not resize

### ISSUE THREAD

**Issue by ordtrogen** [Sigil-Ebook/Sigil#204]
When I open an epub file which (apparently) is not well formed, the dialog that is displayed, and which lists the errors, can not be resized and is too small to be read comfortably

Sigil 0.9.5 64 bit on Windows 7

![namnlos](https://cloud.githubusercontent.com/assets/15184875/14110849/94d9f866-f5c8-11e5-8be6-d4228836b49d.png)

**Comment by kevinhendricks** [comment]
That is funny.  That is the complete error message and I can read the entire thing quite plainly in your posting.  In addition, your OS-level accessibility tools can make the dialogs and screen image larger, and you control the resolution of your display.

**Comment by ordtrogen** [comment]
Well, the error message in the case of the book I open is rather long as about 70 files are not well formed. It is possible to browse through them using the scrollbar in the dialog but I cannot resize the dialog (Windows 7 Professional, SP1). Even if I press the Maximize button it doesn't get any larger, it only moves up to the top left corner of the screen.

So, when I move the mouse to one of the dialog corners or sides, the cursor doesn't change to the Resize icon and it's not possible to grab any part of the dialog to change its size. I have enclosed the sample file, embedded in a ZIP archive so the system allows me to upload it.

[Thinking, Fast and Slow - Kahneman, Daniel.zip](https://github.com/Sigil-Ebook/Sigil/files/193796/Thinking.Fast.and.Slow.-.Kahneman.Daniel.zip)

**Comment by kevinhendricks** [comment]
We can try to make this warning window manually resizeable.  Either way, as the release announcement states, you should enable "Mend on Open" and simply let Sigil fix all of the non-wellformed tags on import.  It has to do that before it can reorganize your files to put them in the folder layout that Sigil requires.  If they are not well-formed, they will not be updated properly.

If you do not like the changes, simply exit without saving the revised epub.

**Comment by kevinhendricks** [comment]
I removed the link to your sample epub as it is not needed to demonstrate any issue and I am not 100% sure that it is public domain or your personal work.  We can not allow posting of copyright/commercial epubs as these links are open to the public that would infringe their copyrights.

**Comment by kevinhendricks** [comment]
Fixed in master.  Anytime "Show Details" is hit, the dialog will become resizeable.
Closing
