### ISSUE TITLE
Request: keyboard access to move between windows

### ISSUE THREAD

**Issue by ordtrogen** [Sigil-Ebook/Sigil#207]
I'm working on a book and am editing the text in editor window. I would like to be able to shift focus to the book browser window, navigate to another file in the book, press Enter to open it and then immediately be able to edit (focus should be in editor window)

Cfr Windows Explorer where the TAB key does this job. In Sigil the TAB key is already used (to enter the TAB character) so some modification should be decided. I suggest Ctrl-TAB (and Shift-Ctrl-TAB) to shift focus between windows, forward and backward. Today Ctrl-TAB moves between tabs in editor, but Ctrl-PageUp, Ctrl-PageDown does this too. So you could re-assign Ctrl-TAB to moving between windows and we could continue to move between tabs in editor through Ctrl-PageUp/Down

**Comment by kevinhendricks** [comment]
Again see Sigil->Preferences->Keyboard Shortcuts to control key sequences for Next File and Previous File.

Again closing this as the features already exist.
