### ISSUE TITLE
Suggestion: Multiple Windows

### ISSUE THREAD

**Issue by bubbasheeko** [Sigil-Ebook/Sigil#208]
Not the end of the world, but would be very helpful.  If you could have more than one epub open in multiple windows.

**Comment by dougmassay** [comment]
I don't understand how that would be remotely useful. The last one saved would override the changes from the other. Or do you imagine them staying synced with each other's changes somehow?

**Comment by bubbasheeko** [comment]
I don't think we are on the same page.

I use a website to upload an epub.  However, because of the nature of the site and conversions that are made to the epub, it does not have all the information within the file to work.  I have to change a few things in the content.opf file. I find it helpful to have one of those files open in an epub that has passed all the tests so that I can make changes on a new epub that I am working on.  Doing this by viewing the epubs side by side.

In Windows, I open an epub. If I attempt to open a second epub, the original instance is replaced by the one I just opened.  I do not get two instances of Sigil, I only get one.  Is there a way to achieve this that I am missing?

I know I can achieve what I want to do by opening one copy normally and running a second in a sandbox environment.

**Comment by kevinhendricks** [comment]
On Linux and Win, simply run two instances of the program by launching the second from the command line.  Under Mac the multiple windows open (each with a different epub) is already part of the interface.

Alternatively, you can use Open With ... to open a copy of the opf in a text editor that you can change as you like.  It will only be changed once the external editor saves it.  So you can see the original while editing with a separate text editor a copy.

**Comment by dougmassay** [comment]
You wouldn't even have to technically use the command line on Window and Linux. On Windows, each double-click of the desktop shortcut, start menu shortcut, or program executable will launch a new Sigil instance. On Linux, using the sigil desktop shortcut in /user/local/share/applications (or Sigil's entry under your distro's menu system will do the same thing.

I'm not certain why your second instance of Sigil on Windows would be replacing the first instance. That's not something I've ever encountered in all my years of using Sigil. Multiple instances is inherent; there's nothing you need to do to enable it. Nor can it be disabled (unless there's some sort of Windoes security software out there that restricts multiple instances of the same program).

**Comment by bubbasheeko** [comment]
This was my oversight. I wasn't doing the obvious. Thank you for the assistance and this thread can be disregarded. Keep up the great work!
