### ISSUE TITLE
How to print epub file？

### ISSUE THREAD

**Issue by renyouguo** [Sigil-Ebook/Sigil#210]
I want to print the whole ebook by one click，just like pdf.

**Comment by dougmassay** [comment]
Sigil doesn't provide a feature like that. Mainly because epubs are nothing like pdf.

**Comment by ShutUpMagda** [comment]
In any case, an ebook reader can do it

**Comment by kevinhendricks** [comment]
Glad you found a solution. Next time instead of filing a bug report for something that is not a bug, please use our Mobileread based support forums for questions like this.
Closing.
