### ISSUE TITLE
Split at Cursor results in broken markup in EPUB3

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#214]
Hi Sigil team,

I'm using Sigil 0.9.5. 
When I use the split at cursor button when working on an EPUB3 I get this error every time:
```
This page contains the following errors:

error on line 4 at column 92: xmlns:epub: 'http://http://www.idpf.org/2007/ops' is not a valid URI
Below is a rendering of the page up to the first error.
```

http:// is inserted twice in the first page of the two. It's easily fixable manually in the markup.

**Comment by dougmassay** [comment]
We're going to need some sample markup and some specific steps to recreate your issue. I've "Split at Cursor" in as many awkward places, in as many epub3s as I can find (with many different Sigil settings), and I can't get your error to happen.

**Comment by kevinhendricks** [comment]
I could not recreate it either until I tried splitting using BookView.  ViewEditors/BookViewEditor.cpp is the culprit.

I will fix this when I get back home.

**Comment by shorshe** [comment]
Phew, glad you could reproduce the bug Kevin.
I'm always splitting in book view... so the hunt could have been long. :D

**Comment by dougmassay** [comment]
Ahh... splitting in Book View never even occurred to me. That's always been a risky proposition as far as I'm concerned. ;)

**Comment by kevinhendricks** [comment]
Just fixed this in master.  Fix will appear in the next release.
Thank you for your bug report!
Closing as fixed in master
