### ISSUE TITLE
"Delete Unused Media Files …" will delete images referenced in CSS

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#216]
If your EPUB has an image, which is only referenced in the CSS. 
The command "Tools -> Delete Unused Media Files … " will delete this image.

I've attached a test epub (rename zip to epub) 
The only image apart from the cover image is rose.jpg. Wich is only referenced through the css.
EPUB is valid.

[Testcase_CSS_referenced_image.zip](https://github.com/Sigil-Ebook/Sigil/files/269962/Testcase_CSS_referenced_image.zip)

**Comment by kevinhendricks** [comment]
I will take a look at it.  Thanks for the test case.  My guess is the person who developed that code did not think about background-images in external css stylesheets.  If that is indeed the case, I will try to add that to the routine that tries to determine unused media.

**Comment by kevinhendricks** [comment]
Yes, definitely a "thinko".  There is no code to parse css stylesheets to look for urls in background, background-image, list-style-image, border-image, border-image-source, content, import, etc.   Sigil already has code to do something similar to this but it is used only on initial load to properly update any image url changes when Sigil moves things to its preferred folder structure.

I will add code to return all url paths in a css stylesheet and then use this code to fix the Remove Unused Media and Sigil's Report feature which also showed rose.jpg as unused.

**Comment by kevinhendricks** [comment]
I take that back.  I was able to find code that looked for urls in css stylesheets for DeleteUnusedMedia but it required the url to be inside quotes:
```
url("../Images/rose.jpg")
```
Or use single quotes.  It just did not handle the case of no quotes of any type.  That has now been fixed in master.  Closing.
