### ISSUE TITLE
Add support for spellchecking in multiple languages in the same ebook

### ISSUE THREAD

**Issue by kevinhendricks** [Sigil-Ebook/Sigil#218]
reminder for myself from MR feature request

**Comment by varlog00** [comment]
Just to appear on Github issues mailing list.
The (Multi Language Spelling)mlspell branch of Sigil gets updated. Any input will be welcomed.

**Comment by kevinhendricks** [comment]
Closing this as basic support for multiple language spellchecking has now been pushed to Sigil master.
