### ISSUE TITLE
what the heck's wrong with OS X 10.8 support?

### ISSUE THREAD

**Issue by ratijas** [Sigil-Ebook/Sigil#224]
specifically, 10.8.2.  app says about 10.9.5 or higher.

what's wrong there about 10.8 that i can't fix with `homebrew`?

**update**

how cute — when attempt to run, import error happened to python.  not to mention that i'm a huge fun of python, but packaging and importing things really sucks withing its community.

```
Traceback (most recent call last):

  File "/Volumes/LiteHD/apps/Sigil.app/Contents/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/Volumes/LiteHD/apps/Sigil.app/Contents/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 26, in <module>
    from lxml import etree

ImportError: dlopen(/Volumes/LiteHD/apps/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lxml/etree.so, 2): Symbol not found: _xmlBufContent
  Referenced from: /Volumes/LiteHD/apps/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lxml/etree.so
  Expected in: /usr/lib/libxml2.2.dylib
 in /Volumes/LiteHD/apps/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lxml/etree.so
```

**Comment by kevinhendricks** [comment]
Nothing.
You should be able to follow the instructions and build from source both a relocatable Python 3.4.3 and Sigil for 10.8 with little to no difficulties.  Check out the docs/ directory for instructions.

That said,  I only have one Mac development machine that I also use for home and work so I tend to keep it up to date OSX-wize and with the latest toolchain (XCode).  Right now I am delaying my update to El Capitan just to keep building easily for OSX 10.9.  Support fot 10.9 will soon go away.

FWIW  I can even run El Capitan on early 2008 iMacs with just 4 gig of memory at work, so unless you are stuck using 10.8 you would probably be better off updating to El Capitan as well. It is free.

**Comment by kevinhendricks** [comment]
The missing symbol seems related your version of libxml2.  Are you using a prebuilt version of lxml or are you building it from source.  If the latter, make sure it can find the correct version of libxml2 to build lxml against.  Older Mac versions of libxml2  that came with the Mac OS were old and broken.  This is no longer an issue with newer Mac OSX versions.

**Comment by kevinhendricks** [comment]
Closing this as not actually a bug. The source builds as expected with the provided instructions on both Yosemite 10.10 and El Capitan 10.11.  If you need help with your build setup for older OS X platforms or figuring out how to handle build issues, please post in our Sigil support forums on www.mobileread.com.  I (and others) would be happy to provide help there.
