### ISSUE TITLE
Allow use of Del key to remove current item in Metadata Edit

### ISSUE THREAD

**Issue by nonentity1001** [Sigil-Ebook/Sigil#225]

**Comment by kevinhendricks** [comment]
As both delete (aka backspace) and forward delete can be used when editing inside a Metadata cell, neither of those key sequences can be used. Instead I have added a QShortcut that uses option + forward delete to activate the Remove button.

Please note, if you want to remove metadata wholesale it is easier to open the opf tab and simply highlight and delete what you want in one fell swoop.
