### ISSUE TITLE
Sigil adds </image> end tag within SVG blocks

### ISSUE THREAD

**Issue by jcsalomon** [Sigil-Ebook/Sigil#227]
Sigil 0.9.6 has changed SVG <image> tags from self-closing to having an end-tag:

    - <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><image xlink:href="../Images/Steeplechaser.png"/></svg>
    + <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><image xlink:href="../Images/Steeplechaser.png"></image></svg>

but Kindlegen gives a warning about this:

> Warning(inputpreprocessor):W29008: Tag rejected due to improper usage: \</image>

**Comment by kevinhendricks** [comment]
This is a bug in Kindlegen.  The svg image tag is NOT a void (empty tag).  It can have contents.  Therefore a closing image tag must be allowed.

See for example the "Permitted Content" for the svg image tag here:  
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

So under xml/xhtml parsing rules, a closing image tag is proper and in fact required if any of the permitted content is included.

So please file a bug report with Amazon.

**Comment by jcsalomon** [comment]
Actually, the example you pointed to includes:

    <image xlink:href="/files/2917/fxlogo.png" x="0" y="0" height="100" width="100" />

_i.e._, the \<image> tag is self-closing.

**Comment by kevinhendricks** [comment]
Please read the entire document I cited.  Their example shows a self-closed tag but the tag is NOT a void element (in other words it can contain other elements) and therefore a closing tag is allowed and proper xml.  So what Sigil generates is perfectly legal xhtml and xml.  If Kindlegen has an issue with it, that is a bug in Kindlegen.  Xhtml/xml tags can be self-closed if empty  but under xml/xhtml parsing rules closing tags are permitted always on xml elements that are non-void (and the svg image element is not a void tag as can be seen by the permitted content).

**Comment by kevinhendricks** [comment]
Here is an example of a non-self closing svg image tag:

http://www.w3.org/TR/SVG/struct.html#ImageElement

**Comment by kevinhendricks** [comment]
'''
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="4in" height="3in" version="1.1"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <desc>This graphic links to an external image
  </desc>
  <image x="200" y="200" width="100px" height="100px"
         xlink:href="myimage.png">
    <title>My image</title>
  </image>
</svg>
'''

**Comment by kevinhendricks** [comment]
All that said ... I may be able to work around things and use self-closing for non-void tags as long as they are empty and I can see they are in the svg or mathml namespace.  That would not prevent the Kindlegen bug completely but would hide the bug as long as the image tag was truly empty.

Let me see if there is somthing I can do, but please do make a bug report to Kindlegen/Amazon as a close tag truly is always valid on non-void tags.

**Comment by kevinhendricks** [comment]
BTW:  What does Kindlegen report when you try to use a snippet that needs an closing image tag (see my example code posted here)?

Does it still provide the error/warning message?

**Comment by kevinhendricks** [comment]
Just pushed a work-around to the Kindlegen bug but it may still fail if non-empty image tag is used.  See my request above.

**Comment by jcsalomon** [comment]
Kindlegen still complains about the end-tag. Looking at the generated file via MobiUnpack, it seems it Kindlegen has self-closed the \<image> tag and put the \<title> tag after it.

Try the attached [SVG_Problem.epub](https://github.com/Sigil-Ebook/Sigil/files/332432/SVG_Problem_epub.zip), for example.

Amazon responded to my earlier email saying,

> Not to worry it is an expected behavior of the tool when tagged.  

> The book won't be affected due to this warning. 

> We request you to preview the book and check if there are any issues with the output of the book. 

I’m sending them this example. It’s still just a warning, and not creating any noticeable difference in how the book appears, but it’s verifiably incorrect and so deserves more attention from Amazon.
