### ISSUE TITLE
book browser files

### ISSUE THREAD

**Issue by moniwe** [Sigil-Ebook/Sigil#229]
for larger Projects the use of versioning Tools (svn, mercurial, git) might be helpful. But to use them effectively the files from the book browser should be within the file System. It therefore would be great if sigil could store a "sigil Project" within the file system containing the epub but also the Folder structure and files listed within the book browser. At least from my Point of view

**Comment by kevinhendricks** [comment]
They are stored unzipped in their folder structure.  In Sigil 0.9.6 you can even set a permanent "temporary" directory where these files can be found.  Furthermore the python plugins are provided with that path allowing a python edit plugin to check in and commit as well as checkout and update those files from a repository.
Closing this as these capabilities already exist.
