### ISSUE TITLE
on the closed topic

### ISSUE THREAD

**Issue by drydenp** [Sigil-Ebook/Sigil#231]
Why do you close a topic to collaborators only? This way even I cannot respond to what you have to say.

Is this some way to stifle debate or what? Anyway, I found the guy's blog after Googling better, and I don't mind if you delete this issue after reading it, but I wouldn't mind a response as well, either, of course. Do what you like, it's just that locking topics is not the most democratic thing there is, and usually comes down to you being the only one who has a voice. And in general I do feel like this happens a lot in Linux these days. Like it has become some corporate interest with the image marketing that comes with it and now no one can say anything about it anymore unless it adds to the sale for it. That's how it feels. I'm sorry if that sounds subjective. But that's just how I feel. Like people are trying to limit the channels of expression that are available to people in order to create a "better product". I hope I'm wrong about that, I just do.

**Comment by dougmassay** [comment]
This is not a democracy. And this is not a Sigil Issue. Please don't subvert the issue-tracking system with non-code/bug issues. I locked the topic because this is not the place for commentary on what Linux is or isn't. This is the place to report bugs or compilation problems with Sigil.
