### ISSUE TITLE
Mouse cursor hovering over scrollbar not swapping to arrow

### ISSUE THREAD

**Issue by fatetrader** [Sigil-Ebook/Sigil#233]
This might seem like a super trivial thing to write about but as they say "the devil is in the detail". 

In a **Book View** mode if there is a scrollbar on the right hand side, when hovering with a mouse cursor over it, cursor is not swapping from **text selector** to **arrow cursor**. This is working correctly in the **Code View** mode.

Any chance to fix this little thing, it has been bugging me since I remember?

**Comment by kevinhendricks** [comment]
Sorry, not a Sigil bug.  The bug is in Qt and was long ago reported but no progress was ever made.
We are planning to update to Qt 5.6.1 so there is hope it may be fixed but I wouldn't hold my breath.

**Comment by eli-schwartz** [comment]
This bug is still present on Arch Linux when built against a system Qt5 5.7.0

So the chances of it being fixed in Qt5 5.6.x aren't looking very good. :wink:
