### ISSUE TITLE
Backref replace not working while using a Regex Search/Replace

### ISSUE THREAD

**Issue by sephiroth1311** [Sigil-Ebook/Sigil#241]
Hello, it would be great if Sigil's Regex engine could be improved with the support to backref replace.

An example: I want to convert `<p>[(number)]` to `<p>[<a` `id="nota(number)">(number)</a>].`

I wrote this Regex to find the text: `^<p>\[(\d{1,2})\]`
and this other one to replace it automatically: `<p>[<a` `id="nota$1">$1</a>]`

It works like a charm on EditPadPro, but Sigil just ignores the $1, which is copied literally.

Thanks.

**Comment by dougmassay** [comment]
PCRE (which is the regex engine Sigil uses) doesn't use the "$" to indicate captured groups and backreferences in its replace expressions. It uses the backslash (\) character. Change your replace expression to: `<p>[<a id="nota\1">\1</a>]` and it works just fine.

**Comment by sephiroth1311** [comment]
Thank you!
