### ISSUE TITLE
enhancement: Highlight Code-/Preview scroll position in Table of Contents

### ISSUE THREAD

**Issue by JulesDoe** [Sigil-Ebook/Sigil#242]
When working on long documents that are splittet over multiple xhtml files its easy to lose track in the document structure. It would be helpfull to have an optional Outliner windo-panel-thingy (like the Book-Browser) that shows the current scroll position of Preview/Codeview in the Heading hirarcy.
cheers

**Comment by kevinhendricks** [comment]
See the Inspector Window at the bottom of the preview pane.  You can close/open html elements as you see fit to see whatever structure you want.

**Comment by JulesDoe** [comment]
That shows me only the nesting of the Previewed HTML elements. (Don't get me wrong thats a very awesom tool for Developing CSS and stuff.)
I was thinking about something that helps people to navigate the Outline of the books contents. For example, when you search something while creating the E-Book for an existing Printet Book.

Lets say you have this HTML Structure:
---
- File1.xhtml
  - div
    - h1
      - h2
      - h2
- File2.xhtml
  - div
    - h1
      - h2
      - h2
- File3.xhtml
  - div
      - h2
      - h2


---

The Outline of the Text might be:
---
- h1
   - h2
   - h2
- h1
   - h2
   - h2
   - h2
   - h2
   - h2

**Comment by kevinhendricks** [comment]
What you are describing is just a Table of Contents.  There already is a Table of Contents window you can use.  And there are already automatic tools in Sigil to help you build exactly that TOC directly from the headings.  You can then navigate directly to that point using your TOC.

Kevin

**Comment by JulesDoe** [comment]
Oh my bad, I never Noticed the Table of Contents!
It would be great to Highlight the current scroll position of Preview/Codeview in the Table of Contents Window.

**Comment by kevinhendricks** [comment]
Sorry but that is not something I am interested in doing as many many locations both inside of and outside of html elements would all map to the same location in the TOC, making the highlighting inside the TOC virtually worthless for knowing where you are in the file. 

The active file is always highlighted in the tab name and the BookBrowser window.  You can always also simply click on a TOC link to navigate to the correct place.  Then use the inspector in Preview to collapse and uncollapse nested html structures to see your current place in whatever level of detail you require.  This Preview Window is kept in sync with what your CodeView location is being edited.

So I am Closing this issue.
