### ISSUE TITLE
Symbols in ePub files

### ISSUE THREAD

**Issue by KatyPerryFan4Eva** [Sigil-Ebook/Sigil#243]
why has Sigil done away with being able to insert symbols you need to use such as the en dash, speech marks etc? I think this is SILLY and they need to put it back as they have just made life a lot harder for people writing ePubs

**Comment by dougmassay** [comment]
You're mistaken. We haven't done away with that ability at all. Perhaps you're confused about html entities vs unicode characters?

The new Sigil html parser will convert html entities to their corresponding characters (unless you specifically add the entity to the Preserve Entities list in the Sigil Preferences).

It's still perfectly possible to insert en dashes and speech marks and such into Sigil built epubs. I do so all the time.

**Comment by KatyPerryFan4Eva** [comment]
How do I go about it then, because symbols used to be in the INSERT tab but now they're not! Where have you put them?

**Comment by mihailim** [comment]
That dialog is exactly where it has been for a very long time:

  * In the menu: Insert -> Special Character...
  * In the toolbar: Click on the "Omega" symbol
  * Keyboard shortcut: Whichever you defined (there's none by default.)

That being said: I'm not associated with Sigil, so I'm probably more in a position to tell you this than the (unbelievably patient) developers are. You are coming across as aggressive and more than a little bit self-entitled; you seem to believe that, somehow, the Sigil developers *owe* you something. You are wrong. If I were you, in the future I'd tone down that attitude. Who knows, you might get better results that way...

**Comment by KatyPerryFan4Eva** [comment]
No it isn't at all, all that's in INSERT is 

CHAPTER BREAK
IMAGE
and
SGF CHAPTER MARKER

**Comment by mihailim** [comment]
You are using an ancient version released years ago, no longer supported by anyone (which means: If something breaks, you get to keep the pieces.) The current version is 0.9.6. Try that. Your phrasing made it look like you were complaining about that dialog disappearing from the current version.

**Comment by KatyPerryFan4Eva** [comment]
is it, oh right, thanx. it said the one I have is the lastest version - weird!

**Comment by mihailim** [comment]
Yup. Sigil ownership and related DNS domains have moved around over the years, and naturally any update check for an ancient version won't find anything at the place where it expected to find new version announcements (Sigil development is supported by a handful of volunteers in their spare time, it's not a commercial company which can afford to keep compatibility with stuff like that.)

**Comment by mihailim** [comment]
I suspect this issue can be closed as NOTABUG now :)

**Comment by KatyPerryFan4Eva** [comment]
Yeh

**Comment by v-v-x** [comment]
[image: Inline image 1]
