### ISSUE TITLE
Huge icons in 0.9.7

### ISSUE THREAD

**Issue by aldomann** [Sigil-Ebook/Sigil#245]
Reading the Release notes, I realised that

> - Fix too small toolbar icons on high dpi displays

is indeed a feature and not some random rendering problem.

The thing is that, these big icons are also shown in 1080p resolutions (haven't tested in smaller ones); this ends up being too big in my opinion. In the picture below we can see Sigil 0.9.7 and QtiPlot (as a reference of a Qt app with usable smaller icons).

![screenshot from 2016-10-31 11-40-32](https://cloud.githubusercontent.com/assets/729732/19851674/632f73cc-9f5f-11e6-8f65-633a96bcbb08.png)

I don't know if the hi-dip icons are supposed to be displayed in a 1080p display; if yes, I would really appreciate an option to select the size of the toolbar icons from the Preferences.

**Comment by dougmassay** [comment]
I think "huge" is a rather large exaggeration, myself. The icons are a bit larger, yes. But I think they look pretty natural on my Windows screens.

If, however, the slight increase is weighing on you heavily, there is an environment variable you can set to tweak the size to your liking:

SIGIL_ICON_SCALE_FACTOR - Valid numeric values: 1.0 to 3.0. The default value (with no variable set) is 2.0 on Windows.

Try 1.8 or or 1.7 (numeric, no quotations) and see if you can find an acceptable compromise. If enough people rage against the default, we'll see about changing it (or making it a preferential setting).

**Comment by aldomann** [comment]
Yeah, definitely an exaggeration. Anyway, where do I modify `SIGIL_ICON_SCALE_FACTOR`?

**Comment by dougmassay** [comment]
> Anyway, where do I modify SIGIL_ICON_SCALE_FACTOR?

You actually need to *create* it. For Windows: https://kb.wisc.edu/cae/page.php?id=24500

On Linux you can quickly test it on the command line when launching Sigil:

SIGIL_ICON_SCALE_FACTOR=1.7 sigil
