### ISSUE TITLE
Move a section in the Book Browser and Sigil changes its ID?

### ISSUE THREAD

**Issue by davylols** [Sigil-Ebook/Sigil#248]
Seems that if you have a book broken into a bunch of sections, then you drag one into a different order, the ID can get changed. So instead of "Section0001.xhtml" as the ID element in the OPF and whatnot, you'd now have "fbb738a7-59f6-477b-bc56-487ab42c84cc". This can also cause validation failure.

**Comment by dougmassay** [comment]
Reordering files does not change their manifest ids. Splitting a file might create a file with a uuid for for an id, though.

**Comment by davylols** [comment]
Thanks for the reply. Sorry for the bad video, but here's what our company is experiencing:

[IMG_2589.MOV.mov.zip](https://github.com/Sigil-Ebook/Sigil/files/576668/IMG_2589.MOV.mov.zip)

I can't speak to the "not a valid ID" thing in validation; it's possible that some of the designers I've worked with haven't updated to 0.9.7, I just know Sigil-created books have been getting rejected from online retailers for us owing to IDs like the one I described. I will look more into that and assume you're correct and that they can fix that problem by updating. The user whose screen you see in this video is using 0.9.7.

**Comment by dougmassay** [comment]
I see it, but I sure can't duplicate it.

**Comment by davylols** [comment]
It was indeed split from another file—in the video, he has split from V1_Bulls.xhtml. What we're looking at there is an EPUB that was exported from InDesign. InDesign's export settings were set to split automatically at chapter title headings (which gets you the standardized ones that come later marked with chapter numbers—V1_Bulls-1.xhtml, V1_Bulls-2.xhtml, etc.). The resulting EPUB had all the front matter lumped together in the first section, and he split it into separate files for the copyright page, dedication, etc. Interestingly, if the file is renamed (say, we change it to Copyright.xhtml instead of Section0001.xhtml), this behavior does not persist. 

My personal instinct is to suspect it's gotta be something related to InDesign, and whenever I get some time I'm going to try to build up an EPUB from scratch and try to duplicate it under those conditions.

**Comment by kevinhendricks** [comment]
Using a uuid to generate a unique manifest id is actually quite legal as long as it does not begin with a number.  Exactly what error message did you get from epubcheck when using the uuid you show in your first post.  It is completely valid to use as a manifest id.

**Comment by dougmassay** [comment]
We know that splitting files (at the cursor) can result in files with uuids for manifest ids. This is by design. We've taken steps starting with 0.9.7 to ensure that those generated manifest ids will always be spec compliant (versions of Sigil prior to 0.9.7 could indeed generate invalid manifest ids). See: 916cb1ea6cb085456795536221c6de363b6de0a3

We're going to need reproduceable steps, however, that show the reordering of the files in the Book Browser actually *causing* the manifest id to change to a uuid. I see the result in the video supplied, but I can't reproduce it.

**Comment by davylols** [comment]
Maybe five times we've gotten numbers when those split IDs have happened. I can't find relevant files at this time to send you since I've just fixed them and sent them on, but I did find a screenshot from an e-mail in which I was trying to figure it out with a designer after it happened.

![image002](https://cloud.githubusercontent.com/assets/23133821/20116852/9164a6ee-a5c3-11e6-8185-c5cc2795bc08.jpg)

I think the only way I can help at this point is that I've told the designers I'm working with to keep an eye out, and if we see a file that does this to stop working immediately and send it to me, along with the exact steps they took to get there. That way, if I can find a way to reproduce it, I can put it here. But I don't honestly have the time to actively investigate it myself right now. I definitely get that you need to be able to reproduce it.

**Comment by davylols** [comment]
Also, like I said, it is totally possible that those invalid IDs were from people who hadn't updated to 0.9.7; we work with a lot of different people, and at least some of the non-compliant epubs were from a designer who went to work for another company a week ago, so I have no way to check. I'll keep an eye out, though!

**Comment by dougmassay** [comment]
Yes, uuid manifest ids are produced under very specific conditions when
splitting: when using the Split at Cursor feature, and when the preferred
id that Sigil wants to use is already taken.

I'm guessing you won't have any more invalid ID issues after v0.9.7. An id
like the one in your image (a uuid that begins with a number) should not be
created by Sigil any more. Uuid manifest ids will still be created from
time to time when splitting files at the cursor, but they shouldn't trigger
any validation issues from v0.9.7 on. Please feel free to revisit if you
nail down a situation where Sigil v0.9.7+ creates an id that won't pass
epubcheck's muster.

**Comment by dougmassay** [comment]
Feel free to reopen if invalid IDs are generated after Sigil v0.9.7
