### ISSUE TITLE
Sigil create new epub3, epubcheck failed.

### ISSUE THREAD

**Issue by JackieFei** [Sigil-Ebook/Sigil#250]
How to reproduce:

1. Preferences > General Settings > Create New or Empty Epubs as: Version 3 > OK
2. File > New > Save
3. Use epubcheck 4.0.1 (or Sigil epubcheck plugin) to check this epub, got the error:
Validating using EPUB version 3.0.1 rules.
ERROR(OPF-073): e3.epub/OEBPS/toc.ncx(3,52): External identifiers must not appear in the document type declaration.
4. Remove the toc.ncx line 2 and 3 (see below), epubcheck will completed.
<!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN"
"http://www.daisy.org/z3986/2005/ncx-2005-1.dtd">

**Comment by kevinhendricks** [comment]
That may be an error in epubcheck.  Doctypes on pure xml files like the toc.ncx are allowed and are needed for backwards compatibility with epub2 readers.  The dtd is allowed to be there as well again for backwards compatibility.   I think there is an official epubcheck bug already filed on this someplace on their site.

**Comment by kevinhendricks** [comment]
FWIW, I think we could modify the code to remove the DOCTYPE on the toc.ncx just for epub3, but it really makes no sense given the only reason to have a toc.ncx under epub3 is for backwards compatibility with epub2 ereaders.  I will look into this as epubcheck rarely if ever updates and fixes its own bugs.

**Comment by JackieFei** [comment]
https://github.com/IDPF/epubcheck/issues/591

**Comment by JackieFei** [comment]
epubcheck has a closed issue above.

**Comment by dougmassay** [comment]
For what it's worth,  none of the commercial epub3s I'm seeing include the DOCTYPE in the NCX. And I'm seeing no compatibilty issues in epub2 reading systems (mainly older ADE on desktops and RMSDK-based portables) as a result.

**Comment by kevinhendricks** [comment]
Just committed fix for this to master.  Closing this issue.
Thank you for your bug report!
