### ISSUE TITLE
Accessing subclass self method

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#251]
Hello everyone !

I'm trying to write some plugins for Sigil.

I have this file `test.py` with this class :
```Python
class Test()
    def __init__(self):
        print("Init Test()")

    def say_hello(self, name):
        print("Hello "+name+"!")
```
And inside of `plugin.py` :
```Python
# Some code

def run(bk):
    Test.say_hello("Jean") # This doesn't work
    Test.say_hello(bk, "Jean") # but this work

# Some code
```
So I can't use the `self` argument inside the `class Test()` because `self` is `<class 'bs4.BeautifulSoup'>` instead of `<class 'test.Test'>`.

Any help please ?

**NOTE** : Don't know if it's an issues or not so sorry if it's not the right place to post it. And not good in English too :disappointed:

**Comment by kevinhendricks** [comment]
Issues is not the place for this.  We have multiple Sigil user's forums on Mobileread (www.mobileread.com) include a Sigil forum for Plugin Developers.
Please direct all questions there.

**Comment by kevinhendricks** [comment]
FWIW - I think you are mixing up Python class methods and normal (instance) methods:

Have you tried the following:

def run(bk):
    mytest = Test()
    mytest.say_hello("Jean")


Also note the plugin wraps the output stream to capture it as part of the response from the plugin so truing to redirect stdout and stderr will not work as these are controlled and captured by the plugin framework.
