### ISSUE TITLE
All files have identical content in HTML view

### ISSUE THREAD

**Issue by chrisridd** [Sigil-Ebook/Sigil#252]
I have a commercial (DRM-free) epub 2 book from Kobo which doesn't seem to behave well in Sigil 0.9.7 on Mac OS X 10.11.

If I open the HTML files in code view, they all have the same HTML content. If I switch to book view, the content now looks correct. If I switch back to code view, the HTML also looks correct.

The only odd thing I can see is that the names of the files in the zip are quite long, e.g. tmp_d43d85b11c3458927fa379304a95cc7c_a5qIby.ch.fixed.fc.tidied.stylehacked.xfixed_split_007.html

I can provide a copy of the book privately for testing purposes.

**Comment by kevinhendricks** [comment]
Travelling now.  But when I get back I'd be happy to look at it if you can post it someplace and privarely pm me "KevinH" on www.mobileread.com/forums/Sigil

Thanks

**Comment by chrisridd** [comment]
PM sent!

**Comment by kevinhendricks** [comment]
Downloaded ebook.  Fired it up on my Mac using the latest Sigil-0.9.7 build on Mac OS X 10.11.6.
All xhtml pages are distinct.  No need to go to BookView and back.

On Mac OX, the max path is 255 characters.  Is there any chance that Sigil might end up with a path longer than 255 characters when opening this ebook inside the tmp directory on your machine?
Have you tried running Disk Utility on your harddisk to make sure that it is working correctly?

I can not yet recreate what you reported on my Mac but I will keep trying.

**Comment by kevinhendricks** [comment]
Just tried this on an older Mac I had around and with no problems at all.  Both Mac's are using a Journaled HFS+ (OSX Extended) Filesystem.   Are you by any chance using a networked drive or external drive not formatted for HFS+?

**Comment by chrisridd** [comment]
I'm running 10.11.6 with the built-in drive using normal case-sensitive journaled HFS+.

Having a look under /var I see that I have files such as:

/private/var/folders/tb/m0xp3fw51vz2kxqcyx050wkc0000gn/T/Sigil-kA2mvv/OEBPS/Text/tmp_d43d85b11c3458927fa379304a95cc7c_a5qIby.ch.fixed.fc.tidied.stylehacked.xfixed_split_070.html

That's only 177 chars. As switching to book view and back seems to fix each file, it doesn't feel like a path size or filename size limit. NB `getconf PATH_MAX /private/var/folders` returns 1024 and `getconf NAME_MAX /private/var/folders` returns 256.

**Comment by kevinhendricks** [comment]
Wow.  I have tried this now on 3 Macs that I have around the house and none of them show the problem you report.  

Have you run Disk Utility on your hard drive to verify the filesystem is operating properly?

All of my HFS+ file systems are case insensitive but case preserving.  They are Journaled also.  So we differ in that you have reformatted your drive at some point to be truly case sensitive.  I have one external drive set up that way that I will test with.  But so far, no luck seeing or recreating your problem on my Macs.

**Comment by chrisridd** [comment]
Whoops, I mean case Insensitive. I've corrected my earlier comment.

Disk Utility shows no issues with the SSD.

Oh dear. This bug is invalid and I've totally wasted your time...

I had the Find panel open. Each file actually does have the first dozen or so lines identical, all the way to the top of the Find panel. If I scroll *down*... yes, they're different.

(facepalm)

**Comment by dougmassay** [comment]
Happens to the best of us! Glad it's all working :)
