### ISSUE TITLE
Can´t run sigil

### ISSUE THREAD

**Issue by JPRuehmann** [Sigil-Ebook/Sigil#258]
if I try to start sigil I get the following error

Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/usr/local/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 26, in <module>
    from lxml import etree

ImportError: cannot import name 'etree'

17 times then the Main Window appears and disappears.
The CLI says,

Warning: QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
Warning: QBasicTimer::start: Timers cannot be started from another thread
Warning: QApplication: Object event filter cannot be in a different thread.
zsh: segmentation fault  bin/sigil

I configured with

cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m/ -DBUILD_PATCHED_LIBXML2=1 .

what can I do to make it work?

**Comment by dougmassay** [comment]
Did you use the Linux  build instructions to make sure all the necessary Python dependencies are present? Also ... unless you're using some special, non-system version of Python 3, then get rid if the -DPYTHON_INCLUDE_DIRECTORY flag in the configuration command and let cmake find the system python3 installation on its own.

**Comment by JPRuehmann** [comment]
Yes
cmake found all but the includes. so  had to set it.

**Comment by JPRuehmann** [comment]
I´ve found it, I had to st the Interpreter to.
This config works,

cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m/ -DBUILD_PATCHED_LIBXML2=1 -DPYTHON_LIBRARY=/usr/lib/python3.5/config-3.5m-i386-linux-gnu/libpython3.5.so -DPYTHON_EXECUTABLE=/usr/bin/pdb3.5 -DUSE_SYSTEM_LIBS=0 -DSYSTEM_LIBS_REQUIRED=0 .

Thanks,

**Comment by dougmassay** [comment]
Glad you got it working. 
Yes, I have discovered that it's usually all or nothing with those Python configure options.

**Comment by dougmassay** [comment]
Closing this issue.
