### ISSUE TITLE
How do I get the Version from CLI?

### ISSUE THREAD

**Issue by JPRuehmann** [Sigil-Ebook/Sigil#259]
Hello
I like to automate the Update Process with a script, for that I need the Version, but I can´t find a CLI comando to do that.
Can you help me please?
Thanks

**Comment by dougmassay** [comment]
Sigil has no command-line interface (other than passing the path to a document for Sigil to open as an argument). There's no way to get the version via cli.

**Comment by JPRuehmann** [comment]
but this should be at least possible

**Comment by dougmassay** [comment]
That is only your opinion. Sigil has lived a long and happy life without this ability. It's a gui-only application. As such here is no need for cli-switches or options.

**Comment by JPRuehmann** [comment]
hat is maybe right.
But is it that complicated to implement a -v or to print the version at start to stdout?
that could make the update process much simpler.
But if you hate the command line that much than may it so.

**Comment by kevinhendricks** [comment]
If Windows or Mac, Sigil will check if updates exist upon start-up and alert the user.
For Linux, I am pretty sure an easily crafted 'grep' of 'strings' run on the Sigil executable can easily and reliably extract the version info.

**Comment by JPRuehmann** [comment]
I will try that, Thanks.
I am a Linux user.

**Comment by eli-schwartz** [comment]
How did you install Sigil? If it was from the distro repositories, your package manager should have the information you need, besides which I am curious to know where you intend on getting an updated version *from*.

If you are building from git, you could -- and should -- simply re-run `make install` every time `git pull` results in new commits. Version numbers wouldn't help in that case, as Sigil does not know how to set the version from git.
Although ideally you would build a package to be installed by your package manager. This is trivially easy in Arch Linux (I maintain the [sigil-git](https://aur.archlinux.org/packages/sigil-git) package there), no idea how to do that on debian-based systems though.

...

@dougmassay, there are a number of other GUI-only programs which have a --version switch. Although granted it is not really important in any way.

**Comment by JPRuehmann** [comment]
I am usin Github and have written a Skript that does the Updating for me and than sends an Email with the old and new Version in it so I can see that there was realy an Update.

The following did the Trick for me.
       grep -ia "\<ncx>" /usr/local/lib/sigil/sigil | grep -iao "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}"
Thanks,
