### ISSUE TITLE
Help does not Work

### ISSUE THREAD

**Issue by JPRuehmann** [Sigil-Ebook/Sigil#260]
Hello
Is it right that none of the Entrys in the Help Menue do anything?
Thanks

**Comment by dougmassay** [comment]
Yes. The Help entries do nothing. The user manual can be found in the docs folder of Sigil's source. Help can also be had at Sigil's subforum at Mobileread.com.

**Comment by JPRuehmann** [comment]
When will it work again or delete the Menue?

**Comment by dougmassay** [comment]
It's just not a high priority area, right now. Patches or Pull Requests will always be fairly evaluated for incorporation, though.
