### ISSUE TITLE
Sigil by adding blank paragraphs

### ISSUE THREAD

**Issue by vltncr** [Sigil-Ebook/Sigil#262]
Sigil by adding blank paragraphs whenever you copy web page content, both in the book viewer and in the code viewer.

-------------------------------

Text shown in any web browser: 

<p ALIGN="JUSTIFY">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Falsidade ideológica</b></p>

<p ALIGN="JUSTIFY">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Art. 299 - Omitir, (...) relevante:</p>

<p ALIGN="JUSTIFY">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pena - (...) particular.</p>

<p ALIGN="JUSTIFY">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Parágrafo único - (...) parte.</p>

--------------------------------------

Code resulting from a copy of the web browser and paste into the sigil:

<p> Falsidade ideológica</p>
<p><br /></p>
<p>        Art. 299 - Omitir, (...) relevante:</p>
<p><br /></p>
<p>        Pena - (...) particular.</p>
<p><br /></p>
<p>        Parágrafo único - (...) parte. </p>

----------------------------------

Sigil 0.9.7 - Windows 10

Follows print:

[Desenho sem título.pdf](https://github.com/Sigil-Ebook/Sigil/files/624553/Desenho.sem.titulo.pdf)
![desenho sem titulo](https://cloud.githubusercontent.com/assets/24294511/20794164/f8f71896-b7b1-11e6-8d96-fdc9f421636c.png)

Thank you

**Comment by dougmassay** [comment]
Need a few specifics. You say you're copying/pasting "code", but I'm only seeing text. Did GitHub eat the tags, or are you, in fact, copying text from a browser (and not code)?

Also, when you paste into Sigil, are you being given any options as to whether you want to past formatted text or plain-text? If so, which are you choosing?

**Comment by vltncr** [comment]
Excuse me. I'm copying text. I made the correction of the post.

I am using the Paste Plain Text Only option. Note that the bold was not copied.

**Comment by dougmassay** [comment]
I'm afraid this may be out of Sigil's hands. Sigil relies on Qt's QWebPage::PasteAndMatchStyle WebAction when pasting plain text into Book View. I'll keep this open while I do some more investigating, but I don't currently see any way of influencing this. It's between Qt, the clipboard, and the existing code the clipboard's content is being pasted into.

**Comment by vltncr** [comment]
Truth. I pasted into notepad now and it occurred to the same problem (including lines).

**Comment by dougmassay** [comment]
Closing for now. I can't think of a feasible way to affect this entirely Qt feature.
