### ISSUE TITLE
compatibility javascript

### ISSUE THREAD

**Issue by italianplayer** [Sigil-Ebook/Sigil#263]
I tested a javascript widget with kotobee-author and it works.
but the create .EPUB3 file, sigil does not read (upgrade to 0.97)
the problem is the browser engine? What uses sigil? WebKit?
thanks

**Comment by kevinhendricks** [comment]
There is no such thing as an ".epub3" file.  There is only a .epub file which uses version set to 3.0 in the opf.  

And yes, Sigil's Preview and BookView are based on WebKit.

That said, if your javascript widgets do not follow Sigil's folder guidelines, they will most likely not work without changing the directory structure of the javascript widget as Sigil reformats the epub to meet these guidelines upon first load.  So standard javascript widgets that are not single javascript files that are stored in Misc/ will need to be changed to make things work within Sigil.

**Comment by italianplayer** [comment]
ok thanks for the reply,
I read the book properly with kotobee or calibre,
I did not know that sigil  only read own javascript structure to read complex book+js

**Comment by kevinhendricks** [comment]
It all depends on how paths are set or used in your javascripts.  For most javascripts, when an ebook is loaded in Sigil for editing, all javascript files are automatically moved to the Misc/ directory and the links to it from the html are all updated properly to keep things in sync.  

Issues only occur if your javascript assumes a hard-coded path within the ebook structure to some other resource.  This often happens with pre-designed widgets which assume a specific directory structure for the ebook and for the widget.  If you have one of those, you can hand edit the widget's javascript to allow it to work with Sigil's preferred editing directory structure.  It should then work in all other readers that support javascript.

**Comment by fatmaozcelik** [comment]
Hello @kevinhendricks,
I have some problem with sigil. I wanna build ebook and I have html document with JS code blocks and some multimedia elements in it. I tried to import this html file in sigil but unfortunately I could not accomplish it. Can you help me please ?

**Comment by kevinhendricks** [comment]
Sigil in epub3 supports javascript but on first import will move all javascripts to the Misc folder just like it moves all chapters to the Text folder and all images to the Images folder.  The Sigil code automatically updates all links and things during the initial import.  But sometimes, some javascripts are not smart enough to determine their location dynamically and are hard coded. Other times, the user has hardcoded the paths to the javascripts.  These would need to be fixed to adhere to the standard layout for an epub that Sigil enforces.  Once that is done, it should just pretty much work.

A better place to discuss this would be on the Sigil User's Forum at www.mobileread.com/forums

**Comment by Tymczas** [comment]
> I tested a javascript widget with kotobee-author and it works.
+italianplayer 
Can you give me some advices cause I need to do some JS in Kotabee but there is not much info around
 thanks in advance

**Comment by dougmassay** [comment]
Looks like one we can close as well, no?

**Comment by kevinhendricks** [comment]
yes any javascript issues that still exist are either device specific or caused by a combination of our forced folder structure and non-position independent code.  Nothing we can do about it util we stop forcing a folder structure
