### ISSUE TITLE
Add support for opening an epub-unzipped folder and exporting as an epub.

### ISSUE THREAD

**Issue by padicao2010** [Sigil-Ebook/Sigil#264]
As epub is an binary format, Git can not track its detailed modification as far as I know.

So sometimes it would be nice to operate directly on an epub-unzipped-format folder rather than an epub file.

**Comment by dougmassay** [comment]
Attribute order in (x)html/xml can often change. Making it a nightmare for diffing programs to keep track of what "actually" changed in an epub. So even if Sigil could open an oebps folder strucure, it very likely wouldn't be that useful for git tracking.

Still ... this is why the ability to write input/output plugns was added to Sigil. Someone could write an input plugin to read the contents of a local git repo, and an export plugin to write the contents back to the repo after editing. It still wouldn't help with changing attribute orders, but it would be a start.

**Comment by eli-schwartz** [comment]
Note that you can do this in calibre, if you **really** need it. Added in calibre v2.41.0
