### ISSUE TITLE
Epub3 editing error with file

### ISSUE THREAD

**Issue by kyumyomyoichigome** [Sigil-Ebook/Sigil#265]
If Epub with prepared illustrations etc is opened and saved with Sigil, if the location of the file differs from the Sigil standard folder structure such as OEBPS \ image etc., the illustrations will not be recognized and will disappear.

The file before editing clears the verification of Epub Check.

**Comment by dougmassay** [comment]
Only if they're improperly manifested n the frst place, will assets disappear from the epub. The opf manifest is how Sigil is able to rearrange the structure/files to suit its internal needs. If everythng is properly manifested to begin with, there should be no problem.

If you have an example of an epub with properly manifested assets that Sigil damages, we'll be happy to take a look. Just post a link to a sample epub we can download.

**Comment by kevinhendricks** [comment]
Also case matters in the manifest and spine but many file systems ignore it.  Please verify that filenames in manifest href exactly match (case and letter) actual files in the epub.

**Comment by kevinhendricks** [comment]
Also verify images are not being loaded with javascript widgets and are properly linked using img or svg image tags.

**Comment by kevinhendricks** [comment]
Simply can not recreate this.  Therefore I am closing this report.  If you have a testcase epub that illustrates this, please post a link on mobilread.com in a pm to KevinH or DiapDealer and we will reopen this issue.
