### ISSUE TITLE
Sigil seg faults when inserting files if running in a Linux Wayland Gnome Shell

### ISSUE THREAD

**Issue by joefidler** [Sigil-Ebook/Sigil#267]
Sigil segmentation faults when inserting files if I am running in a Linux Wayland Gnome Shell (Fedora Linux 25) session. Running Sigil from command line I get:

        (sigil:9740): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
        Segmentation fault (core dumped)

Sigil version: 0.9.6
Loaded Qt: 5.7.1

Linux desktop is Fedora 25 running Gnome shell, with a Wayland compositor session. Since release 25, Wayland is the default compositor for Fedora sessions. The error does not occur when I switch the desktop to run in a Gnome shell Xorg session.

I have found 2 ways to recreate consistently :

* From Sigil File Menu,  select Add , then Existing Files  
 or 
* From Sigil Insert menu, select File. Then in the Insert File dialog hit the "Other Files" button.

If you need me to capture any more diagnostics please let me know.
Cheers, joe.

**Comment by kevinhendricks** [comment]
Closing - this is a known bug in Qt 5.7.X series ...

See https://bugreports.qt.io/browse/QTBUG-55583

**Comment by kevinhendricks** [comment]
ps  - Just in case you build your own Qt, here is the patch that I think is under review for Qt 5.8 to fix this:
https://codereview.qt-project.org/#/c/179124/

**Comment by joefidler** [comment]
No I don't build QT myself so will have to wait for it to come through the normal repo updates. So I can't confirm this fix, but it sure sounds like it from the description. Thanks for the fast response. Just finished writing a book in Sigil and love it - thanks for all your hard work.cheers, Joe.

**Comment by eli-schwartz** [comment]
FWIW: The fix is not "under review", it was merged.
And Arch Linux at least, has cherry-picked that patch for our qt5-base 5.7.{0,1} packages, I think it would be reasonable to ask Fedora to do so as well if they haven't already. ;)

**Comment by joefidler** [comment]
Fedora 25 is now updated with the patch to qt5-base 5.7.1. Thanks @eli-schwartz,  @kevinhendricks  for the heads up. Confirming that Sigil now works under Wayland without the seg fault.

**Comment by mapreri** [comment]
Quick note to say that that patch is going to be in the next update of Qt 5.7 in Debian (unstable) too.  That's also what is going to be in the next stable release (Debian 9/stretch).
