### ISSUE TITLE
"Add Semantics" no longer shows what role is assigned to a file

### ISSUE THREAD

**Issue by larrykollar** [Sigil-Ebook/Sigil#268]
Sigil 0.9.7, MacOSX 10.11.6

Steps to reproduce:

1.  Open Sigil and any EPUB 2 book.
2.  Right-click (or Ctrl-click) the cover page to open the context menu, and select Add Semantics.
3.  Choose "Cover" from the list and click OK.
4.  Re-open Add Semantics for the cover page. There is no indication that Cover has already been selected.

The same behavior is in 0.9.6. I think 0.9.5 worked properly, when "Add Semantics" opened a sub-menu from the context menu. In those earlier versions, the assigned role had a checkmark.

**Comment by kevinhendricks** [comment]
Closing - Semantics are no longer menu items - works as designed.

Simply mouse-over any xhtml file in BookBrowser to see any semantics set on that file.  Mouse-over works this way in all versions of Sigil even old ones. 

If want to see all semantics set at one time open opf in epub2 or nav in epub3
