### ISSUE TITLE
api-ms-win-crt-runtime-1-1-0.dll is missing from my computer

### ISSUE THREAD

**Issue by CJClink** [Sigil-Ebook/Sigil#270]
I had a previous version of Sigil on my computer. I think 0.9.6 -- I last used it in October.

When I went to start it, it said there was a newer version available and did I want it. I said yes.

I selected the windows download that was not the 64 option for the new 0.9.7 version of Sigil. I only have 32 bit, and I assumed the 64 was for 64 bit machines. I run Windows 7 with 32 bits.

First it hung up on the C++ download, so I cancelled it. Then it seemed to say that Sigil was finished downloading.

When I clicked on the shortcut, I got the message:
The program cannot start because api-ms-win-crt-runtime-1-1-0.dll is missing from your computer Try reinstalling the program to fix this problem.

So, I tried that (with no hangup on the C++) but still got the same message trying to open Sigil.

I am not a maven, so I do not know what to do now.

Thank you!

**Comment by CJClink** [comment]
Ah, sorry, this looks like a Windows 7 problem, not a Sigil problem. I will pursue updating Windows 7...

**Comment by dougmassay** [comment]
Windows 7 must have Service Pack 1 installed to successfully install the Visual Studio 2015 runtme that comes with Sigil v0.9.7.

**Comment by CJClink** [comment]
Well... first I mistyped the missing file name, it's actually:
api-ms-win-crt-runtime-l1-1-0.dll
So, 5 hours later, and many attempted updates... I have removed the Sigil v0.9.7 and put the older v0.9.6 back on my computer. That still works, anyways. :)  
At some point, I'll try again.

**Comment by dougmassay** [comment]
Make sure you have Service Pack 1 installed (and a functioning update subsystem) on your Windows 7 system, and you should be good to go for Sigil v0.9.7+

I'm going to close this issue, now.
