### ISSUE TITLE
Is it a problem that the cover.xhtml code not the same when replacing an old cover with a new cover?

### ISSUE THREAD

**Issue by CJClink** [Sigil-Ebook/Sigil#271]
This is Sigil 0.9.6 -- I'm updating the covers on 8 epubs (epub 3 files) and have been using the ADD COVER on the TOOLS menu and uploading a new cover. I then delete the old image and give the new cover image the name Color.jpg (as the actual name of the image is long). I noticed that the code on the ORIGINAL cover.xhtml page is different than the code on the NEW cover page -- somehow the ADD COVER puts in different code.  (no alt tag, for instance) ( I have not been able to update to the new Sigil due to a missing file issue, so that won't help me.) 

The "new" code still validates (on EPUB Validator (beta), so I guess I'm just wondering if it's a problem or not.

Original cover.xhtml code:
![image](https://cloud.githubusercontent.com/assets/17130341/21952751/dc37e642-d9f1-11e6-9a96-ad46c9d5dfc2.png)

New cover.xhtml Code:
![image](https://cloud.githubusercontent.com/assets/17130341/21952766/12a86468-d9f2-11e6-8c98-eadd37db7fdf.png)

Thanks!

**Comment by kevinhendricks** [comment]
Closing - This is *not* a bug.  The code in question is valid and the use of svg assures the cover will properly fill the device screen.

Questions of this sort should not be asked by reporting a bug here.  For support, please use our Sigil user forums found at http://www.mobileread.com/forums as is explained in the ReadMe that is displayed when you come to this site.

**Comment by eli-schwartz** [comment]
You're not replacing the cover image though... if you did that then the cover.xhtml would work as-is.

Sigil is correctly doing exactly what you told it to do -- discard the old cover and generate a new one.

**Comment by CJClink** [comment]
Sorry for posting this in the wrong place -- your group has always kindly helped me. And yes, Eli, that's what I did. But, I noticed the code was quite different on the newly generated page. I guess Kevin is saying it is improved code -- which is fine by me. :)
