### ISSUE TITLE
Translation: duplicate languages

### ISSUE THREAD

**Issue by bershan2** [Sigil-Ebook/Sigil#272]
Dear @kevinhendricks and whom it may concern,

I have been working on Russian translation and noticed that there are duplicates of a few languages. (for record: I first wrote to zdpo, who approved me joining translation teams, via transifex messages and he recommended to write here.)

Therefore I propose:

1. remove "Russian (Russia) (ru_RU)", which has no translations in it at all, and merely duplicates "Russian (ru)";

2. remove either one of "Ukrainian (Ukraine) (uk_UA)" or "Ukrainian (uk)", after backing up translated strings.
If you can exporting translations into a file similar to ones at https://github.com/Sigil-Ebook/Sigil/blob/master/src/Resource_Files/ts/, that'll be enough for me. I'll start working on Ukrainian translation soon after finishing Russian, and I'll merge translations first thing. Or we could leave it for now and I'll ask you to remove it once I move translations.
I'm not sure which one is better ("ua" or "uk"), since all formal documents list "uk", but "ua" is by far more common in day-to-day use (.ua domain in DNS, UA inscription in the language selection menus, UA stickers on windshields of cars traveling abroad, etc.) In fact, I have never seen "uk" anywhere but in ISO code tables.

There are a few more languages with duplicates, but I do not have expertise to call for their removal. On the other hand, there should be only one Ukrainian and only one Russian. (Although both languages have some differences, e.g. Russian spoken in Saint-Peterborough vs. usual Russian and Ukrainian of West- and East-Ukraine, there is absolutely no point in maintaining multiple versions of translations.)

**Comment by kevinhendricks** [comment]
Duplicate languages is not a real concern as Sigil only ships with translations files that have 30% or more of the translations complete.  The ru_RU should not meet this criteria if it is empty.  As for the Ukrainian one - I did not want to lose any information and have no ability to tell which is better or more correct.

Also, given governmental and political forces driving translations (ie. Taiwan vs Mainland China, Middle Eastern issues, etc, Russia vs ? ... etc) I simply do not want to get into the business of saying which translations are "more correct" or "more official" and for which regions.

Therefore the more translations the merrier.

Just choose which project or projects you want to add translations for and add them.  Once any translations for any language reaches the 30% of source strings threshold they will be automatically included in the next release of Sigil. As Sigil code is modified and the string change, any inactive languages will soon fail to meet the 30% threshold.  These "inactive" translations will never be  downloaded and never included in Sigil.

Closing this as it is not an issue that I feel can and should be addressed by Sigil for political reasons.  Any active translations that meet or exceed the threshold will be included in Sigil.
