### ISSUE TITLE
colin

### ISSUE THREAD

**Issue by colin-Prime** [Sigil-Ebook/Sigil#274]
I use SIGIL and it is great. 

However, I encountered a minor issue.  I import an image --- then insert the image all ok it generates something like the code below.

<p style="text-align: center;"><img alt="21f-table" src="../Images/21f-table.jpg"/><br/></p>

No problem so far.   
I then find I need to reorder the images due to let's say inserting a figure preceding this and so I go to images and RENAME the file above to 21g-table.jpg   {instead of f} .  
Again so far ok it renames the file in the IMAGES directory
What I find is it DOES DO is update the src=...... part of the aboe code 
but does **NOT** update the alt="....... which stays as the OLD file name.
It's only very and so I either delete image and reinsert or MANUALLY change the code.
Otherwise for me great Programme

**Comment by dougmassay** [comment]
There is no reason for sigil to automatically update the "alt" attribute of an img tag during a file rename. That you choose to put the file name as the value of the alt attribute is neither here nor there. Sigil only updates the filenames that affect the functionality of an epub.
