### ISSUE TITLE
A Sigil 0.97 panel appears in greek language.

### ISSUE THREAD

**Issue by dankom** [Sigil-Ebook/Sigil#279]
Despite my user language is Italian, in Sigil (version 0.97) screen, bottom right, appears a panel 
in Greek language.
I attach a screenshot with the panel highlighted in red.
![screen_001](https://cloud.githubusercontent.com/assets/9793115/22865762/d87f41ea-f16a-11e6-8165-8f57427b2e6c.png)

**Comment by kevinhendricks** [comment]
That is the standard web inspector widget, we do not modify that widget in Sigil as its menus and dialogs are internal to Qt.  So it appears for some reason your version of Qt is missing the standard internal translations for your language.  Not sure why or how to fix that as it is internal to Qt.

**Comment by dankom** [comment]
I do not have QT installed directly, thus the QT package must be in the installation of Sigil.
I checked the settings on my computer, and all locales refer to the Italian language.
I also tried to eliminate from the Translations folder all translations except sigil.it, but the problem remains.
All that remains to me to try to downgrade to version 0.74 (which was displaying the widget correctly)

**Comment by dankom** [comment]
I do not have QT installed directly, thus the QT package must be in the 
installation of Sigil.
I checked the settings on my computer, and all locales refer to the 
Italian language.
I also tried to eliminate from the Translations folder all translations 
except sigil.it, but the problem remains.
All that remains to me to try to downgrade to version 0.74 (which was 
displaying the widget correctly).


Thank you for your help.


Il 14/02/2017 15:58, Kevin Hendricks ha scritto:

**Comment by dankom** [comment]
Thank you for

**Comment by dankom** [comment]
I do not have QT installed directly, thus the QT package must be in the installation of Sigil.
I checked the settings on my computer, and all locales refer to the Italian language.
I also tried to eliminate from the Translations folder all translations except sigil.it, but the problem remains.
All that remains to me to try to downgrade to version 0.74 (which was displaying the widget correctly).


Thank you for your help.

**Comment by dougmassay** [comment]
In my experience, changing Sigil's UI language in the preferences has absolutely no effect on the web inspector's language. I tried changing Sigil's UI language (Sigil v0.9.7) to Italian on Linux and on Windows and after the restart, Sigil's UI was Italian, but the web inspector widget remained English. Perhaps there's an environment variable in play somewhere?

**Comment by kevinhendricks** [comment]
There are Qt internal ts files for internal menus and dialogs.  The inspector is a webkit widget.  Perhaps the internal translations needed by webkit widgets are getting lost in the build process.

**Comment by kevinhendricks** [comment]
Closing this as bug report could not be recreated.
