### ISSUE TITLE
Sigil deletes complete directory content

### ISSUE THREAD

**Issue by ezazatesz** [Sigil-Ebook/Sigil#280]
Hi all, 

when opening an epub Sigil 0.9.7 randomly quits and erases all other files from the folder. This only happened to me when the files were on the desktop or in the downloads folder of my browser. The files get completely erased (not recovereble from the recycle bin, the only way to restore the folder content is using getdataback or recuva). OS: windows10. 

Any ideas? Thanks!

**Comment by dougmassay** [comment]
The only directory Sigil could _possibly_ delete is its own temporary scratch directory. And that directory is not intended to persist after Sigil closes (nor is the content there intended to manipulated by anything other than the current instance of Sigil).

If you've relocated/redefined your Sigil temp directory via Sigil's preferences, that's fine. But the contents of that temp directory will always be deleted when Sigil exits. That's intended behavior.

As for Sigil "randomly quitting," you'll need to provide step by step instructions on how to recreate the issue. There have been no other reports of Sigil randomly quitting on any platform.

**Comment by kevinhendricks** [comment]
If it is constantly crashing and erasing things, then you have somehow written files into Sigil's temporary scratch space, which you had to work hard to do as Sigil uses uuid based directory naming  and secure directory creation to create its scratch space.  Simply stop writing files into or changing the contents of scratch directories that Sigil creates.

**Comment by kevinhendricks** [comment]
duplicate of bug reported and fixed in Issue # 285
