### ISSUE TITLE
Installing on Mac

### ISSUE THREAD

**Issue by peterdragon** [Sigil-Ebook/Sigil#281]
Hi, a suggestion to improve the installation instructions on Mac, as seen in 
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.7.

Many Mac users manage packages more simply by using homebrew and cask. You can install from the command line, don't have to remember all the source websites for packages, and you get the latest updates easily. 

Install homebrew as described at https://brew.sh 
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
and cask as described at https://caskroom.github.io/
$ brew tap caskroom/cask

Then to install active tcl v8.6.4.1 and sigil v0.9.7:
$ brew install Caskroom/cask/tcl
$ brew install Caskroom/cask/sigil

When later package releases come up, users can upgrade with
$ brew upgrade Caskroom/cask/sigil 

Regards, Peter

**Comment by kevinhendricks** [comment]
Sorry,
I am not a fan of Homebrew tried it a few years back.  Simply horrible, way too much breakage on OSX Updates and XCode updates, unneeded and some times incorrect build patches, putting things in /usr/local with no real versioning going on, etc, etc.  

And more importantly most ebook authors are NOT command line specialists or command line users.

The current Sigil installation is a dmg.  The package is self-contained, needs no installer, and can be installed anyplace (fully relocatable) just like any other Mac gui application.  Homebrew would simply be a step backwards in that regard.

Thanks
