### ISSUE TITLE
CTRL+e shortcut doesn't work.

### ISSUE THREAD

**Issue by Bystroushaak** [Sigil-Ebook/Sigil#282]
When I assign the `CTRL+e` shortcut, it doesn't work and jumps to end of the line instead.

```
Sigil versions: 0.9.5, 0.9,7.
QT version: 5.5.1
OS: Linux mint 18.1 Serena
```

This behavior is consistent with readline and other default linux textarea behavior, but I think it should be possible to remap it.

**Comment by Bystroushaak** [comment]
I am trying to use `CTRL+e` for striketrought text.

**Comment by dougmassay** [comment]
Use Clips to wrap highlighted text with <del> (or other) tags. You can
assign whatever keyboard shortcuts you like to your clips.

**Comment by Bystroushaak** [comment]
Nope, still doesn't work. To further clarify, it doesn't work in html render view, it works in source code view.

**Comment by dougmassay** [comment]
It's not intended to work in "render" (Book) View. Clips should be applied
in Code View.

**Comment by Bystroushaak** [comment]
Okay.

I don't want to be pain in the ass, but it works with other shortcuts (I am using it with `CTRL+d`), so why not with `CTRL+e`?

**Comment by dougmassay** [comment]
And for what it's worth ... unassigning the Ctrl+E shortcut from the "Centering" function, and reassigning it to the "Strikethrough" function via Sigil's Shortcut Manager allows me to use it in either Book View or Code View on my Linux system (though I don;t recommend using it in Book View _at all_).

You must have a system shortcut of some kind that's interfering.

**Comment by Bystroushaak** [comment]
Ok, thanks for help. You are doing great work!
