### ISSUE TITLE
Feature request: Allow saving epub as directory structure

### ISSUE THREAD

**Issue by Bystroushaak** [Sigil-Ebook/Sigil#283]
I think it would be great, if there was possibility to save and read directory structure, instead of .epub (which is just zipped directory structure).

This would made possible to use version control systems with greater granularity, which would allow for better collaboration in teams. It would also made smaller network footprint when synchronizing via services like Dropbox or Syncthing.

**Comment by kevinhendricks** [comment]
The way to achieve what you want is via the Sigil plugin interface.  It is not hard to write an input plugin to read an expanded folder, and an output plugin to go the other way.  This is not something we want in Sigil proper as it will just confuse users, especially Windows users whose gui makes it easy to confuse zip and unzipped folders.

**Comment by eli-schwartz** [comment]
Previously rejected in #264...

**Comment by wzyboy** [comment]
> The way to achieve what you want is via the Sigil plugin interface. It is not hard to write an input plugin to read an expanded folder, and an output plugin to go the other way.

I searched for a while and found such a pair of plugins in MobileRead: https://www.mobileread.com/forums/showthread.php?t=293649

... and I realized you are the author of the plugins!

Just want to say thanks. And may this link help others who found their way here.
