### ISSUE TITLE
Crash on osX 10.10.5

### ISSUE THREAD

**Issue by Cocolinlin** [Sigil-Ebook/Sigil#286]
Sygil 0.9.8 crashes on open

(0.9.7 still fine)

**Comment by kevinhendricks** [comment]
Just updated a new build for Mac OSX of Sigil 0.9.8 that will hopefully work back to Mac OS X 10.9.  Tested on OSX 10.11 and OSX 10.12.  Please let me know if this fixes your issue for OSX 10.10

**Comment by kevinhendricks** [comment]
The new build is available in Releases

**Comment by kevinhendricks** [comment]
closing as fixed according to testers

**Comment by Cocolinlin** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thanks for your good work, KevinAnd sorry for this late answerI was travelling for work till yesterday


Envoyé depuis Yahoo Mail pour iPhone


Le vendredi, mars 24, 2017, 21:28, Kevin Hendricks <notifications@github.com> a écrit :


Closed #286.
