### ISSUE TITLE
Sigil preview video

### ISSUE THREAD

**Issue by javipe19** [Sigil-Ebook/Sigil#287]
The Sigil previewer won't reproduce any video. Currently using the 0.9.8 version. The type of the source is video/mp4.

**Comment by dougmassay** [comment]
Windows? Mac? Linux?

On Windows, media playback relies on media player being able to play the codec in question. You may have install some codecs for it to work.

On Linux, media playback relies on the correct gstreamer plugins being installed for the media type being used.

**Comment by kevinhendricks** [comment]
I have a simple epub3 with one mp4 video and it loads just fine and plays perfectly in Sigil in Preview and in BookView.

This is with the latest Mac OSX build.

I simply can not recreate your issue on any of my OSX machines.

**Comment by javipe19** [comment]
I'm using Windows. I think I have all the right codecs installed since it can be played in the windows media player. Maybe It has something to do with the configuration of the sigil web console? or the activex plugin?

This is the look of the preview:
![image](https://cloud.githubusercontent.com/assets/13244439/25312715/7f401770-2820-11e7-99d8-be5e2a549a88.png)

Thank you for the quick responses.

Regards

**Comment by kevinhendricks** [comment]
Are you sure it is a true mp4?  What happens if you double-click on the *.mp4 file in the Video folder inside Sigil's File Browser?  Does the xhtml point to the right tag with the video tag's src attribute?

**Comment by dougmassay** [comment]
After installing a third-party codec pack (directshow-compatible), I'm able to preview an mp4 video sample added to an epub with Sigil 0.9.8 on Windows Vista (with Media Player 11).

What version of Windows/Windows Media Player are you using?

**Comment by dougmassay** [comment]
There very well could be some issues with multimedia-playback on Windows 7 (or higher). I can't play my sample video in a Windows 7 Virtual machine. I'll have to try on a physical Win7 machine when I get some time.

Qt Multimedia is such a nightmare in general, but it's especially frustrating on Windows where you have Qt choices between OpenGL (hardware/software depending on the graphics adapter's capability), Angle, or a dynamic version which claims to be able to be able to choose from all the above on the fly. Then you have to choose between directshow vs. a wmf backend that doesn't seem to behave consistently from Windows version to Windows version.

I'll do some more experimenting and focus on making sure things work for Windows 7 onward.

**Comment by javipe19** [comment]
@kevinhendricks Yes, it does point to the right tag. When I double click in the video file, the xhtml is opened (the one in which the video tag is defined). I also tried with another video files such as a standard .webm from the official page: http://www.webmfiles.org/demo-files/ but I get the same result.

@dougmassay I am using Windows 10 and the version of the Windows Media Player is this one:

![image](https://cloud.githubusercontent.com/assets/13244439/25345266/e8f58796-2914-11e7-9a91-214b6f4a27fd.png)

Thank you

**Comment by dougmassay** [comment]
Thanks for the info. Version 12 of WMP should play mp4 video inherently (no 3rd-party codecs required). I'm able to duplicate your issue on Windows 7 (mp4 video plays in Windows Media player, but NOT in an epub in Sigil 0.9.8).

I'll try to track down the problem.

**Comment by javipe19** [comment]
Thank you. In the meantime, do you have a specific video that you know for sure that it works so I could try it?

**Comment by kevinhendricks** [comment]
Here is a link that will let you download a short video in a webm, mp4, and ogv formats.

I tried this mp4 video in Sigil and it displays just fine:

https://camendesign.com/code/video_for_everybody/test.html

Download big_buck_bunny.mp4

It is a one minute excerpt from a Creative Commons Licensed Movie (Big Buck Bunny).

Here is what the xhtml page to load it would look like:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<link href="../Styles/my_style_sheet.css" type="text/css" rel="stylesheet"/>
<title></title>
</head>
<body>
<video width="400" controls="controls">
  <source type="video/mp4" src="../Video/big_buck_bunny.mp4"/>
  Your browser does not support HTML5 video.
</video>
<p>Video courtesy of <a target="_blank" href="http://www.bigbuckbunny.org/">Big Buck Bunny</a>.</p>
</body>
</html>
```

**Comment by javipe19** [comment]
It does not work for me...

**Comment by dougmassay** [comment]
Yes. It appears that the version of Qt5.6.2 that I build for Windows is not supporting the WMF engine, but rather defaulting to directshow instead. According to my research, that is not what should be happening with the configuration I used for building Qt5. Both should be supported.

It appears both multimedia engine choices for Windows are quite unreliable, depending on the platform.

I'll have to try disabling the directshow engine entirely in Qt5\WebKit and specifically enable the Windows Media Foundation engine. That should help with media playback on Windows 7 forward, but it's another nail in the coffin for full Sigil support on Vista, I'm afraid.

I'll ping this issue when I have a test version of Sigil to try.

**Comment by Taebu** [comment]
i will make still image use poster attribute
```html
<video controls="controls" width="320" height="240" poster="../Images/test.png" src="../Video/test.mp4">test</video>
```

**Comment by whitehairzoids** [comment]
@javipe19 
I have the same issue and found your post today. 2017/7/25
And I follow @dougmassay  suggestion to download codec from here:
http://www.mediaplayercodecpack.com/

After that my issue was resolved.
(Kind of resolved, the preview bar become very weird, and preview video is darker than original one)

Wish this input helps.

**Comment by dougmassay** [comment]
Thank for letting me know. But from Windows 7 on ... Qt/Webkit (and thus Sigil) should be able to play mp4 video without any codecs being installed.

**Comment by dougmassay** [comment]
Big Buck Bunny is performing quite admirably with the very latest Sigil on Windows 7 and higher. Closing this issue.
