### ISSUE TITLE
Sigil GTK3?

### ISSUE THREAD

**Issue by Momoe** [Sigil-Ebook/Sigil#292]
Hi hiii~

I was browsing through dA and found that someone made a nice vizual mock up of what sigil could look like with the Linux GTK3 frame work. I was hoping I could share it here and maybe inspire the creator to take a look at making a gnome compatible variation of Sigil to better encorporate into the user experience? 

[http://aldomann.deviantart.com/art/Sigil-GTK-3-redesign-485211945](url) ![Image of SigilGTK](http://orig01.deviantart.net/499e/f/2016/117/9/6/sigil_gtk_3_redesign_by_aldomann-d80vrxl.png)

All the best, 
-Momoe

**Comment by dougmassay** [comment]
It looks nice. Unfortunately, Sigil is a cross-platform, single code-base, Qt5 application. A Linux-only, GTK3 Sigil variant would need to be a project that someone else volunteers to undertake/maintain. The various Linux software repos are also free to incorporate their own themes (including gtk3) into their Qt5/Sigil packages, if they like. Many already do.

This is not really the place for feature-requests, by the way. The issue system is reserved for bug reports or build errors.
