### ISSUE TITLE
Icon not display after re-order files

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#294]
There're icons before each item of file list.

![bug1](https://cloud.githubusercontent.com/assets/1551595/26144423/5b4fef30-3b1b-11e7-80f1-afb86e263018.png)

Drag&drop a file item to re-order it. Now the icon before 098.xhtml is missing.

![bug2](https://cloud.githubusercontent.com/assets/1551595/26144424/5d74e658-3b1b-11e7-9f99-20d41397b9c8.png)

Sigil 0.9.8

**Comment by dougmassay** [comment]
Yes. This cosmetic issue has been mentioned other places and verified. It's been around for quite a few versions, actually. I'll leave this issue open to serve as a reminder to look into it.

Thanks for the report.

**Comment by dougmassay** [comment]
Fixed as of commit ecb56b1fe5. Closing this issue. Thanks for your report.
