### ISSUE TITLE
Error XML not well formed

### ISSUE THREAD

**Issue by beellis** [Sigil-Ebook/Sigil#295]
Hi there, 
                 I am rather new to the ebook world. I am have converted a word doc to xhtml using notepad++ and want to clean it up in sigil. It keep coming up with this error:

> Error XML not well formed: attribute name near column 11

When I go that section is shows:

`<dc:dc:date opf:event="publication" opf:scheme="DCTERMS.W3CDTF">2017-05-25T11:24:00</dc:dc:date>`

I don't see what is wrong with it..any thoughts or suggestions? Thanks

```
<?xml version="1.0" encoding="utf-8" ?>
<package unique-identifier="BookId" version="2.0" xmlns="http://www.idpf.org/2007/opf">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:identifier id="BookId" opf:scheme="UUID">urn:uuid:2bc70065-7d5d-481c-9e1d-338b5ed4dba6</dc:identifier>
    <dc:language opf:scheme="DCTERMS.RFC4646">en-US</dc:language>
    <dc:source>http://xml.openoffice.org/odf2xhtml</dc:source>
    <dc:creator>Briana Ellis</dc:creator>
    <dc:dc:date opf:event="publication" opf:scheme="DCTERMS.W3CDTF">2017-05-25T11:24:00</dc:dc:date>
    <dc:contributor>Briana Ellis</dc:contributor>
    <dc:dc:date opf:event="modification" opf:scheme="DCTERMS.W3CDTF">2017-05-25T11:24:00</dc:dc:date>
    <dc:subject>,</dc:subject>
  </metadata>
  <manifest>
    <item href="toc.ncx" id="ncx" media-type="application/x-dtbncx+xml"/>
    <item href="Text/Carmilla%20V3.xhtml" id="Carmilla_V3.xhtml" media-type="application/xhtml+xml"/>
  </manifest>
  <spine toc="ncx">
    <itemref idref="Carmilla_V3.xhtml"/>
  </spine>
  <guide>
  </guide>
</package>
```

**Comment by dougmassay** [comment]
There's two dc prefixes on both of your date-type metadata entries: dc:dc:date

Should be: dc:date

I don't mind answering questions, but this is really more of a "How do I..." type of question than a Sigil Issue/bug. Mobileread's Sigil/EPUB forums are great resources for learning about Sigil, epubs and for getting "what's wrong with this code?"  support from more advanced users.
