### ISSUE TITLE
Sigil Crash when saving multiple images to New folder

### ISSUE THREAD

**Issue by nonentity1001** [Sigil-Ebook/Sigil#296]
wrong place

**Comment by kevinhendricks** [comment]
Not sure if this is an still an issue for you or not.  This is the right place to file official bug reports for Sigil.

I have tested your bug report on Mac OSX and Linux and can not get Sigil to crash at all.  The multiple images are simply saved in the new folder as expected.  So this is either a bug in Windows Qt or more likely a Shell utility you have on your system that interferes with Sigil’s Qt when you try to use a Native File Dialog box.

Kevin
