### ISSUE TITLE
Regression: Bold/Italic icons in Book View create spans instead of b or i

### ISSUE THREAD

**Issue by larrykollar** [Sigil-Ebook/Sigil#298]
MacOSX 10.11.6, Sigil 0.9.8

Steps to reproduce:

1.  Start Sigil 0.9.7. Add an HTML text file to the blank book.
2.  In Book View, select a string of text and use the **B** or **I** icons (or Cmd-B / Cmd-I) to make the text bold or italic.
3.  Switch to Code View. Verify the text is wrapped in &lt;b> or &lt;i> tags as appropriate.
4.  Quit Sigil
5.  Install and start Sigil 0.9.8. Add an HTML text file to the blank book.
6.  Repeat steps 2 and 3, but note that the text is wrapped in &lt;span> tags instead.

**Note**: I made no other system changes other than updating Sigil.

**Comment by kevinhendricks** [comment]
Yes as BookView editing (mainly determined by internal Qt widgets) started to use incorrect tags we decided to make BookView use the more proper span with class.  Qt's internal widgets supports that.

If you actually care about which tags are used you should be using CodeView not Bookview and html in-line editing built into Qt's webkit provides little to no control of how and which tags are generated.
