### ISSUE TITLE
Linux "cutting edge" build guide

### ISSUE THREAD

**Issue by AFulgens** [Sigil-Ebook/Sigil#301]
Linux [build guide](https://github.com/Sigil-Ebook/Sigil/blob/master/docs/Building_on_cutting_edge_Linux.md) for Ubuntu 16.04+ is missing one step:

In "Getting Qt5" the package `qttools5-dev` and `qttools-5-dev-tools` is missing. w/o these you get a CMake error:

[1] 
```
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```

Additionally, after install the "New Version of Sigil is available (0.9.8)" is shown, however I installed the latest exactly that one :)

Apart from that everything seems to be OK :+1:

**Comment by dougmassay** [comment]
There is no qttools-5-dev-tools package. It's qttools5-dev-tools .. which is clearly included in the instructions. Installing that package installs qttools5-dev as a dependency.

**Comment by AFulgens** [comment]
My bad, typed the package name instead of copy-pasting it into the issue. Hmm... wonder why I have to install `qttools5-dev` independently, if it's a dependency of `qttools5-dev-tools`. Never mind, it's solved now.
