### ISSUE TITLE
Make comment deletion optional (OPF)

### ISSUE THREAD

**Issue by AFulgens** [Sigil-Ebook/Sigil#302]
In OPF files currently comments are auto-deleted. In NCX and (X)HTML that's not the case. Would be great the retain comments in OPF files too.

Use-case: TODOs

**Comment by kevinhendricks** [comment]
Sorry but that will probably not happen.  Each tool used by Sigil that impacts the ebook (add files, remove files, change spine order, change metadata, change semantics, update properties, rename files or extensions, etc, etc makes changes in the opf which is stored in an opf specific set of data structures and not as an xml node tree for speed and ease of manipulation.  Effectively, unlike other files the opf is more under the control of Sigil than any other file.  

Comments are removed as they are not necessary, and are free form (can appear anywhere in the opf) and as such do not fit into the data structures designed to store and manipulate the opf.   If you completely rebuild the ncx from scratch, you will see it drop comments too.   

The only "solution" would be to add a "comments-only" data structure and collect the various comments from where-ever they might be and store them in an comments section between the metadata and the manifest.  Either that or allow one comment section per data structure  - one for the manifest, one for the spine, one for the guide, one for metadata, etc.

That is simply not worth the development time needed just to store comments that no-one reading the ebook will ever see, especially one that touches the critical data structures and code that parses the opf.

You will need some other place to make To-Do notes.   Simply adding an extra temporary xhtml "chapter" with any To-Do items and removing it when done editing in Sigil is probably safest way.

Closing this as it is not an issue/bug but a feature request that I have no immediate plans to implement.

**Comment by AFulgens** [comment]
Thank you for the thorough explanation. I agree with your bottom line, I just wasn't aware of the details.
