### ISSUE TITLE
Validators and Code

### ISSUE THREAD

**Issue by lunanara87** [Sigil-Ebook/Sigil#305]
I use flightcrew plugin with Sigil and when I run it, my ebooks show as no errors. I had a friend who ran their ebook through D2D and Pronoun and they get an issue. I checked again, FlightCrew says no issue. I run it through Epub Validator and I get about a dozen 

ERROR | OEBPS/Text/index_split_011.html | 32 | 23 | Error while parsing file 'element "span" not allowed here; expected the element end-tag or element "address", "blockquote", "del", "div", "dl", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ins", "noscript", "ns:svg", "ol", "p", "pre", "script", "table" or "ul" (with xmlns:ns="http://www.w3.org/2000/svg")'.

of these errors with same issue, just a different file and line/position flag. Anyone understand and can put this in laymen turns WTF is going on?

**Comment by kevinhendricks** [comment]
This is not a bug report.  It is a user support request.  Please use our user support forums on Mobileread (www.mobileread.com) to get answers to your validation questions.   There is an entire community of epub authors and experts at this site who are very generous with helpful advice.  Use either the Sigil forum or the epub forum.

**Comment by lunanara87** [comment]
Sorry. I thought I was in the right spot. Thanks for redirecting me.
