### ISSUE TITLE
sigil adds inline style when changing tags

### ISSUE THREAD

**Issue by tilmanj** [Sigil-Ebook/Sigil#309]
`<p class="hang1"><a id="celist1" class="calibre1"></a><a id="celistitem1" class="calibre1"></a>• <strong class="calibre6">[..]</strong> [..]</p>`

When I change e.g. the `<p>` tag in a `<ul>` sigil adds

`<li><span style="font-size: 1em; line-height: 1.2; text-indent: -1em;">• </span><strong class="calibre6" style="font-size: 1em; line-height: 1.2; text-indent: -1em;"> [..] </strong><span style="font-size: 1em; line-height: 1.2; text-indent: -1em;"> [..] </span><br/></li>`

This makes it very hard for me to make logic html files. No other html editor adds additional style to tags when the tag is changed. There is a reason why I change tags. I want that the style changes. There is also no Setting in preferences to change this behavior.

**Comment by kevinhendricks** [comment]
How did you change the tag?  In Codeview mode, you can easily change tags with no other changes.  If you are edting using Bookview mode, the code generated is determined by the live DOM editing done in a QtWebkit widget.  In general, we do NOT recommend editing in Bookview mode if you want to control all html generated.

Exactly what sequence of steps in Sigil did you use to change the p tag to a ul?

**Comment by kevinhendricks** [comment]
Please feel free to re-open this if once you have added the requested additional information. Closing this  as I simply can not recreate what you are seeing in Codeview or BookView modes.

**Comment by tilmanj** [comment]
I changed it in bookview mode. Because there is no way in Codeview mode to change `<p>`-tags in `<ul><li></li></ul>`-tags. But this explains a lot. When I want to add subscript in Codeview it adds 
a `<sub></sub>` tag, while in Bookview it adds  `<span style="vertical-align=sub"></span>`. This is even not correct: a sub tag in browsers is `<span style="vertical-align=sub;font-text:smaller"></span>` and looks also weird..

**Comment by kevinhendricks** [comment]
Yes, in CodeView you simply type to make changes just like in any other text editor.  Again, what exact sequence of steps did you use in BookView to make your changes.  What did you highlight, what keys/buttons did you yse and in what sequence?

And again, editing a live DOM in Bookview is NOT recommended if you care about the exact html generated.  What you are seeing is the internal DOM representation (after editing) converted back to html.  We do not control the exact code generated.  That us why we recoomend editing in CodeView with Preview visible if you have preferences about the exact html generated when editing.

**Comment by dougmassay** [comment]
We've made sure that edits made in BookView create spec-compliant code that renders properly. We can't (nor would we try to) make QWebKit's widget automatically generate code that satisfies everybody's personal coding sensibilities all the time. Those concerned with maintaining their own, exacting coding conventions should not use Book View to make edits.
