### ISSUE TITLE
Help > Report an Issue is broken

### ISSUE THREAD

**Issue by chrisridd** [Sigil-Ebook/Sigil#31]
It goes to a page https://code.google.com/p/sigil/wiki/ReportingIssues which is no longer on the wiki.

**Comment by charlieman** [comment]
The 0.8.6 version's spanish translation still contains the link to google code: https://github.com/user-none/Sigil/blob/master/src/Resource_Files/ts/sigil_es.ts#L11407

Should I open a new issue?

**Comment by user-none** [comment]
Translations are managed at https://www.transifex.com/projects/p/sigil/ .
