### ISSUE TITLE
UI elements too small on dual monitor system

### ISSUE THREAD

**Issue by Nick-Payne** [Sigil-Ebook/Sigil#310]
Sigil 0.9.8 / Qt 5.6.2 on Windows 10 x64. Primary monitor is 80cm 2560x1600, secondary monitor is 80cm 3840x2160. Sigil UI elements are correctly sized with Sigil window on primary monitor, but with window on secondary monitor, UI elements are too small and too closely spaced. See attached screen dump - the menus all run together, the buttons are too small for the text they contain, the text in the Book Browser and Table Of Contents panes and Find and Replace fields is very small, results fields - eg number of occurrences of a Replace All - are too small to display the result.
![sigil](https://user-images.githubusercontent.com/3879090/29343743-759a18aa-8276-11e7-99b9-0cdc966a5d1f.jpg)

**Comment by kevinhendricks** [comment]
Does it matter which monitor the app is started on before being moved to the other monitor?  Are there large dpi resolution differences between the two monitors?  I can not recreate this on a two monitor Mac setup at all.  Perhaps the Qt auto-scaling code is getting confused on Windows.  You may need to set Default Sigil preferences for Fonts and icon scaling based on the lower resolution monitor?

**Comment by kevinhendricks** [comment]
Also does setting the second monitor to mirror the first have any impact?

**Comment by Nick-Payne** [comment]
Doesn't matter which monitor the app is started on, the UI elements are incorrectly sized with the Sigil window on the higher res monitor and correctly sized with it on the low res monitor.

Because the monitors are the same size, but different resolution, in Windows settings (Settings / Display) the scaling for the higher res monitor is configured to 150%, with the lower res monitor at 100%. This makes text, icons, etc approximately the same size on both screens, and works fine for native Windows apps. If I duplicate the displays in Windows settings then both monitors get set to 2560x1600 resolution and Sigil looks fine on both screens, but that's a complete waste of a very expensive Eizo 4k monitor.

**Comment by Maradar** [comment]
not sure if this helps, but I had similar problem after reinstalling my Win 10, try to use "set custom scaling level" option in "Control Panel\Appearance and Personalization\Display".

I set my value to 105% and since then it works and it looks normal

**Comment by Nick-Payne** [comment]
Custom scaling is not a viable option because that scaling gets applied to all displays. With custom scaling you can't have a different scaling factor for different displays , and I have two same size displays with a 1.5x difference in DPI.

**Comment by Maradar** [comment]
Just try to change the value, trough method described previously, not trough that new windows settings, apply it and then change it back and apply again. I know it will require 2 sing offs but there is a chance it will look normal after that.

**Comment by Nick-Payne** [comment]
The method you describe disappeared with Windows 10 build 15019 (there is no longer a display item in Control Panel), and I'm running build 15063. The only way now to apply a custom scaling factor is via the Settings app or by setting the LogPixels and Win8DpiScaling values in the registry.

Trying either method and then changing it back makes no difference to the truncated and overlapping UI elements in Sigil when opened on the monitor using the higher scaling factor.

**Comment by Maradar** [comment]
Nick I am using win 10 build 1607 and it is still there
![2017-08-23_10-08-35](https://user-images.githubusercontent.com/6325530/29605467-434427d6-87eb-11e7-8f71-827e13a7af47.png)

tell you what open file explorer and pass the whole address without quotations "Control Panel\Appearance and Personalization\Display" and press enter

**Comment by Nick-Payne** [comment]
I'm on version 1703, and that option no longer exists...
![control](https://user-images.githubusercontent.com/3879090/29606578-0ea70bbe-8832-11e7-9cba-8f663070df45.jpg)

**Comment by Maradar** [comment]
and now you scared the bejesus out of me I guess the only option left is if you try this ttp://news.kynosarges.org/2017/04/16/dpi-settings-in-windows-10-creators-update/
if it is available

**Comment by Nick-Payne** [comment]
Thanks for that link. If I go to the compatibility tab of the properties for the Sigil shortcut, tick "Override high DPI scaling behaviour", and set the scaling to be performed by "System (Enhanced)", then the Sigil UI elements now scale correctly on both monitors.

**Comment by dougmassay** [comment]
Windows hi dpi support is still fairly young in Qt5.6. I'd be curious to know if Qt5.9 has made any advancements on this front. Anyone willing to try a beta-Sigil built with Qt5.9.1 to see if it makes these compatibility adjustments unnecessary?

**Comment by Maradar** [comment]
@Nick-Payne you are welcome I am glad that it worked :-D

@dougmassay although I do not have the Win 10 creator update if there are beta builds of Sigil somewhere I would love to test them :-D

**Comment by dougmassay** [comment]
@Maradar: Well I don't really have any betas lying around, if that's what you mean. :) I tend to create ones for the testing of specific issues.

As to this issue, there are three different levels of "DPI awareness" that a Qt application can have on Windows. From Windows 8.1 on, "Per-Monitor DPI Aware" is the default level. Which means that Windows performs no scaling of its own. Which sounds exactly like what is happening to me (for better or worse).

Another level is "DPI Aware" (the default on Vista, 7 and Windows 8), which means that Windows will calculate a scaling suitable for all connected monitors.

The third level (DPI Unaware isn't really relevant, here).

Those levels can be tweaked at runtime via a qt.conf file.

[More here](http://doc.qt.io/qt-5/highdpi.html)

**Comment by Nick-Payne** [comment]
I'm running the Win10 creators update and can test a beta Sigil with more recent Qt to see if it fixes this problem.

**Comment by kevinhendricks** [comment]
Can this be closed now given our user setable icon sizes, Windows options?

**Comment by kevinhendricks** [comment]
okay closing this
