### ISSUE TITLE
Qt5WebKitWidgets.lib(Qt5WebKitWidgets.dll) : fatal error LNK1112: Modul-Computertyp "x64" steht in Konflikt mit dem Zielcomputertyp "x86".

### ISSUE THREAD

**Issue by Dan5991** [Sigil-Ebook/Sigil#312]
Hi,

I tried to built Sigil on Windows 7(64-bit) as it is descripted in the readme, but I get this error when I execute this command:

cmake -G "NMake Makefiles" WIN_INSTALLER_USE_64BIT_CRT=1 -DCMAKE_PREFIX_PATH="C:\Users\...." DCMAKE_BUILD_TYPE=Release "C:\Users\...."

Error:
Qt5WebKitWidgets.lib(Qt5WebKitWidgets.dll) : fatal error LNK1112: Module-Computertype "x64" is in conflict with target computertype "x86".

Can somebody help me with this?

Kind regards

**Comment by dougmassay** [comment]
Looks like you've mixed and matched x86/x64 components somewhere (or are using the incorrect vs2015 command-line environment shortcut. Did you build Qt5.6.2 yourself (with the guidelines in this repository), or did you download the Qt5.6.2 I precompiled  specifically for use with Sigil?

**Comment by Dan5991** [comment]
I downloaded your precompiled Qt5.6.2 and now I tried to execute the command on the command line tool "x64 native Tools" and get this error:

LINK : fatal error LNK1104: File "python36_d.lib" cannot be opened.
LINK Pass 1 failed. with 1104

**Comment by dougmassay** [comment]
Make sure you specified a Release build in the initial cmake command. It looks like it's trying to link to a debug version of Python. Delete the contents of your build directory to make sure no previous cmake configs are lurking before retrying.

Also note that the instructions call for Python 3.5. I know of no particular reason why it wouldn't build with Python 3.6 on Windows, but to be honest, I've never tried. So there could be issues I've not foreseen.

**Comment by Dan5991** [comment]
Hi again,
solved this problem. Didn't copy your code properly. Somehow I forgot the "-" sign before the second "DCMAKE"!

Thanks a lot for the quick support!

**Comment by dougmassay** [comment]
Glad to help.
Feel free to reopen this issue if you run into any more trouble.
