### ISSUE TITLE
Could not find or load the Qt platform plugin "windows"

### ISSUE THREAD

**Issue by niroGH** [Sigil-Ebook/Sigil#315]
Hi,
if I build sigil on my windows 10 its build successfull, but if I execute the .exe-File then I get this error:
![install error](https://user-images.githubusercontent.com/30118585/30405573-e613c27a-98ec-11e7-9928-f3ae03f51239.jpg)
 I have already searched in google solution like execute of windeploy, install some .dll files etc.
nothing helps me.
Can anyone help me please?

Another question is: if I build sigil on Windows or MAC and have the .exe or dmesg-File can I execute the files on my other windows or mac pc`s? 

Thank you

**Comment by dougmassay** [comment]
You must deploy Sigil on Windows via the installer package (nmake makeinstaller). The exe will not run from the build directory as is. The environment is not complete.

Once the installer is built (found in the <build-dir>\installer directory, you can use that to install Sigil on that, or any other Windows machine (provided the architectures are compatible). Same with the dmg file on Macs

**Comment by niroGH** [comment]
Thank you very much 
I just did it and its works :+1:
