### ISSUE TITLE
Feature request: code style options

### ISSUE THREAD

**Issue by lauras** [Sigil-Ebook/Sigil#318]
It would be really great if we could set default options for how code is formatted.

For example, tabbed indents on CSS put my teeth on edge. I know preferences for tabs vs. spaces (2 or 4) is split among us FEDs, but it would be nice to be able to do this without taking the file in question out of Sigil into BBEdit or Sublime etc. For most books, the character savings of universal formatting via tabs is a non-issue.

Thanks. I love Sigil! As a webdev, having transparent hands-on tools specifically for books is a delight.

**Comment by dougmassay** [comment]
You don't have to take the file out of Sigil to use an editor that can format css the way you want. The open With feature allows you define an external editor for different mimetypes. Right-clicking on a css file in the Book Browser for instance will allow you to select the exe of the editor you want to assign for the css type. Then the Open With context menu will allow you to open the selected file in that external editor. After saving/exiting, Sigil's Code View will be updated with the results.

Allowing users to define their own individual coding styles prefs within Sigil is probably not in the cards.

**Comment by dougmassay** [comment]
> For example, tabbed indents on CSS put my teeth on edge.

Sigil's context menu-available "Reformat CSS" does not use tabbed indents. It uses spaces. It DOES use 4 spaces for indents, but they are spaces and not the tab character.

Also, Sigil's Edit Plugin framework allows anyone who is so inclined to create their own code-formatting/pretty-printing rules.

**Comment by dougmassay** [comment]
Closing as there are already numerous ways to get/keep Sigil epub code formatted in a manner that suits individual tastes.
