### ISSUE TITLE
Mathematics formulas is not displayed properly under windows

### ISSUE THREAD

**Issue by niroGH** [Sigil-Ebook/Sigil#319]
Hey,

I wrote an example ebook which contains mathematics formulas (Code from: http://asciimath.org).
If I open the ebook on Linux (Ubuntu) OS online via Chrome here: https://www.ofoct.com/viewer/epub-reader-online.html or with Readium they shows the mathematics formulas correct but If I open the same ebook on Windows OS the mathematics formulas are not displayes correctly like on this images:
On Linux:
![math_on_linux_ubuntu](https://user-images.githubusercontent.com/30118585/31046182-a2ba417e-a5f4-11e7-8084-199817a406cf.png)

On Windows:
![math_on_windows](https://user-images.githubusercontent.com/30118585/31046184-b85381f8-a5f4-11e7-94fc-4b6c293981a4.png)

The Chrome version on both OS are stable.

Can anyone please tell me why it is so or may be the reasons for that?

Thank you.

**Comment by kevinhendricks** [comment]
This is not a Sigil Issue.  Those are not images taken from Sigil's Preview.  Please use Sigil's Preview and look.  The mathml should display correctly.  If it does not, please let us know.  

If you are not using mathml but instead some other math representation, then that is not supported as it is outside the html5 and epub specs unless it uses svg to create an image or replaces the math with images.

As for why one reader on one platform works while another does not with mathml is not something we can explain.  No chrome based reader even supports mathml natively.  Chrome's fork of Webkit removed all mathml support while Apple's Webkit kept and improved on it.  Google chrome decided mathml was not used enough to warrant support and so relies on the MathJax.js polyfill to display math.  MathJax  is how Sigil Preview supports mathml.  The two chrome based readers may have different versions of MathJax.  Who knows...

**Comment by kevinhendricks** [comment]
BTW, if you need or want to discuss this further, please use our support forums on Mobileread as explained in the README.md as shown on our github page and not here as this is reserved for bugs in Sigil and not user support.

Thanks

**Comment by dougmassay** [comment]
In addition to Kevin's points, there is also list of EPUB3 tests that Sigil fails to render correctly in the Release Notes for the Sigil 0.9.3 release. Among those failed test are these two MathML relevant entries:

- mathml-080:   support for long division (passes on Linux and Mac OS X, fails on Windows)
- mathml-081:   support for mstack,  mscarries (passes on Linux and Mac OS X, fails on Windows)

**Comment by kevinhendricks** [comment]
Good point!  That may explain the Windows specific issues.  FYI,  those two Windows only bugs are in fact MathJax bugs that happen because those features relay on xml stylesheet transformations that are not supported in Webkit on Windows and many browsers.  I have already posted a bug at MathJax illustrating the issue, so it is a known problem for mathml via MathJax on Windows versus all other platforms.

**Comment by niroGH** [comment]
Thank you.
Yes with MathML its works fine on sigil and Readium displays its properly too but this (https://www.ofoct.com/viewer/epub-reader-online.html ) reader is based on epub.js and its not displays the MathML properly whether Linux or windows. Ok its not sigil problem I try it by epub.js. 
Thank you very much.
