### ISSUE TITLE
Build Sigil on Cutting Edge Linux Problem

### ISSUE THREAD

**Issue by E-World333** [Sigil-Ebook/Sigil#321]
I'm not an expert on linux but I'm using Xubuntu 16.04 and ElementaryOS Freya on my old Laptop, reading on the internet I found that using "sudo make install" is basically a bad idea, unfortunately I did that so I first tried to find a way to uninstall it since "sudo apt remove " wouldn't do anything. I found a way... I think.
First you need to erase these:
usr/local/bin/sigil [file]
usr/local/lib/sigil [folder]
usr/local/share/applications/sigil.destop [file]
usr/local/share/pixmaps/sigil.png [file]

This should work for the uninstall thing, now we need to reinstall Sigil but in a more appropiate way.
Follow all the instructions that are on "Building_on_cutting_edge_Linux.html" but don't do the last step, the installation part, we have to do a checkinstall but first we need to install it, so, on terminal:

sudo install checkinstall

now, open the terminal on "sigil-build" directory and instead of

sudo make install

you will use

sudo checkinstall

You probably should read a bit about how to use it, but hitting the enter button until it ends should do the work, there's just one little thing that I think could give you an error, so... just ins case, at some point when using checkinstall, it will ask you if you want to change some data something like "Press the number of the option you want to change or press ENTER to cotinue" you have to press the number with the "version" option, since we are running checkinstall on the "sigil-build" directory it should said "Version: build", and that gives you an error message at some point, you have to change it to "0.9.8" for example. and that would be all, hit the Enter key until it ends. Now you can uninstall Sigil whenever you want, for an update for example.

This should work for all debian and ubuntu based OS... I think.

P.D.: Sorry for my not so good english, I hope you could understand what I was trying to explain.

**Comment by dougmassay** [comment]
This is not a "Problem." Nor is this the place for user tutorials.

"sudo make install" is only "dangerous" if one doesn't understand the implications of using it. And those who don't understand those implications should probably stick to installing the repository version of Sigil anyway.
