### ISSUE TITLE
Well-formed check epub does not recognize processing instruction

### ISSUE THREAD

**Issue by ionum** [Sigil-Ebook/Sigil#323]
XML may contain processing instructions like <?dp n="202" folio="202" ?> (see https://en.wikipedia.org/wiki/Processing_Instruction)

"Well-formed check epub" complains about "improperly nested tag"

p.s. using sigil 0.9.8

**Comment by kevinhendricks** [comment]
Epub3 only supports xml-stylesheet processing instructions.  Please include the exact line that is determined to be not well formed.

**Comment by ionum** [comment]
- it is an &lt;?dp n="241" folio="241" ?&gt; tag
- example error line:  Improperly nested tags: parsing end tag "p" but current parse path is "html.body.div.div.?dp.p.?dp". See line 31 col 0.  near column 169
- it is an epub2
- epubcheck returns valid result ....

**Comment by kevinhendricks** [comment]
This is not an xml-style  PI so this would be illegal in epub3 and epub3.1.  Using PI's is not recommended in epub2 or epub3, so I recommend using search and replace to convert these to xhtml style comments throughout or removing them completely.  I will look into fixing the well-formed check to ignore all PIs.

Thanks for your bug report.

**Comment by ionum** [comment]
Thanks. BTW great piece of freeware.

**Comment by kevinhendricks** [comment]
Closing as just pushed fix for this to master.  The fix will appear in our next release.  We plan on a new release sometime soon during the holiday period.
