### ISSUE TITLE
Default Templates

### ISSUE THREAD

**Issue by LeoM49** [Sigil-Ebook/Sigil#325]
Hi, I am am new here. So sorry for the question. I saw a YouTube tudorial about sigil and there it was said, that a default template for sigil is available, whith prepared chapters, css file etc. Where can I get this???
Thanks for your help.

**Comment by kevinhendricks** [comment]
Closing as this is not a bug. As explained in the README on this site, this is for bug reports. Please use our User Support forums on www.mobileread.com for user questions and help related to Sigil.
