### ISSUE TITLE
I cannot see the right font, and it showed only square.

### ISSUE THREAD

**Issue by Speaknut** [Sigil-Ebook/Sigil#327]
![4](https://user-images.githubusercontent.com/14882665/34029252-835cbc9a-e135-11e7-8f52-bf50f9f36d37.png)
This is my targeted result,and 

![3](https://user-images.githubusercontent.com/14882665/34029123-c951342a-e134-11e7-9375-ca9925697cda.png)

I ended up with this.

[ZawgyiOne.zip](https://github.com/Sigil-Ebook/Sigil/files/1561744/ZawgyiOne.zip)

I try to type using my font, but it only show square. How can I fix this problem? I also attached the font file in zip. Thank you for your help.

**Comment by dougmassay** [comment]
As requested in the README, please do not use the issue tracker to ask general usage questions. The issue tracker is reserved for bug reports, feature requests, and other things pertaining to Sigil's codebase.

The Sigil user-support forums at Mobileread (link in the README) is the place to ask your questions pertaining to embedded fonts and the like.

**Comment by Speaknut** [comment]
My apology. I am so sorry sir.
