### ISSUE TITLE
Could I stop Sigil creating an old toc.ncx file, which causes an epubcheck error.

### ISSUE THREAD

**Issue by tomochan001** [Sigil-Ebook/Sigil#331]
When I open an EPUB3 file, which has passed epubcheck (4.0.2) successfully, Sigil seems to add a toc.ncx file, which causes an error on epubcheck.
As far as I understand, the toc.ncx file is not necessary for EPUB 3.0. I have produced over 2000 epub files for major epub retailers, including Kindle and Kobo, all of which lack toc.ncx files but have been sold with no problem.
Could I stop Sigil generating toc.ncx files? That is the only one problem that hinders me from using this splendid software with great pleasure.

**Comment by dougmassay** [comment]
The short answer is, no, you can't stop Sigil from creating an ncx file (even for EPUB3). The NCX is ingrained too deeply in Sigil's codebase to easily eliminate it. We hope to get there someday, though.

But Epubcheck shouldn't be giving you an error when an NCX is present either. As you noted: the NCX is not required, but neither is it forbidden. If the IDs match between OPF and NCX (and Sigil 0.9.9 ensures that NCXs generated with Sigil will have an ID that matches the OPF), and the xml is valid, Epubcheck shouldn't care if an NCX is present.

As a workaround, I wrote a Sigil output plugin that will remove the NCX from EPUB3s. Sigil will always add the NCX upon opening, but if you do your editing and remember to save with the output plugin before publishing, your EPUB3 will be NCX-free.

https://www.mobileread.com/forums/showthread.php?t=284445

**Comment by tomochan001** [comment]
Thanks a lot! I will give it a try.
As for the error, yes, I fully understand it, but I am too lazy to dig into NCX files given that I do not need and will remove it eventually...
