### ISSUE TITLE
Font importing problem

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#334]
Occasionally, fonts that I've imported into an epub go missing after saving the epub and exiting Sigil. On the second go round, the fonts are imported as expected. This behavior started with version 0.9.9 and is triggered by no particular font set. Unfortunately, I can't come up with a repeatable example.  Screen grab 1 shows the first go round in which I imported fonts (note the missing icons); grab 2 is the same epub reopened and with fonts re-imported.

![grab1](https://user-images.githubusercontent.com/13193709/34949667-98e3a198-f9c5-11e7-9a7d-995d55a24720.jpg)
![grab2](https://user-images.githubusercontent.com/13193709/34949668-98f7bc5a-f9c5-11e7-8d82-94449c62eb0b.jpg)

**Comment by kevinhendricks** [comment]
There were no changes to the epub reading or writing code at all.  

So there us something else going on.  Before saving the epub, please verify that the fonts are properly listed in the opf manifest and that the font extension, font type, amd mime-type match that in the opf.  Make sure the file you imported them from has not obfuscated the fonts without a correct encryption.xml being present with the proper entries.

**Comment by kevinhendricks** [comment]
Also on what OS are you using?  If Linux, how was it built or which repository are you installing from.

**Comment by mrprobert** [comment]
I downloaded Sigil from
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.9 and it's running
on Windows 10 with current patches.

The fonts aren't obfuscated. I'll check the opf the next time I encounter
the issue.

Thanks much.

**Comment by kevinhendricks** [comment]
Closing this as I can not recreate it at all with any valid fonts that epubs recognize that get properly imported directly into the Fonts folder.  I have tried repeatedly.

Feel free to post again if the problem re-occurs and you are able to provide additional information - then I will reopen the issue.
