### ISSUE TITLE
.suit and .dfont fonts not being handled properly on Windows

### ISSUE THREAD

**Issue by BaconCatBug** [Sigil-Ebook/Sigil#335]
I opened an epub that uses (presumably obfuscated/subset) .suit and .dfont fonts, and they were placed in the misc folder, and the css styles didn't edit the entries for the suit or dfont fonts, causing errors when I opened the newly saved file in AZARDI. The other entries are correctly edited to point to the Fonts folder (the folder is called font before I open in Sigil).

Furthermore, when I edit the css to point to the correct folder (Misc instead of Fonts) and re-open the file in Sigil, the fonts are not rendering properly in the display window (they display correctly in AZARDI)

Any chance I can make a feature request to handle .suit and .dfonts?

**Comment by dougmassay** [comment]
You'll need to take that up with the IDPF, I believe. Regardless of what devices/apps those fonts _might_ work with, they're not EPUB spec compliant.

**Comment by kevinhendricks** [comment]
Your best bet is to get a good font conversion program (assuming you have the license for using such fonts) and convert them to one of the many official font types supported by epub2 and/or 3.  These include .ttf, .otf, .woff, .woff2, etc.  

See the spec here:

https://idpf.github.io/epub-cmt/v3/#sec-cmt-supported
