### ISSUE TITLE
Update CMake build system to be able to use CMP0020=NEW

### ISSUE THREAD

**Issue by dbelyaev** [Sigil-Ebook/Sigil#336]
Trying to build latest release v0.9.9 with cmake v3.10.2 gives me error:

```
>> cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ./../sigil-src/

  CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

**Comment by dbelyaev** [comment]
I think the same goes for [CMP0043 on line 16](https://github.com/Sigil-Ebook/Sigil/blob/14ea6531c689aceee59f7b56e0713c0bf97bb2fd/src/CMakeLists.txt#L16).

**Comment by dougmassay** [comment]
A deprecation warning is not an error. It is a warning. Sigil will still build. We'll get around to updating the CMake file eventually, but it's not a pressing matter. I'll leave this issue open as a reminder to work on it, though.

**Comment by dougmassay** [comment]
Made sure policies were correctly enforced from our minimum required cmake (3.0.0) to the latest cmake without resorting to the forcing of any OLD behavior. Should eliminate warnings in newer versions of cmake. b21268b6c8ebea5453f6e21d800520e13fee5f94

Closing.
