### ISSUE TITLE
While building from source, getting error: You are trying to run CMake from the <top_folder>/src/ directory

### ISSUE THREAD

**Issue by dbelyaev** [Sigil-Ebook/Sigil#337]
I have an unpacked source dir for Sigil, and mine `sigil-build` directory is on the same level as `sigil-src` directory that came with archive (along all other files) and while trying to run command:

`dmitriy@hostname:~/Downloads/Sigil-0.9.9/sigil-build$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../sigil-src`

I am getting error:

```
CMake Error at CMakeLists.txt:25 (message):
  You are trying to run CMake from the <top_folder>/src/ directory, instead
  of just from the <top_folder> directory.

  DO NOT DO THIS.

  The correct way looks like this:

    cmake -G '<generator_name>' /path/to/topmost/folder/in/source/package

  You will probably now need to first clean your build directory.


-- Configuring incomplete, errors occurred!
```

**Comment by dbelyaev** [comment]
Sorry, for creating an issue, but as I can see it is only way to get some help with build process (in addition to build instructions).

**Comment by dougmassay** [comment]
Using a build directory completely outside of the directory where the source was unpacked is the easiest way to avoid this problem. But if you feel you must build inside the Sigil source directory, just make sure to do it in a newly created subdirectory.

You can always get build help in Sigil's support forum(s) at Mobileread.

**Comment by dougmassay** [comment]
You also need to be IN the build directory when you issue the command.

**Comment by dbelyaev** [comment]
@dougmassay , thanks for help! My bad, I misread build instructions thinking that source dir is an `src` directory inside of the source archive not the whole directory unpacked from archive.

**Comment by dougmassay** [comment]
No problem!
