### ISSUE TITLE
Setting direction causing error on epub checker

### ISSUE THREAD

**Issue by coder4567** [Sigil-Ebook/Sigil#342]
Kindly note that when we set direction rtf on sigil, it inserts a div element with the direction, unfortunately the div is being inserted in H1 as shown in the screenshot, which is causing an error on epub checker, this is causing a problem on many epubs we are producing. 

Kindly find attached the html file causing the error along with the error raised by epub checker:
![img_13032018_140426_0](https://user-images.githubusercontent.com/1804546/37757655-6d1b0392-2db6-11e8-9113-74f2b3c8fc05.png)
<img width="1396" alt="screenshot 2018-03-21 15 12 42 copy" src="https://user-images.githubusercontent.com/1804546/37757660-6f631a86-2db6-11e8-85c4-03c33c1a8023.png">

Thank you for your efforts

**Comment by kevinhendricks** [comment]
Where was your cursor when you inserted the div?  Are you editing in BookView mode when you add the div?

**Comment by coder4567** [comment]
Kindly note that we select all the text or part of it, then choose the rtl option, as shown in the screenshot below, 
![img_23032018_133611_0](https://user-images.githubusercontent.com/1804546/37827390-fb563d90-2e9f-11e8-946a-618386bec7cf.png)

it may occur that the div is inserted in an h1 tag which breaches the epub checker rules

<img width="1396" alt="screenshot 2018-03-21 15 12 42 copy" src="https://user-images.githubusercontent.com/1804546/37827376-f29c69cc-2e9f-11e8-9f7a-9f00d9a876d2.png">

Thank you for your follow up, I hope you could guide me further to solve this problem.

**Comment by kevinhendricks** [comment]
To have finer control over the xhtml generated select text in Codeview.  Editing in BookView is fraught with user selection errors and generally deprecated for that reason.  Switch to CodeView mode in Sigil to have more fine control of what gets selected.

**Comment by kevinhendricks** [comment]
In Codeview, adding dir=“rtl” to the html tag itself is enough.  All children will inherit it.  You only need to mark text that differs from the dir set in the html node.

**Comment by kevinhendricks** [comment]
I strongly recommend ONLY setting text direction in CodeView and only for exceptions as the document text direction is set using a dir="rtl" attribute in the html tag.  Use BookView to try to select text is extremely fraught with difficulties as live editing a webpage has no way to fine control the selection.

A patch to force code view to use dir attributes under epub3 has been committed to master.

Closing
