### ISSUE TITLE
When pasting text from Word creates the TAG: <o: p> </ o: p>

### ISSUE THREAD

**Issue by Reulym** [Sigil-Ebook/Sigil#343]
I am an amateur user of Sigil. I understand little of codes, but I would like to point out an error that happens that made me stop updating Sigil and stop at version 0.8.7.

Until version 0.8.7 it was possible to copy text from Word and paste it into sigil and the text was completely formatted. From version 0.8.9 onwards until the current available 0.9.9, whenever you paste a WORD text it results in the creation of a TAG which is the following tag: <o: p> </ o: p>

And this causes an error when you return to the BOOK VIEW with the following message:

> This page contains the following errors:
> 
> error on line 659 at column 101: Namespace prefix 'or' not declared
> Below is a rendering of the page up to the first error.

Until version 0.8.7 this does not happen.

Here's how each paragraph looks:

`<p class="MsoNormal" style="margin: 3pt 0cm 0.0001pt 21.25pt; text-indent: -7.1pt;"><span style="font-size:11.5pt;mso-bidi-font-size:12.0pt;font-family:&quot;Times New Roman&quot;,serif;
mso-fareast-font-family:Arial">TEXTO DO PARÁGRAFO<o:p></o:p></span></p>`

**Comment by dougmassay** [comment]
This isn't likely to change. When you decline the dialog option to paste as plain text into Book View, then you're going to _get_ Word markup. In all its prefix-laden glory.

There's plenty of Sigil plugins that can get Word content safely into Sigil without needing to resort to copy/pasting into Book View.

**Comment by dougmassay** [comment]
For the record: neither Sigil, nor the paste process is responsible for creating the <o:p> tags. That's Word markup. Dutifully being copied to the clipboard and pasted into Sigil as is (when you decline to paste as plain text).

**Comment by Reulym** [comment]
I just do not understand why in the versions up to 0.8.7 this problem did not happen. I use the longer version 0.8.6 and it is perfect for making paste epub of a WORD text. This problem only happens in version 0.8.9 onwards. Do you have any explanation for that? Can you correct that?

**Comment by Reulym** [comment]
Thank you for listening, my friend. It's a pity there's no fix for that. Some users, like me, used this feature to create their epubs. This way I will be doomed to use version 0.8.6 forever, which satisfies my needs and satisfies my limited knowledge.

**Comment by dougmassay** [comment]
You're only "doomed" to stick with 0.8.6 forever if you refuse to avail yourself of the countless other (and invariably better) ways to get Word content into Sigil.

Besides: if 0.8.6 satisfies your needs, then why do you feel "doomed" at all?

**Comment by Reulym** [comment]
You are right! I'm going to download the most up-to-date version and try other ways to get WORD formatted content to Sigil. I'll try to learn more. As I said I know little or nothing about codes and ccs, but I will not give up. You made me excited by those words. If you have any tips that will help me feel free to tell me. And sorry if English is strange. I'm using the google translator because I live in Brazil and I understand English very little. Thanks again, my friend, for the attention.

**Comment by dougmassay** [comment]
I'd start by joining the Mobileread.com forums where the Sigil support forums are hosted. There you can talk to other Sigil users about Sigil plugins, Word addins and other techniques used to get clean html/css from Word and into Sigil.

https://www.mobileread.com/forums/forumdisplay.php?f=203

Personally, I'd recommend using Toxaris' (a Sigil user) ePub-Tools Word add-in for creating an epub directly from within Word. More can be found on it here: https://www.mobileread.com/forums/showthread.php?t=213372
