### ISSUE TITLE
Request: A proper zoom function

### ISSUE THREAD

**Issue by BaconCatBug** [Sigil-Ebook/Sigil#344]
I am making a fixed layout epub3 (the one with background images with text on top). I need a way to zoom in so I can actually READ the text I am editing, right now on my 1080p screen it's like reading font size 5 text. I can't just make the text bigger because it's a fixed layout epub. I can't imagine what it would be like for someone with poor eyesight.

Is there any way you could add this, or direct me to a plugin or other software that can?

**Comment by dougmassay** [comment]
I don't know what you mean by a "proper" zoom function. Is Sigil's built-in zoom feature not working for you?

I'm not certain Sigil fully supports fixed layout epubs (other than code editing of course) quite yet.

**Comment by kevinhendricks** [comment]
Closing as incomplete with no updates.  A zoom bar already exists in Sigil and can be used to zoom all windows.
