### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#346]
A few strings missing in Transifex (no way to translate).

1. Find: field context menu [[image](https://i.imgur.com/79otCWM.png)]
2. Preferences -> Keyboard Shortcuts -> Description [[image](https://i.imgur.com/GpJXicB.png)]

**Comment by kevinhendricks** [comment]
If these are context menus internal to Qt you need to install Qt Libraries own translations as these are not part of Sigil proper.

**Comment by kevinhendricks** [comment]
For example tr is properly used around the "Tokenise Selection" string so it should be translatable but Copy, Paste, etc are internal Qt menu items that are only translated in the Qt library itself if you add the right translations.

**Comment by kevinhendricks** [comment]
And Tokenise Selection can indeed be found in base.ts
```
<context>
    <name>FindReplaceQLineEdit</name>
    <message>
        <location filename="../../Misc/FindReplaceQLineEdit.cpp" line="58"/>
        <source>Tokenise Selection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../Misc/FindReplaceQLineEdit.cpp" line="71"/>
        <source>Save Search</source>
        <translation type="unfinished"></translation>
    </message>
</context>
```

**Comment by kevinhendricks** [comment]
If these are untranslated in your language, you should contact the Sigil translation project leader for your language on transifex (https://www.transifex.com/zdpo/sigil/) and file a bug report.  Sigil has no control over individual translations.

**Comment by BeckyDTP** [comment]
I saw that.
Sample: https://www.transifex.com/zdpo/sigil/viewstrings/#de/sigil/7176939?q=Tokenise
_Tokenise Selection_ is translated, but this translation does not appear in the UI.

Fresh Windows 10 Home, fresh Sigil installation.

BTW. How I can update Qt library translation?

**Comment by BeckyDTP** [comment]
Change language Sigil UI to German please.
Can you see _Tokenisierte Auswahl_?

**Comment by kevinhendricks** [comment]
Possibly because this was untranslated when the translation files were pulled into Sigil for the release build.  When the next release is made we will pull in any new translations from all supported languages so it might appear then.

**Comment by BeckyDTP** [comment]
It is not it. These strings was translated years ago.
I remember, that this context menu always was untranslated over the years.

**Comment by kevinhendricks** [comment]
I am not at a Desktop machine, but I did search the current sigil_de.ts file for that string and it does exist.

Tokenisierte

That is very strange.

**Comment by BeckyDTP** [comment]
I have sigil_de.ts from Transifex and from [Github Sigil-Ebook](https://github.com/Sigil-Ebook/Sigil/blob/master/src/Resource_Files/ts/sigil_de.ts
). 
_Tokenisierte Auswahl_ exist in both.

**Comment by kevinhendricks** [comment]
And there is no need to add Q_DECLARE_TR_FUNCTIONS in that header for that file as it inherits from a QObject (in this case a QLineEdit).

So as far as I can tell, all code is correct but translation is being ignored.  Perhaps we need to file a bug report with Qt.  But I have had little to know progress with any bug filed there.  I will see if we can workaround it in some way

**Comment by kevinhendricks** [comment]
If you have your own build of Sigil, please try adding Q_OBJECT to src/Misc/FindReplaceQLineEdit.h
as follows:

```
class FindReplaceQLineEdit : public QLineEdit
{
    Q_OBJECT

public:
```

**Comment by kevinhendricks** [comment]
And then recompile to see if that impacts the lookup of TR functions for FindReplace.  If so, please let me know and I will add it for the next release.

**Comment by BeckyDTP** [comment]
I confirm that your patch fixes the problem in the context menu.

[Proof](https://i.imgur.com/ERGZRiB.png).

As for the problem in the keyboard shortcuts window:
In the BookBrowser.cpp file, you forgot to add _tr()_ in four lines.

Look [here](https://i.imgur.com/4R7zwng.png).

**Comment by kevinhendricks** [comment]
Thanks, I will commit fixes for both unless you would rather create a Pull Request that I could merge.

Thanks!

**Comment by BeckyDTP** [comment]
It's me again.

The issue of default translations from Qt remains open.

I can remind you of my [screenshot](https://i.imgur.com/79otCWM.png).

Your answer:

> [...] but Copy, Paste, etc are internal Qt menu items that are only translated in the Qt library itself if you add the right translations.

In addition, an [old post](https://www.mobileread.com/forums/showpost.php?p=2953553&postcount=106) in the same case.

@user-none [wrote then](https://www.mobileread.com/forums/showpost.php?p=2953658&postcount=107):

> The menus that Divingduck has pointed out are a long standing issue. They are created by Qt and the strings are part of Qt. Qt does provide translations files for a number of languages, however they are not packaged or used at this time. Packaging and using them is the long standing issue.

I agree that the default, multilingual translation of Qt messages should work. It may work on your computer because you have Qt installed and you probably use Sigil in English, so you do not see the problem.

I think that in order to work the default translation from Qt – you have to **load them before** (and of course you need to have the appropriate .qm files on the disk).

To test change UI language in Sigil, e.g. to German or French, open a new file, write anything in paragraph and try close Sigil. You'll see the [message](https://i.imgur.com/QF6fcz4.png).

## My proposal (standard)

* Copy qtbase_XX.qm files from Qt folder and copy to Sigil/translations folder (in this example: _qtbase_de.qm_).

* Add to _main.cpp_ file (BEFORE sigil_XX.qm load – to avoid overwriting some translations):

<pre><code>
        QTranslator baseTranslator;
        const QString qm_name_base = QString("qtbase_%1").arg(settings.uiLanguage());
        foreach(QString path, UILanguage::GetPossibleTranslationPaths()) {
            if (QDir(path).exists()) {
                if (baseTranslator.load(qm_name_base, path)) {
                    break;
                }
            }
        }
        app.installTranslator(&baseTranslator);
</code></pre>

It works: [dialog box proof](https://i.imgur.com/Pf9os3f.png).
Of course context menu too: [context menu proof](https://i.imgur.com/exnP6sr.png)

## My proposal (alternative)
Because the standard proposal (described above) requires the user to have qtbase_XX.qm files – can it, however, add a translation of these over a dozen strings directly in the Sigil translation?

@kovidgoyal in calibre added used default strings (Undo, Redo, Cut, Copy, Paste etc.) for translation and there the problem does not exist.
If I understand correctly, it is [here](https://github.com/kovidgoyal/calibre/blob/master/src/calibre/utils/localization.py#L314) (and next lines).

<pre><code>
&lt;context&gt;
    &lt;name&gt;QLineEdit&lt;/name&gt;
    &lt;message&gt;
        &lt;source&gt;Cu&amp;amp;t&lt;/source&gt;
        &lt;translation&gt;&amp;amp;Ausschneiden&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;Copy&lt;/source&gt;
        &lt;translation&gt;&amp;amp;Kopieren&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;Redo&lt;/source&gt;
        &lt;translation&gt;Wieder&amp;amp;herstellen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;Undo&lt;/source&gt;
        &lt;translation&gt;&amp;amp;Rückgängig&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;Paste&lt;/source&gt;
        &lt;translation&gt;Einf&amp;amp;ügen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Delete&lt;/source&gt;
        &lt;translation&gt;Löschen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Select All&lt;/source&gt;
        &lt;translation&gt;Alles auswählen&lt;/translation&gt;
    &lt;/message&gt;
&lt;/context&gt;
&lt;context&gt;
    &lt;name&gt;QPlatformTheme&lt;/name&gt;
    &lt;message&gt;
        &lt;source&gt;OK&lt;/source&gt;
        &lt;translation&gt;OK&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;No&lt;/source&gt;
        &lt;translation&gt;&amp;amp;Nein&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;&amp;amp;Yes&lt;/source&gt;
        &lt;translation&gt;&amp;amp;Ja&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Help&lt;/source&gt;
        &lt;translation&gt;Hilfe&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Open&lt;/source&gt;
        &lt;translation&gt;Öffnen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Save&lt;/source&gt;
        &lt;translation&gt;Speichern&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Abort&lt;/source&gt;
        &lt;translation&gt;Abbrechen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Apply&lt;/source&gt;
        &lt;translation&gt;Anwenden&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Close&lt;/source&gt;
        &lt;translation&gt;Schließen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Reset&lt;/source&gt;
        &lt;translation&gt;Zurücksetzen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Retry&lt;/source&gt;
        &lt;translation&gt;Wiederholen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Restore Defaults&lt;/source&gt;
        &lt;translation&gt;Voreinstellungen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Cancel&lt;/source&gt;
        &lt;translation&gt;Abbrechen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Ignore&lt;/source&gt;
        &lt;translation&gt;Ignorieren&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;N&amp;amp;o to All&lt;/source&gt;
        &lt;translation&gt;N&amp;amp;ein, keine&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Save All&lt;/source&gt;
        &lt;translation&gt;Alles speichern&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Discard&lt;/source&gt;
        &lt;translation&gt;Verwerfen&lt;/translation&gt;
    &lt;/message&gt;
    &lt;message&gt;
        &lt;source&gt;Yes to &amp;amp;All&lt;/source&gt;
        &lt;translation&gt;Ja, &amp;amp;alle&lt;/translation&gt;
    &lt;/message&gt;
&lt;/context&gt;
</code></pre>

I did not check all expressions, but the above ones make it much better.
Anyway, it's easy to find them all, because 99% of them are either in the context menu or in the QtMessageBox.

## Links
[1 – programtalk.com](https://programtalk.com/python-examples/qtpy.QtCore.QLibraryInfo.TranslationsPath/)
[2 – github.com/keepassxreboot](https://github.com/keepassxreboot/keepassxc/issues/1093)
[3 – stackoverflow.com](https://stackoverflow.com/questions/31533019/title-qt-how-to-translate-the-buttons-in-qmessagebox)
[4 – stackoverflow.com](https://stackoverflow.com/questions/35887523/qmessagebox-change-text-of-standard-button)
[5 – forum.qt.io](https://forum.qt.io/topic/43355/solved-qmessagebox-standard-buttons-untranslated-context-problem)
[6 – forum.qt.io](https://forum.qt.io/topic/84194/qmessagebox-buttons-translation-not-working/4)
[7 – doc.qt.io](https://doc.qt.io/qt-5.10/i18n-source-translation.html)

**Comment by dougmassay** [comment]
We'll look into providing support for qt_*.qm and qtbase_*.qm translations files. We just have to make sure what we do works for all three platforms. They don't have to be placed in Sigil/translations folder, though. Sigil already uses QLibraryInfo::TranslationsPath to find relevant, platform-specific paths to search for qm files (see Misc/UILanguage.cpp). It's just currently limiting that search to Sigil_*.qm files is all.

I'm not in favor, however, of adding Qt-specific translations strings to Sigil's translation strings. Seems kludgy, inefficient, and not very future-proof.

**Comment by dougmassay** [comment]
I just pushed some changes that implemented your "standard proposal." The editing of main.cpp to allow the loading of qtbase_XX.qm files if present. This worked for me on Linux and on Windows. Before the change, standard qt message box buttons weren't being translated. After the change, they were (provided that the language chosen HAD a qtbase_XX.qm file, of course).

I've even modified the Windows installer to include the qtbase files when there's a matching sigil translation file being included. This results in a minimal increase in Sigil's installer file. Of course, only translation files that exist for the Qt5 version that Sigil is built with on Windows (5.6.2 at this time) will be candidates for inclusion. There is no qtbase_es.qm file included with Qt5.6.2 for instance. People are welcome to manually copy translation files from newer Qt versions at their own risk if they like, however.

When we move to a newer Qt5 version, more qtbase languages will be included with the Windows installer (provided they coincide with included Sigil translation languages).
