### ISSUE TITLE
Recent files

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#349]
Could Sigil save in configuration (sigil.ini) **recentfiles** always with full paths to the recently opened files?

Image: [sigil.ini](https://i.imgur.com/zB7TC8c.png)

I often run Sigil from within a specific folder (for example d:\Work\client\epub\)

`"C:\Program Files\Sigil\Sigil.exe" "final.epub"`

The next time I start Sigil (for example by a shortcut on the desktop), I see the recent file name in the "File" menu: "final.epub"…

Image: [File menu](https://i.imgur.com/bFdaMa0.png)

…but after choosing this file I always get the message:

`This file no longer exists. Click OK to remove it from the menu. final.epub`

Image: [Message](https://i.imgur.com/uEHaAnX.png)

**Comment by kevinhendricks** [comment]
Settings already keeps whatever is passed to it for recent files.  You can see this by passing in final.epub as an absolute path then all functions as expected

**Comment by kevinhendricks** [comment]
Your easiest solution would be to use a bat file to launch Sigil the way you want and use bat commands to get the absolute path of the file you are passing in.  Similar things can be done in Linux using the bash script to launch Sigil and realpath (and in many other ways). On a Mac, the full path is always passed in when using a drag and drop operation to launch a particular file.

Alternatively, you could do this inside Sigil with the following patch:
```
diff --git a/src/MainUI/MainWindow.cpp b/src/MainUI/MainWindow.cpp
index 21b618f..2dab197 100644
--- a/src/MainUI/MainWindow.cpp
+++ b/src/MainUI/MainWindow.cpp
@@ -4757,7 +4757,7 @@ void MainWindow::ExtendIconSizes()
 void MainWindow::LoadInitialFile(const QString &openfilepath, bool is_internal)
 {
     if (!openfilepath.isEmpty()) {
-        LoadFile(openfilepath, is_internal);
+        LoadFile(QFileInfo(openfilepath).absoluteFilePath(), is_internal);
     } else {
         CreateNewBook();
     }
```

**Comment by BeckyDTP** [comment]
You're right. Of course, the full path to the file is enough. Both solutions work. Thank you.

New batch for Windows (for those interested):
`@"C:\Program Files\Sigil\Sigil.exe" "%~f1"`
