### ISSUE TITLE
Metadata editor adds two group-position properties.

### ISSUE THREAD

**Issue by Christmas-Cavalier** [Sigil-Ebook/Sigil#353]
Two group-position properties will be created when added in the Metadata Editor. 
This has been present for me on Sigil versions 0.9.8 and 0.9.9 running on Windows 10 64-bit.

![image](https://user-images.githubusercontent.com/38570314/39070503-61ddd4e8-447f-11e8-8784-34266be73f77.png)

**Comment by kevinhendricks** [comment]
Confirmed.  A leftover extra line from a copy and paste in MetaEditor.cpp
```
        } else if (code == "group-position") {
            QString content = "1";
            insertChild(code, content);
            insertChild(code, content);
        } else if (code == "display-seq") {
```
I will fix this in master.  Thanks for the bug report!

**Comment by kevinhendricks** [comment]
Fixed in master, closing
