### ISSUE TITLE
Compile on Mint 19 Beta

### ISSUE THREAD

**Issue by Jucker7** [Sigil-Ebook/Sigil#359]
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.5", minimum required is "3.4") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.5", minimum required is "3.4") 
-- Using Bundled ZLIB
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Using Bundled MiniZip
-- Using Bundled Hunspell
-- Using Bundled PCRE
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for C++ include type_traits.h
-- Looking for C++ include type_traits.h - not found
-- Looking for C++ include bits/type_traits.h
-- Looking for C++ include bits/type_traits.h - not found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoq
-- Looking for strtoq - found
-- Looking for _strtoi64
-- Looking for _strtoi64 - not found
-- Check size of long long
-- Check size of long long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Could NOT find Qt5LinguistTools (missing: Qt5LinguistTools_DIR)
CMake Warning at src/CMakeLists.txt:58 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "LinguistTools" config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt5LinguistTools/Qt5LinguistToolsConfig.cmake"

  

CMake Error at src/CMakeLists.txt:558 (qt5_add_translation):
  Unknown CMake command "qt5_add_translation".

-- Configuring incomplete, errors occurred!
See also "/home/alex/sigil-build/CMakeFiles/CMakeOutput.log".
See also "/home/alex/sigil-build/CMakeFiles/CMakeError.log".

============
Where I was wrong? I don't know English well...

**Comment by mihailim** [comment]
Install the package `qttools5-dev-tools` and retry.

**Comment by Jucker7** [comment]
This package is already installed.

**Comment by mihailim** [comment]
Ah, my bad, turns out in newer Debian releases that file is provided by the package `qttools5-dev` , try installing that one, too.

**Comment by mihailim** [comment]
Any feedback, @Jucker7 ?

**Comment by kevinhendricks** [comment]
Closing as no response.
