### ISSUE TITLE
Click on preview window is notsyncro with editor window

### ISSUE THREAD

**Issue by brbsoft66** [Sigil-Ebook/Sigil#376]
Sygil 0.9.10, Windows 10 x64
I've installed last version of sygil and the editor wiew is not sync with the preview window. I can scroll text in preview but when I click on the preview over a paragraph, the editor window is not updated at new position.
The inverse work properly, if I click on editor winndow the preview move to the new position of the text.

Luca

**Comment by dougmassay** [comment]
I'm leaving this issue open in the hope that others will see it and not open additional new issues about it.

**Comment by brbsoft66** [comment]
Ok, thanks, I've installed 0.9.9 and it works perfectly.
Regards

**Comment by kevinhendricks** [comment]
this is now fixed in master.  This fix will appear in the next release.  Closing this issue.
