### ISSUE TITLE
&nbsp; doubling when switching to standard view and HTML

### ISSUE THREAD

**Issue by piffy** [Sigil-Ebook/Sigil#377]
I'm using Sigil 0.9.9 under Linux(Ubuntu). I noticed that each time that I change view to HTML and back, Sigil attaches nbsp . The issue is particularly annoying for frequently used files (in the footnotes file I have lines and lines of empty spaces to clean up manually.

**Comment by dougmassay** [comment]
This is known Linux issue with a buggy system versions of libxml2. It has been reported and fixed upstream as of libxml2 version 2.9.5. Problem versions are v2.9.3 & v2.9.4.

Workarounds can be [found here](https://www.mobileread.com/forums/showthread.php?t=277628).

**Comment by dougmassay** [comment]
Closing.

**Comment by dougmassay** [comment]
Added an entry to the [Sigil Wiki](https://github.com/Sigil-Ebook/Sigil/wiki) which documents this issue and its workaround.

https://github.com/Sigil-Ebook/Sigil/wiki/Linux-Notes#if-you-notice-html-entities-being-doubled-in-your-epubs-html
