### ISSUE TITLE
Book view is unreadable when using a dark theme on plasma desktop

### ISSUE THREAD

**Issue by mikelima** [Sigil-Ebook/Sigil#381]
Hello I just tried sigil, and I have found it is unusable for me when using a dark theme on plasma desktop, as the book view has black text on dark grey. I could not find a way to change that in the settings (only the colors for the raw html view are available).

The easiest fix would be to set the canvas color to white in addition to the text color to black...
I would suggest to use the qt style colors for both background and text, but as this is a preview, you may want to keep the black text on white background.

**Comment by dougmassay** [comment]
It is the book-maker and not Sigil who would define a black canvas with grey text in Book View/Preview with the css/html in their epub (which is an epic mistake on the book maker's part). Sigil itself is unaffected by any OS-level theming in that department (nor would qt styles have any effect on the canvas of those two QWebView-base elements).

That said...

Sigil has provided users a way to apply their own preferred qt styles (.qss) to Sigil's interface for some time now, and Sigil v0.9.10+ provides a way to override the Book View/Preview css provided by an ebook.

**Comment by dougmassay** [comment]
If the background of Sigil's Book View is gray, then that is the fault of your distro altering their Sigil package to honor their desktop theming engine. No matter what theme I choose for my desktop, Sigil's Book View/Preview remains white with black text.

You could override their decision with a custom user CSS file if you had Sigil 0.9.10, but I'm afraid I've no idea how they've forced a gray Book View background. Trying to style a QWebView widget's canvas with qt styles has proven entirely unfruitful for myself and others.

As you can imagine, we're loathe to make internal changes to Sigil that would override the epub maker's wishes with regard to the html palette.

The only remedy I can suggest for you is to push your distro to upgrade to Sigil v0.9.10 so you can override the palette yourself with custom CSS, or find a way to thwart your DE's Qt theming.

**Comment by dougmassay** [comment]
Closing, as this is really a platform theming issue. There's scads of reports out there about non-KDE apps that don't look good with Plasma's dark-breeze.
