### ISSUE TITLE
Sigil crashes on macOS

### ISSUE THREAD

**Issue by laggardkernel** [Sigil-Ebook/Sigil#383]
It crashes a lot, usually when I'm scrolling across a html file. Here is the crash log, https://pastebin.com/ppS1jrFi

**Comment by kevinhendricks** [comment]
I can not recreate this at all on Mac OSX.  Your backtrace shows an issue/crash with gui Accessibility widgets deep inside Qt.  Have you enabled Apple's Accessibility features?  If so please try disabling them briefly and seeing if you can recreate the crashes.  If not, try reenabling any Accessibility features you currently are using and see if you can isolate which specific Accessbility feature(s) are causing a problem for Qt and I will try to recreate it on my MacOSX dev machine.

**Comment by kevinhendricks** [comment]
Here is a Qt bug that shows the exact same backtrace: 
https://bugreports.qt.io/browse/QTBUG-32440?attachmentViewMode=list 
that seems to be related to  Mac OSX versions and the use of "Enable access for assistive devices" enabled i n OS X.

An identical backtrace seems to have been submitted in a Sigil bug report back in 2014.  
https://github.com/Sigil-Ebook/Sigil/issues/43
That seems to come and go with Accessibility being enabled and Qt version.

**Comment by kevinhendricks** [comment]
Closing this as none of the requested additional information about which Accssibibily features were used has been provided.  If you supply that information , I would be happy to reopen this issue as I  may then be able to recreate what you are seeing.
