### ISSUE TITLE
Next tab & Previous tab shortcut assignments

### ISSUE THREAD

**Issue by daemonblade** [Sigil-Ebook/Sigil#386]
There appears to be some inconsistency in the default Next/Previous tab keyboard shortcut:

The default "Next File" assignment is "Alt+PgDown"
The default "Previous File" assignment is "Alt+PgUp"

However, default "Next Tab" is "Ctrl+PgUp"; and default "Prev Tab" is "Ctrl+PgDown". This requires mental shifting when using keyboard shortcuts.

I propose that:
- default "Next Tab" be "Ctrl+PgDown"
- default "Prev Tab" be "Ctrl+PgUp"

Coincidentally, this would also align with Chrome's next & previous tab shortcut mappings.

[Yes, I know that I can manually re-map the keyboard shortcuts]

**Comment by dougmassay** [comment]
> [Yes, I know that I can manually re-map the keyboard shortcuts]

Seeing as how changing the default shortcut mappings has managed to stomp on a few custom user mappings in the past, we're hesitant to change existing default shortcuts. And given the huge range of preferences out there, it's just safer for us to let users remap things the way they want.

My two-cents, anyway.

**Comment by kevinhendricks** [comment]
Given a user can control this if they so desire, I am in agreement with DiapDealer here.  That said if we simply reverse the one setting by default, then only if a user has reassigned only 1  of the pair, it may mess up.  This should be better than assigning new default sequences that may cause ripple conflicts.

**Comment by dougmassay** [comment]
Closing; as we seem to be in agreement about not changing the defaults at this time.
