### ISSUE TITLE
Ouput of EPUB is not same as segil book view

### ISSUE THREAD

**Issue by rockingA** [Sigil-Ebook/Sigil#388]
I have below ebook view in SIGIL
![screenshot 2018-12-04 at 12 40 33 am](https://user-images.githubusercontent.com/6483077/49396218-9d216c80-f75e-11e8-9d5b-0958f523ea78.png)

This is what I get when I save and open in ebook reader in mac
![screenshot 2018-12-04 at 12 42 05 am](https://user-images.githubusercontent.com/6483077/49396217-9d216c80-f75e-11e8-98d1-36d35be79d8e.png)

What am I missing ?.

**Comment by dougmassay** [comment]
You're not missing anything. All ebook devices and reading apps have different quirks and issues. Looking right in Sigil is no guarantee that it will render identically everywhere else. It's always been a game to get a similar look across a range of devices/apps.

Is what you're trying to accomplish even possible in the reading app you're viewing it in?

Is there a syntax error in your css that Sigil's WebKit renderer is more forgiving of than the rendering engine of your app? Adobe's RMSDK engine is notoriously unforgiving of the slightest syntax issue.

Could be any number of things.

**Comment by kevinhendricks** [comment]
This is better left to our Mobileread Sigil User's forum.  So closing this as not a Sigil bug but instead something our users should be able to help with.
