### ISSUE TITLE
Internal stylesheet cleanup

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#391]
It would be nice if the "Remove unused CSS selectors" also worked on the internal stylesheets in XHTML files.

**Comment by kevinhendricks** [comment]
Best practice for epub is not to use internal style definitions in the head tag.  Please consider extracting them  into their own stylesheet.  This is simething a plugin could do quite easily.

 That said, we have recenly embedded a new python CSS parser to improve Sigil's css parsing features and so building a single html page internal stylesheet parser plugin should now be possible.

**Comment by kevinhendricks** [comment]
Support for listing selectors in style tags in xhtml files has been added to Reports under CSS Selectors and
also to DeleteUnusedStyles.

Closing this as now fixed in master
