### ISSUE TITLE
Empty element <guide> in OPF file generating an error with epubcheck 4.1+

### ISSUE THREAD

**Issue by TristerosEmpire** [Sigil-Ebook/Sigil#392]
In my content.opf (Epub 2.0.1), I've got an empty element :

```
  <guide>
  </guide>
```

generating an error with epubcheck and the IDPF validator : 

> Error while parsing file: element "guide" incomplete; missing required element "reference"

The specification Open Packaging Format indicates : 

> Within the package there may be one guide element, containing one or more reference elements. The guide element identifies fundamental structural components of the publication, to enable Reading Systems to provide convenient access to them.

If I remove this empty <guide> (after tricky manipulations outside Sigil) everything is alright.

**Comment by dougmassay** [comment]
Yes. The change in epubcheck was noted [in this discussion](https://www.mobileread.com/forums/showthread.php?t=314323), and a fix to remove empty guide elements from epub2s [has been committed](https://github.com/Sigil-Ebook/Sigil/commit/1778e6b4f17c0f11605d8e8b2862107e50a23f4a). It will be included in the next release of Sigil.

**Comment by kevinhendricks** [comment]
Until then as a workaround simply set the start of text using set Semantics in Sigil

**Comment by kevinhendricks** [comment]
In addition in epub2, properly identifying the structural semantics (ie, the guide elements) are an important tool for quick navigation in most epub2 readers  and even mobi readers such as KindlePreview.  FWIW, IMO a well designed epub2 should rarely if ever have an empty guide element.
