### ISSUE TITLE
9.11 and 9.12 Keeps 'doubling my spaces'

### ISSUE THREAD

**Issue by rdean30** [Sigil-Ebook/Sigil#395]
I upgraded and now whenever I edit a page in my epub created in 9.10,  every `'&nbsp;'` is doubled.

**Comment by mihailim** [comment]
Your libxml2 version is buggy. Please see issue #232.

**Comment by dougmassay** [comment]
Yikes! It looks like the problematic version of libxml2 accidentally made it into my Windows installer packages. I'll re-upload some fixed installers sometime this evening. Sorry about that.

No changes to the source code or the Sigil binary itself, just the wrong libxml2 included, so no need for a new Sigil release. Thanks for catching it.

**Comment by mihailim** [comment]
Oops :) Not a Windows user so I couldn't verify easily :)

**Comment by dougmassay** [comment]
No problem. The long-standing Linux issue was my first thought, too. ;)

**Comment by rdean30** [comment]
> Yikes! It looks like the problematic version of libxml2 accidentally made it into my Windows installer packages. I'll re-upload some fixed installers sometime this evening. Sorry about that.
> 
> No changes to the source code or the Sigil binary itself, just the wrong libxml2 included, so no need for a new Sigil release. Thanks for catching it.

THANK YOU!  I'll re-download this evening.

**Comment by dougmassay** [comment]
> THANK YOU! I'll re-download this evening.
I'll post when it's safe to do so.

**Comment by dougmassay** [comment]
OK. New Windows installers and their checksums have been uploaded. Please verify that the problem is resolved and I'll close this issue. Thanks again for pointing it out so quickly.

**Comment by rdean30** [comment]
Issue is resolved with updated installer.
