### ISSUE TITLE
Chinese (Taiwan) translation removed?

### ISSUE THREAD

**Issue by cges30901** [Sigil-Ebook/Sigil#396]
After I updated Sigil to 0.9.12, I noticed that the interface language is in Simplified Chinese, and I cannot find translation for zh_TW. It seems that zh_TW translation is removed in https://github.com/Sigil-Ebook/Sigil/commit/24db6741330ed7d48c9a9d5f9da4ad739949ed81. Can you add the translation back?

**Comment by kevinhendricks** [comment]
That translation is partial and inactive.  Of the 3 Chinese translations, only zh is actively being translated and keeping up.  Until the zh_TW translations on transifex actully become active and complete the translations, they will not be added back given the zh alternative is available.

**Comment by kevinhendricks** [comment]
Also, you can also go to Transifex to the Sigil project and download the latest zh_TW ts file (download for use) and use Qt Qlinguist or Qt's lrelease command line program to convert your .ts file to a .qm file and manually add it to the released version of Sigil.

That will get you back to what you had before.

Closing this as "not a bug" as even more languages with inactive translations will  be dropped and not added back until the translations for those languages become active again.

**Comment by cges30901** [comment]
> That translation is partial and inactive

OK, I thought that strings in context GuideItems, Landmarks, MarcRelators, MarkEditor, XMLEntities were less important and was too lazy to translate them.
So, if I translate more, can you include zh_TW translation in the next version?

**Comment by kevinhendricks** [comment]
Yes, if you or others start actively translating strings and getting close to 100% (or close) like other activetranslation teams have done, I will include all active translations into Sigil.

**Comment by cges30901** [comment]
Hello, the zh_TW translation is 100% complete now.

**Comment by cges30901** [comment]
After completing translation, I find that some parts in Sigil are still in English, like file dialog.
![_2019-03-01_22-10-52](https://user-images.githubusercontent.com/19516286/53643415-f2422100-3c6e-11e9-8465-7ce1de7e1fcb.png)
It seems that Qt translation is not loaded correctly. I will open a new issue later.
