### ISSUE TITLE
Dark mode Mac Mojave

### ISSUE THREAD

**Issue by NoralK** [Sigil-Ebook/Sigil#399]
Sigil 0.9.12 on a Mac with Mojave in dark mode does not show the TOC or the Book Browser.  The backgrounds and text color are white and unless you click on something it will not show.

I tested 0.9.11 and this issue was present as well.  I have reverted to 0.9.10 which does not have this issue.

Noral

**Comment by kevinhendricks** [comment]
Darkmode support in MacOS mojave under Qt less than 5.12.2 is still incomplete.  Digil uses Qt 5.11.2 and so dark mode is not officially support by Sigil inany version yet.  What works and what doesn't changes with each release.  There are ways to work around these issues using Qt stylesheets which are supported in Sigil.  There is an entire thread on DarkMode support in our MobileRead users forum.

Sorry thisis not a "bug" in Sigil and is completely under the control of the Qt library Sigil depends on.

Please check outour user forum on www.mobileread.com for help.

Closing this as nota Sigil bug.
