### ISSUE TITLE
Better integrate a css parser into Sigil was Fixed: Stylesheet cleanup removes used styles with non-ASCII names

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#402]
If there is a used style with a name like `títul`, it gets removed despite its being used.

**Comment by kevinhendricks** [comment]
Does your stylesheet have the correct charset set as its first line.  Is it utf-8 encoded and not latin 1.  Any class names and text /html will be converted to utf-8 upon loading to Sigil.

Please post a test case epub with one html file that uses that class and the associatd css stylesheet so we can recreate your issue.

**Comment by BeckyDTP** [comment]
A sample file that demonstrates the problem.
[issue402-epub.zip](https://github.com/Sigil-Ebook/Sigil/files/2968909/issue402-epub.zip)

**Comment by kevinhendricks** [comment]
@BeckyDTP 
If you get a free moment please try this patch with some of the more complicated css styles sheets you use to see if this change of what not to remove (ie. not a unicode \w in the regular expression) as opposed to the not in A-Z,a-z, range) is not too loose that it allows the parser to get confused.

This part of css parsing is another task that I will spin off for the python based css_parser in the future.

If it seems to be robust, I will push it for the next release hopefully sometime in the next week or so.

In your simple testcase, it now found all 3 classes in the html and visa versa.

Thanks,

```
diff --git a/src/Misc/CSSInfo.cpp b/src/Misc/CSSInfo.cpp
index 4e69e534..ae88811d 100644
--- a/src/Misc/CSSInfo.cpp
+++ b/src/Misc/CSSInfo.cpp
@@ -463,7 +463,8 @@ void CSSInfo::parseCSSSelectors(const QString &text, const int &offsetLines, con
 {
     QRegularExpression strip_attributes_regex("\\[[^\\]]*\\]");
     QRegularExpression strip_ids_regex("#[^\\s\\.]+");
-    QRegularExpression strip_non_name_chars_regex("[^A-Za-z0-9_\\-\\.:]+");
+    // QRegularExpression strip_non_name_chars_regex("[^A-Za-z0-9_\\-\\.:]+");
+    QRegularExpression strip_non_name_chars_regex("[^\\w_\\-\\.:]+", QRegularExpression::UseUnicodePropertiesOption);
     QString search_text = replaceBlockComments(text);
     // CSS selectors can be in a myriad of formats... the class based selectors could be:
     //    .c1 / e1.c1 / e1.c1.c2 / e1[class~=c1] / e1#id1.c1 / e1.c1#id1 / .c1, .c2 / ...
```

**Comment by BeckyDTP** [comment]
I feel that it is better (at least for Latin characters with diacritics).

Although the standard allows more
https://www.w3.org/TR/CSS21/syndata.html#characters

... but does anyone _really_ use [them](https://css-tricks.com/unicode-class-names/) in epub files? 
[issue402-v5-epub.zip](https://github.com/Sigil-Ebook/Sigil/files/2970658/issue402-v5-epub.zip)

On the other hand – in the calibre editor it works.

**Comment by kevinhendricks** [comment]
Hi Becky,

Yes the spec allows all of them including nonbreaking spaces and other whitespace!
The Qt code handles them just fine.  The only code that has an issue is the reports code and checking for unused classes.

So I will push the change as is and in a future release move more of the CSSInfo code to use our new python based css-parser.

Thanks for testing it.

I will leave this issue open to remind me.

Take care,

Kevin

**Comment by kevinhendricks** [comment]
This change has been pushed to master and will appear in the next release, hopefully soon.

**Comment by kevinhendricks** [comment]
Closing this as a C++ CSSParser has now been added to master that can better be used to parse CSS.  In addition, work is also underway to create an embedded python interface to our python css-parser.
