### ISSUE TITLE
Does Sigil 0.9.13 on Windows 10 displays CSS grids in book view ? 

### ISSUE THREAD

**Issue by YKastell** [Sigil-Ebook/Sigil#403]
the following code that displays well with Firefox / Chrome / Edge does not work in Sigil book view 

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto auto;
  grid-gap: 10px;
  background-color: #2196F3;
  padding: 10px;
}

.grid-container > div {
  background-color: rgba(255, 255, 255, 0.8);
  text-align: center;
  padding: 20px 0;
  font-size: 30px;
}
</style>
<title></title>
</head>
<body>
<h1>grid-template-columns</h1>

<p>You can use the <em>grid-template-columns</em> property to specify the number of columns in your grid layout.</p>

<div class="grid-container">
  <div>1</div>
  <div>2</div>
  <div>3</div>
  <div>4</div>
  <div>5</div>
  <div>6</div>
  <div>7</div>
  <div>8</div>
</div>
</body>
</html>

**Comment by dougmassay** [comment]
It does work. But unfortunately, WebKit still requires the -webkit- prefixes for it to work.

`.grid-container {
  display: -webkit-grid;
  -webkit-grid-template-columns: auto auto auto auto;
  -webkit-grid-gap: 10px;
  background-color: #2196F3;
  padding: 10px;
}`

**Comment by YKastell** [comment]
Thanks !
doubling the lines (with and without -webkit-) seems to authorize a fallback (sigh!)

**Comment by dougmassay** [comment]
Yeah, I tested it by doubling everything, too.

Still ... I have to figure it's a _bit_ of a nice upgrade. Grids wouldn't display _at all_ with the WebKit that came with Sigil 0.9.10 and earlier (prefixes or no).
