### ISSUE TITLE
I have some problem in the windows?

### ISSUE THREAD

**Issue by GentlePony** [Sigil-Ebook/Sigil#405]
I follow the your step in windows,but I still  experience some problem at the last step.when I configuring Sigil with cmake,it's tell me the following:
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at D:/cmake-3.14.0-win64-x64/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/sigil-mybuild/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_2a030\fast
        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" -f CMakeFiles\cmTC_2a030.dir\build.make /nologo -L                  CMakeFiles\cmTC_2a030.dir\build
    Building C object CMakeFiles/cmTC_2a030.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe @C:\Users\ADMINI~1\AppData\Local\Temp\nmCB16.tmp
    testCCompiler.c
    Linking C executable cmTC_2a030.exe
        D:\cmake-3.14.0-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_2a030.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\cmTC_2a030.dir\objects1.rsp @C:\Users\ADMINI~1\AppData\Local\Temp\nmCB85.tmp
    RC Pass 1: command "rc /foCMakeFiles\cmTC_2a030.dir/manifest.res CMakeFiles\cmTC_2a030.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。NMAKE : fatal error U1077: 'D:\cmake-3.14.0-win64-x64\bin\cmake.exe' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)

-- Configuring incomplete, errors occurred!
See also "D:/sigil-mybuild/CMakeFiles/CMakeOutput.log".
See also "D:/sigil-mybuild/CMakeFiles/CMakeError.log".
So,can you tell me why?

**Comment by dougmassay** [comment]
Looks like something's wrong with the environment being created by the Visual Studio developer prompt. Note that installing Visual Studio 2017 breaks the Visual Studio 2015 Dev Prompts (even if you tell the installer to include the Visual Studio 2015 toolchain). Either that, or you've installed a newer Windows SDK on top of Visual Studio 2015 and broken something.

If you DO have Visual Studio 2017 installed, use the corresponding VS2017 developer prompt and pass it the new -vcvars_ver=14.0 option to make it to use the correct VS 2015 toolchain.

**Comment by dougmassay** [comment]
If you DO have VS2017 installed, there are more details here:
https://developercommunity.visualstudio.com/content/problem/139884/vs2015-native-tools-command-prompt-not-working.html

If not, I'm afraid I'm out of ideas. Cmake 3.14 is pretty new. perhaps back off to 3.11 or 3.12.?

**Comment by dougmassay** [comment]
I'm afraid that's about all the help I can provide on this issue. Rest assured that the instructions for building Sigil on Windows will work if your Visual Studio is set up correctly. I do it that way all the time. Unfortunately I can't be much help if there's something wrong with your Visual Studio setup/config.

**Comment by GentlePony** [comment]
If I have uninstalled the VS2017,the VS2015 will not be work normally.Now how can I configure -vcvars_ver=14.0 and x64 option on the VS2017.I'm not be familiar with VS.

**Comment by dougmassay** [comment]
You don't have to uninstall VS2017, you just can't use the shortcuts for VS2015 developer prompts after VS2017 is installed. Instead you should copy the corresponding VS2017 developer prompt  (probably x64 Native Tools) to your desktop and tweak it to use the VS2015 toolchain (-vcvars_ver=4.0).

From the Start button you can open the VS2017 program group, right-click on one of the Developer Prompt shortcuts and select More->Open File Location. Then copy the x64 Native Tools Developer Prompt shortcut to your desktop. Right click on it and select Properties. In the Target field; add -vcvars_ver=14.0 to the end of that line (outside of the quote, with a space between).

Alternatively, you could just run:

`CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.0`

from within a command prompt. As long as you don't close that command prompt, the 64- bit VS2015 toolchain should be configured and ready.

Some familiarity with Visual Studio is going to be required, I'm afraid. I hope what I've given you will help you on your way.

**Comment by GentlePony** [comment]
In fact(I reinstalled VS2015 and uninstalled VS2017),if I'm building a 64-bit version of Sigil with the "VS2015 x64 Native Tools Command Prompt" shortcut,it will be wrong.But if I'm building a 32-bit version of Sigil with the "Vs2015 x86 Native Tools Command Prompt",it will not.can you tell me why?
X64;
D:\sigil-mybuild>cmake -G "NMake Makefiles" -DWIN_INSTALLER_USE_64BIT_CRT=1 -DCMAKE_PREFIX_PATH="D:\Qt\5.11.2\mscv2015_64\lib\cmake" -DCMAKE_BUILD_TYPE=Release "D:\sligil-src"
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at D:/cmake-3.14.0-win64-x64/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/sigil-mybuild/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_beb57\fast
        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" -f CMakeFiles\cmTC_beb57.dir\build.make /nologo -L                  CMakeFiles\cmTC_beb57.dir\build
    Building C object CMakeFiles/cmTC_beb57.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe @C:\Users\ADMINI~1\AppData\Local\Temp\nm2C6B.tmp
    testCCompiler.c
    Linking C executable cmTC_beb57.exe
        D:\cmake-3.14.0-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_beb57.dir --rc=rc --mt=C:\PROGRA~2\WI3CF2~1\8.1\bin\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\cmTC_beb57.dir\objects1.rsp @C:\Users\ADMINI~1\AppData\Local\Temp\nm2CDA.tmp
    LINK Pass 1: command "C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\cmTC_beb57.dir\objects1.rsp /out:cmTC_beb57.exe /implib:cmTC_beb57.lib /pdb:D:\sigil-mybuild\CMakeFiles\CMakeTmp\cmTC_beb57.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_beb57.dir/intermediate.manifest CMakeFiles\cmTC_beb57.dir/manifest.res" failed (exit code 1120) with the following output:
    testCCompiler.c.obj : error LNK2001: 无法解析的外部符号 __RTC_InitBase
    testCCompiler.c.obj : error LNK2001: 无法解析的外部符号 __RTC_Shutdown
    LINK : error LNK2001: 无法解析的外部符号 _mainCRTStartup
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\kernel32.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\user32.lib : warning LNK4272:库计算机类型“x64”与目标计 算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\gdi32.lib : warning LNK4272:库计算机类型“x64”与目标计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\winspool.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\shell32.lib : warning LNK4272:库计算机类型“x64”与目标计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\ole32.lib : warning LNK4272:库计算机类型“x64”与目标计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\oleaut32.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\uuid.lib : warning LNK4272:库计算机类型“x64”与目标计算 机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\comdlg32.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“X86”冲突
    C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64\advapi32.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“X86”冲突
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64\MSVCRTD.lib : warning LNK4272:库计算机类型“x64”与目标计算机类型“X86”冲突
    cmTC_beb57.exe : fatal error LNK1120: 3 个无法解析的外部命令
    NMAKE : fatal error U1077: “D:\cmake-3.14.0-win64-x64\bin\cmake.exe”: 返回代码“0xffffffff”
    Stop.
    NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"”: 返回代 码“0x2”
    Stop.
X86:
D:\sigil-mybuild>cmake -G "NMake Makefiles"  -DCMAKE_PREFIX_PATH="D:\Qt\5.11.2\mscv2015_64\lib\cmake" -DCMAKE_BUILD_TYPE=Release "D:\sligil-src"
-- Using Bundled ZLIB
-- Using Bundled MiniZip
-- Using Bundled Hunspell
-- Using Bundled PCRE
-- Using the 64 bit CRT in the Sigil Windows installer
-- Ensure vcredist_x64.exe for VS2015 has been placed in installer/ if you plan on running makeinstaller
-- Configuring done
-- Generating done
-- Build files have been written to: D:/sigil-mybuild
So does X86 refer to CPU architecture or operating system digits?

**Comment by GentlePony** [comment]
Thanks,I solve the problem.

**Comment by GentlePony** [comment]
when I build All_BUILD in the VS2015
error LNK1104	 can't "python37_d.lib”	Sigil	D:\sigil-mybuild\src\LINK	1

**Comment by GentlePony** [comment]
So,I will tell you that python37_d.lib not exist,just python37.lib.so I think the python37_d.lib is remove.
https://blog.csdn.net/zhuxukang/article/details/79614335

**Comment by GentlePony** [comment]
when you install python,you need select deug binaries.(it's important)

**Comment by dougmassay** [comment]
Building a debug version of Sigil with VS is not possible at this time. So do not try to Build All. Build Release. A!so ... while it may work. Generating Visual Studio project files is not the recommended way to build Sigil. Generating nmake makefiles is.
