### ISSUE TITLE
Sigil won't open.

### ISSUE THREAD

**Issue by Tinker-Books** [Sigil-Ebook/Sigil#406]
Just installed Sigil on my Windows 10 x64 laptop and it doesn't open. Click on any of the shortcuts and nothing happens. Installed using the windows x64 setup.

**Comment by dougmassay** [comment]
https://github.com/Sigil-Ebook/Sigil/wiki#if-youre-here-because

**Comment by dougmassay** [comment]
Feel free to reopen this issue if the wiki info I posted the link to didn't fix your issue.

**Comment by Tinker-Books** [comment]
Re-installed and it works Okay now.
