### ISSUE TITLE
I try to modify it in VS,but I can't find any view.so it's hard to modify it.Do you have any suggesttion in windows?

### ISSUE THREAD

**Issue by GentlePony** [Sigil-Ebook/Sigil#407]

**Comment by GentlePony** [comment]
I want add format not only epub.

**Comment by GentlePony** [comment]
I want add zip format in the project not only epub.

**Comment by GentlePony** [comment]
for example,i want modify output file epub to zip.

**Comment by dougmassay** [comment]
Please don't use the Issue database for getting advice on how to modify Sigil's codebase, or how to achieve a particular goal. That's not what the Issue system is for. It's for reporting bugs and suggesting new features. I've been patient with giving you some advice on how to use Visual Studio, but the time has come for you to start doing your own homework. Good luck in your endeavors.

**Comment by GentlePony** [comment]
I'm sorry to disturb you and thanks for you support me build in VS.
