### ISSUE TITLE
Turkish gui

### ISSUE THREAD

**Issue by umitkabuli** [Sigil-Ebook/Sigil#408]
Where is gui and messages language files. I forked it and want to translate to Turkish Sigil.

**Comment by umitkabuli** [comment]
sigil_<lang_code>.ts 
Qt 5 Linguist. Ok, I learning

**Comment by dougmassay** [comment]
Please note that if you want your work to be included in new Sigil releases, you'll need to join the volunteer group at Transifex. That's where we get all our Sigil translation files when making a new release. We don't accept direct translation pull-requests.

There's already some work that's been done on a Turkish translation there, but it doesn't meet out requirement of having a minimum of 75% of the translatable strings translated to be included in Sigil releases.

https://www.transifex.com/projects/p/sigil/

**Comment by kevinhendricks** [comment]
closing this as I see you have joined at Transifex
