### ISSUE TITLE
"Entity 'nbsp' not defined" with the Sigil 0.9.13

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#410]
Hello guys,

I got this error :

![Annotation 2019-04-02 090749](https://user-images.githubusercontent.com/8157490/55379873-0e173c00-5527-11e9-9532-4889027a4d7f.jpg)

on this code :

![Annotation 2019-04-02 090837](https://user-images.githubusercontent.com/8157490/55379899-25eec000-5527-11e9-9690-d2ede7e0c44b.jpg)

I can't find where to solve this. Note that this error appears only on the preview panel when I preview the document at the same time with the "F2" key on the next side. This error doesn't appear when I switch back to the code view.

Thanks team.

**Comment by dougmassay** [comment]
Named entities aren't valid in EPUB3. As mentioned in the [General Tips](https://github.com/Sigil-Ebook/Sigil/wiki#general-platform-agnostic-tips) in the Wiki, you should change the entities in your Preserve Entities list to their numeric equivalents if you're primarily going to be working with EPUB3.

**Comment by dougmassay** [comment]
If that's not the problem, then you may have some corruption in your Sigil preference files. The only way to fix that is to delete them.  See here: https://github.com/Sigil-Ebook/Sigil/wiki#if-youre-here-because

**Comment by hantsaniala** [comment]
Thanks for the answer, deleting the "&nbsp;" in the "Preserve Entities" solve the problem.

**Comment by dougmassay** [comment]
You'll probably want to put the numeric equivalent in there (& # 1 6 0;). For the time being, having one or the other in there will prevent Sigil from inserting the wrong one anyway. The numeric entity will work for either EPUB2 or EPUB3.
