### ISSUE TITLE
Frequently unresponsive and then force quit

### ISSUE THREAD

**Issue by madlogos** [Sigil-Ebook/Sigil#411]
The software frequently gets unresponsive and then quits forcefully when I try to open a file by double clicking the object in the left navigation pane. There is no definite trigger for this problem, seems quite random. 

OS: Windows 10 Home Edition (64-bit), 1809
Version: 0.9.13 64-bit
QT: 5.11.2

**Comment by kevinhendricks** [comment]
Yes there is a bug/leak in the new Qt Webkit that seems to hit Windows harder than Mac or Linux.  Typically this happens with epubs with embedded fonts, lots of images or svg based images.  We are working to track it down and minimize our memory footprint to try to compensate but a completely new version of QtWebkit may be required.

We are also working on porting Sigil to QtWebEngine (google/chrome based) just in case as work on QtWebkit seems to have come to a stop.

Partial Workaround: Use Windows Defender security settings to disable Control Flow Guard (CFG) just for Sigil as google engineers discovered that CFG never frees its memory at all (a severe Windows bug) and is this hits very hard by programs that start up lots of new threads/processes at new locations (javascript jit and garbage collection threads in QtWebkit).  This hit google chrome so hard they had to redesign their blink engine to reuse thread starting locations from previous threads that exited.

See: 

https://randomascii.wordpress.com/2018/08/22/24-core-cpu-and-i-cant-type-an-email-part-two/
For more info about CFG related bugs in the latest Windows builds.

**Comment by kevinhendricks** [comment]
As an alternative, you may want to drop back to Sigil-0.9.10 as it uses a much older version of QtWebkit (from Qt 5.6.2) that seems to be immune to most of these issues.  Do NOT use Sigil 0.9.11 or Sigil-0.9.12 as they suffer from huge Qt bugs regarding utf-8 settings ini files that we tried to use but had to walk back from.

**Comment by kevinhendricks** [comment]
In addition, we have moved our next release build to use the latest Qt 5.12.2 and even added our own patches to QtWebkit-5.212  (annulen) but webkit still leaks horribly when an epub uses svg images and Preview is reloaded.  Only a new version of WebKit will help with properly freeing memory when svg image files are used.

**Comment by madlogos** [comment]
Hi @kevinhendricks, really appreciate your response and the workaround/suggestions.

**Comment by kevinhendricks** [comment]
As we have an WebEngine based build without these issues and given a new QtWebKit does not look to be in progress, I am closing this issue as our next release based on master or engine should already have improvements in place this.

Thank you for your bug report.
