### ISSUE TITLE
"Open With" forgets applications previously used

### ISSUE THREAD

**Issue by DVdeLima** [Sigil-Ebook/Sigil#412]
When right-clicking on an image, the user is presented with several options, the second being "Open With >" in which the image is opened with a third-party application.

It used to be Sigil had IrfanView saved and that was the only option and it worked. Now it presents multiple choices but they're all greyed out and I have to select "Other Application..." then specify the application path. This occurs every single time I attempt to "Open With >"

**Comment by dougmassay** [comment]
It should allow you to select up to five different external applications for each file-type. This has been tested and found to be working as of the last release. You will have to reset your applications for each different file-type (html, image, css, etc...). If it's not remembering your selections (for each file-type) from session to session, then it's possible you have corrupted ini preference files.

Are you sure it's not remembering, or are you just accessing a different filetype that's not been set yet?

**Comment by dougmassay** [comment]
Can you post a screen shot of the greyed-out choices? I can't duplicate the problem. None of the choice are greyed out for me and they all launch the external app with the file in question.

Also, what OS are you using?

**Comment by kevinhendricks** [comment]
I tested this on MacOSX as well and no issues.  To prevent backwards compatibility with settings, the new Open With does not use or overwrite the old open with settings as that would cause problems when reverting to an older version of Sigil without as many openwith slots.

Closing this as works-for-me.
