### ISSUE TITLE
Cover Semantics not honored when replacing image

### ISSUE THREAD

**Issue by adamjury** [Sigil-Ebook/Sigil#415]
If you have an image that is set to Cover Image and use Add Existing Files to replace it with an updated version, you get the message:

"The multimedia file "$filename" already exists in the book. OK to Replace?"

Selecting OK correctly replaces the image, but it is no longer configured as the Cover Image. I believe the better behavior would be to retain the Cover Image semantics.

**Comment by kevinhendricks** [comment]
Just pushed a fix to both master and engine branches for this issue.  The fix will be in the  will be in the next release of Sigil.  Closing this issue as fixed.

Thank you for your bug report.
