### ISSUE TITLE
Icon of Sigil is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [Sigil-Ebook/Sigil#417]
Hi

I have Sigil 0.9.13 installed on Arch Linux running KDE Plasma 5.15.4 desktop environment.
As we can see in the screenshot below, Sigil shows a Wayland generic icon instead of its own icon on Wayland session.

![sigil](https://user-images.githubusercontent.com/15967631/56924483-5f253c00-6aa3-11e9-9900-bfed4644273f.png)

**Comment by dougmassay** [comment]
Does it show the correct icon in the menus?

I'll be honest: I don't use KDE or Wayland, so it will be difficult for me to debug this. We have tons of workarounds for KDE in place all ready. This will probably require another one.

**Comment by kevinhendricks** [comment]
Shouldn't this be reported to the Arch maintainer too as it is probably build/install related?

**Comment by stikonas** [comment]
You need to set correct desktop file location with
https://doc.qt.io/qt-5/qguiapplication.html#desktopFileName-prop
to fix this.

Icon is taken from desktop file.

**Comment by dougmassay** [comment]
I know the icon is taken from the desktop file, but no other DE that I know of has ever had trouble determining the correct icon from Sigil's existing desktop file without that Qt property being set before this. Sigil's desktop file has always been installed in one of the standard directories for application desktop files. Specifically: \<install prefix\>/share/applications.

**Comment by dougmassay** [comment]
I mean, there's no problem setting desktopFileName to "sigil.desktop" if it will fix the issue. Just seems a bit silly that it's necessary is all.

**Comment by stikonas** [comment]
I think on X most of the DE (including Plasma) were doing a lot of heuristic guesses. I guess with the migration to Wayland it was viewed as an opportunity to do things properly.

A bit similarly people are encouraged not to run GUI apps as root on Wayland even though it is technically possible. On the first glance it was unnecessary change but in the long term not running GUI as root is better.

**Comment by eli-schwartz** [comment]
> Shouldn't this be reported to the Arch maintainer too as it is probably build/install related?

Not really, since I cannot see how the build/install process has to do with my packaging. Wayland is just "different" from X11 and this is exactly the sort of snag I'd expect from fundamentally Wayland things.

I don't use Wayland either, but I thing @stikonas' suggestion is quite plausible.

**Comment by dougmassay** [comment]
I can't really see any downside to setting the desktopFileName property. It's just the basename of the desktop file with no path info. Will it be ignored by other platforms or should I ifdef it for Linux-only, I wonder?

**Comment by stikonas** [comment]
As far as I know it has no effect on other platforms. There were quite a few similar commits fixing icon issue in KDE codebase itself.

**Comment by dougmassay** [comment]
I'm not willing to drop Sigil support for Qt5.5/5.6 for something as simple as an icon showing up. So I'll use the QT_VERSION macro to ensure app.setdesktopFileName only happens on Qt5.7+

Of course we won't really know if it works unless Arch cherry-picks the commit or @glaubersm rolls their own from master.

**Comment by glaubersm** [comment]
Unfortunately I do not understand anything about software development.
Sigil icon also is incorrect on another distribution called Neon developer unstable.
Several other apps also had incorrect icon on Plasma Wayland but now they are already fixed.
And yes, Sigil icon is correct in the apps menu.

**Comment by stikonas** [comment]
> I'm not willing to drop Sigil support for Qt5.5/5.6 for something as simple as an icon showing up. So I'll use the QT_VERSION macro to ensure app.setdesktopFileName only happens on Qt5.7+

`#ifdef` is definitely the right way to do it. You shouldn't run Wayland with anything less than Qt 5.12 anyway, so there is no loss if icons on wayland are not shown with Qt 5.6.

**Comment by dougmassay** [comment]
Thanks. I'll push an update and see what happens, I guess! I appreciate the insight into this particular Wayland quirk.

**Comment by dougmassay** [comment]
@glabersm : if what I'm reading about Wayland from [here](https://github.com/qt/qtwayland/blob/dev/src/client/qwaylandwindow.cpp#L141) is true, you may be able to work around the issue in the meantime by renaming the sigil.desktop file in /usr/share/applications to com.sigil-ebook.sigil.desktop. No guarantees something else might not go wonky, but it would be pretty easy to try it and put it back the way it was if need be.

Otherwise you're going to need to wait until there's a new Arch version of Sigil.

**Comment by glaubersm** [comment]
Right. I still use Plasma X11 because Wayland session is not yet fully usable.
Therefore I can wait for a new Arch version of Sigil.

**Comment by eli-schwartz** [comment]
> unless Arch cherry-picks the commit

Doubtful unless I'm already rebuilding the package for something else.

However, I'd instead suggest using the AUR package "sigil-git", which I maintain as well. And I also provide a custom binary repository here: https://wiki.archlinux.org/index.php/Unofficial_user_repositories#eschwartz

> Unfortunately I do not understand anything about software development/packing.

The AUR is pretty easy to use, but if you don't feel comfortable using it, then you can use my binary repository which I have linked. It is signed by my archlinux-keyring packaging key which I use to sign [community] packages, and is completely trustworthy. This will give you the latest development version of sigil.

**Comment by dougmassay** [comment]
Addressed with commit 4b50b94

Feel free to reopen if it doesn't resolve the issue.

**Comment by glaubersm** [comment]
I just installed sigil-git from AUR.
Bug is fixed.
Thank you all.

**Comment by dougmassay** [comment]
Thanks for reporting back!

**Comment by eli-schwartz** [comment]
Great!

For my part, I've rebuilt sigil-git to include this commit, and it is now available in the custom repo I mentioned.
