### ISSUE TITLE
Sigil 0.9.13 not starting on Windows10

### ISSUE THREAD

**Issue by zohozer** [Sigil-Ebook/Sigil#424]
Just installed the Sigil 0.9.13 on a Windows 10 machine and at launch time seems to don't open. Anything happens. Please help.

**Comment by dougmassay** [comment]
https://github.com/Sigil-Ebook/Sigil/wiki#if-youre-here-because

**Comment by dougmassay** [comment]
Feel free to reopen this issue if that info didn't solve your problem.
