### ISSUE TITLE
请问如何正则替换？

### ISSUE THREAD

**Issue by dusksoft** [Sigil-Ebook/Sigil#425]
`<p  style="text-indent:2em">第(.*)章</p>`
替换为：
`<h2 style="text-align:center">第$1章</h2>`

$1位置没有被替换

**Comment by eli-schwartz** [comment]
Can you clarify what your problem is, in English, for the benefit of most people (who do not speak Chinese)?

**Comment by BeckyDTP** [comment]
Use:
`<h2 style="text-align:center">第\1章</h2>`
