### ISSUE TITLE
add semantics with multiple files selected in Book Browser

### ISSUE THREAD

**Issue by lumpynose** [Sigil-Ebook/Sigil#427]
If I select more than one book in the Book Browser and right click on one of them and select Add Semantics... the Add Semantic Property window doesn't appear; nothing happens.

**Comment by dougmassay** [comment]
Assigning semantic properties to multiple files (simultaneously) in Book Browser is not supported at this time.

**Comment by BeckyDTP** [comment]
Add bolded line:
`            m_ContextMenu->addAction(m_AddSemantics);`
**`            m_AddSemantics->setEnabled(item_count == 1);`**
in BookBrowser.cpp to disable it in context menu for more than one files.


A disabled command in the menu will not suggest that it is possible.

**Comment by dougmassay** [comment]
> A disabled command in the menu will not suggest that it is possible.

Absolutely nothing happening is a pretty-good sign, too. ;)

We'll take it under advisement, though.

**Comment by kevinhendricks** [comment]
After looking at the list of epub 3 landmarks (see https://github.com/Sigil-Ebook/Sigil/blob/master/src/Misc/Landmarks.cpp) only "chapter" would make any real sense being applied to multiple files at once.

So adding this capability really makes no sense unless what your really want is to fire up the AddSemantics Dialog once in a loop for each resource highlighted in BookBrowser.  Given how few landmarks are typically set in any epub, this use case is not really supported.

So I am closing this as "not going to be implemented"  as unless a really good argument for the latter case can be made.

Here again, a plugin to automate setting epub3 landmark semantics en masse might be more useful.
