### ISSUE TITLE
sigil User Guide

### ISSUE THREAD

**Issue by lumpynose** [Sigil-Ebook/Sigil#428]
"If you’re generating an EPUB3 TOC, Sigil will look for nav-toc.css in your preferences directory and use that as the default file."

It's generating/using sgc-toc.css.

**Comment by dougmassay** [comment]
The user guide has it's own github repository. Please use it to report User guide issues (or to submit your own Pull Requests for User Guide changes).

And it's only generating sgc-toc.css files for epub2. For epub3, it uses/generates sgc-nav.css.
