### ISSUE TITLE
too many plugins

### ISSUE THREAD

**Issue by lumpynose** [Sigil-Ebook/Sigil#432]
I would like to use more plugins than Sigil has slots for.  Could you add more slots in a future version?  Or not have a limit on how many plugins can be installed.

**Comment by dougmassay** [comment]
There is no limit to how many plugins can be installed in Sigil. A user can install and use as many plugins as they desire. There's only a finite number of toolbar shortcut slots for a user's most often used plugins. And that number has already been increased to ten for the next version.

**Comment by kevinhendricks** [comment]
Simply install as many as you want and launch them from the Plugins menu organized by type of plugin.
