### ISSUE TITLE
interface language

### ISSUE THREAD

**Issue by holic11** [Sigil-Ebook/Sigil#433]
Please add Korean to the interface language

**Comment by kevinhendricks** [comment]
That is up to the Transifex Korean translation team for Sigil.  Right now that translation is only 39% complete and inactive.  As it stands it does not meet the policy standard for inclusion in Sigil's release builds:

Sigil's policy for inclusion is stated here:

https://www.mobileread.com/forums/showthread.php?t=315826

Your options are:

1. You can manually pull down that incomplete translation and include it with Sigil's source and build your own.

2. You can join the Korean translation team on Transifex  and help complete the translation or support/encourage those doing the translations.

Sorry.

Closing this
