### ISSUE TITLE
epub files could not be unencrypted

### ISSUE THREAD

**Issue by johnciaccio1** [Sigil-Ebook/Sigil#436]
Any idea what I need to do to open, edit and write again?  Thanks in advance for any assistance you may provide.  I am back on ver 9.10.  I can save and read everything from today, before that I cannot.
error message is  https://github.com/Sigil-Ebook/Sigil/issues/436#issue-462253689

**Comment by kevinhendricks** [comment]
A few details would help. Minimalism is not helpful in a bug report.  What is the exact problem?  What platform?  Does Sigil generate that error message (subject header) or something else?  The only “encryption” Sigil uses is to unobfuscate obfuscated font files for embedded font files.  If your epub is using DRM, it can not be edited in Sigil.

**Comment by kevinhendricks** [comment]
Searched for that error message in Sigil but could not find it.  Are you sure it is from Sigil itself.

**Comment by johnciaccio1** [comment]
Good evening,

My platform is windows 10.  The files were generated on sigil ver 9.10.    The error message is  Cannot unzip EPUB: C:\Users\me\Desktop\SigilPortable\4.epub   That message is generated by sigil.  I am not using drm.


________________________________

**Comment by johnciaccio1** [comment]
That is the code I copied off of the gui.   I copied the one I sent you off of the details.  That came through clean.  By reinstalling the program, fourth time, I was able to open three of four epubs.
________________________________

**Comment by kevinhendricks** [comment]
That  error means  Sigil can not open that specific epub  file.  Does the file exist?  Is it readable?  Since an epub is  basically a zip file, test that an unzip program can actually open it.  If so Sigilshould be able to open it to.

**Comment by johnciaccio1** [comment]
7zip can open all but the one.  The file exists, i was just on it last night.

**Comment by kevinhendricks** [comment]
Check your file permissions.  Also Sigil uses a Windows temp directory which users sometimes lose write permission to.  Please check.

This is not a Sigil  specific. Error.  This is your computer preventing Sigil from unzipping

**Comment by johnciaccio1** [comment]
Even though I was able to get the other 3 epubs to open?

**Comment by kevinhendricks** [comment]
Reinstalling Sigil is not a fix unless your current installation is corrupted.

Unless your anti-virus or Windows Defender is interfering in some way either by scanning files that Sigil tries to open or preventing a good install of Sigil itself.

**Comment by kevinhendricks** [comment]
If 7zip can not open that epub, then the file itself is corrupted.  Have you scanned your computer hard drive to verify it’s file system is not corrupted?

**Comment by johnciaccio1** [comment]
File permissions check out.  I still have all rights to the directory.  Antivirus is not interfering- just shut it off to check.  I will try moving the file and opening it on my non windows computer.

**Comment by kevinhendricks** [comment]
If you have a Linux because box or Mac try running unzip -t on it to have it check the zip and verify it’s integrity.

**Comment by johnciaccio1** [comment]
It is corrupted.  I will try to fix it.  Not sure why the other three wouldn't unzip.  Thank you for the help.

**Comment by kevinhendricks** [comment]
Some zip software can try to fix a broken zip.  Please try it on a copy of the original file to try to fix it if unzip -t reports it is broken.

Might want to test drive filesystem too just to be safe if reinstalling actually had an impact.

Hope you get it opened.  Closing this as not a Sigil bug since zip software will not open the file.  Feel free to reopen if you find out something more specific.
