### ISSUE TITLE
errors in epub3 intizer

### ISSUE THREAD

**Issue by Qkddl** [Sigil-Ebook/Sigil#437]
Hi
I found errors in epub3 intizer when changing Epub ver 2.0 to 3.0
this is an error code
Status: failed

Traceback (most recent call last):
  File "/Applications/Sigil.app/Contents/plugin_launchers/python/launcher.py", line 134, in launch
    target_script = __import__(script_module)
  File "/Users/YelimKim/Library/Application Support/sigil-ebook/sigil/plugins/ePub3-itizer/plugin.py", line 35, in <module>
    import tkinter
  File "tkinter/__init__.py", line 36, in <module>
ImportError: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so
  Reason: image not found
Error: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so
  Reason: image not found

Thankyou.

**Comment by dougmassay** [comment]
https://github.com/Sigil-Ebook/Sigil/wiki/Mac-OS-X-Notes#attention-mac-os-x-users

**Comment by kevinhendricks** [comment]
Going ahead and closing this as not a Sigil issue
