### ISSUE TITLE
Can be removed?

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#439]
https://github.com/Sigil-Ebook/Sigil/blob/c933189f92931cc013214226b8e16cd964d18653/src/MainUI/BookBrowser.cpp#L1088

The OPF is required for epub and can be removed

I think it should be like this:
The OPF is required for epub and can not be removed

**Comment by dougmassay** [comment]
https://github.com/Sigil-Ebook/Sigil/issues/441

Closing the other duplicate as this one was reported first.

**Comment by BeckyDTP** [comment]
Fixed by commit https://github.com/Sigil-Ebook/Sigil/commit/17ea1241a98c9c8ade472ebc6770b8bf490874ab
