### ISSUE TITLE
String not available for translation

### ISSUE THREAD

**Issue by eevan78** [Sigil-Ebook/Sigil#440]
It seems that Tools>Epub3 tools>Generate NCX from NAV menu item is not present as a source string for translation. I cannot find it in base.ts for Serbian.

![NCX](https://user-images.githubusercontent.com/27575106/61119707-7ffb0c00-a4ac-11e9-8df2-6d2645f28279.png)

**Comment by dougmassay** [comment]
Because that menu item does not exist any more. It's been combined with a new action and the wording has changed.

**Comment by BeckyDTP** [comment]
Now (from version 0.9.15) this item in the menu has the name:
**Generate &NCX/Guide for epub2 e-readers**
