### ISSUE TITLE
Moving an item causes a Segmentation Fault

### ISSUE THREAD

**Issue by kispin** [Sigil-Ebook/Sigil#443]
The last couple of versions have an issue where if I open a EPUB file and notice that one of the sub-HTML files is in the wrong location moving it causes a crash.
Import and other core functions that I use have no issues, only moves. It is easier for me to either copy/paste the file, or export and re-import the html file.

System: Linux
OS: 4.15.0-33-generic #36-Ubuntu SMP
Ver: 0.9.16
QT: 5.9.5

Action:
1) Open a file
2) Select a HTML file
3) Move it to another location in the list
**) Crash - Segmentation Fault

Error:
Warning: Trying to construct an instance of an invalid type, type id: 6357104
Warning: Trying to construct an instance of an invalid type, type id: 687891200
Warning: Trying to construct an instance of an invalid type, type id: 7274606
Warning: Trying to construct an instance of an invalid type, type id: 671118336
Warning: Trying to construct an instance of an invalid type, type id: 7864429
Warning: Trying to construct an instance of an invalid type, type id: 18432
Warning: Trying to construct an instance of an invalid type, type id: 3735600
Warning: Trying to construct an instance of an invalid type, type id: 905981184

**Comment by dougmassay** [comment]
I can't get it to crash on my Arch Linux system, but moving files in Book Browser does seem extra "fiddly" to me. It takes a good bit to get the move to initiate. I'll try it on an Ubuntu VM next chance I get.

@kevinhendricks , didn't we include some sort of delay on drag and drop back when we were trying to eliminate a crash when reordering tabs in Sigil? Can you remind me where that change was?

@kispin : I'm assuming you are building Sigil yourself? Last I checked, Ubuntu's repos weren't quite that up to date on Sigil.

**Comment by kevinhendricks** [comment]
We did do that once.  Check in main.cpp lines 246 to 249.

**Comment by dougmassay** [comment]
That's right; it was a drag distance tweak, not a delay. Thanks.

I doubt it's causing the crash, but I'd like to rule it out. If I can get Sigil to crash in an Ubuntu VM with the older Qt5, I'll see what effect commenting that line out in main.cpp might have. Since we disabled tab reordering (and the crash from doing it was pretty rare), I'm thinking maybe we don't need it. Even on Windows, you have to drag the highlighted file pretty far before the indicator that lets you know where you're dropping it appears. On my Linux system, it's far enough that it almost seems like drag and drop isn't supported in the treeview.

If @kispin is building Sigil from scratch, perhaps they can pull the current github master branch and comment out line #249 of main.cpp and test as well.

**Comment by kispin** [comment]
@dougmassay I am compiling on my own system, and I just did that check, commented out line #249 and recompiled. Although the Drag distance went to 0 (immediate) as soon as I dropped the file into the new location I got the same crash.

Is there a compilation command I can use to get additional information that maybe would assist in tracking down the fault?

**Comment by dougmassay** [comment]
We had another Linux issue like this one time where the "single-click to open files" feature of KDE was causing all kinds of extra signals to be fired when dragging and dropping in Book Browser. I don't remember the outcome and can't find the details right now, but perhaps the OP can verify if they are using the KDE DE?

**Comment by dougmassay** [comment]
If you are using KDE, see if this [entry in our Wiki](https://github.com/Sigil-Ebook/Sigil/wiki/Linux-Notes#crashes-on-kde-desktops-when-reordering-files-in-sigils-book-browser) is relevant and/or useful.

I figured that KDE bug-fix would have made its way down the pipeline by now.

**Comment by dougmassay** [comment]
v5.52.0 of KIconThemes is when the bug was first fixed. That means Disco (19.04) is probably the minimum version of Ubuntu-based distros that will have a new enough KIconThemes version to avoid the bug and not need the workaround mentioned in the Sigil wiki.

**Comment by kispin** [comment]
I put in the workaround and that didn't help.

Although I do have KDE installed it is not actually my primary environment.

**Comment by dougmassay** [comment]
Do you have single-click to open files enabled?

**Comment by kispin** [comment]
I do not

**Comment by dougmassay** [comment]
So what's your distro/version and your DE?

**Comment by kispin** [comment]
Ubuntu 18.04 lts
I am using Awesome WM

**Comment by dougmassay** [comment]
I'm not familiar with Awesome. Is it running on top of KDE or Gnome, or is it nothing but Awesome and an XServer? I'm wondering if you can login to the same machine with a different WM/DE session to eliminate Awesome as a suspect.

**Comment by kispin** [comment]
I am trying that on another system I have (Debian install with XFCE) but the initial build didn't execute
setext parseropf error -2 traceback Error: traceback report is missing

**Comment by kispin** [comment]
I have done some checks (re-compile, install and test run) on a different system that does not have the libraries installed and there is no issue. 

As a result that it the most likely cause. I will see what I can do about installing updated versions of the libraries on my main PC and see if that helps.

**Comment by kispin** [comment]
I have confirmed, I removed the libraries and the seg fault resolved.

So we can say I think that those libraries are the root cause, my system also looks to be working fine without them so I will leave them out.
We can probably lose this off, unless @dougmassay you wish to leave it open to track and try to resolve the issue with that specific version of the QT library

**Comment by dougmassay** [comment]
If by libraries, you mean the KDE libraries that they use for their system Qt theming, then yes, I agree we can close this. Though I am a little surprised that the standard workaround didn't resolve the issue. Then again, your use-case is a little non-standard. Not many people are running an alternative Window Manager with the KDE desktop installed. :)

As far as resolving the issue... I'm pretty sure it's already resolved. As soon as no one is shipping versions of KIconThemes earlier than  v5.52.0, the issue will go away. For Ubuntu, that means the Disco release.

**Comment by kispin** [comment]
Closing as the issue was caused by older QT libraries associated with Ubuntu 18.04
