### ISSUE TITLE
Sigil's CSS/Code view can not correctly display and edit Mongolian script

### ISSUE THREAD

**Issue by siqinbilige** [Sigil-Ebook/Sigil#444]
1. In sigil's preference did not list Mongoian Baiti font in windows. So can not select and use mongolian font.
![evidence1](https://user-images.githubusercontent.com/13462439/61925912-485e8a80-afa9-11e9-92e4-1440b6396099.png)
2. Even change the font with mongoian in sigil.ini file, in CSS/Code view can not correctly display and edit mongolian script.  In particular NNBSP(202F) and MVS (180E). If using newest harfbuzz( not harfbuzz-ng ), should be able to correctly display and edit Mongolian Script.
![evidence2](https://user-images.githubusercontent.com/13462439/61925913-48f72100-afa9-11e9-98db-1cae164bc791.PNG)

**Comment by dougmassay** [comment]
We're using whatever harfbuzz comes with Qt/QtWebkit.

**Comment by kevinhendricks** [comment]
According to Qt docs, at build time you can decide to use harfbuzz (or harfbuzz-ng) that comes with Qt sources in qtgui or opt to use the system-level harfbuzz.

I have no idea which harfbuzz version comes packaged in qt sources.  So this bug report should probably be directed at Qt.

**Comment by kevinhendricks** [comment]
Snooped around on the qtbase github site.  It seems according to qt, dev work on harfbuzz stopped long ago.  Their harbuzz is over 8 years old.  So they decided default to harfbuzz-ng and it is also quite old.  They use harfbuzz-ng version 1.74 and it is hugely old as well.  They still keep the original harfbuzz around for specific tasks.  So effectively they use both.

There are a number of harfbuzz-ng related bug reports to update things, but they have no plans to change anything for the Qt 5.12.x series. 

See: https://bugreports.qt.io/browse/QTBUG-70912
for one example.

So your best bet would be to add to that bug report and see if Qt will update both harfbuzz and harfbuzz-ng.

If you build your own Qt, you may be able to configure it to use a newer system harfbuzz and harfbuzz-ng.

Sorry, but this is purely a Qt issue as they determine the harfbuzz and harfbuzz-ng versions employed by Sigil.

**Comment by dougmassay** [comment]
We do a little patching of Qt, but I'm not getting into the nest of dependencies it would require to build harfbuzz on Windows. Not unless it's dead-simple (and a quick glance assures me it's not). I'll look into it for the next time we update Sigil's Qt5/QtWebEngine for Windows, but no promises.

**Comment by kevinhendricks** [comment]
Fwiw, I think Qt customizes both harfbuzz and harbuzz-ng for QtGui.  To complicate things further  QtWebengine has its own versions of both which again have been customized by Google for chrome.

**Comment by dougmassay** [comment]
Yeah, I know QtWebEngine bundles a ton customized support libraries. Even more so on Windows. It works well for the most part, so I'm not complaining, but it still makes for an overnight compilation (even on a machine with 6 cores and 32Gb of ram). So I'm not re-compiling and testing without some very compelling reasons. ;)
