### ISSUE TITLE
Last word on a paragraph clip error

### ISSUE THREAD

**Issue by tuesdaypd** [Sigil-Ebook/Sigil#446]
When I apply the last word on a paragraph, sigil translates css class into style.

For example,
● My Clip 1 = &lt;span class="title"&gt;\1&lt;/span&gt;
●  I apply it with shortcut(CTRL + 1).
● The last word of the paragraph which I applied my Clip 1 is "A"
● according to my expectation, the last word "**A**" should be changed into **&lt;span class="title"&gt;A&lt;/span&gt;**
● But It was changed into, so to speak, **&lt;span style="font-size: 0.8em;"&gt;A&lt;/span&gt;**

It is relevant to Book view.
It is NOT relevant to Code view.

Is it a bug? or intended work?
Please reply me.

**Comment by kevinhendricks** [comment]
Sigil never changes classes into styles.  BookView is gone. Please ask for further help on the Sigil user forums on www.mobileread.com.
