### ISSUE TITLE
Build 9.17 lost WYSIWYG panel view (Windows 10)

### ISSUE THREAD

**Issue by dianexml** [Sigil-Ebook/Sigil#449]

**Comment by dougmassay** [comment]
No. 0.9.15 lost the WYSIWYG view (All Platforms). On purpose.

Warnings given here:
https://github.com/Sigil-Ebook/Sigil/releases

and here:
https://www.mobileread.com/forums/showthread.php?t=320663

With reminders and notices and alternatives here:
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.15
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.16
https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone

**Comment by kevinhendricks** [comment]
Also, fwiw, You can install PageEdit-0.8.0 also by Sigil-Ebook and set it up to be easily launched by Sigil and it supports much of the same capabilities that BookView had.

**Comment by dianexml** [comment]
Cutting and pasting my notes from my internet searches and grouping them in ePubs was my main reason for using Sigil.  Non-proprietary, it was the best tool for the job.

I hope you will reconsider.  In the meantime, I will revert to a previous version.

Diane Gratton
Content Architect

________________________________
De : Doug Massay <notifications@github.com>
Envoyé : Saturday, August 10, 2019 4:20:31 PM
À : Sigil-Ebook/Sigil <Sigil@noreply.github.com>
Cc : dianexml <diane_xml@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Sigil-Ebook/Sigil] Build 9.17 lost WYSIWYG panel view (Windows 10) (#449)


No. 0.9.15 lost the WYSIWYG view (All Platforms). On purpose.

Warnings given here:
https://github.com/Sigil-Ebook/Sigil/releases

and here:
https://www.mobileread.com/forums/showthread.php?t=320663

With reminders and notices and alternatives here:
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.15
https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.16
https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone

**Comment by kevinhendricks** [comment]
Or try PageEdit launched from Sigil.

**Comment by dianexml** [comment]
No thanks, I really just need cut and paste, then I can adjust the markup (usually by removing style and class with regex).

________________________________
De : Kevin Hendricks <notifications@github.com>
Envoyé : Saturday, August 10, 2019 4:31:34 PM
À : Sigil-Ebook/Sigil <Sigil@noreply.github.com>
Cc : dianexml <diane_xml@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Sigil-Ebook/Sigil] Build 9.17 lost WYSIWYG panel view (Windows 10) (#449)

Or try PageEdit launched from Sigil.

**Comment by dougmassay** [comment]
The PageEdit program he mentioned will allow you paste your content into Sigil just like you did with Book View. And it integrates with Sigil specifically _because_ a lot of people used Book View to paste snippets into Sigil.

**Comment by kevinhendricks** [comment]
Closing as this is not actually a bug report.
