### ISSUE TITLE
Menus/clickable items and cursor don't line up correctly on secondary monitor in windows 10

### ISSUE THREAD

**Issue by ScotsScripts** [Sigil-Ebook/Sigil#454]
The cursor is almost 1/4" above it's "hot spot" so that in order to activate a menu item or anything else I need to put the cursor close to 1/4" above. This does not happen on the primary monitor, only on the secondary monitor.

I've seen this before and it happens when an app is only reading the primary monitor resolution et al instead of the current monitor. I don't know the tech jargon to describe this.

<img width="277" alt="2019-09-06 15_29_53-sigil-menu-issue" src="https://user-images.githubusercontent.com/2638315/64464120-904df280-d0bb-11e9-8848-88c5db46691e.png">

**Comment by dougmassay** [comment]
Sigil doesn't do anything with regard to primary or secondary monitors' resolutions. It relies entirely on Qt to handle that. We have several people on the user forums who use multiple monitors (some with different resolutions) and this is the first I've heard of this issue.

**Comment by dougmassay** [comment]
Incorrect mouse coordinates are usually triggered by incompatible or incorrect DPI settings/scaling. Sigil allows Qt to use a default of "Per-Monitor DPI Aware" on Windows 8.1 or higher. Are you overriding the default DPI scaling settings for the second monitor? Have you tried right-clicking on the Sigil executable and disabling DPI Scaling in the Compatibility tab?

**Comment by ScotsScripts** [comment]
I haven't changed any dpi settings for anything (windows 10.)

I tried different combinations of the DPI scaling settings (there is no override setting) and the behavior doesn't change.

Any other ideas?

**Comment by kevinhendricks** [comment]
Please test with latest versions of Sigil as it uses a newer Qt version.  If the problem still exists we can try running Qt's qtdiag.exe on your system to see exactly how Qt is interpreting your displays.

**Comment by kevinhendricks** [comment]
Closing this as no one here has been able to duplicate this Qt bugand improvements in Qt 5.15 are supposed to have fixed any of these issues.  If you can recreate this with Sigil-1.5.1 please comment here and I will reopen the issue.
