### ISSUE TITLE
No module named 'css_parser'

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#457]
Hello,
After upgrading Sigil 0.9.18, I'm facing this kind of problem with the plugin I've created. Can someone help me please ? What I should change with my code ?
Thanks.

![image](https://user-images.githubusercontent.com/8157490/65579100-ba3e5a80-df7f-11e9-8ac4-fa3c432dd380.png)

![image](https://user-images.githubusercontent.com/8157490/65579158-dfcb6400-df7f-11e9-9ecb-985e46f33b67.png)

**Comment by dougmassay** [comment]
Either tick the box to use the bundled python that comes with Sigil (which already includes css-parser), or install the css-parser module in the external python you ARE using. css-parser is a Sigil pre-req now.

**Comment by dougmassay** [comment]
I'll try to trap this error in a future release of Sigil so that it doesn't affect those who use an external python interpreter for plugins on Windows/Mac. If you don't want to install css-parser, you can also temporarily  comment out lines 234, 235 in launcher.py (or wrap them in a Try/Except clause).

**Comment by hantsaniala** [comment]
Just downloading the css-parser with `pip install css-parser` solve the problem. No need to comment the lines on launcher.py. Thanks.

**Comment by dougmassay** [comment]
Great. Thanks. Just wanted to give you some options. I honestly didn't take Windows/Mac users using external Pythons for plugins into account when adding those two lines.

**Comment by dougmassay** [comment]
Might want to make a mental note that any Windows/Mac users using an external Python interpreter will probably run into this using the the official Sigil installers starting with 0.9.18.

On Linux, the embedded python used by Sigil and the external Python used by plugins is one and the same. So css-parser's a pre-req for building and running on Linux. The distro's package management system will take of this. But with the official Windows and Mac installers, the embedded python used by Sigil will _always_ be the bundled version; which in turn, will always have css_parser available for import. But the bundled css-parser won't be available to any external Python interpreters configured for use by plugins.

Not sure if we should try/except on the launcher.py call to import css_parser (ironically only used to make sure any plugins that used cssutils will continue to function!), make css-parser a requirement in the documentation for a functioning Plugin environment (external or internal), or both.

**Comment by kevinhendricks** [comment]
We could add a try clause but fail at things later just so that the new testplugin version runs and they can manually add that package as it is required.

**Comment by dougmassay** [comment]
I'd also be OK with just telling all users who use an external python installation for plugins to make sure the test plugin passes all tests. That's what we tell Linux users to do after all.

**Comment by kevinhendricks** [comment]
But it will not run if they do not have css_parser installed yet, right?

**Comment by dougmassay** [comment]
Whoops! Yes, you're correct.

**Comment by hantsaniala** [comment]
>But the bundled css-parser won't be available to any external Python interpreters configured for use by plugins.

Do you mean that, one day, css-parser will be not available for external python interpreter ? Or maybe I misunderstand..

**Comment by dougmassay** [comment]
No. Sorry to confuse. There's no reason the css-parser module won't always be available to be installed via pip. I meant tha an external python doesn't have access to the modules that come with Sigil'l bundled python.
