### ISSUE TITLE
Book View edit mode feature no found 

### ISSUE THREAD

**Issue by chan2093** [Sigil-Ebook/Sigil#458]
Hi, before 0.9.15 Book View edit mode feature still provided, mean that feature is moved from sigil?

**Comment by eli-schwartz** [comment]
https://github.com/Sigil-Ebook/Sigil/wiki#yes-book-view-is-really-gone

Did you not read the release notes? https://github.com/Sigil-Ebook/Sigil/releases/tag/0.9.16
