### ISSUE TITLE
Logical TOC problem in Kindle on iOS

### ISSUE THREAD

**Issue by ash-f** [Sigil-Ebook/Sigil#461]
Logical TOC is shown correctly on all platform except iOS when convert epub into Kindle file.
Only iOS app does not show logical TOC.

Is this a bug or there is particular setting for iOS?

**Comment by dougmassay** [comment]
This is not a Sigil issue. How you have to create the epub in order to get a good conversion to Kindle is not our concern. If the epub is valid, Sigil's job is done.

**Comment by ash-f** [comment]
Is there a sample epub that can be converted correctly?
Just a couple of page is fine.

**Comment by kevinhendricks** [comment]
These types of questions should be directed to our Sigil users forum on Mobileread.  See our README for the link.  Our issues should not be used for user support which is why we have our user's forum.

**Comment by ash-f** [comment]
Thank you, I'll try on Mobileread.

**Comment by dougmassay** [comment]
I have no idea what the quirks of the iOS Kindle app might require in the way of special toc treatment. As Kevin mentioned, this is a question for users who have experience converting epubs to kindlebooks
