### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#463]
Filetypes here https://github.com/Sigil-Ebook/Sigil/blob/master/src/Dialogs/EmptyLayout.cpp#L51 (and next lines) are not translated, although they exist in ts/qm files.
Two translations are currently ready in 100% (Polish and German).
I tested fresh files from Transifex.
![sigil-1 0-translation-issue-de](https://user-images.githubusercontent.com/22416021/67982539-2bc69400-fc23-11e9-856c-76968d5475bf.png)
![sigil-1 0-translation-issue-pl](https://user-images.githubusercontent.com/22416021/67982540-2c5f2a80-fc23-11e9-96a0-1be4fe49ca18.png)

**Comment by dougmassay** [comment]
New dialog. I'm not the translation expert, but there's probably some sort of context missing for this dialog that allows the lupdate tool to connect all it's strings/translations properly. Either that, or it's the properties of the ui elements in question themselves. I'll take a look, but we may have to wait until Kevin is back around.

**Comment by BeckyDTP** [comment]
Sure.
This may be related to:
https://www.qtcentre.org/threads/5230-Translating-a-QStringList?p=27107

**Comment by kevinhendricks** [comment]
That issue is for trying to translate an entire QStringList in one go. We are not trying that.  So I think the problem is that they are static const and not namespaced.  I will move the definitions of those two strings into the routine that builds that menu, removing the need for static and removing the const bit also.  

I'll try that when I get back.

**Comment by dougmassay** [comment]
Not that that pull request needs to be used or anything. Just throwing it put there as a possibility in case you didn't want to move the the entire stringlist creation into the relevant routine.

And in fact, it clearly doesn't compile anyway, so there's also _that_ ;)

**Comment by kevinhendricks** [comment]
Something is funny here.  Inside the EmptyLayout we should not need to use or add QObject:: to tr.  The EmptyLayout.h file specifies the proper QOJECT macro.

So something is broken as tr here should work inside that objects code.  So you change should have been correct.

I am not sure why the QOBJECT macro is being ignored in a dialog that specifies it and that inherits directly from QDialog.

This may take some digging.

**Comment by dougmassay** [comment]
It's building now (without QObject::), but I can't really test it without regenerating the base language file and getting new translations.

**Comment by kevinhendricks** [comment]
Nice catch!  The exact steps to delete the base.ts file locally and rebuild it are in the Translating.md file in Sigil/docs.  Once recreated it can be pushed.  Don't forget the numerusform fix!  I think there are 9 places that that find and replace are needed.

**Comment by dougmassay** [comment]
It's not quite working. lupdate complains that there's no context for those QT_TR_NOOP requests. Might need to use QT_TRANSLATE_NOOP and manually give those strings a context.

I'd like to test it locally if I could. Is there anyway that I can grab the latest, mostly complete, German .ts file from Transifex so I can manually merge my small changes with it and create my own .qm file to test with?

**Comment by kevinhendricks** [comment]
Or just move that QStringList into the routine that builds the menu.  That might be simpler in the end.

**Comment by dougmassay** [comment]
You're probably right. Should we move both QStringLists into that routine? Considering that's the only place they're used and that they need to be kept in sync with each other?

@BeckyDTP Just to satisfy my own curiosity, can you take one of your fresh Transifex .ts files, use it to build a new .qm file, and insert it into an installation of my latest PR build (https://ci.appveyor.com/project/Sigil-Ebook/sigil/builds/28548716/artifacts) and let me know if there is any difference? Or you can get me one of the updated Transifex .ts files if you like.

It may not work. But then again, I've not changed any of the line numbers, contexts or strings with my experimenting, so I'm hoping it might be able to prove the concept without having to do a full recreate of the base.ts file. That can happen later.

**Comment by kevinhendricks** [comment]
You can move both or even easier get rid of both lists and the loop and covert them to a straight sequence of assignment statements in the menu creation routine that use tr directly on the string literals.

**Comment by dougmassay** [comment]
I'm rolling the dice with commit 4670b45 for now. If it's still not working after translating is done, we'll revisit after we get the v.1.0 pre-release out there.

I think I regenerated base.ts correctly (and did the numerusform fix in 9 places) :)

**Comment by BeckyDTP** [comment]
I tested this commit and there is no difference.
English names in this menu should suffice during beta 1.0 tests and you can think about a solution.

Attached last polish translation from Transifex (does not yet include the last base.ts regeneration).
[sigil_pl_ts.zip](https://github.com/Sigil-Ebook/Sigil/files/3799978/sigil_pl_ts.zip)

**Comment by dougmassay** [comment]
We probably won't know for sure until the the latest base.ts gets processed on Transifex. I think they only poll for changes once a night.

**Comment by BeckyDTP** [comment]
I confirm – is OK now.
![sigil-1 0-translation-issue-pl-solved](https://user-images.githubusercontent.com/22416021/68076888-03719d80-fdbb-11e9-9dd5-429b41d2f292.png)

**Comment by dougmassay** [comment]
Great! Thanks for reporting back.
