### ISSUE TITLE
[Feature Request]Not only "Virtual" but "Real" folders and naming rule when create new files in epub

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#466]
_for Sigil 0.9.991_

Supporting complex directories in epub is really a good news.

But

1. Will Sigil support dislpay **real** structure of epub in BookBrowser(as another display mode)?
2. When "Add Blank HTML File" and "Add Copy", the new filename is "Section" plus an 4-digit number. But the number is uni-ordered.

e.g

  1. Create a new epub. Now there is "Section0001.html"
  2. "Add Copy". Now "Section0001.html" and "Section0002.html".
  3. Move "Section0001.html" to “OEBPS/Text/001”
  4. Click Section0001 and "Add Copy" and get "Section0003.html" in “OEBPS/Text/001”

So, will sigil **also** support generate new filename due to the existed file names in directory where it located in?
Also, will sigil  support custom template for filename generating(e.g A setting accepts a string like `Section[Inc]`)?

**Comment by kevinhendricks** [comment]
Go to Sigil Preferences->Appearance and enable show full book paths in BookBrowser.

Then BookBowser will always show you the exact path of the file within the ebook.  They are just grouped by file types.

There will be no "file explorer view", as that would make selecting multiple files of the same type for mass renaming, mass moving, or merging next to impossible.  

Yes, all file name creation defaults to be universally unique.  Simply right on the filename in BookBrowser and click to rename it to something else.  

You can always, just as before, select multiple files of the same type and then mass rename them in Sigil in one action and specify a template.  This has always existed in Sigil.  It is documented in the users manual.
