### ISSUE TITLE
Bug with the image preview

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#470]
Hello,

The image preview on when Ctrl clicking the `src` attribute of the `<img/>` doesn't work well.

![Annotation 2019-12-03 090758](https://user-images.githubusercontent.com/8157490/70025181-4c309800-15ad-11ea-8213-ab0377f1634f.jpg)

Sigil 0.9.18

Thanks.

**Comment by kevinhendricks** [comment]
Yes, I can recreate this bug as well.  This should now be fixed in master.
The fix should appear in our next release: Sigil 1.0
Thank you for your bug report!
