### ISSUE TITLE
No content/text in files

### ISSUE THREAD

**Issue by shnaps** [Sigil-Ebook/Sigil#471]
Hi. I'm getting strange behavior in Sigil. It misses the text content of every file in epub book. 

![2019-12-12-182355_1366x768_scrot](https://user-images.githubusercontent.com/18357973/70759757-055d4380-1d0d-11ea-8798-6a58ff6f82dd.png)
![2019-12-12-183633_1366x768_scrot](https://user-images.githubusercontent.com/18357973/70760231-a3054280-1d0e-11ea-8783-ddb15a34aa17.png)

It shows just empty lines with the number of lines as it is in html file. At the same time, I'm able to preview all the pages/book/TOC/etc without any problem and nano/vim/notepadqq/atom not missing the content of file. There are no errors in the debug when I start app with terminal. I'm also using kindle plugin to generate mobi files for my kindle and it works normally.
I'm using latest stable linux build(0.9.18).

**Comment by dougmassay** [comment]
Repo version of Sigil? Or did you build it yourself?
What's the Qt version reported in Sigil's About dialog?

**Comment by shnaps** [comment]
I'm using Void Linux and got Sigil from its repo. [Link](https://github.com/void-linux/void-packages/blob/master/srcpkgs/sigil/template).
So basically we can count that I've built it from sources. Qt version is 5.13.2.

**Comment by dougmassay** [comment]
I've no experience with Void, but I have no issues like that with Sigil 0.9.18 on Arch with Qt5.12.3. Does it happen with every epub you open, or just one in particular?

**Comment by dougmassay** [comment]
Sorry, I meant Qt 5.13.2 on Arch.

**Comment by shnaps** [comment]
It is an Arch-like distro. 
It does happen to every book that I open with Sigil. 
Also, seems when I open an empty project, I'm able to write text in xhtml/html file. Sigil will count symbols, the preview will try to render stuff that I typed but there still won't be any symbols displayed.

**Comment by shnaps** [comment]
Here I typed some stuff in an empty file and tried to find all letters in it. 
![2019-12-12-195007_1366x768_scrot](https://user-images.githubusercontent.com/18357973/70763158-bc12f100-1d18-11ea-96ee-72ff2b5a0d86.png)
Symbols are there but they not displayed for some reason.

**Comment by dougmassay** [comment]
Hmmm. Very odd. I may need to see if I can set up a Void virtual machine this weekend. Is that a Gnome desktop?

**Comment by kevinhendricks** [comment]
Font missing? Font related library missing?  Try going to Sigil Preferences and change font and font colours for CodeView to some fixed width font that actually exists on your system.

**Comment by kevinhendricks** [comment]
FWIW Preview is QtWebEngine based and it its own font engine libs.  Codeview needs a fixed width font like Courier, etc.

**Comment by shnaps** [comment]
> Hmmm. Very odd. I may need to see if I can set up a Void virtual machine this weekend. Is that a Gnome desktop?

Xmonad DE.

> Font missing? Font related library missing? Try going to Sigil Preferences and change font and font colours for CodeView to some fixed width font that actually exists on your system.

Hm, this may be an issue. 

Just checked it. Changing font helped. By default Sigil used some weird "A-something" font that I never heard about and never had in my system. Changing it for Dejavu(firefox default font) helped.

**Comment by shnaps** [comment]
Confirmed, changing font to one that exists in system fixed problem.

**Comment by kevinhendricks** [comment]
For the record, Sigil does not set that font, it just asks the Qt font system to provide it with a list of suitable fixed width fonts on the system that Qt knows about.  Perhaps the fontdatabase that Qt uses on your system needs to be updated.  Or just adding more fonts in general may help.

**Comment by dougmassay** [comment]
Qt typically relies upon FontConfig on Linux. Unfortunately, it seems to require some sort of perfect, and often unattainable, harmonious balance with XDG to work well. It refuses to select reasonable fonts (by default) on my Arch system as well. On other people's systems, it work with no issue.

**Comment by shnaps** [comment]
> For the record, Sigil does not set that font, it just asks the Qt font system to provide it with a list of suitable fixed width fonts on the system that Qt knows about. Perhaps the fontdatabase that Qt uses on your system needs to be updated. Or just adding more fonts in general may help.

Guess that for some reason Qt haven't choosed font that been installed in the system(I have awesome, hack, powerline, iosevka, etc). And all of them been cached.



> Qt typically relies upon FontConfig on Linux. Unfortunately, it seems to require some sort of perfect, and often unattainable, harmonious balance with XDG to work well. It refuses to select reasonable fonts (by default) on my Arch system as well. On other people's systems, it work with no issue.

I think this is the same for me too. Well, it is good that I know about it now.
