### ISSUE TITLE
release 1.0.0 doesn't matches homebrew rule causing upgrade fail 

### ISSUE THREAD

**Issue by gonejack** [Sigil-Ebook/Sigil#476]
```rb
cask 'sigil' do
  version '1.0.0'
  sha256 '1db9f16460b4d2ff6a83556c58d380ba7bd2a1b741ff0c0c2c7fca3ed6b60321'

  # github.com/Sigil-Ebook/Sigil was verified as official when first introduced to the cask
  url "https://github.com/Sigil-Ebook/Sigil/releases/download/#{version}/Sigil.app-#{version}-Mac.txz"
  appcast 'https://github.com/Sigil-Ebook/Sigil/releases.atom'
  name 'Sigil'
  homepage 'https://sigil-ebook.com/'

  depends_on macos: '>= :sierra'

  app 'Sigil.app'

  zap trash: [
               '~/Library/Application Support/sigil-ebook',
               '~/Library/Preferences/com.sigil-ebook.Sigil.app.plist',
               '~/Library/Saved Application State/com.sigil-ebook.Sigil.app.savedState',
             ]
end
```

![image](https://user-images.githubusercontent.com/2720676/71331606-f2990900-256d-11ea-9576-c87a86e2bfe0.png)

```
~> brew cask install sigil
==> Downloading https://github.com/Sigil-Ebook/Sigil/releases/download/1.0.0/Sigil.app-1.0.0-Mac.txz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'sigil' with message: Download failed: https://github.com/Sigil-Ebook/Sigil/releases/download/1.0.0/Sigil.app-1.0.0-Mac.txz
```

**Comment by kevinhendricks** [comment]
Yes, there was a late macOS specific bug fix added.  To distinguish it from the earlier version that had the bug, the actual release package for macOS is called:  
Sigil.app-1.0.0a-Mac.txz

You do not need to use Homebrew to install this package.  It is prebuilt for macOS.  Simply download that file and uncompress it to get a perfectly relocatable Sigil.app package.  Place it anywhere you want.

Just go to our releases page here on github and download it yourself.

Please report this issue to Homebrew, it is not a Sigil bug.

**Comment by gonejack** [comment]
I know how to download & install the app,  could you please don't break the rule since there is no `Sigil.app-1.0.0-Mac.txz` in releases hence no need to put an `a` for distinguishing version don't exist.

**Comment by dougmassay** [comment]
We don't support or worry about installing Sigil via homebrew. It is homebrew's job to work with our builds/releases, not vice-versa.

**Comment by eli-schwartz** [comment]
@gonejack Hmm, would you prefer they silently replace the uploaded installer with a different checksum?

**Comment by kevinhendricks** [comment]
There was a 1.0.0 version briefly.  It had a macOS specific bug. It was replaced by a 1.0.0a build.  There is no "broken rule".
