### ISSUE TITLE
No "virtual" folders contrary to doc

### ISSUE THREAD

**Issue by Mick2nd** [Sigil-Ebook/Sigil#478]
I use Sigil 1.0.0. Cannot recognize any virtual folders. In EPUB (when I open as ZIP) I have Text, Image etc. folders as before. Also the Image src attribute in HTM files is renamed to src="../Image/sample.gif". So, what's virtual here?

**Comment by kevinhendricks** [comment]
This is not a place to ask questions.  This is for issuing actual bug reports.  Please use our clearly marked user support forums on Mobileread.

That question has already been asked and a answered there.

**Comment by dougmassay** [comment]
Please read the release notes carefully. If you open epubs that were already saved with orevious versions of Sigil, you're not likely to notice any difference whatsoever. The physical structure of the epubs already matches the virtual structure of Book Browser. That does not change the fact that Book Browser's "folders" are now virtual filetype groups. 

You may encounter, however, epubs that have internal structures that DON'T match Sigil's virtual groupings.

Also keep in mind that this issue database is not a help system. Please use the Sigil forums at MobileRead for user support questions. Closing this as it is not a bug/issue.
