### ISSUE TITLE
Insert Special Character window - add scrollbar

### ISSUE THREAD

**Issue by kpk-in** [Sigil-Ebook/Sigil#480]
Positioning the 'Insert Special Character' window conveniently when editing books with lot of accented-Latin characters is difficult. It would be good to have at least one (or all!) of the following features for the window:

- free flow of characters when resizing the window (now only space between characters increases without flowing to next/ previous line

or
- vertical / horizontal scroll bars, so that we can scroll to the required line in a small window, without having to resize/reposition the window as required

or

- customising the window by repositioning the required characters at the first line, etc.

![image](https://user-images.githubusercontent.com/5056431/71415061-06349480-2680-11ea-974d-7cccd6880890.png)

**Comment by kevinhendricks** [comment]
Or Just manually grow the Window to be the height you need.  Even I can do that of my laptop screen.  

If you have a lot of special characters you could use named or numeric entities, or the proper key sequence to generate that key directly from the keyboard, or clips to handle that.  Constantly trying to use Insert Special Character is not the right approach in that situation.

**Comment by kpk-in** [comment]
Thank you. Yes definitely using clips and using keyboard shortcuts are an option. Growing / moving the window up is also a given.  But then it hides a lot of the book text. Hence this enhancement request.
It is _not_ an urgent or "must have" request. Just a suggestion... Thanks again for the wonderful software.

**Comment by kevinhendricks** [comment]
After considering it some more I will at least add a vertical scrollbars to this Dialog for the next release and possibly both.

**Comment by kpk-in** [comment]
Yes a vertical scrollbar would be fine. Great!

**Comment by kevinhendricks** [comment]
Let's leave this open until the actual change goes into master, just so I do not forget.

**Comment by kevinhendricks** [comment]
Okay, got a free moment and added both horizontal and vertical scrollbars (ie. a scroll area) to the SelectCharacter dialog.  I have pushed this to master.  This new feature will appear in the next release of Sigil.
