### ISSUE TITLE
Linking to current file

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#487]
Linking to the current file (without id) causes a problem in EpubCheck.

Step by step:
1. Create a new file.
2. Write `<p>Kevin</p>`
3. Highlight this name and click on "Insert Link" icon.
4. Select current file (Section001.xhtml)
5. In Target field is "./" – in this case (link=current file) it should just be the file name.
6. I get the result:
`<p><a href="./">Kevin</a></p>`
Expected result:
`<p><a href="Section001.xhtml">Kevin</a></p>`

**Comment by kevinhendricks** [comment]
Internal links should technically never include the filename in the url.  If you want the link to top of file it should end up being just "#".  Otherwise an internal link becomes external and must go through security checks again.

Does the link not work?

**Comment by BeckyDTP** [comment]
Sure. "#" or filename should be OK – then lint to top of file works.

Currently, the link "./" does not work.

**Comment by kevinhendricks** [comment]
This was just now fixed in master.  Thank you for your bug report!
