### ISSUE TITLE
Error in preview window after css injection

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#489]
Due to css injection, an incorrect line number is given in the preview window when an error message occurs.

This is not trivial, because conditions must take into account::

- additional (if dark) injection = 5 lines
- additional (if dark + win) `win_dark_scrollbar.css` = 1 line
- additional (if exist) `custom_preview_style.css` = 1 line

![sigil-preview-injection-error](https://user-images.githubusercontent.com/22416021/72212691-e8b95480-34e0-11ea-9426-f4f761af9fbc.png)

![sigil-preview-injection-error-inspect](https://user-images.githubusercontent.com/22416021/72212692-eeaf3580-34e0-11ea-873b-e998fee05fb6.png)

I once noticed that the error was one line (because I use `custom_preview_style.css`) and I did not pay much attention to it, but with 7 lines of difference – it became bothersome.

**Comment by dougmassay** [comment]
This had present even before the darkmode stuff, right (even if it was only one line)?

Yuck, yuck, yuck. Thanks for tracking it down, though. :)

**Comment by kevinhendricks** [comment]
Yes, we are going to have to figure something out.  Probably have to use css variables in an inline style to set color values right on the body tag  and merge all of the rest of the dark and user css into one linked in stylesheet.  As far as I can tell we can not modify the error results screen on the fly.

**Comment by dougmassay** [comment]
With our current strategy, the best we could probably hope for is to cram all of our injections into one line.

**Comment by kevinhendricks** [comment]
Yes, agreed.  Our smallest footprint would be one line.  I think we could prepend it to the ending head tag on its same line.  Its too bad we can't enforce a padding or comment line being normally present that we could simply replace

**Comment by kevinhendricks** [comment]
So we can use javascript to set the document foreground color:

document.body.style.color=a;

and we already set the background color.

So I will add a javascript routine to set the foreground color on the body tag which can be run on preview immediately after load completes (perhaps we can limit this to white or black?) 

That will just mean we merge the remaining darkstyle css into the custom-user css and inject it without a newline in front of </head> tag.

Thoughts on that approach?

**Comment by kevinhendricks** [comment]
If we limit foreground color to white or black it may be possible to run javascript that gets the current background color and properly chooses the foreground color automatically?

**Comment by dougmassay** [comment]
Sounds doable--I'm game. The worst that can happen is it blows up (and then we'll fix it)! :)

**Comment by kevinhendricks** [comment]
I found a few routines to take the background color and choose between white and black for foreground.  It just depends on how color is returned by javascript.

I will take a shot at this now.

**Comment by kevinhendricks** [comment]
And wasted a whole day trying to do it, as it turns out the background color is transparent so it shows iur set background which I can not detect.

So I am going to set both bg and fg using javascript.

**Comment by dougmassay** [comment]
Ouch! Hope it goes smoother from here.

**Comment by kevinhendricks** [comment]
Okay, this seems to now work with no line offset unless you inject your own user css.
It uses javascript to dynamically set a style on the body tag using the name of Base and Text colors.

Then via Utility::AddDarkStyleSheet() it only injects a link to the dark scrollbar stylesheet (which now has link colors in it).  It injects onto the same line as </head> so it will not cause a line offset.

The Utility::AddDarkCSS routine is still needed for ImageTab, AVTab, ViewImage, and SelectFiles.

So I am closing this as fixed since it will report the correct line number of an error even in dark mode and will be only offset by 1 line if using a user css stylesheet.

BTW, if mathml is injected, Preview's error line numbers will be meaningless anyway so we are simply not going to worry about that as mathjax makes wholesale changes.

Closing this since this now works.

Thanks for your bug report!

**Comment by dougmassay** [comment]
Can confirm on Windows. All looks good!

My Linux dev machine is offline at the moment (I'm using the hardware to boot a physical Windows ssd for testing purposes), but I can't imagine there being any problems RE Linux.

**Comment by BeckyDTP** [comment]
Remove `\n` in line https://github.com/Sigil-Ebook/Sigil/blob/master/src/MainUI/PreviewWindow.cpp#L243
and then even for the `custom_preview_style.css` file, the line number on the error will be OK.

**Comment by kevinhendricks** [comment]
Is that really needed?  If a user injects there own css script they should expect the line number to be off by one given how Sigil handled this in the past.  I am okay with leaving it as is given that is how it was done, and line numbers will be completely meaningless under situations with mathjax and mathml use.

If the user gets confused and needs a valid line number, then they can run a fast well-formed check.

**Comment by BeckyDTP** [comment]
Sure. It was just a suggestion (purely aesthetic).
