### ISSUE TITLE
Delete unused media not working correctly

### ISSUE THREAD

**Issue by wocmultimedia** [Sigil-Ebook/Sigil#490]
Hi,
I'd like to point out at an issue occurred to me with the new 1.00 version.
I exported from LibreOffice as epub 3.0 then open as usual with sigil to clean the messed code.
Well, after cleaning and dividing some sections in more parts I made my final check.
I also created the NCX and updated the manifest properties then I run the delete unused media tools and it shows a list of about 40 pictures/images to be deleted. I went to Images folder and they are not duplicated into it. The images are all shown in the manifest. I made a copy of the book and tried to delete it to see what happen. Once deleted the images were not existing in the related sections. So I suppose there's something wrong in the Sigil parsing. 
If I misused the program let me know so I learn it.

2-There's a specific way to export from LibreOffice or it's correct to export as epub3.0 then I mend it?
Thanks

**Comment by wocmultimedia** [comment]
Hi the **problem actually exists** but it can be solved clicking on the Tools>Restructure Epub to Sigil Norm then updating the manifest and clicking on Tools > Delete unused media files it shows correctly the unused media.
Please, let me know what's wrong or if you have to fix something to avoid this issue.
Thanks
Angelo

**Comment by dougmassay** [comment]
Sigil wouldn't be able to Restructure the epub successfully if the everything wasn't already properly manifested, so it very well could be Sigil bug. But I'd be curious to see the results of EpubCheck before opening with Sigil, after opening with Sigil and after Restructuring to Sigil Norm. In the meantime, I'd be very careful that nothing is being silently removed from the epub by the workaround.

**Comment by dougmassay** [comment]
It doesn't seem to be a general issue of media files being located in non-traditional locations. I can open an epub (2 or 3) with images and non-standard locations without them mistakenly showing up as "unused" before restructuring. Any way you could provide a small sample epub that exhibits the issue?

**Comment by kevinhendricks** [comment]
I can not recreate this either.  So it is perhaps something about the links being generated by libreoffice for media when you export to epub that is confusing Sigil or Sigil simply has a bug with certain links and can not grok them, that really needs to get fixed.

We really need to see an sample epub that shows this problem so we can track down what is going on.  

If you only want to share that epub privately, you can PM "KevinH" or "DiapDealer" with a link to it via Sigil's user's forum on www.mobileread.com.

**Comment by dougmassay** [comment]
Also, what version of LibreOffice you're using (and if it was recently updated) would be helpful.

**Comment by dougmassay** [comment]
I just tried exporting a document with an image (default settings) from LibreOffice Writer 6.2.8 and it all worked as it should. It created a valid epub3 with the image properly manifested that opened with Sigil just fine and didn't need to be restructured.

But more importantly, you seem to EXPECT there will be a certain amount of unused media to delete after exporting them to epub3. I guess I'm confused as to how a LibreOffice document would have unused media files in the first place. Shouldn't _all_ image files exported have links to them in the text somewhere? Otherwise why would LO have exported them to the epub in the first place?

**Comment by kevinhendricks** [comment]
So we need more information from you or better yet a sample epub so we have some chance of diagnosing if there is a issue.  As it stands neither of us can recreate the problem you reported.

**Comment by kevinhendricks** [comment]
Closing this as can not be recreated.
