### ISSUE TITLE
Double Rename in Keyboard Shortcuts

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#491]
"Rename" appears twice in the list of keyboard shortcuts. Of course, one of them is real "Rename" and the other is "Rename RegEx", but the user does not see the difference because the displayed name is identical.

**Comment by BeckyDTP** [comment]
This is not a significant problem, so you don't have to stop preparing for release.

**Comment by kevinhendricks** [comment]
Now fixed in master.  We are not going to immediately release anything yet, as we want to give the translators a chance to translate all of the new strings related to Dark mode and preferences changes.
