### ISSUE TITLE
Another small (and rare) problem with the "other" semantics

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#496]
I found one more place where Sigil doesn't recognize the "other" semantics.
1. Create epub3
2. Set semantics to "Footnotes" at any xhtml file
3. Run "Generate NCX/Guide for epub2 e-readers"
4. "other.footnotes" does not appear in the Guide

**Comment by kevinhendricks** [comment]
The funny thing is the ncxgenerator.py code in Sigil/src/Resource_Files/python3lib/ clearly shows that mapping.

I will have to look into it further.

**Comment by kevinhendricks** [comment]
Fix should now be in Misc/Landmarks.cpp
