### ISSUE TITLE
Resource organization

### ISSUE THREAD

**Issue by momingxu** [Sigil-Ebook/Sigil#497]
> Upon initial load, the epub structure that exists will be loaded and kept in its “as-is” state, moving and renaming nothing
> The BookBrowser will still show the Text, Images, Styles, Fonts, Audio, Video, and Misc “folders” but these are now “virtual folders” that simply organize the existing resources by type but do not restrict their actual location within the epub.

It is recommended to restore the standardized organization of resource folders or provide control options.

**Comment by dougmassay** [comment]
We have provided all the control options a user needs to manipulate the internal structure of an epub any way they want to (including restructuring to Sigil's historical standard).
