### ISSUE TITLE
Code View: can't change background color 

### ISSUE THREAD

**Issue by lodgerz** [Sigil-Ebook/Sigil#498]
hi,
in last version of Sigl isn't possible to change background color of code view (i used "black"), why? it's for QT5?

i use ArchLinux64 without DE (only openbox):
`$ uname -r
5.5.4-arch1-1
`
`$ pacman -Q|grep -i sigil
sigil 1.1.0-1
`

**Comment by dougmassay** [comment]
We made no changes that would (should) prevent anyone from using qss to change Code View's background in 1.1.0. 

Are you certain it's not your desktop theme that's disabling stylesheets?

**Comment by kevinhendricks** [comment]
I think she/he is referring to the CodeView Sigil preferences setting for foreground and background colour which were removed since Sigil now follows the desktop theme.   I think she/he is trying to set a black background not at the desktop level but only for Sigil.

And as you said qss is the way to go here.

**Comment by dougmassay** [comment]
Oh, you're talking about the forerground/background color preferences. Yes. We took those preferences away (along with text highlight colors) to make sure things would work out of the box for all theming engines.

Use a custom qss file if the default background doesn't work for you. Or if black is your color of choice, try Sigil's inherent darkmode by setting the FORCE_SIGIL_DARKMODE_PALETTE environment variable before launching Sigil.

**Comment by dougmassay** [comment]
If you're not used a Sigil custom stylesheet (or qt stylesheets in general), just create a file named "qt_styles.css" in your Sigil preferences directory and add the following to it:

QPlainTextEdit {
  background-color: black;
}

[qt_styles.zip](https://github.com/Sigil-Ebook/Sigil/files/4246639/qt_styles.zip)

Should you want to experiment with Sigil's new darkmode (outside of any DE platform themes), use the following at a command prompt:

`FORCE_SIGIL_DARKMODE_PALETTE=1 sigil`

If you like it and want to make it permanent, export the environment variable in your .profile file (or create a sigil entry for your shell in /etc/profile.d).

I'm going to close his issue as things are working as intended.

**Comment by lodgerz** [comment]
thx for reply.
what do you mean for "qss"? i have tried to set "FORCE_SIGIL_DARKMODE_PALETTE" but sigil is still white.

**Comment by dougmassay** [comment]
See above. We were posting at the same time. :)

**Comment by lodgerz** [comment]
thank you dougmassay! i have SOLVED following your instruction.

**Comment by lodgerz** [comment]
ops maybe i haven't solved: using your "qt_styles.qss" the background is black but also normal text in black then it is unusable O_O

i have tried to add "text-color: white" but text is still black.

`QPlainTextEdit {
  background-color: black;
  text-color: white
}`

**Comment by dougmassay** [comment]
You should really try darkmode first. Setting that environment variable to one has worked on every flavor of Linux I've ever tried it on. If you get it working, though, you'll want to move/rename the qt_stles.qss file (as it will always take precedence).

But if you choose to continue with the custom stylesheet method, what you're looking for is:

QPlainTextEdit { background-color: black; color: white }

**Comment by lodgerz** [comment]
ok, with "color: white" it's all right! :-)

dark mode works and is good, but the colors of code view are totally different than the colors i had set years ago. I should edit them all again X-|

**Comment by dougmassay** [comment]
> colors of code view are totally different than the colors i had set years ago. I should edit them all again X-|

Your choice, of course. But those colors are easily changed in the usual Code View preference settings (though the default colors have been chosen with dark mode in mind). Keep in mind that there's two sets of colors for Code View: dark-mode and light-mode. They are set independently of each other (when in a dark theme, and when in a light theme).
