### ISSUE TITLE
Deletion of html resource does not update m_TOCModel automatically

### ISSUE THREAD

**Issue by kevinhendricks** [Sigil-Ebook/Sigil#500]
This is a note to myself to look into this...  

If an html resource is deleted using BookBrowser, should we be automatically removing any targets that reference that deleted resource in the NCX and/or Nav?  

If yes, we do not do this now or we somehow broke it at some point.

This would involve adding a call to MainUI/Table_of_Contents.cpp/.h  to remove and free the m_TOCModel entries whose target currently has the bookpath of the html resource just deleted.

Given the hierarchical nature of the TOC, we would need to either 
1. delete all of its children
or
2. add its children (assuming they point to some other target) to the parent of the node we deleted.

I see no code in Sigil currently that will handle this case, other than running the EditTOC dialog and having the user manually delete that entry, so I do not think this ever existed in Sigil.

Not sure why though?

**Comment by dougmassay** [comment]
Don't quote me or anything, but I think the rationale for NOT doing it was the same as the rationale for not removing img/a tags in xhtml that reference image/html resources that were deleted: sometimes people want to delete a resource and add a new version (with the same filename) without having to recreate all the links to it.

I'm fairly indifferent about resource deletions being automatically removed from ncx/nav entries myself. I can live with it either way. ;)

**Comment by kevinhendricks** [comment]
That makes sense!  I only noticed it as I was demoing your diff code and noticed when I deleted a chapter that the opf was changed but no diff of the ncx was present.

I may still add some code to handle this, so I would like to keep it open as it is a very low priority item.

**Comment by kevinhendricks** [comment]
The more I think about this, the less inclined I am to change anything.
So I am going to close this.
