### ISSUE TITLE
There's a typo in TextView.cpp

### ISSUE THREAD

**Issue by PhotonQyv** [Sigil-Ebook/Sigil#504]
You have tried to include &lt;QTextBlocK&gt; rather than &lt;QTextBlock&gt; in  Sigil/src/ViewEditors/TextView.cpp file.

Consequently the build fails at that point since QTextBlocK header doesn't exist.

**Comment by kevinhendricks** [comment]
Thanks for catching that.  I will fix it shortly.

**Comment by PhotonQyv** [comment]
@kevinhendricks No worries

**Comment by kevinhendricks** [comment]
The ci are only done on Windows and on macOS and both are case insensitive so that  include actually worked (and passed).  We should think about adding a Arch Linux style ci platform.
Now fixed in master.
Thank you!
