### ISSUE TITLE
PYTHON_LIBRARY not found

### ISSUE THREAD

**Issue by jcotman** [Sigil-Ebook/Sigil#505]
Following the Linux build steps, I run `~/sigil-build$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../sigil-src` and this is the end output:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "sigil" in directory /home/user/sigil-src/src

-- Configuring incomplete, errors occurred!
See also "/home/user/sigil-build/CMakeFiles/CMakeOutput.log".
See also "/home/user/sigil-build/CMakeFiles/CMakeError.log".
```

This is probably because of this earlier error

```
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "3.4")
```
I manually set the env variables discussed after `If cmake couldn't automatically ` in the LInux build instructions.  Maybe I need to set these other variables also?

**Comment by dougmassay** [comment]
If libpython is installed, it should typically be found automatically. In the rare case that it's not, the Sigil build instructions explain the various python-related directives that might need to be added to the initial cmake configuration command to explicitly tell cmake where the python pieces can be found.

It sounds like you have two things possibly wrong: 1) the python-dev package for your distro (or its equivalent) may not be installed. And 2) it's not environment variables that are to be set if cmake can't find the python pieces automatically, its cmake directives. They're added to the cmake configure command and not the environment.

**Comment by jcotman** [comment]
@dougmassay You are right.  I did not see that python3-dev needed to be there.  Build is successful.
