### ISSUE TITLE
File path disappears after certain operation

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#507]
1. Check "BookBrowser should show full paths"
2. Create an epub
3. Right click the only file in Book Browser, select "Rename"
4. Click any where EXCEPT the input control for filename.

The path disappears, left raw file name.

Sigil 1.1.0

**Comment by dougmassay** [comment]
Yes. It's been reported in the user forums at MobileRead. It's cosmetic only, and a fix would not be at all trivial. Best to get in the habit of using ESC to cancel a rename instead of clicking elsewhere with the mouse.

**Comment by firstrose** [comment]
Thanks for your reply.

**Comment by dougmassay** [comment]
I believe I've corrected this behavior with 793c150
