### ISSUE TITLE
Merge feature bug?

### ISSUE THREAD

**Issue by dougmassay** [Sigil-Ebook/Sigil#508]
The Merge feature still proceeds to make changes even when only one file is highlighted in Book View. It merges the selected file with the one immediately preceding it.

I'm creating this issue for my own reference. I'm not sure if this is intentional or not, but I would think that "Merge" should fail to do anything when only one file is highlighted. In fact, it seems to me that the Merge context menu item should be disabled except when multiple contiguous files are highlighted.

**Comment by BeckyDTP** [comment]
From _Sigil User Guide_:

> If you select a single HTML file, then the file will be merged into the previous HTML file in the list.

> If you select multiple HTML files, then all files will be merged into the first HTML file you selected.

**Comment by dougmassay** [comment]
Well there you go. Thanks! It still seems a little counter-intuitive to me, but as long as it's documented, I guess. :)

**Comment by kevinhendricks** [comment]
So should we close this?

**Comment by dougmassay** [comment]
I think so, yes.
