### ISSUE TITLE
[FR]Rule for file name when add blank file/copy

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#509]
When use "Add blank HTML file" or "Add Copy", sigil will generate a file names prefix plus a number. I think the context should be take in consideration as Sigil allows folders in epub.

e.g.

1. Create an epub. There is a file Section0001.xhtml in OEBPS/Text
2. Add two more blank files.
3. Move Section0003.xhtml to "OEBPS/Text/001"
4. Rename OEBPS/Text/001/Section0003.xhtml to OEBPS/Text/001/Section0001.xhtml
5. Right click on OEBPS/Text/001/Section0001.xhtml and Add Copy, then get OEBPS/Text/001/Section0003.xhtml

Looks that Sigil sets the order of the new file according to the last file in the DEFAULT folder.
Could Sigil set the order according to the folder of the file clicked?(for the example above, the new file should be section0002, not 0003)

**Comment by kevinhendricks** [comment]
Given you can rename it to whatever you like either before or after moving it, is this really an issue?  As soon as you have more files in a new folder the default folder will adapt.

**Comment by firstrose** [comment]
> 
> 
> Given you can rename it to whatever you like either before or after moving it, is this really an issue? As soon as you have more files in a new folder the default folder will adapt.

Looks reasonably. But what should I do if I need ten folders, each with ten files in?
e.g 01/01.htm, 01/02.htm......01/10.htm, 02/01.htm......02/10.htm.......10/10.htm

Rename? Yes, plenty of renaming actions required.

Is there another choice?

**Comment by kevinhendricks** [comment]
Some thoughts ... 
- do not use digits to start file names or directory names.
- do not use .htm as an extension if epub3 is a target, use .xhtml
- Create a bunch of blank .xhtml in one folder, then use normal rename and Regex ReRenamer to bulk rename to all use a unique prefix and renumber.
- For a new directory choose a new unique prefix.

**Comment by firstrose** [comment]
> 
> - do not use digits to start file names or directory names. 
> - do not use .htm as an extension if epub3 is a target, use .xhtml 

Thanks for advice. It's just a example for less key-in.

> - Create a bunch of blank .xhtml in one folder, then use normal rename and Regex ReRenamer to bulk rename to all use a unique prefix and renumber. 

Do you mean create a bunch in Sigil's folder? How can I COPY them to another folder? Only "MOVE" available.

Thanks

**Comment by BeckyDTP** [comment]
If you already have to do it this way.

1. Create all the empty files you will need.
2. Select files, which you need to first part.
3. [This step is unnecessary, but if you have to ...]
Move the selected files to folder `OEBPS/Text/part01` (or something else)
4. Rename the selected files according to the pattern `p01ch01.xhtml` (_part 01, chapter 01_)
5. Now select the next files for the next part.
6. Rename the selected files according to the pattern `p02ch01.xhtml` (_part 02, chapter 01_)

etc.

File names will uniquely indicate their place in the document structure.

**Comment by firstrose** [comment]
> 
> 
> If you already have to do it this way.
> 
>     1. Create all the empty files you will need.
> 
>     2. Select files, which you need to first part.
> 
>     3. [This step is unnecessary, but if you have to ...]
>        Move the selected files to folder `OEBPS/Text/part01` (or something else)
> 
>     4. Rename the selected files according to the pattern `p01ch01.xhtml` (_part 01, chapter 01_)
> 
>     5. Now select the next files for the next part.
> 
>     6. Rename the selected files according to the pattern `p02ch01.xhtml` (_part 02, chapter 01_)
> 
> 
> etc.
> 
> File names will uniquely indicate their place in the document structure.

Excuse me,sir. But my trouble is that, I don't want rename many files ONE BY ONE. I need to know how to rename them as simple as possible.

In your 1st step, I create 100 files naming Section0001.xhtml to Section0100.xhtml

For example, the first part contains 20 files. Moving the top 20 files to OEBPS/Text/part01 is simple, as I don't need to rename them.

Now the 2nd part shoule have 30 files. I want they have names from p02ch01.xhtml to p02ch30.xhtml in OEBPS/Text/part02

Now, the point is, what is the FASTEST method of renaming Section0021.xhtml......Section0050.xhtml to p02ch01.xhtml....p02ch30.xhtml?

Of course, you can click the first file and rename it, then click the next and rename, then the next......

But it's slow and painful to rename lots of files one by one.

Can you tell me HOW TO BATCH RENAME FILES IN SIGIL?

@BeckyDTP

**Comment by BeckyDTP** [comment]
Batch renaming EXIST in Sigil.
Please, do _exactly_ what I described earlier.

1. Select  `Section0021.xhtml......Section0050.xhtml`,
2. Rename
3. Write FIRST name `p02ch01.xhtml`
4. Sigil will do the rest.

It's simple and fast, which is exactly how you need it.

**Comment by firstrose** [comment]
Thank you very much.
