### ISSUE TITLE
changed gpg key?

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/Sigil#515]
1.2.0 seems to be signed by `6EC59D41083E5F0F7E61424C56CD953D30E1BBCD` instead of the usual `B5A56206AB0FBC1A24EFAB8AA166D29A8FCDAC63`.

did you change gpg key?

**Comment by mapreri** [comment]
sorry, that's me missing stuff in some place, nvm...

**Comment by kevinhendricks** [comment]
A 1.2.1 tag specifically with a fix for Linux with Python versions less than 3.8 is coming soon so you might want to wait.

**Comment by dougmassay** [comment]
Thanks for letting me know @mapreri . I panicked there for minute. :)

As Kevin mentioned, the new dulwich python module requirement may cause issues on Linux systems with Python less than 3.8. I'll be creating a signed 1.2.1 tag to accommodate that fairly soon.

**Comment by mapreri** [comment]
alright.  That said after fixing my keyring, I couldn't verify the tarball 🤔

```
mattia@warren /tmp/tmp/gpg % sha256sum 1.2.0.tar.gz Sigil-1.2.0.tar.gz.sig
30925bc801ee091e8be8625f67a84402d6d60247f608857db8476fc326733596  1.2.0.tar.gz
915c0c38268f5c9a685dd950099265bc777466ed1763260b7ed7f56138e1b3d5  Sigil-1.2.0.tar.gz.sig
mattia@warren /tmp/tmp/gpg % GNUPGHOME=$PWD gpg --verify Sigil-1.2.0.tar.gz.sig 1.2.0.tar.gz
gpg: Signature made Sat 28 Mar 2020 09:19:09 PM CET
gpg:                using RSA key 6EC59D41083E5F0F7E61424C56CD953D30E1BBCD
gpg: BAD signature from "Doug Massay <douglaslmassay@gmail.com>" [unknown]
1 mattia@warren /tmp/tmp/gpg %                                                                                                                                                     :(
```

I downloaded the usual https://github.com/Sigil-Ebook/Sigil/archive/1.2.0.tar.gz here…

**Comment by mapreri** [comment]
(for clarity, I was startled initially because somehow my keyring didn't have 6EC59D41083E5F0F7E61424C56CD953D30E1BBCD which is simply the subkey of B5A56206AB0FBC1A24EFAB8AA166D29A8FCDAC63 - that's all it happened at the start…)

**Comment by dougmassay** [comment]
Strange. It's working for me. I download fresh copies of the source archive and sig files from the release and it checks out fine for me. The only difference I see is that your source tarball downloads as 1.2.0.tar.gz and mine downloads as Sigil-1.2.0.tar.gz

`gpg --verify Sigil-1.2.0.tar.gz.sig
gpg: assuming signed data in 'Sigil-1.2.0.tar.gz'
gpg: Signature made Sat 28 Mar 2020 04:19:09 PM EDT
gpg:                using RSA key 6EC59D41083E5F0F7E61424C56CD953D30E1BBCD
gpg: Good signature from "Doug Massay <douglaslmassay@gmail.com>" [unknown]
`

**Comment by dougmassay** [comment]
I get the same (good result) whether downloading via your provided link (https://github.com/Sigil-Ebook/Sigil/archive/1.2.0.tar.gz) or by downloading directly from the Github release.

**Comment by dougmassay** [comment]
Were you ever able to verify the tarball?

**Comment by mapreri** [comment]
I was.  I think it was a very bad day for me…  I just had a truncated tarball

both 1.2.0 and 1.2.1 verify just fine :)

Sorry again for the needless noise.

**Comment by dougmassay** [comment]
No trouble at all.

I'm not particularly adept at navigating the gpg/pgp/keyserver waters in the first place. So I've changed nothing in that regard since first implementing it. I will, however, be making my first foray into renewing my public key next spring, and I'm not afraid to admit that the process (including deleting and adding the renewed key on Github) frightens the bajeebus out of me! I've started collecting documentation and directions/suggestions already. ;)

Just glad it all worked out in the end.

**Comment by eli-schwartz** [comment]
FWIW, the copy of the key on github isn't very important -- it just makes the Github UI show details on a key, but no one who is verifying the codesign validity is blindly trusting github anyway. ;)

Renewing a key just requires using the gpg tools to edit the key's expiry date, then uploading the key to various servers. Jumping through special hoops to update github as well, is merely an added bonus.

Feel free to reach out to me via github/mobileread/email/IRC/whatever if you need any help whatsoever, I'll be more than happy to walk you through it. :)
