### ISSUE TITLE
Codespell report for "Sigil" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [Sigil-Ebook/Sigil#516]
The FOSS server [fossies.org](https://fossies.org) - also supporting "Sigil" - offers a feature "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the new Sigil release 1.2.0:

&nbsp;&nbsp;https://fossies.org/linux/www/Sigil-1.2.0.tar.gz/codespell.html
 
Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also two supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/www/Sigil-1.2.0.tar.gz/codespell_conf.html) and all obvious [False Positives](https://fossies.org/linux/www/Sigil-1.2.0.tar.gz/codespell_fps.html).

If appropriate, additional reports for the current release or also master versions could be willingly created (but the latter in a special "test" folder) .

**Comment by dougmassay** [comment]
What's the Sigil issue you're reporting?

**Comment by kevinhendricks** [comment]
To prevent meaningless changes in the tree, we are NOT fixing spelling errors in text and comments unless actually seen by the end-user.

What exactly does the "T" type column in your report link actually mean?  What for example is a "c" or "C" in that field meant to indicate.

Is there any setting with your tool to supress any spelling checks in comments (C++, C, Python, bash, etc).  If so the output of  such a report may be of some use.

**Comment by BeckyDTP** [comment]
Abbreviations for the supported context types:
t = text file line
_ = text file line (uncorrectable?)
c = commented line
C = Comment block
F = Formatted text file line
D = Debug string
E = Error string
P = Print string
Q = Quoted string
? = Unassigned context (maybe source code)

**Comment by kevinhendricks** [comment]
@BeckyDTP, Where did you find that on his link?

**Comment by BeckyDTP** [comment]
Hint (hover mouse) on letter "T".

**Comment by kevinhendricks** [comment]
I could not find it.  If we filter out all .md files, all .txt files, all .html files, all _, all base.ts files, all c and all C, and all of the QDebug stuff, out we should be left with the actual useful pieces.

So far that looks like a "metdata" in a MetaEditor.ui file, and a misspelled file name parameter in MainWindow.h.

**Comment by kevinhendricks** [comment]
And some python debug output print statements.

I will fix those and close this.  

As for the idea of assigning "grades" based on these reports, that is ludicrous especially if a report is not requested.  

This is the second bug report on this subject and hopefully the last.  

Typos in comments made by devs is a time honoured tradition, and one I have followed since my first programming course in 1978!  ;)

**Comment by dougmassay** [comment]
Hell, why would anyone in their right mind try to improve on a B- ? Especially if you got a B- without even knowing you were being graded on it? :D

**Comment by kevinhendricks** [comment]
Just pushed the 4 small changes that might actually matter.  All of the remaining changes are in comments, in md, txt, or .html docs files, or in debug output that is currently disabled and not meant for the end user anyway.

Closing this as fixed in master.

**Comment by jschleus** [comment]
Sorry for opening this issue respectively "non-issue". I know and understand that misspelling corrections have a very low priority but nevertheless I was encouraged to open this issue by the positive feedback I got for similar reports by other FOSS projects. Naturally I have no problem if this issue is simply closed.

By the way, Fossies tries to determine the context type (and thereby the importance) of the found spelling errors and represents it by a single letter. The according column is sortable (if JavaScript is enabled) so especially the "unassigned" errors (that are often indicating an error in the source code itself and are represented by a "?") are easier to be found. The probably less important errors (found in comments) are grey-colored, the others black-colored.

And sorry for the "grade" (now removed). As mentioned in the general short description it's not a serious rating but more a "gimmick". And the codespell page isn't linked within the Fossies server so it isn't visible by normal users within the main [Sigil](https://fossies.org/linux/www/Sigil) page offered by Fossies.

If the Fossies support for Sigil is generally undesirable, please let me know it and naturally all Sigil entries will be immediatialy removed.

**Comment by kevinhendricks** [comment]
If there was a way to NOT report misspelled words in Comments and QDebug print statements, and to screen out entire file types by extensions such as .md, .txt, .html, etc, then the ability to get periodic reports may prove useful for finding typos in user facing code that may actually indicate an error.  Is there a way to configure that?

**Comment by jschleus** [comment]
Unfortunately that isn't currently possible (although it may be possible in the future). At least I have excluded now the files with the extensions .md, .txt and .html.

What about to just ignore the irrelevant misspellings and typos? Another possibility may be to apply and configure the codespell tool directly.

**Comment by kevinhendricks** [comment]
That helped.  There is one .ts file that should be omitted as well as it is a translation file that is built from the source code so any issues there are duplicates of issues that exist in the source.

Too bad you can not disable spellchecking in comments though.

There are only 11 files after removing comments, 4 of those have now been fixed and the remainder are in disabled debug output not presented to the user.

Is the codespell source code available on github to look at?  I am sure if they recognize the Type as c or  C, there should be a way to disable that.  

Or perhaps something as simple as a filter on the code that generates the output table you are producing?

Either way, our code is now error free when it comes to what the end user will see, and I am happy with that.

**Comment by jschleus** [comment]
Just for completeness: I have made a run for the master "277d5e6" (after your corrections) and no errors were found outside comments and debug messages. Should I remove the codespell pages created for 1.2.0?

The following link to the codespell page was given also in the original issue report and the Fossies codespell pages:

 https://github.com/codespell-project/codespell

**Comment by kevinhendricks** [comment]
You can delete it if you want.  Some additional code is being used with codespell as codespell itself knows nothing about code structure or comments, so something is using regular expressions to add the T type info.

**Comment by jschleus** [comment]
Ok, indirectly removed since the new release 1.2.1 is now the Fossies supported one.

And yes, Fossies does some simple post-processing (a.o. to detect block comments).
