### ISSUE TITLE
Create Checkpoint for Epub button results in "Embedded Python Error"

### ISSUE THREAD

**Issue by daemonblade** [Sigil-Ebook/Sigil#517]
I'm running sigil 1.2.1 on FreeBSD.

If I click on the **Create Checkpoint for Epub**, a popup appears with **Embedded Python Error**.
Show Details: **Error: traceback report is missing**

Where are the logs?

**Comment by mihailim** [comment]
Hm, that's odd. Does it say anything more than that if you run Sigil from a terminal then reproduce it?

**Comment by daemonblade** [comment]
Nothing.

**Comment by daemonblade** [comment]
No terminal output at all. Is there somewhere that sigil output its logs to?

**Comment by dougmassay** [comment]
Do you have a recent version of the dulwich python module installed? It's a requirement for the checkpointing feature.

**Comment by kevinhendricks** [comment]
Yes, embedded Python  not report a traceback error if it can not even import the target module file it is supposed to start in.

Sounds like you are missing some required python pieces.  You can use the testplugin_v017.zip Sigil plugin to test with.   It can be found in the Sigil/docs directory.

**Comment by dougmassay** [comment]
I think that as long as Sigil can be built/run on Linux/BSD without dulwich, we're going to run into many situations where people attempt to use Sigil without dulwich installed. We should probably consider testing for its presence first in all checkpointing python routines and reporting back an appropriate error that can be displayed.

I fear we're going to see a lot more of these reports (from Linux users who roll their own Sigil). It's why I hate spending time on documentation. Nobody reads it (or only glance at parts).

**Comment by kevinhendricks** [comment]
Isn’t that the reason for the testplugin?  If people do not test to see if their build is complete as we both document in our build instructions, do we really want to have to work around that?

**Comment by mihailim** [comment]
Perhaps dynamically disable the Checkpoints menu at runtime if dulwich isn't present or throws? However this is potentially an expensive check...

**Comment by dougmassay** [comment]
> Isn’t that the reason for the testplugin? If people do not test to see if their build is complete as we both document in our build instructions, do we really want to have to work around that?

Actually. The test plugin is billed as being used for testing that the plugin framework is complete. But in the end, it's only that there's a lack of a detailed error message that concerns me, here. We can save ourselves a lot of support grief by giving the user a clue why creating a checkpoint failed, I think.

**Comment by kevinhendricks** [comment]
Embedded python has always done that (no traceback if you can not import the target you are trying to launch).  The easiest solution would be to embed our own version of dulwich.

Do you want us to fork dulwich and include our own version.  I would be happy to do that as dulwich is so incomplete that it has issues even with the simple way we use it now.

But FWIW, this "I do not use plugins so they are optional" therefore I do not want to build/package them is a dead end street for Sigil.  Sigil is not Sigil without plugins and python, and therefore not supporting all of Sigil for some reason or another has never made much sense to me. 

We now rely on css-parser in a similar way but we do not include it as it is part of the required packages for plugins.

**Comment by dougmassay** [comment]
No. I don't want to include dulwich. And I agree that it's a mistake for packagers to assume plugins are an optional feature. I didn't mean to be argumentative in that way. I was just coming at this from a self-preservation mode. I don't want to have to close a dozens of issue reports with "install dulwich" if it can be helped.

I've discovered this is all moot, though. A missing dulwich module clearly shows in the Show Details of the Embedded Python error messagebox for me. As does a missing lxml, or a missing css_parser. So I'm not exactly sure why the OP's traceback is completely empty here. There must be a lot more missing from their python environment is all I can think. Or there's something wrong in general with Sigil's Embedded Python support on BSD (though not likely since multiple missing lxml/six error messages would be happening upon Sigil launch in that case).

**Comment by kevinhendricks** [comment]
Understood.  And agreed.  So there was no traceback provided but the details button shows what is missing, right?  Or are you getting a traceback error that message as well on Windows?  I will test this on macOS to see what it shows by renaming the dulwich folder in site-packages to see what happens.

**Comment by dougmassay** [comment]
On Windows and on Arch Linux, I get a traceback report (seen by clicking the Show Details button) for missing required modules.

```
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/repomanager.py", line 43, in <module>
    import dulwich

ModuleNotFoundError: No module named 'dulwich'
```
With missing css_parser when attempting to reformat css:

```
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/cssreformatter.py", line 3, in <module>
    import css_parser

ModuleNotFoundError: No module named 'css_parser'
```

**Comment by kevinhendricks** [comment]
Here is what happens when I rename dulwich to huh in site-packages.

I do get an error message and when I hit "Details" I see the following:

```
Traceback (most recent call last):

  File "/Volumes/SSD-Drive/repo/build7/bin/Sigil.app/Contents/python3lib/repomanager.py", line 43, in <module>
    import dulwich

ModuleNotFoundError: No module named 'dulwich'
```

But if I remove repomanger.py itself, then I get no traceback of any kind.

```
Error: traceback report is missing
```

So he either can not find the python3lib but that would create an lxml error, or it is missing repomanager.py.

So maybe an incomplete build or not a clean build?

**Comment by dougmassay** [comment]
Something's up. As you said: if repomanager or python3lib is missing, there'd probably be lxml errors at launch. So the fact that python3lib/lxml is being found suggests that there's nothing wrong with the way we're finding embedded python routine paths on BSD in general.

Maybe if we could get them to try and reformat some css and see what happens?

**Comment by dougmassay** [comment]
None of these embedded python errors are output to stderr, by the way. There's no reason they would be.

**Comment by kevinhendricks** [comment]
We could change Misc/EmbeddedPython.cpp to add qDebug() output and that may be a good idea for the next release but that would not help in this case as no traceback was provided.  I guess we could build up a "embedded python issue: module  blah will not load" error message if and only if a traceback is missing.

So either they are missing repomanager.py or something else is preventing that specific module from being found or imported.

**Comment by dougmassay** [comment]
That doesn't sound like a bad idea at all. "If and only if a traceback is missing." That would typically imply there's some piece of Sigil missing or otherwise unavailable.

**Comment by kevinhendricks** [comment]
I just pushed it to master.  It creates a default error message from the module name and the method or function name that will only be used if the traceback is empty.

**Comment by kevinhendricks** [comment]
I run into this issue all the time when I forget and leave syntax errors or typos in the ptyhon3lib code, so I immediately new it what it meant but this will at least provide more feedback to us and the user.

**Comment by kevinhendricks** [comment]
Close this or leave it open in case the real issue is the build process somehow?

**Comment by dougmassay** [comment]
Let's wait just a bit to be sure. I doubt FreeBSD is packaging 1.2.1 yet, so I assume the user built Sigil themselves. I'd like to verify that the build process is indeed putting everything where it belongs on that platform. I've tried to maintain the "if osx, elseif windows, else..." approach to ifdef and platform-dependent logic in general. But that doesn't mean some sort of "if linux" logic isn't biting us in the ass somewhere on FreeBSD.

Maybe I'll create a FreeBSD VM and do some testing of my own.

**Comment by daemonblade** [comment]
Ok, installing "dulwich" resolves the problem.
I'm not sure why there is no traceback, but for now this issue can be closed.

**Comment by dougmassay** [comment]
Well that's odd (the no traceback part). Thanks for reporting back, though!
