### ISSUE TITLE
Mac OS X Notes not complete

### ISSUE THREAD

**Issue by francwalter** [Sigil-Ebook/Sigil#518]
Hallo
on [Mac OS X Notes](https://github.com/Sigil-Ebook/Sigil/wiki/Mac-OS-X-Notes) I can read:

> Attention Mac OS X Users
> The latest version of Sigil requires macOS 10.12 or higher. macOS upgrades are available for free directly from Apple.

But there is not any note, which version this is. I had to download several versions to find, that it is  Version 0.9.10 which is the last version running on Mac OS 10.11
And yes, I would update my Mac if that was possible, but 10.12 runs not on any MacBook, only on MacBooks since around 2010, so no chance to use actual Sigil.

Thanks if you update the Notes.

frank 
MacBook Pro from Mid 2009 with 10.11.6

**Comment by kevinhendricks** [comment]
The Version information is provided always in the Release and at runtime in the About.  Yes very old MacOS versions are no longer supported and have not been for some time.

**Comment by kevinhendricks** [comment]
FWIW, We do have a Mobileread user's forum linked to from the ReadMe and other places for general questions and information.

**Comment by francwalter** [comment]
> The Version information is provided always in the Release and at runtime in the About. 

I havent found the system requirement in the release information and I cannot read anything in the About if the app is not running on my system.

**Comment by kevinhendricks** [comment]
It clearly states the minimum requirement for Sigil on macOS  Support for older macOS versions is not provided.  Old Sigil versions have bugs that I can not fix without upgrading Qt version and that determines the minimum supported platform.

Sorry, not a bug and really something the User forum would be able to handle.

**Comment by francwalter** [comment]
Good, Ok and thank. I understand now :)
