### ISSUE TITLE
Brazilian Portuguese translation ready for use.

### ISSUE THREAD

**Issue by kadu20es** [Sigil-Ebook/Sigil#523]
Hello, 

I've working on Sigil translation for Brazilian Portuguese at Transifex and it is ready to use. In fact, I'm already using it in my desktop since yesterday and would like it would be included in future versions of Sigil.

Thanks

**Comment by kevinhendricks** [comment]
Before each Sigil release, the base.ts file is updated, and one to two weeks later, each translation language that is 75% complete or more at the time of release will automatically be included.  The same rules are true for PageEdit
