### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by kadu20es** [Sigil-Ebook/Sigil#524]
Hello, 

I've working on Sigil translation for Brazilian Portuguese at Transifex and it is ready to use. In fact, I'm already using it in my desktop since yesterday and would like it would be included in future versions of Sigil.

Thanks

**Comment by kevinhendricks** [comment]
duplicate of closed issue.  Please do not use Sigil issues to leave messages that are not real issues.  Transifex does notify us when translations are complete and we do include all those that beat the 75% complete hurdle at the time of release.
