### ISSUE TITLE
Update Building_on_Linux.md for Conda users

### ISSUE THREAD

**Issue by AlexYash** [Sigil-Ebook/Sigil#526]
If someone has installed and activated Conda environment on Linux (Ubuntu in my case) it is necessary to explicitly indicate paths to system's default Python locations. Otherwise Cmake adds a path to Conda's Python in Sigil's configuration and it doesn't work properly.

So for Conda users Cmake string should look like:
`cmake -G "Unix Makefiles" -DUSE_SYSTEM_LIBS=1 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DPYTHON_EXECUTABLE=/usr/lib/python3  -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so  -DCMAKE_BUILD_TYPE=Release ../sigil-src`

**Comment by dougmassay** [comment]
I'm not including the necessary cmake configure command for every potential flavor/situation. I already indicate in the instructions that the exact Python variables you specified may have to be used if there's different Pythons to choose from:

 > If cmake couldn't automatically find the necessary Python 3.4 (or higher) stuff it needs (like if you installed manually in an unusual location, or you want to use a different Python version) you may need to tell cmake specifically where things can be found. Do so with:
>
> -DPYTHON_LIBRARY=<the full path to the python3.4 (or higher) shared library> (usually something similar to /usr/lib/libpython34.so)
>
> -DPYTHON_INCLUDE_DIR=<the full path to the directory where python3.4's (or higher) header files can be found> (ex: /usr/include/python3.4)
>
>-DPYTHON_EXECUTABLE=<the full path to the python3.4 (or higher) interpreter> (ex: /usr/lib/python3)

 All the relevant cmake options that may need to be used are listed at the end of the build instructions.

**Comment by mapreri** [comment]
Also, I advocate the simple fact that people should understand what they
are doing. If one starts a conda environment they can't just pretend
everything's fine and run normal programs in it.  It's a given that trying
to do non-expected things in such specific mangled environment is going to
break stuff, and it's not that stuff's fault.

Just saying...

**Comment by dougmassay** [comment]
Closing, as the cmake options for specifying a particular python installation are already documented in the build instructions.
