### ISSUE TITLE
Clip encoding error

### ISSUE THREAD

**Issue by Moilleadoir** [Sigil-Ebook/Sigil#527]
It seems like the way the clips are encoded has changed again. I’ve had this happen before and fixed the clips I had then, but the list is a lot longer now. I haven’t used Sigil for a while, so it wouldn’t be a very recent change.

You can see how my clip list appears below. Some I can figure out and some I might be able to figure out by searching through epubs, but it’s annoying that Sigil has corrupted this data.

An example I can figure out:
Original | Now | sigil_clips.ini
-------- | --- | ---------------
Spás idir rainn  | SpÃ¡s idir rainn | `Sp\xc3\xa1s idir rainn`
`<div class="spásrainn"></div>` | `<div class="spÃ¡srainn"></div>` | `<div class=\"sp\xc3\xa1srainn\"></div>`
*(recreated entry -->)* | Spás idir rainn | `Sp\xe1s idir rainn`
*(recreated entry -->)* | `<div class="spásrainn"></div>` | `<div class=\"sp\xe1srainn\"></div>`

Has the text been double-encoded?

![2020-06-09 23-28-00 Sigil Clips](https://user-images.githubusercontent.com/1229543/84155436-aace5580-aaab-11ea-97a8-b350ae09cf84.png)

Previously using Ubuntu 18.04 & Sigil 0.9.13
Currently Manjaro & Sigil 1.2.1

**Comment by dougmassay** [comment]
Looks to me like your ini was corrupted at some point. Very likely by one of the bad Sigil versions that included the failed attempt to convert ini files to utf-8. Sigil v0.9.11/12 were pulled for this very reason.

https://github.com/Sigil-Ebook/Sigil/wiki#versions-0911-and-0912-of-sigil-are-very-buggy

**Comment by dougmassay** [comment]
0.9.11/12 were the only versions of Sigil that we knowingly messed with the encoding of clips (stored in ini files). If something happened again, then it could be Qt. Qt 5.15.0 definitely broke several things. Perhaps I can add this to the list. Has Manjaro recently updated its system Qt to 5.15.0?

**Comment by Moilleadoir** [comment]
The version I have in Ubuntu 18.04 (still current LTS for another couple of weeks) is 0.9.13 and it had already happened there. It had happened before that as well, but I can’t say which version. They probably weren’t updated as often in Ubuntu, so I doubt I got hit by both 0.9.11 and 0.9.12, but it’s possible.

The more I stare at these, the more I think I can probably figure them out.

**Comment by dougmassay** [comment]
Opening an existing preferences directory with either one of those bad versions would be enough to do the damage.

**Comment by kevinhendricks** [comment]
Closing this because and the bug was in an old version of Sigil that has clearly been marked as do not use.  There is no current bug in master.
