### ISSUE TITLE
Multiple/Batch Find & Replace

### ISSUE THREAD

**Issue by SilverGreen93** [Sigil-Ebook/Sigil#528]
Does Sigil 1.2.0 feature a Batch Find & Replace function?

I would like to define and save a set of rules, for example replace all "123" with "1234" etc. and run the rules on the current book without doing all the find x replace with y manually on every book.

Thanks.

**Comment by dougmassay** [comment]
You want the Saved Searches feature. Which can be used to group searches to be performed sequentially.

**Comment by dougmassay** [comment]
Please use the Sigil user forums at [Mobileread](https://www.mobileread.com/forums/forumdisplay.php?f=203) for general usage questions. It's in the [Important Links](https://github.com/Sigil-Ebook/Sigil/wiki/Important-Links) section of the [Wiki](https://github.com/Sigil-Ebook/Sigil/wiki).
