### ISSUE TITLE
Linux version fails to start

### ISSUE THREAD

**Issue by MSoszynski** [Sigil-Ebook/Sigil#536]
Error info: Fatal: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Sigil version: 1.3.0
Runtime Qt: 5.15.0
Compiled Qt: 5.15.0
System: PCLinuxOS 2020
Architecture: x86_64

**Comment by dougmassay** [comment]
Reboot. Had the same thing happen to me on Arch with an nvidia driver update.

**Comment by MSoszynski** [comment]
Rebooting didn't work What did work was to edit a line in /usr/bin/sigil so that instead of "QTLIB_DIR="usr/lib64" it now reads "QTLIB_DIR="usr/lib64/qt5". Of course, as a user, I shouldn't need to do this.

**Comment by dougmassay** [comment]
As a user, you're right. You shouldn't have to. But as maintainers, we also shouldn't have to hold PCLOS package maintainers. That launch script hasn't changed in years. This is on PCLOS. They've changed something RE Qt5.15 packaging and didn't adjust the launch script accordingly.

**Comment by dougmassay** [comment]
Closing, as this is a distro packaging issue.

**Comment by eli-schwartz** [comment]
> Rebooting didn't work What did work was to edit a line in /usr/bin/sigil so that instead of "QTLIB_DIR="usr/lib64" it now reads "QTLIB_DIR="usr/lib64/qt5". Of course, as a user, I shouldn't need to do this.

This is configured by CMake using the value of `qmake -query QT_INSTALL_LIBS`, and needs to point to the libQt5*.so shared libraries used by Sigil. If PCLinuxOS is putting this somewhere other than in the QT_INSTALL_LIBS directory, that's a distro bug.

On Arch Linux, there is

```
$ ls /usr/lib/qt
libexec/  mkspecs/  plugins/  qml/
```

But this directory should definitely not contain the shared libraries.

Your proposed fix deals with finding those shared libraries for $LD_LIBRARY_PATH but your initial error was about OpenGL so I don't really understand how this is supposed to fix anything...

**Comment by MSoszynski** [comment]
Sigil wouldn't start, and gave the error I quoted. After my edit, it started okay. I've reported this on the PCLinuxOS forum.

**Comment by MSoszynski** [comment]
I'm pleased to report that the good and efficient people at PCLinuxOS have now fixed the package in their repository.

**Comment by dougmassay** [comment]
Good news; Thanks for reporting it to them.
