### ISSUE TITLE
Creating books in multiple languages

### ISSUE THREAD

**Issue by Marcello-mco** [Sigil-Ebook/Sigil#538]
Hi. When I create an e-book, for example, when I create a ToC, Sigil creates a "Table of Contents" heading automatically. I helped to create the Brazilian Portuguese translation, and now that I've begun to use it, Sigil started creating "Tabela de conteúdos"  as the new heading. OK, that's what I've wanted.
But when I create e-books in English, with the user interface set as Portuguese, Sigil uses the Portuguese string instead of the English version, even when I use English as language at the MetaData Editor. Is there a way for the strings to be inserted using the language specified in the MetaData Editor, or using the language set at Preferences -> Language -> Default Language For Metadata, instead of using the language set at Preferences -> Language -> User Interface Language?

**Comment by Marcello-mco** [comment]
By the way, I mean, this happens when I use "Create HTML Table of Contents" option.

**Comment by kevinhendricks** [comment]
This bug was supposedly fixed in previous versions of Sigil.  What version of Sigil are you using and on what platform?

**Comment by Marcello-mco** [comment]
Hi, Kevin,
I'm using version 1.3.0, released last week. It's the first version I've seen with Brazilian Portuguese native, so it's the first time I'm trying this feature. I'm using Windows 10 (10.0.18362.959).

Marcello
> 
> This bug was supposedly fixed in previous versions of Sigil. What version of Sigil are you using and on what platform?

**Comment by kevinhendricks** [comment]
Okay, Becky is right.  I will pass in the default metadata lang to the TOCWriter code to get it "Table Of Contents" more properly created.

The fix should be in our next release.

Until then after creating it, use Sigil's CodeView to simply edit the xhtml to fix it the way you want before your final save.

**Comment by kevinhendricks** [comment]
BTW,  There were many earlier releases of Sigil with pt_BR support but the transifex translation team stopped updating it.  Sigil  requires a minimum 75% of strings to be translated before it will include a translation language in our official releases.  So for a while there it stopped being included.  The transifex translation team for pt_BR must be active again.

**Comment by Marcello-mco** [comment]
Thanks a lot, Kevin. That was really fast.
BTW, I'm accessing transifex at least twice a week to make sure pt-BR translation keeps up to date. I've come across Sigil about 8 months ago, started using it and, I must say, it's by far the best epub creating software I've seen. Congratulations for the fantastic job.

Marcello

**Comment by kevinhendricks** [comment]
Just pushed a fix for this to master.
Thank you for your bug report!
Closing
