### ISSUE TITLE
TOC title generation use Interface Language not Metadata language

### ISSUE THREAD

**Issue by ebray187** [Sigil-Ebook/Sigil#542]
**Create HTML Table Of Contents** should preserve _Metadata Language_ not _Interface Language_ (or maybe there should be a specific option for it).
For example Spanish language for metadata with English language interface returns:
Current: `<div class="sgc-toc-title">Table of Contents</div>`
Expected: `<div class="sgc-toc-title">Índice de contenido</div>`

Configuration (Interface to the ebook language) and full restart its needed to go through this for every TOC generation.

Regards.

Sigil 1.3.0
QT: 5.14.2
Gentoo Linux KDE 5.70.0 / Plasma 5.18.5
Python 3.7

**Comment by ebray187** [comment]
Duplicated #538

**Comment by kevinhendricks** [comment]
No, just edit the TOC in CodeView as a workaround untilthe next release with this fixed. Thanks for catching this was a duplicate that has already been fixed in master and closing it.  Every bit helps.
