### ISSUE TITLE
QFontMetrics’ has no member named ‘horizontalAdvance’

### ISSUE THREAD

**Issue by kiwiG** [Sigil-Ebook/Sigil#546]
Following the Linux installation instructions for Sigil 1.30 on Ubuntu 18.04.5 LTS yields the above error. According to the Qt [documentation](https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance-1), this is the result of using a Qt version less than Qt 5.11. The default installation version for Ubuntu 18.04,5 is Qt 5.9.5.

Suggest you update the docs!

**Comment by kevinhendricks** [comment]
No.  We can just conditionally ifdef it on Qt version to use the older version of this call (width) like it used to.  We will make that change for the next release.  That said Qt 5.12.9 or Qt 5.15.x (both LTS versions) would be better choice as Qt 5.9.5 is missing some features, especially in QtWebEngine.

**Comment by kevinhendricks** [comment]
No.  We can just conditionally ifdef it on Qt version to use the older version of this call (width) like it used to.  We will make that change for the next release.  That said Qt 5.12.9 or Qt 5.15.x (both LTS versions) would be better choice as Qt 5.9.5 is missing some features, especially in QtWebEngine.

**Comment by dougmassay** [comment]
In the meantime, this patch to the 1.3.0 src should let you build 1.3.0. The patch just removes the changes from the one deprecation warning commit, so nothing feature-related will be missing. It should be applied from the root of the Sigil repo/tarball.

[warning_revert.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/5136252/warning_revert.patch.zip)

**Comment by kevinhendricks** [comment]
Do all those changes need to be ifdef'd to Qt Version to get Qt 5.9.x to still work or just the horizontalAdvance to width ones?

**Comment by dougmassay** [comment]
I don't know for sure, to be honest. I was going to give him a patch with just the horizontalAdvance stuff reverted, but I didn't know if any of the other changes would cause problems (without building on 18.04 to be certain). So I just played it safe. I suspect it's just the horizontalAdvance stuff, though. We should definitely start with that. I can fire up a 18.04 VM to test it.

**Comment by kevinhendricks** [comment]
Okay, checked the changes in your patch.  Only horizonatalAdvance() to width() is needed, as in Qt 5.9.5 QSet.values() exists, QTreeview.sortByColumn() exists, and QTextFormat,firmats() exists.

So all we need to do is ifdef to Qt < 5.11 the use of QFontMetrics width() otherwise use horizontalAdvance().

Do you want to push those changes or should I?  Happy to do either.

**Comment by kevinhendricks** [comment]
@kiwiG - Sorry about the breakage.  I was just trying to get Sigil to build without warnings on Qt 5.15.X for other Linux distributions and inadvertently changed to something that did not exist in Qt 5.9.5.  I should have checked but I do not have a Linux dev machine with Qt 5.9.5 installed.  Our minimum support target is still Qt 5.9.5 on Linux.

**Comment by dougmassay** [comment]
Please go ahead and push the change, if you would. I can test it easily enough in my vm, but pushing from the vm would present challenges (not insurmountable, but still ;) ).

Remember that the ifdef will also need to accommodate setTabStopWidth vs setTabStopDistance (as well as width vs horizontalAdvance) in the two affected files. I just got an error that setTabStopDistance was not declared when building on Mint 19 (based on Ubuntu 18.04 with qt 5.9.5).

**Comment by kevinhendricks** [comment]
Good catch!  There may be other things missed.  So I just pushed what I think will work to master.  It does compile on Qt 5.12.9 but we may still run into other issues from my warnings related changes.  Just let me know if you run into anything else.

**Comment by dougmassay** [comment]
I think it will be fine. I quickly made similar changes to the two files in question and it compiled and ran OK. But I'll pull your changes when I get home to make certain.

**Comment by kiwiG** [comment]
Cheers guys! I did get it built using a Qt 15 PPA ([this one](https://launchpad.net/~beineri/)), but it's great to have a source-level fix.
