### ISSUE TITLE
Cannot install Sigil-1.3.0 on Windows 10

### ISSUE THREAD

**Issue by CaryKnoop** [Sigil-Ebook/Sigil#547]
I try to install on Windows 10 and get the following error:

"This program does not support the version of Windows your computer is running."

Windows version installed: 

Windows 10 Pro
Version: 1909

**Comment by dougmassay** [comment]
I install it on the latest Windows 10 Pro all the time. Are you sure you have the correct installer?

**Comment by CaryKnoop** [comment]
Yes, strange after attempting to update windows 2004 (which failed and back to 1909) it installed correctly.

**Comment by dougmassay** [comment]
Thanks for the update.
