### ISSUE TITLE
CMake Build Error 'class QFontMetrics' has no member named 'horizontalAdvance'

### ISSUE THREAD

**Issue by Shadeclan** [Sigil-Ebook/Sigil#548]
Attempting to create a Linux (Mint 19.1 Cinnamon) install package of Sigil but got the following error message:

`sigil-sourcecode/src/Widgets/TextView.cpp:106:51: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     return LINE_NUMBER_MARGIN * 2 + fontMetrics().horizontalAdvance(QChar('0')) * num_digits;
                                                   ^~~~~~~~~~~~~~~~~
src/CMakeFiles/sigil.dir/build.make:3212: recipe for target 'src/CMakeFiles/sigil.dir/Widgets/TextView.cpp.o' failed
make[2]: *** [src/CMakeFiles/sigil.dir/Widgets/TextView.cpp.o] Error 1
CMakeFiles/Makefile2:318: recipe for target 'src/CMakeFiles/sigil.dir/all' failed
make[1]: *** [src/CMakeFiles/sigil.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

Although there were no errors during the building of the make file, some libraries were not found or failed in some way:
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for windows.h
-- Looking for windows.h - not found [this would be expected on a linux system, I think]
-- Looking for C++ include type_traits.h
-- Looking for C++ include type_traits.h - not found
-- Looking for C++ include bits/type_traits.h
-- Looking for C++ include bits/type_traits.h - not found
-- Looking for _strtoi64
-- Looking for _strtoi64 - not found

Hope you can figure out the issue quickly.

**Comment by dougmassay** [comment]
Already fixed in master: a32f890

**Comment by dougmassay** [comment]
Should be able to cherry-pick that one commit, if you don't want the other stuff that's being tested since v1.3.

**Comment by Shadeclan** [comment]
I looked at that - do I need to add the code to the appropriate libraries or is there a build with this already in it?

**Comment by dougmassay** [comment]
There's no build with the fix yet. But I was under the impression you were building from source anyway. Is that not the case? If so, then yes: you would need to make the changes in that commit to your source code to work around the issue. You could cherry-pick the commit in question to the 1.3.0 source if you're using git, or you could make the changes manually. I think there's also a patch I attached to the #546 issue that should be able to be used to patch the 1.3.0 source.

That's the best I can do until a new release.

**Comment by Shadeclan** [comment]
OK, I replaced the files with the ones from your link - we'll see how it goes.

**Comment by dougmassay** [comment]
If you're you're replacing them with the latest files from the master branch, I can't guarantee there weren't other changes along the way that could cause problems by dropping them wholesale into the v1.3.0 source. The safest approach would be to patch the problem areas specifically.

**Comment by Shadeclan** [comment]
kk

**Comment by Shadeclan** [comment]
Also, you are correct.  Got this error:
`/home/woody/Apps/Sigil/sigil-sourcecode/src/ViewEditors/CodeViewEditor.cpp: In member function ‘bool CodeViewEditor::AddSpellCheckContextMenu(QMenu*)’:
/home/woody/Apps/Sigil/sigil-sourcecode/src/ViewEditors/CodeViewEditor.cpp:1221:43: error: ‘class SpellCheck’ has no member named ‘suggestPS’; did you mean ‘suggest’?
             QStringList suggestions = sc->suggestPS(selected_word);
                                           ^~~~~~~~~
                                           suggest
src/CMakeFiles/sigil.dir/build.make:4748: recipe for target 'src/CMakeFiles/sigil.dir/ViewEditors/CodeViewEditor.cpp.o' failed
make[2]: *** [src/CMakeFiles/sigil.dir/ViewEditors/CodeViewEditor.cpp.o] Error 1
CMakeFiles/Makefile2:318: recipe for target 'src/CMakeFiles/sigil.dir/all' failed
make[1]: *** [src/CMakeFiles/sigil.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
I'll redo this and just add or replace the specific code section .

**Comment by Shadeclan** [comment]
Worked.  Thanks for your help.

**Comment by kevinhendricks** [comment]
Closing this.
