### ISSUE TITLE
Can't undo the All HTML Files replacement.

### ISSUE THREAD

**Issue by NoNameUserDev** [Sigil-Ebook/Sigil#551]
I think the title is expressing the issue perfectly )
Well, I'll explain when it occurred:
I used the RegEx for replacing to commit some changes at once in all HTML files, but something went wrong and I wanted to undo it, but I couldn't. That sort of thing.

**Comment by kevinhendricks** [comment]
Undo only works on simple cut paste edits.  That is why we added Sigil's Checkpoint features which can save and restore the full epub.
Use Checkpoints.

**Comment by NoNameUserDev** [comment]
@kevinhendricks Oh, I see! I didn't know that function )) From now I'll do so, thank you for the answer!!

**Comment by NoNameUserDev** [comment]
OMG, How convenient it is! The checkpoints! Thank you again ))
