### ISSUE TITLE
hrefutils.py not found

### ISSUE THREAD

**Issue by linuxreinhard** [Sigil-Ebook/Sigil#566]
Commit 5328d6ccb46a19824296d46358121b82caa69902 moved some functions out of metadata_utils.py and some other files to hrefutils_py. As hrefutils_py id not in the same directory as metadata_utils.py , the functions were not found.

**Comment by dougmassay** [comment]
Where exactly are you seeing this error when running Sigil?

It's true that many of the python scripts in the python3lib directory import procedures from hrefutils.py, and that hrefutils.py is not in the same physical directory--but it never was in the same directory and there was never any issues with functions from it being found. The scripts in python3lib are used exclusively by Sigil's embedded python.  And when Sigil's embedded python is initially set up in main.cpp, the directory where hrefutils.py resides (the python plugin launcher framework location) is manually added to Python's sys.path with the following code:

`// Set up embedded python integration first thing
EmbeddedPython* epython = EmbeddedPython::instance();
epython->addToPythonSysPath(epython->embeddedRoot());
epython->addToPythonSysPath(PluginDB::launcherRoot() + "/python");`

So unless I'm badly missing something, all of the embedded python scripts in python3lib (including metadata_utils.py) can still (and do in my experience on my Linux/Windows systems) import anything from hrefutils during normal Sigil operation.

So unless you can point to any specific Sigil breakage as a result of the functions being relocated in the commit you reference (and provide steps to reproduce that breakage), we'll need to close as it's not an issue.

**Comment by kevinhendricks** [comment]
It is in the python path as set by Sigil so it can be found.  It is code shared with the plugin_launchers.  It is properly loaded bu opf_newparser.py and xmlproccessor.py.  So unless there is a typo it should be found.

What is the exact error message?

**Comment by linuxreinhard** [comment]
The error message:
setext parseropf error -2 traceback Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/opf_newparser.py", line 30, in <module>
    from hrefutils import urlencodepart, urldecodepart

ImportError: cannot import name 'urlencodepart' from 'hrefutils' (/usr/local/share/sigil/python3lib/hrefutils.p

On my system there are 2 versions of hrefutils.py
 reinhard@apollon:/usr/local/share/sigil$ find -name hrefutils.py | xargs ls -l
-rw-r--r-- 1 root root 12803 22. Okt 17:21 ./plugin_launchers/python/hrefutils.py
-rw-r--r-- 1 root root  5115 26. Sep 2019  ./python3lib/hrefutils.py

The problem is the old version of hrefutils.py in python3lib. If I remove that file, sigil works well.

**Comment by kevinhendricks** [comment]
The master tree does not have any hrefutils.py in python3lib.  Try a fresh git checkout.  Or alternatively, it could be a leftover from a previous install.

**Comment by linuxreinhard** [comment]
It must be a leftover from an installation a year ago. A fresh checkout would not remove the old file in /usr/local. Purging the file removed the problem.

**Comment by dougmassay** [comment]
It's a good idea to clean up older versions before reinstalling over top of them for precisely this reason. Either with your distro's package management system, or by using something like CheckInstall if you roll your own.  Files move, they get renamed. Uninstalling it does not remove any of Sigil's preferences.

**Comment by dougmassay** [comment]
It's still something we're probably going to encounter on Linux after the next release, so we'll need to be prepared for it from a support standpoint. Thanks for bringing it to our attention.

**Comment by kevinhendricks** [comment]
But I do not remember an official release with hrefutils.py in python3lib.  I know it was there briefly in master at one point but not for a release.  Perhaps I am mistaken.

**Comment by kevinhendricks** [comment]
And current master has not been released yet either.  So what distribution is making binaries from current master?  Or is this just on your system?

**Comment by dougmassay** [comment]
I think it's just on his system.

You may be right that it was never located in python3lib for a release. I didn't check that far. If that's the case, it should be a big deal at all from a support standpoint. Especially for users who primarily install Sigil from repositories. But we still might run into it from time to time. Linux users doing their own compilations don't traditionally do a lot of cleaning up the install directories (if it's not done for them via make uninstall or CheckInstall). So anyone who ever happened to build/install Sigil when hrefutils was in python3lib will probably only run into this issue in the next release; when the functions were removed from hrefutils.py. Granted: that should be a pretty small number of people.

**Comment by linuxreinhard** [comment]
Yes, I compile it myself and not only for a new release. hrefutils.py was created in python3lib at Sept. 16. 2019 and moved to
plugin_launchers/python at Sept. 26. 2019. So I compiled and installed sigil between that dates. There was no release between that dates.
The version in Debian Sid/testing (1.3.0) has it only at the right place.

**Comment by dougmassay** [comment]
> If that's the case, it should be a big deal at all from a support standpoint.

Shoot! I meant to say "SHOULDN't be a big deal at all".

**Comment by kevinhendricks** [comment]
So I think we can close this one.  As it will only hit users who build from current master which is in no way is even guaranteed to work or even compile cleanly as it is a work-in-progress.  That is the whole point of making stable source releases.

And given how much work we do in master as opposed to separate branches and merging in, using our master at any point is probably not the best idea.  I mean we are still fixing major crashing bugs as of a few minutes ago with lots of extra debug output enabled.

**Comment by kevinhendricks** [comment]
Of course, if you do regularly build from master, and are willing to test for us and report back issues before a release, that would always be welcome!  ;)

Closing

**Comment by linuxreinhard** [comment]
Next time, before reporting an issue, I will not only use a fresh git, but make an uninstall and then look for any files left.
