### ISSUE TITLE
Additional ids checking in the manifest is required

### ISSUE THREAD

**Issue by BeckyDTP** [Sigil-Ebook/Sigil#567]
I very like commit https://github.com/Sigil-Ebook/Sigil/commit/f43824ef8923079e12622259d9ebc5c0fd2e433e but… 

This issue is related to the current version (all latest commits, _AppVeyor build 391 for Windows_).

It is possible to create two IDs with the same name, but one is written in lowercase and the other in uppercase.
Perhaps this only applies to Windows, which is sensitive in this regard.

Step-by-step:
1. Run newest build
2. Create empty EPUB3
3. Create HTML TOC
4. Two files will be created (`sgc-toc.css` and `TOC.xhtml`)
5. Now rename `sgc-toc.css` to `toc.css`
6. In the OPF file you will now have two identifiers:
* `toc` for the `toc.css` file
* `TOC` for the `TOC.xhtml` file
7. Save the EPUB file
8. Run KindleGen, which is sensitive to duplicate identifiers in the manifest
9. You will get an error:

```
Error(htmlparser):E19001: No BODY tag found in content file.

**Comment by kevinhendricks** [comment]
This is a bug in kindlegen as the xml spec clearly states that all ids are case sensitive.  Ids are not part of filenames and so a filesystem can be case insensitive but not the ids.

**Comment by kevinhendricks** [comment]
I can add back the extension info to the id generation routine but technically what we are doing is legal.  I could also do a case-insensitive id duplication test but that is not part of the spec.

**Comment by BeckyDTP** [comment]
This may be a rare problem, but a problem nonetheless, although the specs do not mention it i although is related to KindleGen than Sigil.
I spent an hour figuring out through trial and error that it was about an ID.
The problem does not occur when the id is shared by Text + Image, but Text + Style is. That's when KindleGen looks for a `body` tag in the CSS file and obviously doesn't find it, so it aborts.

Adding the extension to id should fix the problem.

**Comment by kevinhendricks** [comment]
As a workaround to lower the probability of collision, I added back the extension since it was what we used to do.  You might want to file a bug report with kindlegen about its behavior.  It is really not to spec for any XML including the opf.

Closing this.
