### ISSUE TITLE
Ctrl-F behavior change

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#568]
Windows 10, Sigil v1.4.0

In previous versions of Sigil, if you highlighted some text and then press ctrl-f, the text would be pasted into the find & replace dialog, whether or not the dialog box was open, and the dialog box would remain open.

In v1.4.0, if the find & replace dialog box is open, ctrl-f copies the text into it but also closes dialog box. In effect, I have to press ctrl-f twice to do a find & replace operation. Pressing ctrl-f with the dialog box closed works as it did in previous versions of Sigil.

Is this behavior the new normal?

Thanks.

**Comment by kevinhendricks** [comment]
That change was made by request of one of our contributors. We really did not know that ctrl-f could be used to paste things into the dialog box when open as normal copy and paste shortcuts are typically used under those circumstances.
To us, it appeared that ctrl-f really had no function when f&r was already open.  Therefore, it was decided to make it a toggle to close the open dialog.

This change could be reverted if needed.

**Comment by dougmassay** [comment]
I don't remember this change being discussed (not a recrimination, just an acknowledgement of a feeble memory--I may have heartily approved of it for all I know!), but I'm not sure  the new functionality is an improvement over the old. The ESC key always worked to close the F&R dialog (when it had focus--and Ctr+F would always give it focus), for the keyboard oriented.

https://www.mobileread.com/forums/showthread.php?t=315267

Makes no difference to me in the end. Perhaps we should throw it up for (another) discussion?

**Comment by kevinhendricks** [comment]
@BeckyDTP

I believe it was something BeckyDTP / BeckyEbook  requested.  We can certainly open it up for discussion again.  I am happy to revert it but would like to hear from everyone.  I agreed to it as I did not see any other use for ctrl-f at the time, so making it a toggle made sense.

**Comment by dougmassay** [comment]
I didn't know crtl+f would pre-populate the search field with highlighted text after the F&R dialog was already open either.

**Comment by kevinhendricks** [comment]
Given that it did in earlier versions (and probably for a long long time) we should probably revert this change unless someone feels strongly the other way.  What do you think?

**Comment by kevinhendricks** [comment]
Here is the commit in question, in case we want to revert this for the next release?

https://github.com/Sigil-Ebook/Sigil/commit/2076bad2f1cbb0914113761e932f6a1503b923a7

**Comment by dougmassay** [comment]
I think we should at least consider reverting it. I never like to change long-standing behavior that people  have become accustomed to without some pretty compelling reasons for doing so. Granted: we didn't believe there were any consequences for this otherwise easonable change request, but now that we do...

**Comment by BeckyDTP** [comment]
Of course, please revert this commit.
I admit – I was wrong. Something that seemed to be a good solution to me broke an important functionality that I never used myself (which is a pity!).

It is mentioned in the documentation:
> If you select text in your document, you can use Ctrl + F to open Find & Replace window and your selected text will be placed in the Find box.

I am happy to build a new version for @mrprobert (or he will can download it from Appveyor), so that he can enjoy the new version without losing the Ctrl-F functionality.

**Comment by kevinhendricks** [comment]
I will revert this but there are a number of other bugs reported in the MR Sigil Release thread.  I want to track those down and get them fixed as well.

**Comment by kevinhendricks** [comment]
I have now reverted this in master and added in one other bug fix related to duplicate xmlencoding when processing the opf.

Thank you for your bug report.  Sorry about breaking long term behaviour.
