### ISSUE TITLE
Error adding HTML <dc:description>

### ISSUE THREAD

**Issue by januszoles** [Sigil-Ebook/Sigil#569]
When I add dc:description with html tags in it.
eg:
```xml
<dc:description><div><p>foo i bar</p></div></dc:description>
```
I should get:
```xml
<dc:description>&lt;div&gt;&lt;p&gt;foo i bar&lt;/p&gt;&lt;/div&gt;</dc:description>
```
but Im getting:
```xml
<dc:description>&amp;amp;amp;lt;div&amp;amp;amp;gt;&amp;amp;amp;lt;p&amp;amp;amp;gt;foo i&amp;amp;amp;#160;bar&amp;amp;amp;lt;/p&amp;amp;amp;gt;&amp;amp;amp;lt;/div&amp;amp;amp;gt;</dc:description>
```
Each time I save content.opf amp; multiplies. 
macOS Catalina Sigil 1.4.0

**Comment by kevinhendricks** [comment]
Yes, this is a known bug.  Already reported.  It is fixed in master.  We hope to make a follow-on release of a Sigil 1.4.1 soon with that fix in place.

**Comment by kevinhendricks** [comment]
Closing this as already fixed in master.
