### ISSUE TITLE
Mangled metadata containing ampersands

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#570]
1. Run Sigil and use the MetaData editor to set the publisher to: W. W. Norton & Company
2. Close the editor and content.opf has: <dc:publisher>W. W. Norton &amp; Company</dc:publisher>
3. Save the document and the publisher metadata is now: <dc:publisher>W. W. Norton &amp;amp;amp;amp; Company</dc:publisher>
4. Each subsequent save adds more of: amp;amp;amp;

Windows 10
Sigil v1.4.0

Preferences:
Create new epub as version 3
Mend on open and save

**Comment by mrprobert** [comment]
I mangled the mangle as dc:publisher should wrapped by lt and gt.

**Comment by dougmassay** [comment]
#569 fixed in master with 3b4c1f49e74a6d01a0aab82701e4edc59d76bf1a

We hope to have a quick turnaround on a version 1.4.1

**Comment by mrprobert** [comment]
Cool, thanks!

**Comment by dougmassay** [comment]
Thanks for the report.
