### ISSUE TITLE
How to uninstall after compiling?

### ISSUE THREAD

**Issue by mknepper** [Sigil-Ebook/Sigil#573]
I've compiled Sigil, but I want to uninstall it. I can't seem to find a way to do that. I've tried running `make uninstall` from the source directory and nothing happens. I'm on Linux Mint.

**Comment by dougmassay** [comment]
Cmake generators do not create uninstall targets. Most people use something like checkinstall when installing custom compiled programs to  make uninstallation easier. If you didn't use something like that, there's always the install_manifest.txt file that's created in the Sigil build directory that can be used to determine what to remove. This can even be automated using something like `xargs rm < install_manifest.txt` from a terminal in the Sigil build directory (clearly you'll need to use sudo if you installed Sigil with sudo).

By default, Sigil installs primarily to just a couple of directories: `<INSTALL_PREFIX>/share/sigil` and `<INSTALL_PREFIX>/lib/sigil`. Remove those directories and that's the bulk of it. Then there's just a couple of other files remaining:
`<INSTALL_PREFIX>/bin/sigil`
`<INSTALL_PREFIX>/share/pixmaps/sigil.png`

If there's nothing else but sigil.png in `<INSTALL_PREFIX>/share/pixmaps/` then the install probably created the `pixmaps` directory as well.

**Comment by dougmassay** [comment]
Closing this, as it's more build advice-related than it is an issue/feature request.
