### ISSUE TITLE
Segfault in 1.4.0-1 on launch

### ISSUE THREAD

**Issue by RudiAusBuddeln** [Sigil-Ebook/Sigil#574]
I have just upgraded to Sigil 1.4.0-1 through pacman on Manjaro Linux, and now everytime I try to start Sigil, it segfaults.

For the fraction of a second, the border of a window named `untitled.epub - Sigil` is visible.

Starting the program without any input:

```
$ sigil
Debug: attempted to load a non-exsitant dictionary:  "en_US"
Debug: attempted to load a non-exsitant dictionary:  "en_US"
Segmentation fault (core dumped)
$ # Exit code is 139
```

With a file:

```
$ sigil test.epub
Debug: attempted to load a non-exsitant dictionary:  "en_US"
Debug: ImportEpub with Manifest item:  "Styles/sgc-nav.css" "Styles/sgc-nav.css"
Debug: ImportEpub with Manifest item:  "Styles/stories.css" "Styles/stories.css"
Debug: ImportEpub with Manifest item:  "Text/nav.xhtml" "Text/nav.xhtml"
Debug: ImportEpub with Manifest item:  "Text/solutions.xhtml" "Text/solutions.xhtml"
Debug: ImportEpub with Manifest item:  "Text/story87.xhtml" "Text/story87.xhtml"
Debug: ImportEpub with Manifest item:  "Images/a.png" "Images/a.png"
Debug: attempted to load a non-exsitant dictionary:  "en_US"
Segmentation fault (core dumped)
$ # Exit code 139
```

The log from `coredumpctl`:
```
           PID: 52951 (sigil)
           UID: 1000 (monke)
           GID: 1000 (monke)
        Signal: 11 (SEGV)
     Timestamp: Mon 2020-11-23 20:09:32 CET (48s ago)
  Command Line: /usr/lib/sigil/sigil
    Executable: /usr/lib/sigil/sigil
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (monke)
       Boot ID: <I don't know whether this sensitive>
    Machine ID: <I don't know whether this sensitive>
      Hostname: monke-pc
       Storage: /var/lib/systemd/coredump/core.sigil.1000.98a3dc993b694633b303d4d7b3fc726d.52951.1606158572000000.zst
       Message: Process 52951 (sigil) of user 1000 dumped core.

                Stack trace of thread 52951:
                #0  0x00007ff06b56482f _ZNK10QTextCodec11fromUnicodeERK7QString (libQt5Core.so.5 + 0x31382f)
                #1  0x0000562cf6f706eb _ZN10SpellCheck7spellPSERK7QString (sigil + 0x3256eb)
                #2  0x0000562cf6f22985 _ZN14HTMLSpellCheck18GetMisspelledWordsERK7QStringiiS2_bb (sigil + 0x2d7985)
                #3  0x0000562cf6f22ab9 _ZN14HTMLSpellCheck18GetMisspelledWordsERK7QString (sigil + 0x2d7ab9)
                #4  0x0000562cf6f1c48e _ZN16XHTMLHighlighter13CheckSpellingERK7QString (sigil + 0x2d148e)
                #5  0x0000562cf6f1c6f4 _ZN16XHTMLHighlighter14highlightBlockERK7QString (sigil + 0x2d16f4)
                #6  0x00007ff06ba5d8e8 n/a (libQt5Gui.so.5 + 0x2ba8e8)
                #7  0x00007ff06ba5dab1 n/a (libQt5Gui.so.5 + 0x2baab1)
                #8  0x00007ff06ba5de6e _ZN18QSyntaxHighlighter11rehighlightEv (libQt5Gui.so.5 + 0x2bae6e)
                #9  0x0000562cf6fb5bf3 _ZN14CodeViewEditor19RehighlightDocumentEv (sigil + 0x36abf3)
                #10 0x0000562cf6fb66a9 _ZN14CodeViewEditor17CustomSetDocumentER12TextDocument (sigil + 0x36b6a9)
                #11 0x0000562cf6dc6b1b _ZN7FlowTab21DelayedInitializationEv (sigil + 0x17bb1b)
                #12 0x00007ff06b5317e2 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2e07e2)
                #13 0x00007ff073226752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
                #14 0x00007ff06b504cda _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b3cda)
                #15 0x00007ff06b5077d3 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2b67d3)
                #16 0x00007ff06b55e304 n/a (libQt5Core.so.5 + 0x30d304)
                #17 0x00007ff0676a9914 g_main_context_dispatch (libglib-2.0.so.0 + 0x52914)
                #18 0x00007ff0676fd7d1 n/a (libglib-2.0.so.0 + 0xa67d1)
                #19 0x00007ff0676a8121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #20 0x00007ff06b55d941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #21 0x00007ff06b50365c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #22 0x00007ff06b50baf4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2baaf4)
                #23 0x0000562cf6d8abff main (sigil + 0x13fbff)
                #24 0x00007ff06aeb7152 __libc_start_main (libc.so.6 + 0x28152)
                #25 0x0000562cf6d9c38e _start (sigil + 0x15138e)

                Stack trace of thread 52971:
                #0  0x00007ff06acc56a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007ff06e5e28ac n/a (libQt5WebEngineCore.so.5 + 0x27728ac)
                #2  0x00007ff06ee02038 n/a (libQt5WebEngineCore.so.5 + 0x2f92038)
                #3  0x00007ff06e5e8c5a n/a (libQt5WebEngineCore.so.5 + 0x2778c5a)
                #4  0x00007ff06acbf3e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007ff06af8f293 __clone (libc.so.6 + 0x100293)

                Stack trace of thread 52955:
                #0  0x00007ff06acc59c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007ff06b325058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007ff06b322fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007ff06b31ee8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007ff06acbf3e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007ff06af8f293 __clone (libc.so.6 + 0x100293)

                Stack trace of thread 52972:
                #0  0x00007ff06acc56a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007ff06e5e28ac n/a (libQt5WebEngineCore.so.5 + 0x27728ac)
                #2  0x00007ff06e5e3423 n/a (libQt5WebEngineCore.so.5 + 0x2773423)
                #3  0x00007ff06e5e35ef n/a (libQt5WebEngineCore.so.5 + 0x27735ef)
                #4  0x00007ff06e54a105 n/a (libQt5WebEngineCore.so.5 + 0x26da105)
                #5  0x00007ff06e5926c8 n/a (libQt5WebEngineCore.so.5 + 0x27226c8)
                #6  0x00007ff06e56d622 n/a (libQt5WebEngineCore.so.5 + 0x26fd622)
                #7  0x00007ff06e5af322 n/a (libQt5WebEngineCore.so.5 + 0x273f322)
                #8  0x00007ff06e5e8c5a n/a (libQt5WebEngineCore.so.5 + 0x2778c5a)
                #9  0x00007ff06acbf3e9 start_thread (libpthread.so.0 + 0x93e9)
                #10 0x00007ff06af8f293 __clone (libc.so.6 + 0x100293)

                Stack trace of thread 52956:
                #0  0x00007ff06acc59c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007ff06b325058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 +
```

This occurred the first time after I attempted to load en EPUB with 40 chapters, although not very large each, but with a couple hundred images and audio. Maybe that corrupted it somehow?

**Comment by RudiAusBuddeln** [comment]
This problem persists after reinstalling Sigil. I have also tried deleting the (unmodified since multiple weeks) cache folder.

**Comment by kevinhendricks** [comment]
First both Sigil 1.4.0 and Sigil 1.4.1 have been pulled from github due to serious issues (unrelated to the problem you are seeing).  So please upgrade to Sigil-1.4.2 which has critical issues.

Second you appear to have an incomplete install.  The en dictionary is shipped as part of Sigil source so can not be missing in a good build.

The segfault happens because the code is looking for a non-existent codec to match that used in a non-existent dictionary.

I will add code in the future to prevent this from happening, but the easiest way forward now to to upgrade to Sigil-1.4.2 and make sure you install all required components including hunspell dictionaries.

In addition, if you build Sigil from source, remember to make install and to be sure launch sigil via the launch script so all paths are set appropriately.

**Comment by dougmassay** [comment]
hunspell-en_US is an optional Sigil dependency when installed from an Arch repository. Repository builds don't install all of the dictionaries that ship with Sigil by default. We may need to do something if the new multi-language spell-checking feature expects all of those dictionaries to be present.

**Comment by RudiAusBuddeln** [comment]
@dougmassay Exactly, that was what happened to me. I informed the package mantainer about this pitfall.

**Comment by kevinhendricks** [comment]
It does expect the en_US dictionary to be present since that is the default dictionary on startup when no sigil.ini file is present.  Once started up, Sigil expects that the whatever the default dictionary is set to by the user is present.

**Comment by dougmassay** [comment]
Has that always been the case? hunspell-en_US has always been an optional dependency in Arch sigil packages in the past. There's been no reports of issues due to this before now.

Repo versions of Sigil on Linux have always reserved the right to use their own system hunspell dictionaries. That's why there's lots of config options to not install the ones from Sigil's source (as well as the ability to specify what location in the system they reside in).

**Comment by kevinhendricks** [comment]
Some dictionary would be needed, .. unless we disable the real time spell check (red squiggley underline).  We could I suppose check locale to get a default dictionary but that does not always work either.

I will look to disable real time spellchecking when no sigil.ini file is found and to check for a proper codec being present in a dictionary.  This should allow start-up on systems without a dictionary loaded.

**Comment by kevinhendricks** [comment]
The best solution for now, would be to require the dictionaries.

**Comment by dougmassay** [comment]
I don't think we can reasonably require non-english speaking users to have english spellchecking dictionaries installed to run repo versions of Sigil on Linux. For anything other than a temporary workaround, I mean.

**Comment by kevinhendricks** [comment]
In Sigil/src/Misc/SettingsStore.cpp we should disable realtime spellcheck by default when no sigil.ini file is present to look as follows:

```

bool SettingsStore::spellCheck()
{
    clearSettingsGroup();
    return static_cast<bool>(value(KEY_SPELL_CHECK, false).toBool());
}
```

**Comment by dougmassay** [comment]
I don't understand why this is an issue now, when it never was in the past??

**Comment by dougmassay** [comment]
Besides, if this person was upgrading their version of Sigil, that means there already was a Sigil.ini prresent. So why the crash starting with 1.4.0?

**Comment by kevinhendricks** [comment]
I checked the code and it protects against the case when no dictionary can be found.  So the only way to hit this is to find an dictionary for the language that does not include a encoding line in its aff file.  That is a broken dictionary according to myspell/hunspell rules.

Not sure what is going on here at all.

**Comment by eli-schwartz** [comment]
Speaking as a distro maintainer, I'd definitely prefer Sigil to disable spellchecking rather than segfaulting if no dictionaries are available. This is kind of difficult to enforce on our end and I definitely don't want to shove en_US down everyone's throat given the whole point of debundling those is to let the user configure their own system dictionaries.

Is that actually what is happening?

**Comment by dougmassay** [comment]
Let me do some checking on my end. I can simulate an Arch package build pretty easily.

**Comment by eli-schwartz** [comment]
Also I did upgrade the Arch repos to 1.4.2 this morning...

**Comment by kevinhendricks** [comment]
But I could easily have messed things up given this code was heavily modified when supporting multiple spellchecking.

I am going to see if I can recreate this in macOS by manually removing both the en_US dictionary and my sigil.ini file.

From the backtrace and error messages the load dictionary is detecting the missing dictionary and spitting out the non-existent dictionary warning but somehow the SyntaxHighlighter is trying to invoke the spell and it is not returning true (spelled correctly) when no dictionary exists and it should.

I just never dreamed anyone would be installing Sigil without its dictionaries so the new code was never designed or tested for that case properly.

I am on it.

**Comment by dougmassay** [comment]
Here's the scoop: 

It's definitely new behavior. Sigil 1.3.0 installed as an Arch package will start up fine on a new installation (no Sigil.ini) even without any hunspell dictionaries installed or present. Spellchecking clearly doesn't work, and no dictionary is selected in the preferences, but no segfaults.

Sigil 1.4.0+ crashes under the exact same scenario.

Our best bet is to probably change Sigil to somehow gracefully disable spellchecking without crashing when no dictionary is present. I'm sure @kevinhendricks  is probably looking into to that already. @eli-schwartz : in the meantime, we'll handle all support of the issue and recommend that people temporarily install hunspell-en_US to work around the problem. I don't expect you to force the installation of an English hunspell package even a temporarily. Once the english package is installed and Sigil will launch they can install their own language dictionary and switch to it in Sigil and then remove the english package altogether.

I don't really expect there to be that many people using Sigil without at least their primary language dictionary installed. Which means this will primarily affect Linux users installing Sigil from repos for the first time (and starting with 1.4.0).

Those who roll their own and those who are already spellchecking with installed dictionaries should be unaffected. I don't think that will be a ton of people, so I don't really see this as an emergency. Even if we released a quick v1.4.3, there's no guarantees that anyone other than Eli and Arch Community would pick it up anytime soon anyway.

**Comment by kevinhendricks** [comment]
Here is a patch to hopefully fix this issue so that no en_US dictionary is needed by anyone.
@DiapDealer, if you can recreate the issue on your Arch box, please give this patch a try to see if it does what we want.  It should prevent segfault on startup with empty sigil.ini when missing em_US dictionary and also prevent segfaults when sigil.ini has selection for a dictionary that does not exist anymore do to it being deleted.

[spell_check_crash_fix.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/5585783/spell_check_crash_fix.patch.zip)

**Comment by eli-schwartz** [comment]
I'd be willing to cherry-pick a patch fixing this to spare you the effort of rolling out a new release just for distro packages.

From spot checking, I think we and Debian are the only people using system dictionaries. Pinging @mapreri about this bug in Debian sid...

**Comment by kevinhendricks** [comment]
Here is a slightly more conservative version of the patch that protects against issues in suggestions as well and not just spell of words.

[spell_check_crash_fix_v2.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/5585909/spell_check_crash_fix_v2.patch.zip)

**Comment by kevinhendricks** [comment]
@DiapDealer when you get a moment, please try the second patch and let me know if it does what we want on Linux. It seems to fix things on my macOS dev box but I did not try with removing all dictionaries just the one it defaults to when no sigil.ini file exists.

**Comment by dougmassay** [comment]
Is the patch based on the current HEAD of master or one of the previous tags?

**Comment by dougmassay** [comment]
That seems to do the trick when I patch 1.4.2 with it. Any concern for any plugin framework stuff with regard to changes due to multiple language spell-check support? I've never really been set up for that sort of testing.

**Comment by kevinhendricks** [comment]
It is based on master but none of those files were touched between 1.4.2 and current master.  So It should apply to either.

**Comment by kevinhendricks** [comment]
We only give the paths and dictionary names to plugins but I will take a look to double-check.

**Comment by dougmassay** [comment]
Being able to apply cleanly to 1.4.0/1/2 would be a bonus (easier to be cherry-picked by distros), but as I said earlier, I don't think we're in an emergency situation, here.

**Comment by kevinhendricks** [comment]
Can't ... as we touched spellcheck code in 1.4.1 or 1.4.2, so this patch must be applied to Sigil-1.4.2 official source.

Checked out plugins, we pass along the paths to the dictionaries folder and the current selected dictionary name.

It is up to plugin devs to use pluginhunspell (the original) or pluginhunspellml (the new) and it  is the plugin code that loads the dictionaries for both.  

Since we are fully backwards compatible here due to pluginhunspell 
and no plugunhunspellml was not released until 1.4.x we should be perfectly safe with regards to plugins.

**Comment by dougmassay** [comment]
That's Ok. I say push the change (if it can be applied to the current master). I don't know what version of Sigil Debian is currently on, but @eli-schwartz could cherry-pick the commit if he wants for Arch, and we should be in good shape. We have a workaround for the few who may fall through the cracks between now and the next release.

**Comment by eli-schwartz** [comment]
As I implied above, only Debian sid is on 1.4.x -- also for the record, https://repology.org/project/sigil/versions is handy for quickly comparing the version across a ton of packaging entities.

**Comment by kevinhendricks** [comment]
I will push the change to current master, but please note current master is not suitable for any release as I have today pushed some very invasive changes that really need some serious testing.

So this change should be added to Sigil-1.4.2 official source if you decide to cherry pick.

I will push these changes to current master now.

**Comment by kevinhendricks** [comment]
Just pushed this patch to master so it will be there for future releases.

**Comment by dougmassay** [comment]
Got it. So only commit 16babc8 should be considered for cherry-picking and only when applied to the 1.4.2 source tree.

**Comment by dougmassay** [comment]
Thanks for reporting the issue @RudiAusBuddeln . In case it wasn't clear with all this back and forth, installing the hunspell-en_US package with pacman should be an easy workaround for your crashing problem. Hopefully Manjaro will pick up the Sigil 1.4.2 update (and possibly the cherry-picked patch if it happens) sooner rather than later.

**Comment by eli-schwartz** [comment]
I tested the segfault and the patch. It no longer segfaults on startup after I backport 16babc881ac0f996641cc693a7564c4e08e27266, but using the Tools -> Spellcheck menu will still manually provoke a segfault. If you click "Highlight misspelled words" it will immediately save, to sigil.ini, 
```
[user_preferences]
spell_check=true
```

and once more, will segfault on every startup.

**Comment by kevinhendricks** [comment]
@eli-schwartz 
Code was basically sound but my eyesight is not what it once was.  Hitting my 60th birthday has made me miss seeing things.  I missed protecting an access for a Qt QHash in SpellCheck.cpp when it retrieves the wordchars and Qt QHashes generate a default constructed value if you do not test if the hash key is present first.  That put a null en_US dictionary entry in the hash of open dictionaries that of course had no codec or encodings since the real dictionary did not exist.

The user preferences are fine being changed by the Spellcheck dialog.

Please Add on a second commit (966fe5e) change applied *after* the one you just did.
It fixes a spelling typo in a debug message and includes the needed one line fix.

Tested on macOS after removing the en_US dictionary for startup and for spellcheck dialog. 

https://github.com/Sigil-Ebook/Sigil/commit/966fe5e8fa16d791d995d4655894f1d328e3c76e
```
diff --git a/src/Misc/SpellCheck.cpp b/src/Misc/SpellCheck.cpp
index c736e79d..92c49cd6 100644
--- a/src/Misc/SpellCheck.cpp
+++ b/src/Misc/SpellCheck.cpp
@@ -305,7 +305,7 @@ void SpellCheck::loadDictionary(const QString &dname)
     QMutexLocker locker(&mutex);
     // If we don't have a dictionary we cannot continue.
     if (dname.isEmpty() || !m_dictionaries.contains(dname)) {
-        qDebug() << "attempted to load a non-exsitant dictionary: " << dname;
+        qDebug() << "attempted to load a non-existent dictionary: " << dname;
         return;
     }
 
@@ -396,6 +396,7 @@ QString SpellCheck::getWordChars(const QString &lang)
     if (!m_opendicts.contains(dname)) {
         loadDictionary(dname);
     }
+    if (!m_opendicts.contains(dname)) return "";
     HDictionary hdic = m_opendicts[dname];
     Q_ASSERT(hdic.codec != nullptr);
     Q_ASSERT(hdic.handle != nullptr);
```


Sorry about all of that!

**Comment by kevinhendricks** [comment]
If you want a single patch to Sigil-1.4.2 instead of the two commits, just let me know and I will generate one tomorrow asap.

**Comment by eli-schwartz** [comment]
Thanks, that seems to work much better!

**Comment by kevinhendricks** [comment]
Took a look at:  https://repology.org/project/sigil/versions 

Wow!  I had no idea how many old and outdated versions of Sigil are out there.  Sad really.  The one that jumped out to me was Fedora Rawhide stuck at 0.9.14.  

Does Fedora not package QtWebEngine?

Who is supporting all of those old versions?  Where are bugs getting posted?  Are they distro supported?   

QtWebKit is back so far from current WebKit and riddled with bugs and memory leaks in the updated versions.  Some might hate Qt but at least its LTS versions get security fixes in QtWebEngine.

Strange choices are being made by many distributions.  And I wonder how many of these distributions are even being actively maintained.

Are QtWebEngine Chromium 3rdparty licensing issues still keeping some distributions away?

The proliferation of distributions and lack of maintenance seems to make Linux its own worst enemy to more mainline acceptance.

**Comment by dougmassay** [comment]
Even the variance within Manjaro's repos seem arbitrary/silly to me. Manjaro stable and testing are both at 1.4.0 and unstable is at 1.4.2. Yet 1.4.0, 1.4.1, 1.4.2 were all released within one week of each other. So how "stable" are the stable packages, how "unstable" are the unstable packages, and what's the point of any of them if all three Manjaro repo tracks are on versions released within the past seven days? What's the criteria? Does it have to stay in unstable for 12 hours before it moves on?!

**Comment by eli-schwartz** [comment]
Your guess is correct. Manjaro is mostly automated, following the approach that your system is somehow "more stable" if it contains all packages from archlinux but with a time delay.

So if a buggy version lands in arch, manjaro gets it after idk, let's say 1 week of arch users suffering through the bug. And if arch fixes it after a day, manjaro users will get the buggy version 6 days later, and the fixed version a day after that.

If their maintainer team of maybe 5 people notices a specific package is issueful I'm sure they can manually override this. But arch has closer to a hundred people, and dedicated maintainers for each package, which manjaro by its fundamental nature does not, so in practice there are a handful of high-profile packages that manjaro actually pays attention to... And in the end it turns out they forked those packages and maintain their own packaging recipes independent from arch.

**Comment by eli-schwartz** [comment]
Fedora has an open release monitoring bug to update sigil, which doesn't really provide details on why it's getting moldy: https://bugzilla.redhat.com/show_bug.cgi?id=1724109

**Comment by dougmassay** [comment]
I'd be surprised if Fedora's issue was anything other that the switch from webkit to webengine. Somebody probably just needs to update some packaging scripts/parameters or some such. They need a "kick this project in the ass" button somebody can push!

**Comment by kevinhendricks** [comment]
I saw a failed build log and it was applying patches as far back as Sigil-0.8.0 which of course fail to apply.

@eli-schwartz
Are there long standing patches needed by most/many Linux distributions that we have not yet incorporated into the Linux build time settings that you feel are important to include?

Is breakage of old patches what is preventing some newer releases? Or are many distributions just not updating their builds scripts?

**Comment by dougmassay** [comment]
I'm wondering if there's some sort of fast-fail going on after the initial arm build failure. Like none of the other architectures are even being tried.

**Comment by eli-schwartz** [comment]
I only track my own build patches, not other distros.

Many of the entries in repology are for multiple versions of a distro -- e.g. Fedora will generally only update packages in rawhide and maybe the most recently numbered version of Fedora, the rest are frozen in time.

So it's not as bad as it might initially look.

**Comment by eli-schwartz** [comment]
Going back to Kevin's question from before, Parabola, at least, will not update sigil until the GNU FSDG decides whether webengine counts as free/open source software.

**Comment by eli-schwartz** [comment]
Back on topic... If you look above, you'll see that this issue was referenced by a commit in archlinux/svntogit-community, in which I backported both commits to fix this issue.

**Comment by dougmassay** [comment]
I saw this morning that Arch was up to 1.4.2-3. Thanks!

**Comment by kevinhendricks** [comment]
Yes, Thank You!

**Comment by eli-schwartz** [comment]
I must confess to feeling slightly ridiculous at the sheer number of times I've built sigil in the past week... Because every time I release a new version I need to build it twice, once  for the stable repo and once for the in-progress python 3.9 mass rebuild.

:D

Hopefully things will settle now.

**Comment by kevinhendricks** [comment]
I am closing this as the required changes have reached master and were cherry-picked by Arch.
