### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by Otakuzu** [Sigil-Ebook/Sigil#575]
Hi, I was using an old version and made the bad decision to upgrade to the latest version, now I can't find the button that allows me to change the html mode and the preview mode (I could edit the book in this mode), can someone tell me if the function is still there or tell me which version had it? This is the most useful function for me

**Thanks!**

**Comment by eli-schwartz** [comment]
From the readme:

> Support forums are located at http://www.mobileread.com/forums Select Sigil from the list of main forums

**Comment by Otakuzu** [comment]
> From the readme:
> 
> > Support forums are located at http://www.mobileread.com/forums Select Sigil from the list of main forums

thanks!
