### ISSUE TITLE
when TXT.file been saved,it cannot open again!! 

### ISSUE THREAD

**Issue by cj0293** [Sigil-Ebook/Sigil#576]
![11](https://user-images.githubusercontent.com/75459544/101111331-f48c9880-3615-11eb-9f29-031cd66e81cc.JPG)

Error info: Cannot load file C:\Users\Neo\Desktop\harry potter2.epub: D:/Temp/Sigil-UMDnXU/OEBPS/toc.ncx: The system cannot find the specified file.
Sigil version: 1.4.3
Runtime Qt: 5.12.9
Compiled Qt: 5.12.9
System: Windows 7 SP 1 (6.1)
Architecture: x86_64

**Comment by dougmassay** [comment]
What does a TXT file have to do with any of this? Sigil doesn't save txt files.

**Comment by dougmassay** [comment]
Sigil hasn't created an ncx file when "opening" txt files for a long, long, time. We'll look into having Sigil autocreate a dummy ncx when opening a txt file so that a valid epub2 gets created/saved (and doesn't crash on opening) in a future release. But it's not going to be a priority. Creating epubs by opening txt files isn't all that popular (or recommended).

In the meantime, if you HAVE to open txt files and save them as epubs, set your "Create New or Empty Epubs As" Sigil preference (Edit->Preferences->General Settings->Basics) to "Version 3". Then when you open a txt file it will import/save as an Epub3 and won't crash when opening.

**Comment by dougmassay** [comment]
@kevinhendricks : no ncx when opening a txt files with Sigil seems to have been around a long while. The subsequent crash when reopening an epub without the ncx seems to be nothing new either. I tested back to version 1.2.0 and Sigil crashes when opening an epub that was saved after opening a txt file. Trying to generate a toc crashes as well.

An ncx file is manifested in such an epub's opf, but the file does not exist in Book Browser or on disk in Sigil's Scratch directory.

**Comment by dougmassay** [comment]
Is there a specific reason we've kept the ability to open text files as epubs around this long? I seem to recall it being talked about a while ago, but can't remember what (if anything) was the reason it was still being supported/included.

**Comment by kevinhendricks** [comment]
I did not even know we could open a txt file.  Was this a holdover from when Sigil had its own file format before we saved things as epubs.

My first thought is to remove support for loading a txt file completely from Sigil.

Then the user could start up with an empty epub and simply copy and paste the text between pre tags in the body of the default Section0001.xhtml if that is what they wanted.

Perhaps an edit plugin to add a txt file to an epub might be better.

I think Doitsu has a edit plugin that will import txt that is in markdown format (.md) following the github extended version of markdown.  So something similar might be useful.

Do we want to support reading in pure text?

**Comment by kevinhendricks** [comment]
Took a look at Importers/ImportTXT and checking current epub version and adding an ncx if epub2, should be easily doable if we decide to keep that feature.  All it does really is split on newlines and wrap each line in a p tag and let mend do the rest to fix it up.

That is something we could do for a future release easily enough.

**Comment by dougmassay** [comment]
> Do we want to support reading in pure text?

I don't. I've never even used it in any practical way. But then I vaguely remember some sort of pushback when its removal was discussed before. It seems to work fine when opened as an epub 3. If it wouldn't take much to generate a dummy ncx when opening a txt as an epub2, I wouldn't be opposed either. But in the long run, someone's got a tough row to hoe in convincing me this feature should stick around long term.

**Comment by kevinhendricks** [comment]
We might want to keep this around only as an option to AddExisting... which would prevent this ncx issue.

**Comment by kevinhendricks** [comment]
For 1.5.x I will fix it until we figure out its longterm fate.

**Comment by dougmassay** [comment]
If we keep it, moving the functionality to AddExisting makes much more sense to me than the current one-text-file-one-epub implementation does.

**Comment by cj0293** [comment]
> 长时间打开“ txt”文件时，Sigil尚未创建ncx文件。我们将研究让Sigil在打开txt文件时自动创建一个虚拟ncx，以便在将来的发行版中创建/保存有效的epub2（并且不会在打开时崩溃）。但这不是优先事项。通过打开txt文件创建epub并不是很流行（或建议使用）。
> 
> 同时，如果您必须打开txt文件并将其另存为epub，请将“创建新的或空的epubs为” Sigil首选项（“编辑”->“首选项”->“常规设置”->“基本”）设置为“版本3”。然后，当您打开一个txt文件时，它将作为Epub3导入/保存，并且在打开时不会崩溃。



> Sigil hasn't created an ncx file when "opening" txt files for a long, long, time. We'll look into having Sigil autocreate a dummy ncx when opening a txt file so that a valid epub2 gets created/saved (and doesn't crash on opening) in a future release. But it's not going to be a priority. Creating epubs by opening txt files isn't all that popular (or recommended).
> 
> In the meantime, if you HAVE to open txt files and save them as epubs, set your "Create New or Empty Epubs As" Sigil preference (Edit->Preferences->General Settings->Basics) to "Version 3". Then when you open a txt file it will import/save as an Epub3 and won't crash when opening.



> Sigil hasn't created an ncx file when "opening" txt files for a long, long, time. We'll look into having Sigil autocreate a dummy ncx when opening a txt file so that a valid epub2 gets created/saved (and doesn't crash on opening) in a future release. But it's not going to be a priority. Creating epubs by opening txt files isn't all that popular (or recommended).
> 
> In the meantime, if you HAVE to open txt files and save them as epubs, set your "Create New or Empty Epubs As" Sigil preference (Edit->Preferences->General Settings->Basics) to "Version 3". Then when you open a txt file it will import/save as an Epub3 and won't crash when opening.



**It's working！！**
Thank you all！！！
Love Forever~~

**Comment by kevinhendricks** [comment]
This has now been fixed in master.
But it might be a good idea to convert this Importer to only work with AddExisting.
Closing as fixed in master.
