### ISSUE TITLE
"Close without Saving" button too small

### ISSUE THREAD

**Issue by algent-al** [Sigil-Ebook/Sigil#579]
Using sigil 1.4.3
![sigil](https://user-images.githubusercontent.com/46356616/102811366-87bf1f80-43c5-11eb-84ba-cfcab7df9e47.png)

Not a big issue, but it's good to have it fixed.

**Comment by dougmassay** [comment]
OS?? Sigil version?

I've just looked at this on Windows, Linux and macOS with the latest version of Sigil and none of them try to fit all of the text "Close without Saving" into the button.

If you're on Linux, I suspect your DE's platform theme might be at fault for modifying the button text.

Either that, or I'm at a different prompt. Please provide the exact steps needed to produce the prompt.

**Comment by algent-al** [comment]
Yes, I am using linux, the Solus Budgie.

**Comment by algent-al** [comment]
Initially I thought it is a theme issue. Tried several themes but no change at the button.

**Comment by kevinhendricks** [comment]
Yes, somehow it is showing the tooltip and not the button string.  Not sure why?

**Comment by dougmassay** [comment]
Then it's as I suspected. Your DE's platform theme is using native dialogs that we can't control. Nowhere in Sigil's source code are we assigning the text "Close without Saving" to any button.

**Comment by dougmassay** [comment]
Nor do we impose any hardcoded button dimensions on any of those generic dialogs. Not that I'm aware of anyway.

**Comment by algent-al** [comment]
Oh, found the problem. Deleted `~/.local/sigil-ebook` folder and launched again.
![sigil-ok](https://user-images.githubusercontent.com/46356616/102815697-0f5c5c80-43cd-11eb-80a0-bd19725ed941.png)

The problem was with`qt_styles.qss` that I used, to try the dark theme.

**Comment by algent-al** [comment]
Sorry for the noise. You may close this issue.

**Comment by dougmassay** [comment]
Easy enough to make that mistake. :) Thanks for reporting back.

Still not sure why Budgie is using our tooltip text for the button text, but... stranger things happen in the Linux world all the time. KDE injected its own keyboard shortcuts into Sigil's menu text, once, that prevented plugins from being launched via the menu. 

In the future, just know that you can rename or delete individual files in the preference folder. No need to delete the entire thing unless you're looking for a complete reset.

**Comment by kevinhendricks** [comment]
For the record, that text was not a tooltip, I spoke incorrectly.   It is an internal Qt string that was generated by this code in MainWindow.cpp:
```
        QMessageBox::StandardButton button_pressed;
        button_pressed = QMessageBox::warning(this,
                                              tr("Sigil"),
                                              tr("The document has been modified.\n"
                                                      "Do you want to save your changes?"),
                                              QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel
                                             );
```

So that must be the string that Qt assigns when you use QMessageBox::Discard.  That explains why a full grep pf the source .h, .cpp. and .ui files did not find the string "Close without Saving".

**Comment by dougmassay** [comment]
My guess is that the underlying OS/theme picks the text for the standard "discard" button text. I see three different messages on three different platforms. But none as lengthy as what the OP is seeing on Budgie. The Qt version may play a small part, but there's precedent for linux platform plugins just injecting what they like in these situations, too. The good news is that we're not limiting the button width, so it shouldn't normally pose a problem.
