### ISSUE TITLE
"Delete unused stylesheet classes" removes valid selectors that match elements in EPUB.

### ISSUE THREAD

**Issue by GSM** [Sigil-Ebook/Sigil#583]
Steps to reproduce:

version: Sigil-1.4.3 (Win64)

**Section0001.html**
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link rel="stylesheet" href="../Styles/styles.css" type="text/css"/>
  <title></title>
</head>

<body class="cover">
  <h1 class="invisible" title="Cover page"></h1>

  <p class="img_centera"><img alt="cover" src="../Images/cover.jpg"/></p>
</body>
</html>
```

**styles.css**
```
.img_centera {
	text-align: center;
	margin: 1em auto;
}
.img_centera img {
	height: 100%;
```
This selector gets removed after using "Delete unused stylesheet classes" tool:
`.img_centera img`
despite properly matching an element - visible in inspector:
![image](https://user-images.githubusercontent.com/12634430/104428324-a0fe5a80-5584-11eb-9394-1b556b903c7b.png)

**Comment by kevinhendricks** [comment]
Yes, this has already been reported on our user forum.  Sigil's current C++ based css parser is inadequate and does not properly handle combinators that start with class names instead of elements.

We are in the process of adding a new cssparser and cssquery selector to try to address these shortcomings.  In the meanwhile when prompted to delete, do not accept deletions that use combinators or better yet use the much smarter cssRemoveUnusedSelectors plugin for Sigil instead:

See  https://www.mobileread.com/forums/showthread.php?t=274926 for the python plugin.

See https://www.mobileread.com/forums/showthread.php?t=336074
for a discussion and updates on getting a better css parser into Sigil.

**Comment by kevinhendricks** [comment]
The use of classes as the start of selectors that have descendant, child, or sibling combinators seems to be just started to be found in the wild.  

So may I ask what software was used to produce this stylesheet?  Did you hand tune it or is this generated by InDesign or something else?  Just curious, as this problem has never been reported before in all the long years of Sigil and both examples that were reported refer to img descendent elements of a .classs.

**Comment by GSM** [comment]
Thank you for your prompt response.
> Yes, this has already been reported on our user forum.

Sorry, I wasn't aware of this.

Since current parser may produce undesirable results, wouldn't it be good to disable this feature (delete unused css) until it gets a better parser?

> The use of classes as the start of selectors that have descendant, child, or sibling combinators seems to be just started to be found in the wild.
> So may I ask what software was used to produce this stylesheet? Did you hand tune it or is this generated by InDesign or something else? Just curious, as this problem has never been reported before in all the long years of Sigil and both examples that were reported refer to img descendent elements of a .classs.

It's a custom css overlay for our e-books.
It's just that after three years of using Sigil I've got curious and used this feature for the first time.

**Comment by kevinhendricks** [comment]
It will be fixed for the next release one way or the other so disabling it is not practical.

I strongly recommend using the cssRemoveUnusedSelectors plugin to replace Sigil's version since it does not have this issue and examines all selectors, not just class based ones.

**Comment by kevinhendricks** [comment]
A Workaround to prevent these errors has been committed to Sigil master just in case adding a CSSParser and query library takes longer than expected.

Closing this as fixed in master.
