### ISSUE TITLE
integrate nvim as code editor

### ISSUE THREAD

**Issue by voyeg3r** [Sigil-Ebook/Sigil#584]
Neovim has an API allowing integrete it as a code editor, it will help many people to code faster on sigil

https://neovim.io/doc/user/api.html

**Comment by eli-schwartz** [comment]
Sigil has a button to open up files in your choice of external editor programs, and the developers previously stated they don't have any interest in one-off integrations with cherry-picked programs.

**Comment by dougmassay** [comment]
No interest on my part, that's for sure. Besides... even the most thorough api imaginable is not going to fully integrate easily (if at all) with Sigil. The hooks necessary for Preview Sync alone would be depressingly daunting. Never mind integration with Sigil's plugin framework, Clips feature, multi-language spellcheck, saved searches (and searches come to think of it).

As Eli mentioned: if you'd prefer to code your epubs with Neovim, feel free to assign it to the external html editor button provided by Sigil (or the Sigil "Open With" feature). That's what they're there for. But Sigil won't be integrating any specific drop-in Code View replacements. It's not at all feasible.

**Comment by kevinhendricks** [comment]
This is a non-starter.  Closing it.
