### ISSUE TITLE
Deprecated embedded Python functions

### ISSUE THREAD

**Issue by dougmassay** [Sigil-Ebook/Sigil#585]
[Starting with Python 3.9.x:](https://docs.python.org/3.9/whatsnew/3.9.html#deprecated)

> The PyEval_InitThreads() and PyEval_ThreadsInitialized() functions are now deprecated and will be removed in Python 3.11. Calling PyEval_InitThreads() now does nothing. The GIL is initialized by Py_Initialize() since Python 3.7.

When (or if) these functions are removed, we need to come up with a plan to either support both pre- and post-Python3.7 (perhaps using defines), or raise the minimum supported Python version to 3.7 when the time comes. The latter will be easier, but would remove support for the 18.04 LTS version of Ubuntu (and it's variants) that we currently maintain support for.

Leaving this issue as a reminder for when the time comes to worry about it.

**Comment by kevinhendricks** [comment]
Closing this as we handle this during the build now with Python.h header info.  So it will only use that call if Sigil is built against Python 3.6 or earlier.
