### ISSUE TITLE
Does SIGIL complies with Antidote SDK's features  ?

### ISSUE THREAD

**Issue by electroremy** [Sigil-Ebook/Sigil#586]
Hi everybody

I use SIGIL to work on a 500 pages french book, on Windows.
I use "Antidote" software that is a good advanced corrector for french and english (https://www.antidote.info/en/antidote-10)
Antidote have an SDK with a COM API for Windows (https://www.antidote.info/en/antidote-10/documentation/developer-tools)
The Antidote SDK documentation explains :
a) Your application must allow access to text using character positions. Example: Antidote may send a request to your application to return the text between characters 1023 and 1725.
b) Your programming infrastructure (language, libraries, etc.) must allow access Antidote's COM interface.
c) You need to be able to implement a COM interface in your application.
d) Antidote and your application must be running simultaneously. The API simply allows them to communicate with each other.

**So I just need to know if SIGIL complies with this features above** :-)

I've some programming skill (c++, c#, VB.NET, ATMEL µC assembly and c++)

Bests regards
[Antidote-API_COM-v2.0.R2-en.pdf](https://github.com/Sigil-Ebook/Sigil/files/5881500/Antidote-API_COM-v2.0.R2-en.pdf)

**Comment by kevinhendricks** [comment]
No.  It does not use or support COM object models as Sigil is explicitly a cross-platform app for Windows, Linux, and macOS.  The COM object model is an old Windows only interface.

Your only hope would be to use Sigil's python plugin interface to get access to the book inside Sigil and then write your own Windows code launched from python to handle this case.

All that said, you might easily just try using this already existing Sigil plugin for French books:

Grammalecte
https://www.mobileread.com/forums/showthread.php?t=319793

**Comment by kevinhendricks** [comment]
And for what's its worth, Sigil should never be used to actually author the content of a book.  Instead use software explicitly desined for that such as Word, or OpenOffice/LibreOffice and use the grammar tools there first.

Then either export that doc or docs to html, or better yet use one of the existing Sigil plugins to import the doc as saved into Sigil.  Then use Sigil to create, clean-up, and check the epub to ready it for distribution.  With the proper use of styles in your wordprocessor, even css styling gets properly imported into Sigil.  Chapters can easily be split into their own files, final proofing done, etc.

**Comment by electroremy** [comment]
Thanks for your response

My book is already made with SIGIL.
It's a big history book on World War II in my region.
The book have a lot of picture and tables.
So .doc to .html or .epub convert is not good, it's the reason why I type the book in SIGIL.
It's harder but I get a good .epub HTML code, and it's fully responsive (I want the book can be readed printed, on a computer screen or on a smartphone screen)

I found that Antidote built-in text editor can handles HTML formatted text with an 'exclusion' setting : it can be used to exclude text between '<' and '>' chars so that all HTML code is ignored.
I just have to copy and past text between SIGIL and Antidote Editor.

Indeed, have a good corrector is a key feature for writting a book.

Bests regards

**Comment by kevinhendricks** [comment]
The Grammalecte plugin is free and integrates right into Sigil's validation window, which allows easy access for fixes.  You might want to give it a try.
