### ISSUE TITLE
Can the translation branches zh and zh_cn be merged?

### ISSUE THREAD

**Issue by lvzhenbo** [Sigil-Ebook/Sigil#600]
I maintain the zh branch, but found that the program uses the zh_cn branch, and found that the two are in Simplified Chinese, so I requested a merger.

**Comment by kevinhendricks** [comment]
I have been only including one of the two into official Sigil releases for that reason.  As far as I know I can not "merge" two transifex languages but I can delete one.

I assume that "zh_CN" would be the one to focus on with "zh" going away?  Is that correct?

If so, please work together with the people doing "zh_CN" translation to take the best of both into "zh_cn" and then let me know once that is complete.  I can then try to delete the "zh" one from the list of languages for Sigil on transifex if everyone in "zh" and "zh_CN" approves.

**Comment by kevinhendricks** [comment]
Even though this is not a Sigil code issue and instead a transifex, one I will leave this open so that you and others can comment about how you would like to join your efforts.

**Comment by kevinhendricks** [comment]
Any contact with the zh_CN translators?  Did they agree to merge your translations?

**Comment by lvzhenbo** [comment]
Since I don’t know the contact information of other translators, I decided to go directly to the translation of zh_cn and give up the translation of zh. This issue can be closed.

**Comment by lvzhenbo** [comment]
I joined the translation at that time because when I was using the software, I found that the simplified Chinese language had not been maintained for a long time. Now that zh_cn has been maintained and the translation is good, I can directly transfer to maintain zh_cn.  The zh branch can be deleted because no one maintains the zh branch anymore.

**Comment by kevinhendricks** [comment]
Will do.  Thanks for letting me know.
