### ISSUE TITLE
Sigil never saved window size and position when "Find & Replace" panel is shown

### ISSUE THREAD

**Issue by sh2sg** [Sigil-Ebook/Sigil#601]
Sigil 1.5.1
macOS Big Sur 11.2.3
(This issue actually existed in all previous versions of Sigil and macOS)

Open Sigil
Adjust window size and position
Cmd+F to bring up "Find & Replace" panel
Quit Sigil
Open Sigil again, it starts with default window size

If "Search & Replace" panel is not shown when quitting Sigil, then next start will remember last window size.

**Comment by dougmassay** [comment]
This is on our radar already. But thank you. We'll leave this issue here as a reminder.

It actually used to be an issue on the other platforms as well. But it seems that it might be limited to macOS now.

**Comment by kevinhendricks** [comment]
Yes, so far, the only way to prevent it under my coding experiments is to save info that Find & Replace was open, close it, do the save of window positions.

 On next open restore window positions, then check if F&R was open, and if so open it.

We may have to change to this for macOS under the hood.

**Comment by dougmassay** [comment]
When this was an issue on other platforms, it was always more of a problem when the Sigil window was maximized. Does that (maximized or not) play a factor in the current macOS situation?

**Comment by kevinhendricks** [comment]
I never maximize it and still see the problem.  One of the issues is that Find and Replace (m_FindReplace) stores its own "visible" or not setting but does not set it until in the FindReplace destructor which is much too late as macOS has already closed other widgets resulting in incorrect resizes at it reacts to other things being cleaned up or hidden by their destructors.  That is why preventing that internal visible flag from being set, and instead handling that manually before and after the restore is better for macOS.

Not sure why that visible or not flag is needed inside the m_FindReplace widget at all given isVisible is always possible to be called.

**Comment by dougmassay** [comment]
Noticed this on line of MainWindow.cpp

`m_FindReplace->setObjectName("FIND_REPLACE_NAME");`

By itself, I don't think this would cause the problem--it's a valid name afterall. But it technically should be:

`m_FindReplace->setObjectName(FIND_REPLACE_NAME);`

The FIND_REPLACE_NAME constant is defined as "findreplace" very early in MainWindow. I know that saveState() should have flushed any remnants of a "findreplace" object name in it long ago, but I mention it as a longshot. I just know that saveState() and restoreState() relies quite heavily on objects having a name set.

**Comment by kevinhendricks** [comment]
Good catch.  I will try that first otherwise I will add an ifdef for osx and manually hide it, save, restore, show it.

**Comment by kevinhendricks** [comment]
The name had no effect but it should still be requested.

For MacOSX, the only way to deal with this is to record the fact that the FR was open, then hiding it, saving state, and doing the reverse to on next open.

I have this working in my local tree.

I will clean it up and push it to master later this week. 
All of these changes will be specific to MacOS since I do not want to mess up what is working on Linux and Windows.

Once I push it to master, I will then close this issue.

Thank you for your bug report.

**Comment by kevinhendricks** [comment]
Closing this as I just pushed the workaround for the Qt bug to master.
