### ISSUE TITLE
Preview window on Windows 7 is flipped upside-down

### ISSUE THREAD

**Issue by SteffenBauer** [Sigil-Ebook/Sigil#602]
I observe a very strange issue. The preview window displays its content flipped upside-down. See here a screenshot:

![sigil_flipped](https://user-images.githubusercontent.com/5973070/112721907-bee22700-8f06-11eb-9a7e-5eb524b4fdb0.png)

**Environment:**
* Windows 7 64-bit, running under virtualbox with Linux Debian as host system
* Sigil 1.5.1, installed from package `Sigil-1.5.1-Windows-x64-Setup.exe` directly downloaded here from the Releases page.

**Steps to reproduce:**
Open _sigil_ bare without file. Sigil starts with default basic epub structure. Ensure that the preview window is shown. Add some text in `Section0001.xhtml`. Text is shown flipped in preview window.

**Additional information**
By resizing the preview window (grabbing the frame border and moving it around to the left / right), the display sometimes flipped back to the correct orientation, but seemingly without any predictable behaviour.

The preview window also shows other elements flipped upside-down, for example cover pictures.

Images are also shown flipped upside-down when opened directly from the `Images` folder and displayed in the main frame window.

This issue happens at all ebooks I opened.

I compiled sigil 1.5.1 in parallel on the Linux Debian host system from source, there everything works fine.

**Comment by dougmassay** [comment]
We've encountered this before. I just can't remember where, or what the solution turned out to be. I'll try to track it down.

**Comment by dougmassay** [comment]
Now I remember. It's the Virtualbox video drivers. Try disabling the 3D acceleration and it should be fine. I've never encountered it anywhere outside of the Virtualbox environment.

A similar Virtualbox bug report involving Calibre: https://forums.virtualbox.org/viewtopic.php?f=2&t=96600

**Comment by dougmassay** [comment]
Also here: https://forums.virtualbox.org/viewtopic.php?f=2&t=92944

**Comment by dougmassay** [comment]
It also could be an issue with underlying host'svideo driver not translating OpenGL properly. It's certainly not an issue with all Linux VirualBox hosts running Sigil on a Windows guest . In fact I develop, test, and package Sigil with a Window 10 guest (used to be Windows 7 until not long ago) running on an Arch Linux VirtualBox host without experiencing the issue.

**Comment by SteffenBauer** [comment]
Just tried disabling 3D acceleration, that indeed solved the issue.

**Comment by kevinhendricks** [comment]
Yes, it appears that in Virtual Box enabling 3D acceleration of guest just direct calls into host opengl software.  There must be a mismatch in that part of the vm.  Compile and run on native Windows is correct.  Compile and run on native Linux is correct, so the bug must be someplace in Virtual Box.  Nothing we can do anything about.  So I will close this.
