### ISSUE TITLE
Sigil doesn't remember zoom in preview window

### ISSUE THREAD

**Issue by leschek** [Sigil-Ebook/Sigil#606]
I use Sigil 1.5.1 (portable version) on 11.6 inch Windows 10 laptop - quite small screen, so I have to increase zoom to see content in code panel and in preview panel. Code panel is working OK, but preview panel doesn't remember zoom I set (usually 150%). Every time I save changes in epub in Sigil the preview panel is reseted to 100%. Interesting is, that zoom value still shows 150%, but text is small, so after saving project I have to click on preview panel, increase zoom to 160% (I have to choose different value than previous value) and after that I can continue my work.

Sigil 1.4.3 didn't remember the zoom setting in preview window too, but only when I opened the epub file. Than I changed it and Sigil remembered it whole time until I closed it.

**Comment by dougmassay** [comment]
Preview Zoom does seem to acting squirrelly (tested the official version--we have no control or input into the portable version of Sigil). It does seem to reset when saving (though the zoom factor still reports being zoomed in or out). I haven't used it in a long time, though, so I'll need o compare the behavior to older versions.

Thanks for the report.

**Comment by kevinhendricks** [comment]
This is now fixed in master.  The fix will appear in the next release.
Thank you for your bug report!

**Comment by dougmassay** [comment]
Wow! That was quick. Thanks! :)

**Comment by leschek** [comment]
Thank you
