### ISSUE TITLE
Metadata editor: alternate-script breaks the dialog

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#613]
When the metadata editor is used for adding `alternate-script` property, it does not add the `xml:lang` attribute, and, if confirmed, the editor no longer opens due to Python error.

When `xml:lang` attribute is added manually, the dialog opens and it is represented by `altlang` pseudoproperty, but there seems to be no way to add it from the editor. (another part of the bug.)

**Comment by kevinhendricks** [comment]
altlang was deprecated even before epub3 spec went final in favour of using xml:lang.  As for alternate-script I will have to see what the epub 3.2 spec states.

**Comment by kevinhendricks** [comment]
Yes, I had forgotten my altlang was just a placeholder to distinguish it from xml:lang used on the parent directly which is always possible.

I will revert my change and put it back for the next release.

Thank you for the bug report!

**Comment by kevinhendricks** [comment]
This is now fixed in Sigil master.

Thanks!

**Comment by Carmina16** [comment]
Now, when the "Alternate language" property is selected, the language list appears. But selecting an item there, the translated language name is put into `xml:lang`, instead of the code.

**Comment by kevinhendricks** [comment]
In the opf?  It should be converted to an xml:lang attribute on a meta tag with property “alternate-script” that refined the original meta tag such as title or creator.

**Comment by kevinhendricks** [comment]
Please take a screen shot of MetaEditor showing exactly what you have input, then hit OK and open the OPF in CodeView and snap a screenshot of the generated metadata and post it here.

That way I can see exactly what is happening.

Thanks.

**Comment by Carmina16** [comment]
``` xml
  <dc:title id="tle">Title</dc:title>
  <meta refines="#tle" property="alternate-script" xml:lang="Немецкий">Title2</meta>
```
![image](https://user-images.githubusercontent.com/16445796/117393471-66973f80-af1e-11eb-823e-1f1b9ae530be.png)
The text was provided by the language selector dialog.

**Comment by kevinhendricks** [comment]
Okay, I understand the problem.  I am obviously missing a call to convert the translated value back to the proper language code.

I will fix that today and let you know when pushed to master.

**Comment by kevinhendricks** [comment]
Just pushed a fix for this to master.  It should have been part of the previous fix for this bug but was missed.

Please let me know if it still causes you any problems.

Thanks for the bug report!

**Comment by Carmina16** [comment]
Yes, it works now. A little detail: is it possible to add that property automatically when the `alternate-script` is added?

**Comment by kevinhendricks** [comment]
Just pushed this to master.
