### ISSUE TITLE
Feature request: seach limited to text (not within html markup)

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#618]
**Scenario:** 
When exporting from InDesign to ePub I tick option to remove forced line breaks. 
This act removes all `-` characters which are auto-generated, but the characters which were added manually during my fie-tune remain in the text. 

**Current state of sigil search:** seaching by `-` parses everything, including css class names.

**TODO:** In the search box there should be an option to "search in the text only". 
Thank you!

**Comment by BeckyDTP** [comment]
Duplicate #220

**Comment by kevinhendricks** [comment]
And restricting a search to things outside of html tags is already doable using regular expressions right now.

Closing this as duplicate.

**Comment by kevinhendricks** [comment]
See these two posts about the issues involved and a way to use regular expressions to do what you want right now:

https://www.mobileread.com/forums/showpost.php?p=4099971&postcount=168
https://www.mobileread.com/forums/showpost.php?p=4099971&postcount=169
