### ISSUE TITLE
Sigil can not use Chinese IME

### ISSUE THREAD

**Issue by mingits** [Sigil-Ebook/Sigil#619]
If I want to typing Chinese charactor in Sigil using Microsoft Pinyin, the cadicate interface could only stay in few seconds, and if I don't choose a word, it will input the pinyin to Sigil instead of a Chinese word. It's very annoying.

**Comment by kevinhendricks** [comment]
No idea what this particular IME is.  That said IMEs do work with Linux.  There is nothing Sigil is doing to prevent this as all keyboard input is controlled by the Qt library, not Sigil itself.  Once focus in on the IME widget it should stay there until you manually move focus away.  Are you moving your mouse or using the tab key when your IME decides to close?  Have you filed a bug report with Qt?  Have you filed a bug report with Microsoft?

**Comment by kevinhendricks** [comment]
From a simple Google search:

https://forum.qt.io/topic/88117/widgets-of-qt-can-not-be-typed-in-chinese-win10-and-qt5-x/4

https://bugreports.qt.io/browse/QTBUG-68520

https://bugreports.qt.io/browse/QTBUG-60334

So this appears to be a Qt issue on Windows, not a Sigil issue.

**Comment by kevinhendricks** [comment]
Closing this issue as this is out of our control, as it is an issue in the Qt libraries not Sigil itself.  Please file a bug report with Qt.  Sigil on Windows and macOS uses Qt version 5.12.9.
