### ISSUE TITLE
Two mimetype files after saving

### ISSUE THREAD

**Issue by wold5** [Sigil-Ebook/Sigil#623]
Saving a particular ePub file with Sigil produced an ePub containing two mimetype files. 
The file was then marked broken by an e-reader. Removing either file solved this.

It turned out the original mimetype file was not stored according to spec (not uncompressed, and not first in the zip archive*). 

Now I don't need this fixed, but adding a warning or prevention can be considered.
This issue occurred with Sigil 1.3.0 and 1.6.0, on a recent Ubuntu variant.

*) see line 144+ in src/Exporters/ExportEPUB.cpp
Required for at least 2.x epubs (see container specs: https://web.archive.org/web/20210228074314/http://idpf.org/epub/201). Absent from 3.x https://www.w3.org/publishing/epub3/epub-ocf.html#sec-zip-container-mime

**Comment by dougmassay** [comment]
The only time I recall Sigil produced epubs having two mimetypes, it turned out to be the fault of third-party plugin (that has since been fixed). Do you use any third-party plugins? If so, are they all the latest versions?

**Comment by wold5** [comment]
No plugins for either version. 1.6.0 was compiled from source, though with -DUSE_SYSTEM_LIBS=1

The file has more errors BTW, as the mimetype and container file are included in the manifest. Removing them before saving doesn't prevent the issue.
`The OPF has an illegal Manifest entry for a file inside the META-INF folder for file "container.xml" - You should edit your OPF file to remove this entry.
` 

PS. I can share the epub privately, as it's a (mainstream) subscription newspaper.

**Comment by dougmassay** [comment]
It was an old version of the EPUBCheck plugin that caused it.

**Comment by kevinhendricks** [comment]
Sigil does not store any mimetype file nor any file that is not manifested when opening an epub.  When saving an epub it writes one mimetype file fully following the spec.  

So the only way for a second mimetype file could be present is via a broken plugin or someone physically manifesting the mimetype file itself.

Which was it?

**Comment by kevinhendricks** [comment]
We cross posted - you loaded a broken epub with a manifested mimetype file.  And deleting the incorrect manifest entry in the opf did not help?  Is that the issue?

**Comment by wold5** [comment]
> We cross posted - you loaded a broken epub with a manifested mimetype file. And deleting the incorrect manifest entry in the opf did not help? Is that the issue?

Yes. The manifest entry actually explains the issue, after further testing. In summary:

If the mimetype opf entry is removed IN Sigil after opening, saving results in duplication. 
If it's removed before* opening in Sigil, there's no duplication when saving.

*) epub was renamed to .zip, and opened using the gnome archive manager. Manifest was edited in the archive.

**Comment by kevinhendricks** [comment]
We could refuse to load any manifested file named "mimetype" that exists at the root level of the epub.  But if they put a file called mimetype anyplace else and properly manifested it, they we should load it just like any other file.  Using that as a filename is not against the spec since it does not explicitly forbid it anyplace I can see.

We just modified the code to skip any manifested files inside META-INF so we can try to do something similar with a root level mimetype file.

But would that help?  
Where in the broken epub, according to the opf manifest was this manifested mimetype located?  Was it at the root level of the epub or someplace else?

**Comment by wold5** [comment]
> Where in the broken epub, according to the opf manifest was this manifested mimetype located? Was it at the root level of the epub or someplace else?

It's located at the root level. The manifest contains the following two problematic entries:

```
	<manifest>
		<item id="mimetype" href="mimetype" media-type="text/plain"/>
		<item id="META-INF-container-xml" href="META-INF/container.xml" media-type="text/plain"/>
                (...)
```

Mimetype was actually stored properly, contrary to my earlier post (don't ask ;) ). I've checked more files out of a 100 or so, and they all have the problem.

```
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
      20  Stored       20   0% 2021-05-06 12:03 2cab616f  mimetype
```

I'll also inform the party in question, though I doubt it will high priority for them (all online...)

**Comment by kevinhendricks** [comment]
Sigil master will not load anything from the META-INF folder anymore so deleting that entry in the OPF will fix that issue.

I will add code to prevent loading any mimetype file at the root level of the epub, so the same deletion of the bad entry in the opf should then work.

So many crap epubs and bad epub processing software out there that do not even try to follow the spec.  Please do inform them that neither the mimetype file nor anything in the META-INF directory should ever be placed in the OPF manifest.  It is against the spec.  They are part of the epub "packaging" not a part of the book.

**Comment by kevinhendricks** [comment]
Just pushed fix to master. Any manifested mimetype at the root will not be loaded.  Produces a load warning.  Closing this.
Thank you for your bug report and helping us track it down.
