### ISSUE TITLE
My feature suggestion #2:  using 'create element' buttons should change an element in cursor within html code

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#624]
Consider this scenario: fixing a scientific book and I have hundreds of places here I need to change <span> element into <b> or <i> depending on the context. Of course I can perform FOUR searches of all `<span>` and then all `</span>`, but I see a place for a small improvement: 

**Now:** The buttons `B`, `I`, 'U` and others work when user selects a text, then the selected text is surrounded by the <b> element. 

**Improvement:** new behavior. if the cursor is within a element code `<b•>` (where the middle-dot is here) pressing the `U` (underline) changes both the opening and closing tag into `<u>`. 

Thank you for considering the change.

**Comment by kevinhendricks** [comment]
You should really read the Sigil User's manual and read up about Clips.

**Comment by kevinhendricks** [comment]
Also, These types of user based things are better suggested and discussed in our MobileRead user forums.  See the link on our github main page and join in.  There are many users willing  to help and answer questions about the best ways to use Sigil to create epubs.
