### ISSUE TITLE
Feature suggestion #3: a dropdown with user-defined html elements.

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#625]
Now in Sigil there is a dropdown with all the `h` (headers) & `p`. It is very convenient. 

My need: I very often use other html elements, such as `blockquote` or `span` , `em`.

Improvement: can we have a dropdown with user-defined html elements? I say `user-defined` as every one of us has different needs, and in my personal view a professional tool's attribute is to let the user to fine-tune a tool to his need and to the task. Sublime Text excels in the idea.

**Comment by kevinhendricks** [comment]
Again this can already be done with Clips
