### ISSUE TITLE
Sigil windows remains maximized on macOS

### ISSUE THREAD

**Issue by Cubik65536** [Sigil-Ebook/Sigil#628]
On macOS, when I open a new Sigil window, that window will remains maximized and could not be resized (it will become maximized again after I resize it). And it's very inconvenient when I need to open another window (for example, the text that I need to input). Is it possible to fix it?

------

Operating System: macOS Big Sur 11.4
Sigil version: 1.16.0 (latest version)

**Comment by kevinhendricks** [comment]
You have a corrupted sigil.ini file.  Try renaming it and then restarting Sigil when not in Full Screen Mode.

**Comment by kevinhendricks** [comment]
Also make sure you have used Sigil's Quit menu and not just closing the window before renaming the sigil.ini file to something else.

Look in ~/Library/Application Support/sigil-ebook/sigil/
to find the sigil.ini file.

**Comment by Cubik65536** [comment]
It is fixed by renaming the `sigin.ini` file! Thanks for the help!

**Comment by kevinhendricks** [comment]
Note to self ...

It seems we have to disable being maximized on exit for macOS as we have done here for fullscreen as macOS seems to be not properly exiting from that state as well.

See MainWindow.cpp

#ifdef Q_OS_MAC
        // macOSX can not be left in fullscreen mode upon exit
        if (isFullScreen()) setWindowState(windowState() & ~Qt::WindowFullScreen);
#endif

**Comment by kevinhendricks** [comment]
Reopened, Just for me to remember to try to prevent the sigil.ini from being corrupted by being left as maximized upon close.

**Comment by kevinhendricks** [comment]
Pushed "fix" to master to prevent this problem in the future.
Thank you for your bug report.
