### ISSUE TITLE
Feature suggestion: automatic population of 'alt' attribute for an IMG inside figure element

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#629]
I am now working with an ebook with large number of graphic images. Filling in the alt attribute is a pain. 
I think a new function in Tools menu might save a lot of time for many of us: 
- Flling in the `alt` in img element with content of the `figcaption` text.
- With or without overwrite (as tickable option).

### Another idea is this: temporary generation of 
Scenario: in many cases the image filename is descriptive, for instance `Mapa_Chiny_Wiosny-i-jesienie-v2.jpg`.

**Now:** When Inserting image, the `alt is filled with the filename with the extension stripped.
 
**Suggested feature:** Inn addition to striping extension, all the `-` and `_` characters can be changed into spaces. The result would obviously look crude, but as long as the filenaming practices are observed, the result in many cases it would be accaptable.

With best.

**Comment by kevinhendricks** [comment]
Much of this is already part of the AccessAide plug-in for Sigil. See the Sigil plug-in index

**Comment by kevinhendricks** [comment]
FWIW, new feature suggestions should really be offered in the Sigil user's forums on Mobileread and not here.  That way other users can comment on its usefulness.  If positive, that would greatly increase its chances of possibly being accepted for a future version of Sigil or being offered in a plugin.

Things like this request are much better suited to plugins as their general usefulness to most epub developers is quite limited.
