### ISSUE TITLE
move from pcre to pcre2 latest version

### ISSUE THREAD

**Issue by kevinhendricks** [Sigil-Ebook/Sigil#630]
Update and rewrite Sigil's SPCRE to use pcre2 (latest released version).  Remember to update 3rdparty/pcre, 3rdparty/cmake, and relevant CMakeLists.txt as well during the migration:

There is no migration guide or docs that I could find but the interface seems to be quite similar with some organizational changes to use context data structures, remove study, etc

To act as examples here are some links to the migration diffs used by other projects when they moved from pcre to pcre2

1. A link to a diff of migration from pcre to pcre2 done for php.

https://github.com/php/php-src/commit/a5bc5aed71f7a15f14f33bb31b8e17bf5f327e2d

2. Another diff migrating from pcre to pcre2

https://github.com/libguestfs/libguestfs/commit/82493579f38f39769861f31403ccfb8e97b41f96

3. Another example showing pcre and pcre2 side by side in R code project grep.c command

https://github.com/wch/r-source/blob/af9a038e277d14b038ef877366652b6e5400c399/src/main/grep.c

**Comment by mapreri** [comment]
Hi,

JFYI, in Debian the PCRE maintainers are now starting to nudge projects to move to pcre2 too.  See https://bugs.debian.org/999963

There doesn't seem to be a schedule on when they plan to force the deprecated library off (also there are still 200+ packages depending on it still), but I reckon it might be best if projects did the move :)

**Comment by kevinhendricks** [comment]
It would be nice if someone from debian or the debian maintainers would nudge the pcre2 project to create an up to date document for "porting your application from pcre to ocre2".

It is not a drop in replacement but nothing really explains what needs to change and why.  They first removed but now added back "study" in their headers but I am not sure if it is just for compatibility sake or if it is needed.

With that many projects to move, some better porting docs would be helpful.

**Comment by mapreri** [comment]
So it looks like study() is not a thing.  The nudging bug is https://github.com/PhilipHazel/pcre2/issues/51

**Comment by kevinhendricks** [comment]
Thank you.  Seems like the pcre2 author is not interested creating such a porting guide.  But based on earlier comments his reluctance has been true from the very start of pcre2.

I have marked a few project diffs that seemed to make the change from pcre to pcre2 effectively but each takes a different approach and so it ends up being confusing.

If at all possible, as other debian projects successfully make this change and you see it, I would appreciate you posting a link here to their commits so that I can learn from their approaches and successes.

I will start to look at this next week.

**Comment by kevinhendricks** [comment]
Note to self, on porting from the pcre2 project ...

[QUOTE]
```
Off the top of my head, the executive summary for is: 

(1) There is no separate study() function; 
(2) Use pcre2_match() instead of pcre_exec(); 
(3) Call pcre2_match_data_create() before calling pcre2_match(); 
(4) Adjust the number and type of various arguments and options bits; 
(5) If using JIT, call pcre2jit_compile() before pcre2_match(). 

For guidance, take a look at pcre2demo.c.
[/QUOTE]
```

**Comment by mapreri** [comment]
> If at all possible, as other debian projects successfully make this change and you see it, I would appreciate you posting a link here to their commits so that I can learn from their approaches and successes.

I'll happily do it, but bear in mind that Debian people can take quite a long time: if you plan to start looking at this matter next week it's likely you'll be quicker than most :)

**Comment by kevinhendricks** [comment]
One last question ...  do most older linux debian system have some version of pcre2 available or will our move to pcre2 force us to drop support for older linux systems (or force them to enable our internal build)?

**Comment by kevinhendricks** [comment]
FWIW ... Printing out and comparing the pcredemo.c vs pcre2demo.c source seems to be the easiest way to see what major changes are needed although those demos ignore the jit part completely.

**Comment by mapreri** [comment]
Debian (and as such Ubuntu) has got pcre2 since 2015 (so Debian stretch/9
and Ubuntu xenial 16.04 LTS) at least, and so did fedora (so f22(?) or f23)
apparently.

From that I think it's fair to say that just dropping pcre completely ought
to be fine, but I suppose that depends on how way back you want to support
distributions 🤷‍♂️

I heard rumors of projects managing to keep support for both, but I haven't
looked at how they did it or at how easy it is.

**Comment by dougmassay** [comment]
I'm fine with that. Distros before 16.04 have such old versions of Sigil in their repos to begin with, that they'll probably never notice that newer versions of Sigil have dropped pcre (1). Our Qt 5.9.4 rock-bottom minimum already makes 16.04 LTS the realistic minimum for package managers to provide the very latest Sigil version.

**Comment by kevinhendricks** [comment]
Great.  I will start work on moving to pcre2 then.  Luckily we wrap all of pcre in our own C++ wrapper so porting just that SPCRE.cpp/.h should suffice for the most part.  I do see that changes in how error messages from pcre are done will require some additional  changes outside of that wrapper but hopefully that will do it.

**Comment by dougmassay** [comment]
Let me know when you have something working. I can test building the bundled 3rd-party libs vs system libs on various Linux systems/versions. For packaging purposes, 16.04 LTS is a fairly hard minimum, but it would nice if we can still support older systems where users might choose to build newer versions of Qt5/Python and custom compile Sigil using the bundled 3rd party-party libs.

**Comment by kevinhendricks** [comment]
Sure thing.  pcre2 uses cmake to build now and supports all 3 platforms out of the box by defaulting to building static libs.  So hopefully we can mesh it right into our 3rdparty builds reasonably easily.

**Comment by kevinhendricks** [comment]
@dougmassay  I will need your help getting the new 3rdparty/pcre2 to build and work on Windows.  I tried to follow the approach from the 3rdparty/cmake/pcre.cmake so it should be close as it sits now.

**Comment by dougmassay** [comment]
I'll take a look tonight. I saw no errors on the Windows CI build, so _something_ happened with the pcre2 build. The Linux CI is set up to use the system libs (in order to save time), so it looks like the old system pcre was used. I'll have to check the logic of the Linux fallback from the bundled 3rd-party libs to the specific system ones being searched for.

**Comment by kevinhendricks** [comment]
CI shows it building successfully on all 3 platforms now after forcing the proper pcre2.cmake to be added.

That said the build logs still show:

Checking for module libpcre16
So some place I am missing changing that to find a libpcre2-16.

**Comment by dougmassay** [comment]
I think we'll need to look here...

https://github.com/Sigil-Ebook/Sigil/blob/1423af847f55beb6467f1d805d7fb516206d3b94/CMakeLists.txt#L96

... to make sure Linux systems look for pcre2 when not using the bundled libs (and the Linux CI _never_ uses the bundled pcre libs).

**Comment by dougmassay** [comment]
Which could still potentially fail on the Linux CI build. I don't know for certain if pcre2 is installed by default on the Linux image/runner I'm using. Easily fixable if it's not, though.

**Comment by kevinhendricks** [comment]
Yes, fixed that and pushed it.  It appears to work just fine.  We seem to be okay build-wise on all platforms according to CI.  Linux finds the system libpcre2-16.

so if it passes run time testing we may be good to go.  Basic regex search seems to work on my macOS build.  I will test more later.

**Comment by kevinhendricks** [comment]
Once we have a chance to test some builds we can then remove the 3rdparty/pcre, 3rdparty/cmake/pcre.cmake, and src/PCRE to help reduce clutter.

**Comment by eli-schwartz** [comment]
Cmake is, in my fairly biased opinion, a disaster at properly handling dependencies. Speaking with my @mesonbuild core maintainer hat on, meson's wrap dependency fallback mechanism is beautifully elegant and will get this right for you. From a project maintainer perspective it's as simple as `pcre2_dep = dependency('libpcre2-8')` no matter how you actually get pcre2, and add an ini file `subprojects/pcre2.wrap` which declared that it provides pcre2. On systems where pcre2 isn't available / detected, it downloads and builds it for you. If you want to enforce acquiring it from the system, configure your build with `--wrap-mode=nofallback`. If you want to enforce building standalone redistributables with private (vendored) copies of all deps, you configure your build with `--wrap-mode=forcefallback`.

Bonus: you don't need to check pcre2 into git ("Showing 418 changed files with 330,335 additions and 24 deletions"!!!!!) and periodically make massive commits to update it, though you can automatically include it in the source tarballs you create with `meson dist` and attach as release artifacts. (So that building the project doesn't require a network connection even when using wraps.)

Linux maintainers love it, because it is a global and standardized mechanism for ensuring that projects build against system libraries. ;)

Alas, switching build systems is annoying...

**Comment by dougmassay** [comment]
Built it at home on my Linux machine at lunchtime to verify that the bundled version builds correctly and everything appears to work just fine. I'll do some more testing later (including building with bundled libs on older systems).

**Comment by kevinhendricks** [comment]
Great!  Looks like we are okay.

**Comment by kevinhendricks** [comment]
Since the required changes are not easily found because of the new folders added, I will attach a diff of primary porting work to go from pcre to pcre2 in case it helps others
[pcre_to_pcre2.patch.zip](https://github.com/Sigil-Ebook/Sigil/files/7584594/pcre_to_pcre2.patch.zip)
.

**Comment by mapreri** [comment]
Thank you for the very fast handling!!

I suddenly found myself hell busy these few days, but I'll make sure to test the patch you just provided by the end of the week :)
(and if you don't disagree, I'll upload it to debian sid so it'll be exposed to users).

**Comment by eli-schwartz** [comment]
> Since the required changes are not easily seen because of the new folders added,

For build systems that make it hard to use toggle between vendored and system code, and which require checking giant folders of external code into git, it's probably a good idea to make one commit adding the vendored code to git with a commit message like "prepare for updating to pcre2 from pcre, by importing pcre2 into git". And then actually "first shot at updating to pcre2 from pcre" in a second, targeted commit.

**Comment by kevinhendricks** [comment]
That was not the reason for the diff, I created a PCRE2 folder as new and kept the PCRE so no diff was generated.

@mapreri 
That patch was meant to show just the porting changes and is not enough by  itself.  You would be better testing with master to get all the changes.

**Comment by kevinhendricks** [comment]
Based on very simple testing, it appears to function.  I am going to "git rm" the pcre and PCRE directories and the pcre.cmake file to unclutter things a bit and then close this.

**Comment by dougmassay** [comment]
I'm headed out of town tomorrow for an extra-long weekend, so I probably won't be able to test much more until I get back. But it does seem to be working on all platforms for very simple searching at least.

**Comment by kevinhendricks** [comment]
Sounds good!  Have a nice extended weekend!

**Comment by dougmassay** [comment]
Will do, Thanks!

Do we foresee any issues with the various UTF/UNICODE defines for pcre2 vs pcre?

For instance: In pcre's cmake file, both PCRE_SUPPORT_UTF and PCRE_SUPPORT_UNICODE_PROPERTIES seem to be set to OFF by default. iin pcre2's cmake files, PCRE_SUPPORT_UNICODE is ON by default. Will that effect any saved searches that use flags like (*UCP)?

**Comment by kevinhendricks** [comment]
Not sure.  The old pcre.cmake did have the following:

```
SET(SUPPORT_PCRE16 1)
SET(SUPPORT_UTF 1)
SET(SUPPORT_UCP 1)
SET(PCRE_SUPPORT_UTF ON)
SET(SUPPORT_JIT 1)
SET(NEWLINE "10") # LF
```

So I am not sure why those would be set to off in any internal build?

**Comment by kevinhendricks** [comment]
I will add the SET(SUPPORT_UCP 1) explicitly to the pcre2.cmake file although it is set in config.h I think.
In PCRE2 all of the UTF defines have been changed to UNICODE defines for the most part.

Here is the pcre2.cmake equivalent section (after my change just now):
```
SET(SUPPORT_PCRE2_16 1)

SET(PCRE2_NEWLINE "LF")
SET(NEWLINE_DEFAULT "2")

SET(PCRE2_SUPPORT_UNICODE ON)
SET(SUPPORT_UNICODE 1)

SET(SUPPORT_UCP 1)

SET(PCRE2_SUPPORT_JIT ON)
SET(SUPPORT_JIT 1)
```

So I think we now have set things to be just like in the old pcre.

**Comment by dougmassay** [comment]
Never mind. I was looking in the pcre2 CMakeLists.txt file (defaults) rather than the pcre.cmake file.

**Comment by kevinhendricks** [comment]
For the record ... the SUPPORT_UCP flag seems to be automatic and is nowhere found in the pcre2-10.39 build sources anyplace based on a grep of the entire source tree on all files.  So my last change was probably unneeded anymore but can not hurt since it is unreferenced.

**Comment by kevinhendricks** [comment]
Okay, the port of Sigil to use pcre2 is basically complete.  Internal builds include the latest pcre2-10.39 source.

Closing this.
