### ISSUE TITLE
Always open 2 Sigil windows....

### ISSUE THREAD

**Issue by sh2sg** [Sigil-Ebook/Sigil#631]
When double clicking *.epub, or using "Open With Sigil", or even opening by Open menu within Sigil... it always opens 2 windows, one is a blank window. this is very annoying.

This issue only happened in v1.6.0

macOS Big Sur 11.4

**Comment by kevinhendricks** [comment]
I can not create this on any macOS machine I have.  Could this be a Big Sur mac bug?  Or the fact that Qt does not yet support Big Sur?  Are you seeing anything similar with any other app?

**Comment by kevinhendricks** [comment]
BTW, Using the open menu in Sigil will and has always opened a new window on macOS.

BTW, what happens if you drag and drop an epub on the Sigil app icon (assuming it is closed)

**Comment by sh2sg** [comment]
If I quit Sigil (cmd+q), then
- double click *.epub, it opens 2 windows
- select "open with Sigil" context menu, it opens 2 windows
- leave Sigil on Docker, drag and drop epub to the icon, it opens 2 windows

If I just close all Sigil windows without quitting it, and repeat the same above, then it opens only 1 window.

**Comment by kevinhendricks** [comment]
Yes, I m seeing the same thing with my builds from master.  The funny thing is the code that handles this in main.cpp has not changed since the last release at all.  My guess it that there are timing differences related to OS and Qt.  I will look into if there is a way to prevent the extra window.

**Comment by kevinhendricks** [comment]
It is a race between when macOS sends out its signal about a file being passed and when Qt processes that singal and generates its own version and delivers it.  This race appears to be system and build dependent as I could not recreate this on my laptop but could on my older desktop.

I have have added code to workaround this race more consistently.  This change has been pushed to master and will appear in the next release.
