### ISSUE TITLE
Edit images externally

### ISSUE THREAD

**Issue by DinizCabreira** [Sigil-Ebook/Sigil#633]
Sometimes when laying out the images in a book it turns out there are some adjustements to be made -- from decreasing size or resolution to minor retouches.

Scribus, for example, handles this with an option to «open image in external editor», and launches whatever program it deems appropiate (GIMP, in my case). It would be very handy to have a similar option in Sigil, and it may not be too hard to implement.

**Comment by DinizCabreira** [comment]
Never mind -- I just realized there is an option already for that (double click on an image, view it, right click → Open With, and then it's configured so you can just right click in the image names in the future). It was a bit obscure, but it work. Request closed.

**Comment by kevinhendricks** [comment]
Perhaps checking the Sigil Users Guide might be a good idea before filing issues.
