### ISSUE TITLE
toc.ncx is easily corrupted

### ISSUE THREAD

**Issue by BobRay** [Sigil-Ebook/Sigil#637]
In my ePub3 book, over time, as the TOCs are re-generated over and over, the sigil_toc_id numbers can be changed to end in larger numbers.  The toc.nxc file contains the old numbers which throws a ton of ePubCheck errors. Renumbering them by hand is a royal pain.

Maybe there's a way to regenerate the toc.ncx from scratch using the same numbers used in nav.xhtml and TOC.xhtml, If so, I couldn't find it. If not, perhaps there should be.

Also, a related issue:

I have separate chapter files that I sometimes do bulk search-and-replace operations on with PhpStorm or a PHP script outside of Sigil. I then delete all chapters in Sigil, then re-import them. This works fine, but if the filenames have changed, the toc.ncx contains the old file names. I haven't found a way to fix this other than to edit dozens of chapter names manually. 

Renaming the files in Sigil might have prevented this, but that would not rename the actual source files (which I used a PHP script to rename to save time).

**Comment by kevinhendricks** [comment]
I am confused...
If you have a nav, then you have an epub3.  The toc.ncx is not rebuilt or updated at all under epub3.  Only the nav is updated.

There are 2 epub3 specific Sigil tools you can use to deal with an ncx in an epub3:

1. You can remove the ncx as it is no longer needed.
2. You can regenerate the ncx from the nav (this will sync the ncx and opf guide to the current state of the nav.

See the Tools menu under epub3 tools.

**Comment by kevinhendricks** [comment]
Again, under epub3 the ncx is NEVER updated for any changes as all changes impact the Nav and the ncx is not needed anymore.  If you want to add or keep a ncx for epub2 only readers, use the menus/tools mentioned above.

**Comment by kevinhendricks** [comment]
Closing this.

**Comment by kevinhendricks** [comment]
These Epub3 specific tools are documented in the Digil Users Guide.

You may want to check that and possibly use the Update Manifest Properties tool as well.

**Comment by kevinhendricks** [comment]
And btw, Sigil can do bulk file renaming using either the built in rename and a filename pattern, or the RERenamer (RegularExpression Renamer).

And Sigil supports python 3 plugins so whatever you are doing in php can probably be done easier with a python3 based plugin right inside Sigil be 
cause there are a number of parsers and tools built right into the plugin interface including our own version of bs4.

 Sigil also supports running saved search groups and importing and exporting them and of couse supports regular expression search and replacement and now has a built in regular expression validator to help.

**Comment by BobRay** [comment]
Thank you! The epub3 tool did the trick. The outdated toc.ncx was causing the ePub to fail validation.
