### ISSUE TITLE
Sigil does not start after compilation on Linux (Debian 11)

### ISSUE THREAD

**Issue by mknepper** [Sigil-Ebook/Sigil#639]
When I attempt to launch Sigil after compiling, I get this error:

Embedded Python Error
`Module Error: xmlprocessor repairXML`

Close the error message, this happens
`error in xmlprocessor repairXML: -2`

This is the next error I get:
`Module Error: opf_newparser parseopf`

From the terminal:
```
setext parseropf error -2 traceback Module Error: opf_newparser parseopf
Segmentation Fault
```

I installed all the dependencies. It compiled fine. Any particular reason this is happening?

Operating system: Debian 11
Kernel: 5.10.0-8-amd64
Python version: 3.9.2

**Comment by dougmassay** [comment]
After compiling, or after compiling AND installing? Sigil isn't likely to run from the build folder. Also... you say you've installed all dependencies, but does that include the python module requirements? Six, lxml, css-parser, and dulwich are hard requirements for running Sigil. And if Sigil is not fully installed, the necessary python3lib scripts won't be available to the embedded interpreter.

**Comment by mknepper** [comment]
I'm not sure what happened but I ran through the process again and now it works. I'm confused as to why it's working now and wasn't before. Maybe an issue with something I did. I'm going to close this.

**Comment by dougmassay** [comment]
Feel free to reopen if it manifests again.

**Comment by mapreri** [comment]
Incidentally, I just uploaded sigil 1.7.0 to bullseye-backports, so you should be able to install it from there once it's processed by the archive admins (normally within 1 week)
