### ISSUE TITLE
Crash on "split at markers"

### ISSUE THREAD

**Issue by luisparravicini** [Sigil-Ebook/Sigil#645]
**Problem**: Sigil crashes when using _Edit / Split at markers_.
**env**: Sigil 1.7.0 on macOS 10.15.7

**How to reproduce it**: Use [crash-on-split.epub.zip](https://github.com/Sigil-Ebook/Sigil/files/7381228/crash-on-split.epub.zip) or, create a new epub and on the only html file, make sure the body is empty: `<body></body>`

It doesn't matter if there's a split marker or not, the empty body causes the crash.
If some content is added to the body tag, it doesn't crash (even adding only some whitespace).

**Comment by kevinhendricks** [comment]
Very similar.  The XHtmlDoc routine that handles this should never return an empty list of sections for any reason. I think I have a fix and will push it to master after some testing.

**Comment by dougmassay** [comment]
After looking at the code, I figured it had to be gumbo that was adding the newline. Thanks for the fix!
