### ISSUE TITLE
regular expression can not match Chinese characters

### ISSUE THREAD

**Issue by andyjustgo** [Sigil-Ebook/Sigil#655]
Hope that the regular expression can match Chinese characters, such as [\u4e00-\u9fa5]

**Comment by kevinhendricks** [comment]
Yes, it already can.  Just use the proper (*UCP) to start your pattern just like all Perl Regular Expression engines.

**Comment by kevinhendricks** [comment]
Reopening in case I am misunderstanding the issue.

**Comment by dougmassay** [comment]
And if you need to use an escape sequence to match a specific unicode codepoint (rather than searching for the atcual unicode charaters using *UCP), PCRE uses the \x{FFFF} syntax to do so, not the  \uFFFF syntax.

**Comment by kevinhendricks** [comment]
If Linux, make sure your system pcre lib has been compiled with both unicode and ucp support.  This is always true in the Windows and macOS builds of Sigil using its internal pcre library.

**Comment by dougmassay** [comment]
For what it's worth: `[\x{4e00}-\x{9fa5}]` works just fine to detect all Chinese character for me in Sigil. As does the much simplified `\p{Han}` I'm assuming that's what you want to do with the [\u4e00-\u9fa5] class?

**Comment by dougmassay** [comment]
I'm going to assume this was just a case of not knowing the correct syntax for PCRE. Feel free to re-open this if the correct syntax doesn't work for you.
