### ISSUE TITLE
Try to support both Qt6 and Qt5 in the same Sigil codebase

### ISSUE THREAD

**Issue by kevinhendricks** [Sigil-Ebook/Sigil#657]
Try to support both Qt6 and Qt5 in the same Sigil codebase:

An issue to log how we slowly go about supporting both Qt5 and Qt6 in the same Sigil code base:

1. Deal with the enum namespace changes similarly to the following:
    - Replace all uses of QString::KeepEmptyParts with QT_ENUM_KEEPEMPTYPARTS
    - Replace all uses of QString::SkipEmptyParts with QT_ENUM_SKIPEMPTYPARTS
    - Then either in its own qt_5_6_compat.h file or directly in the impacted files we add the following:

```
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    #define QT_ENUM_SKIPEMPTYPARTS Qt::SkipEmptyParts
    #define QT_ENUM_KEEPEMPTYPARTS Qt::KeepEmptyParts
#else
    #define QT_ENUM_SKIPEMPTYPARTS QString::SkipEmptyParts
    #define QT_ENUM_KEEPEMPTYPARTS QString::KeepEmptyParts
#endif
```

This change would need to be made in the following files:

Dialogs/TreeModel.cpp
Exporters/NCXWriter.cpp
MainUI/TOCModel.cpp
MainUI/TableOfContents.cpp
Misc/Plugin.cpp
Misc/Utility.cpp
MiscEditors/ClipEditorModel.cpp
MiscEditors/IndexEntries.cpp
MiscEditors/SearchEditorModel.cpp
Parsers/GumboInterface.cpp
Parsers/HTMLStyleInfo.cpp
ResourceObjects/NavProcessor.cpp
ResourceObjects/OPFResource.cpp
ViewEditors/CodeViewEditor.cpp
ViewEditors/ViewPreview.cpp

2. Use the compare() method to replace comparisons to ascii string literals to deal with the QXmlStreamReader change to return QStringView versus a QStringRef as it does under Qt 5.X as QStringView and QStringRef both support the exact same compare method.

This would need to be handled in the following files:

BookManipulation/XhtmlDoc.cpp
Dialogs/PluginRunner.cpp
Importers/ImportEPUB.cpp
MainUI/TOCModel.cpp
Misc/PluginDB.cpp
ViewEditors/CodeViewEditor.cpp
main.cpp

**Comment by kevinhendricks** [comment]
For item 2, we would need to make changes similar to the following:

```
diff --git a/src/Misc/PluginDB.cpp b/src/Misc/PluginDB.cpp
index 2e376a20..89cee165 100644
--- a/src/Misc/PluginDB.cpp
+++ b/src/Misc/PluginDB.cpp
@@ -289,23 +289,23 @@ Plugin *PluginDB::load_plugin(const QString &name)
     while (!reader.atEnd()) {
         reader.readNext();
         if (reader.isStartElement()) {
-            if (reader.name() == "name") {
+            if (reader.name().compare(QLatin1String("name")) == 0) {
                 plugin->set_name(reader.readElementText());
-            } else if (reader.name() == "author") {
+            } else if (reader.name().compare(QLatin1String("author")) == 0) {
                 plugin->set_author(reader.readElementText());
-            } else if (reader.name() == "description") {
+            } else if (reader.name().compare(QLatin1String("description")) == 0) {
                 plugin->set_description(reader.readElementText());
-            } else if (reader.name() == "type") {
+            } else if (reader.name().compare(QLatin1String("type")) == 0) {
                 plugin->set_type(reader.readElementText());
-            } else if (reader.name() == "engine") {
+            } else if (reader.name().compare(QLatin1String("engine")) == 0) {
                 plugin->set_engine(reader.readElementText());
-            } else if (reader.name() == "version") {
+            } else if (reader.name().compare(QLatin1String("version")) == 0) {
                 plugin->set_version(reader.readElementText());
-            } else if (reader.name() == "oslist") {
+            } else if (reader.name().compare(QLatin1String("oslist")) == 0) {
                 plugin->set_oslist(reader.readElementText());
-            } else if (reader.name() == "autostart") {
+            } else if (reader.name().compare(QLatin1String("autostart")) == 0) {
                 plugin->set_autostart(reader.readElementText());
-            } else if (reader.name() == "autoclose") {
+            } else if (reader.name().compare(QLatin1String("autoclose")) == 0) {
                 plugin->set_autoclose(reader.readElementText());
             }
         }
```

**Comment by kevinhendricks** [comment]
That compiles and works just fine under Qt 5.X and should work with the QStringView return types in Qt6.X as well.

**Comment by kevinhendricks** [comment]
Note QStringView was not introduced until Qt 5.10.  It replaces QStringRef which was removed in Qt 6 but still exists in the Qt6 5-compatibility library.

If we rewrite the code that previously used QStringRef to use QStringView we will lose support for Qt 5.9.4 as the minimum and instead require Qt 5.10 as the new minimum.  We will need to see how many distributions this would impact.

**Comment by dougmassay** [comment]
> We will need to see how many distributions this would impact.

Ubuntu 18.04 LTS comes with Qt5.9.5 in its repos. But considering that latest Sigil in 18.04's repos is 0.9.9, I don't think making Qt5.10 the minimum for Sigil 1.9 should really pose too many problems for Sigil package maintainers. And those folks who roll their own Sigil can always install a newer version of Qt if they want newer versions of Sigil.

**Comment by kevinhendricks** [comment]
Great!  Then changing all uses of QStringRef to QStringView makes sense.

**Comment by kevinhendricks** [comment]
3. Deal with the change in the order of arguments to QtConcurrent::run using ifdefs ala this change:

[CODE]
diff --git a/src/Dialogs/CPCompare.cpp b/src/Dialogs/CPCompare.cpp
index 38fd61e3..7dd0f320 100644
--- a/src/Dialogs/CPCompare.cpp
+++ b/src/Dialogs/CPCompare.cpp
@@ -179,7 +179,7 @@ void CPCompare::handle_mod_request()
 
             QApplication::setOverrideCursor(Qt::WaitCursor);
             QFuture<QList<DiffRecord::DiffRec>> bfuture =
-                QtConcurrent::run(&pr, &PythonRoutines::GenerateParsedNDiffInPython, leftpath, rightpath);
+                QtConcurrent::run(&PythonRoutines::GenerateParsedNDiffInPython, &pr, leftpath, rightpath);
             bfuture.waitForFinished();
             QList<DiffRecord::DiffRec> diffinfo = bfuture.result();
             QApplication::restoreOverrideCursor();
[/CODE]

**Comment by dougmassay** [comment]
If we can get a unified codebase, the cmake changes should pose no problem. I could probably do something unified there, too (with qt versionless modules), but I don't think it's worth it, really. I'm think of two different cmake files that can be included based on a configuration parameter (defaulting to Qt5 for now).

**Comment by kevinhendricks** [comment]
4. Deal with Qt 5.15 deprecation of toSet()  using ifdefs.
``` 
-    return all_words.toSet();  // Qt 5.15:  QSet<QString>(all_words.begin(), all_words.end());
+    return QSet<QString>(all_words.begin(), all_words.end()); // pre-Qt 5.15: all_words.toSet();   
```

**Comment by kevinhendricks** [comment]
5. Deal with QtWebEngine default settings change with ifdefs around these changes:

```
@@ -196,7 +197,9 @@ PreferencesWidget::ResultActions AppearanceWidget::saveSettings()
     settings.setSpecialCharacterAppearance(specialCharacterAppearance);
     settings.setMainMenuIconSize(double(ui.iconSizeSlider->value())/10);
     // PV settings can be globally changed and will take effect immediately
-    QWebEngineSettings *web_settings = QWebEngineSettings::defaultSettings();
+    // Qt6.2 removes QWebEngineSettings::defaultSettings() altogether
+    // QWebEngineSettings *web_settings = QWebEngineSettings::defaultSettings();
+    QWebEngineSettings *web_settings = QWebEngineProfile::defaultProfile()->settings();
     web_settings->setFontSize(QWebEngineSettings::DefaultFontSize,   PVAppearance.font_size);
     web_settings->setFontFamily(QWebEngineSettings::StandardFont,    PVAppearance.font_family_standard);
     web_settings->setFontFamily(QWebEngineSettings::SerifFont,       PVAppearance.font_family_serif);
```

**Comment by kevinhendricks** [comment]
6. Deal with QTextStream removal of setCodec and replace ifneeded with new setEncoding via ifdefs
7.

**Comment by kevinhendricks** [comment]
7. Deal with many other individual quirks via ifdefs as identified in @dougmassay qt6.patch for Linux
[qt6.zip](https://github.com/Sigil-Ebook/Sigil/files/7697923/qt6.zip)

**Comment by kevinhendricks** [comment]
Yes, agreed, separate cmake files makes the most sense.

I am going to start working on items in this list little by little in master and once in place we can try Qt6 builds to see if we have done enough.

**Comment by dougmassay** [comment]
Sounds good. I'll update the CI on Linux to use Qt5.10.x when I get a moment. Otherwise that will start failing when you change to QStringView. So don't be caught off guard.

**Comment by kevinhendricks** [comment]
No 1 - using defines to handle qt6 enum changes has now been pushed to master

**Comment by kevinhendricks** [comment]
No 2 - using compare() and QLatin1String to handle QXmlStreamReader differences in Qt6 has now been pushed to master

**Comment by kevinhendricks** [comment]
No.4 deal with removal to Qlist toSet() in Qt 6 has now been pushed to master.

**Comment by dougmassay** [comment]
Bumped the Linux CI Qt minimum to 5.10.0

**Comment by dougmassay** [comment]
Also changed the Linux minimum to 5.10 in Sigil's CMakeLists.txt file.

**Comment by kevinhendricks** [comment]
Thanks!  Will start the replacement of QStringRef with QStringView tomorrow.

Also shooting for the QtConcurrent::run  arg order changes tomorrow as well. 

That should just leave a bunch of one-off fixes and include changes as QStringList is now QList / template based and so using "class QStringList" in a header will not be enough anymore.  Your patch caught those as well.

**Comment by dougmassay** [comment]
No problem. I also pushed the cmake changes to allow buildng with either Qt5 or Qt6. Everything works the same as always right now (Qt5). You must add -DUSE_QT6=1 to the configure command to build with Qt6. Things should configure OK with Qt6, but the actual build will, of course, fail miserably for now. But that's to be expected.

src/CMakeLists5.txt and src/CMakeLists6.txt are the two main files used.

**Comment by dougmassay** [comment]
There's also few includes that will probably need to be tweaked in order to handle a few things that have downright moved in Qt6. I think there's a few examples of those in my patch as well (though I can't seem to find the original documentation for those changes right now). Some things moved from QtWidgets to QtGui, I think.

We'll also need to ifdef the highdpi stuff since that's all handled internally for all platforms in Qt6, but that should be no big deal (except for disabling the highdpi preferences in Sigil's gui whenever Qt6 is used).

**Comment by kevinhendricks** [comment]
Yes, I see they moved QtWebEngine header pieces around, QStringRef header pieces around and it looks like QAction has been moved out of Widgets.

I will examine your patch to try to  catch the bulk of these changes and make sure it gets into the tree.

**Comment by dougmassay** [comment]
On the cmake front: I'd like to try to move all the source-code group definition stuff to the shared src/CMakeLists.txt file if possible. That stuff should be Qt-agnostic, and I'd like to eliminate the need to remember to update source-code file changes in two locations.

**Comment by kevinhendricks** [comment]
Sounds like an excellent idea!

**Comment by kevinhendricks** [comment]
Dealt with the headers that were moved in Qt6 including QAction, QtWebEngine pieces, and the forward definition of class QStringList in headers that needed to change in Qt6 as well.

This should handle the majority of the header fixes but I am sure I may have missed a few.

**Comment by dougmassay** [comment]
There's an odd windows linking error happening with the last commit (QWebEngine). Odd in that it references a file that seems to be untouched by that particular commit (CharactersInHTMLFilesWidget.cpp.obj).

**Comment by kevinhendricks** [comment]
Yes, very odd as I have not touched that file from the previous commit that passed.
Would you retry the CI build as my "hour" of computer time this morning has been used up (according to my wife!).

**Comment by kevinhendricks** [comment]
Okay, I double checked and nothing QWebEngine related is going on in that file.  And none of the changes I made has even changed any of the headers included by that Reports file.

I then looked in its UI file and it does not use anything from QtWebEngine at all either.  So I really have no idea how my last change caused the failure when the previous change it was fine.

Perhaps this is all just a glitch?

Could it be a missing library in one of the changed CMakeLists files for Windows?

I am stumped.

**Comment by kevinhendricks** [comment]
That file is missing #include <QString> for some reason.  I will add it back in now (I just have to sneak to my laptop).

**Comment by dougmassay** [comment]
Not sure if that's it or not (still building), but if it's not... it seems as if it's looking for a FindText(class QString) function in CharactersInHTMLFilesWidget.cpp and there's not one there. There's one defined in CharactersInHTMLFilesWidget.h (as a signal), but it's not in the .cpp file, but I've no idea why it would suddenly start failing.

**Comment by dougmassay** [comment]
Either that, or the latest include commits have reordered some things on Windows where a different FindText() is trying to be linked to the one that appears in CharactersInHTMLFilesWidget.h (but not in CharactersInHTMLFilesWidget.cpp) instead of the one it used to link to. MSVC's link time code generation can be stupid that way sometimes.

**Comment by kevinhendricks** [comment]
I will try renaming that signal in case of a name clash to see if the error changes.

**Comment by kevinhendricks** [comment]
It was some sort of name clash.  Renaming it did the trick.

No.3 - deal with QtConcurrent::run argument order changes has now been pushed to master as well as additional header move changes for QtWebEngine and QShortcut

**Comment by kevinhendricks** [comment]
That still leaves:
-  No.5 (default Preview settings)
- No. 6 (changes due to changes in QTextStream and deprecation of QTextCodec
- Changes to DesktopServices and how to get screen geometry

**Comment by dougmassay** [comment]
This a site I used a lot when working on the Qt6.patch originally. Lot's of good tips and workarounds.

https://embeddeduse.com/2021/01/17/migrating-a-harvester-hmi-from-qt-5-12-to-qt-6-0/

QTextCodec is still available via the Core5Compat library if it makes keeping a polyglot codebase any easier. Otherwise, ifdefing and using the new QStringConverter in the Qt6 scenario is also doable, I think.

**Comment by kevinhendricks** [comment]
No idea about missing a QXmlStreamReader header.  I will fix it.

We are going to have to use QTextCodec as we need it to support the zip lib IBM special codec we wrote and for converting.  And for supporting some spellcheck dictionaries as well.

Their QStringConverter supports only a *very* few codecs.  It is a waste.  Those guys are living in a dream world where everything is already utf-8.  What a joke!

See https://phabricator.kde.org/T14154

And check out the Qt bug reports from people about removing all the codecs support!

Before Qt5 compat goes away I plan to fork the QTextCodec code into Sigil.

It is much easier than adding dependencies to ICU and writing our own code.

**Comment by kevinhendricks** [comment]
So we will need to use QTextCodec in Q5 and if we do that we can keep the QStringRef and not use QStringView and then add back support for Qt 5.9.4 if you like or stick with Qt 5.10.0 minimum.

**Comment by dougmassay** [comment]
I'm fine with leaving things at 5.10.0 from now on. I'm going to do a little work on the highdpi stuff tonight. Maybe some cmake tweaks as well.

We're still talking about moving to Qt5.15 for now though, right. Just getting a good head start on Qt6 for when the time comes?

**Comment by kevinhendricks** [comment]
Yes our next target is Qt 5.15.x but it may be easier to get macOS arm64 support inQt 6.3 instead of all the Qt 5.15 patches that seem to be needed.

**Comment by kevinhendricks** [comment]
Agreed.
So my revised plan is to stick with QStringRef and not port to QStringView and to stick with QTextCodec because there is no suitable replacement.

So I just needed to update the headers for both which I just pushed to master with other minor fixes.

So that just leaves a few one-offs left:
- screen geometry changes by adding ifdefs to your patch changes
- default utf-8 changes in QTextStream via your ifdefs which I can lift right out of your qt6.patch
- some misc minor fixes (I need to go over your qt6.patch one more time to see what if anything I missed)

**Comment by dougmassay** [comment]
Double-check my screen geometry changes. I was in a bit over my head with those, and once it compiled, I moved on.

**Comment by kevinhendricks** [comment]
Will do.  But no worries.  They are mainly collected for Debug output.  I do not think we actually use them anyplace serious.

**Comment by dougmassay** [comment]
Also noted this change from my original patch that I'm not sure was explicitly mentioned:

     // assign basic shortcuts
-    delButton->     setShortcut(QKeySequence(Qt::ControlModifier + Qt::ShiftModifier + Qt::Key_Delete));
+    delButton->     setShortcut(QKeySequence(Qt::ControlModifier | Qt::ShiftModifier | Qt::Key_Delete));

**Comment by kevinhendricks** [comment]
Great! Both are on my to-do list for today.

**Comment by kevinhendricks** [comment]
Okay pushed your changes to handle the above, screen geometry, default settings, and loss of setCodec all to master.
With all of your build changes to support cmake for Qt5 and Qt6 and based on your qt6.patch, I think we should be able build with Qt6 (barring any typos or thinkos).

When you get a free moment, would you please try another Qt6 build on your linux box.  I have my fingers crossed!
Your qt6.patch was simply great work!  Nicely done!

**Comment by dougmassay** [comment]
Will do! Maybe at lunchtime, but definitely after work.

**Comment by dougmassay** [comment]
It got to 97% before bombing out. I thought for sure it was going to make it!

I'm on my lunch break so I don't really have time to investigate much so I'm attaching the last portion of the compile log (after the errors started).

[compile_errors.txt](https://github.com/Sigil-Ebook/Sigil/files/7713634/compile_errors.txt)

A quick glance looks like it might be standards beyond C++11 (C++17 required for Qt6) that are causing issues.

**Comment by kevinhendricks** [comment]
Hi Doug,
It appears all to be minor.  Some missing casts, a missedcall to the removed desktop(), wrong return types, and something is up with the QtConcurrent::run argument reorder because I think those routines are declared static. 

I am tied up this afternoon, but should be able to take a shot at these later.

Thanks!

Kevin

**Comment by dougmassay** [comment]
I pushed one easy fix (using your next to last commit), but there still seemed to be some deep, dark QFuture stuff remaining. I've attached the compile errors.

I noticed that the parameter order was not changed in the QFuture.run call in MainWindow.cpp 2420 and 2423. But changing the order (as we have been doing) didn't bring any joy either. Just a different error.

[compile_errors.txt](https://github.com/Sigil-Ebook/Sigil/files/7714964/compile_errors.txt)

**Comment by dougmassay** [comment]
Actually... flipping the usual parameters and making them both QFuture<QString> seemed to let me move past that error onto a different one

**Comment by dougmassay** [comment]
I'm down to a linking error (for now anyway).

/usr/bin/ld: CMakeFiles/sigil.dir/PCRE2/SPCRE.cpp.o: undefined reference to symbol 'pcre2_match_context_create_16'
/usr/bin/ld: /usr/lib/libpcre2-16.so.0: error adding symbols: DSO missing from command line

Not sure why it's trying to link to the system PCRE2. I certainly didn't configure it that way. (???)

**Comment by dougmassay** [comment]
Might just be some cmake dumb shit. I have high hopes for a build!

**Comment by dougmassay** [comment]
I've no idea what the extra stdout content is (or why darkmode isn't working), but .....

![Screenshot from 2021-12-14 17-29-40](https://user-images.githubusercontent.com/9285982/146089679-5f79bd75-c569-439a-b6c9-ca31e26885ff.png)


[cmd_output.txt](https://github.com/Sigil-Ebook/Sigil/files/7715133/cmd_output.txt)

Basic functionality seems to be there, but I've not done much. Yay!

I fear there's some QSignalMapper work to be done yet, but I'm still happy.

**Comment by dougmassay** [comment]
Looks like starting with with Qt5.15, there is no "mapped" signal any more. Qt5.14 has mappedInt(), mappedObject(), mappedString(), and mappedWidget(). Qt6 seems to drop mappedWidget().

Hopefully those will be able to be used to accommodate our needs?

**Comment by kevinhendricks** [comment]
Yes, I remember something about QSignalMapper or related changes.  I will read up.

**Comment by dougmassay** [comment]
At first glance, it looks like it _should_ be a fairly easy change. We seem to only be using mapped for int and string.

I forgot the old-style connection syntax we use doesn't reveal problems at compile time.

**Comment by kevinhendricks** [comment]
Sounds good.  Feel free to push whatever changes are needed.

**Comment by dougmassay** [comment]
My last commit seemed to take care of most of the signal warnings/errors. Leaving only these three vague entries:

Warning: QObject::connect: No such signal QComboBox::activated(const QString &)
Warning: QObject::connect:  (sender name:   'Dictionaries')
Warning: QObject::connect:  (receiver name: 'SpellcheckEditor')

Any ideas? I see the connection from ui.Dictionaries to the activated() signal in Dialogs/SpellcheckEditor, but I can't find anything about any changes in Qt6 regarding it.

**Comment by dougmassay** [comment]
Looks like QComboBox::activated(const QString &text) was dropped in Qt5.15. Only QComboBox::activated()

**Comment by kevinhendricks** [comment]
It looks like they added a  new signal in Qt 5.14 to replace it, QComboBox textActivated(const QString) so we should be able to ifdef that one away.

**Comment by dougmassay** [comment]
Ahhhh, I missed that signal. That would be the last issue (on Linux anyway) if it works. I'll check it out in the morning. Thanks!

**Comment by kevinhendricks** [comment]
I have not made that change in my tree as I am away from my laptop.
Hopefully, that will do the trick.

**Comment by dougmassay** [comment]
That seemed to have taken care of that runtime error, thanks!

After experimenting further, I've come across another. Arch's qt6 seems to be in some sort of debug mode (either that, or qt6 is just more chatty in general). It's a QProcess signal used in PluginRunner named "error" (line 1065). Funny thing is, I can't find a signal for QProcess named "error" in any of the older Qt5's either. Perhaps this one has been flying under the radar for a long time? Anyway, QProcess has had a signal named errorOccurred() since Qt5.6 that seems to fit the bill (based on parameter type and description). Thoughts?

**Comment by kevinhendricks** [comment]
Yes, that is interesting.  It has probably be broken since the very beginning.
Yes let's go with errorOccurred.  It can't be any worse.

Nice Detective work!

Kevin

**Comment by dougmassay** [comment]
I pushed that change. Just so you know -- and I know we don't have to fix this all immediately -- I'm getting different PCRE2 behavior with a Qt6 Sigil build than I am with a Qt5 Sigil build. So there may be something in our search editor code that's not working as it should with Qt6. Debug output indicates it mat have something to do with getting the current (HTML) resource. I know you were looking at something to do with PCRE2 already, so feel free to wait until you've made those changes.

`Debug:  huh .. HTMLResource(0x7f4934020c30)`

**Comment by kevinhendricks** [comment]
Yes, I wrote that.  My recent changes to  search to use wrap only when searching the current file and instead adding a search restart button to let the user control wrapping across multiple sets of files is messed up.

I am trying to deal with that now.

**Comment by dougmassay** [comment]
I'll wait to revisit, then.

I'm pretty sure the two builds I was seeing different search behavior with were built from the same codebase, but I could be wrong.

**Comment by kevinhendricks** [comment]
Definitely, pcre2 as used in our PCRECache is very broken right now.  Not sure why.  Tries same search test in Sigil 1.6 that uses the older pcre and it works as expected.

So my port to pcre2 is broken somehow.  Tried disabling the jit and it did not help.

**Comment by kevinhendricks** [comment]
Okay found and fixed two problems related to search:

- in SearchOperations we made a reference to a QString value that was a returned value whose underlying value changes due
   to how text resources use an internal m_cache value.

-  until a call to pcre2_match_16 happens even through m_matchdata exists and the ovector count is known, 
      the pcre2_get_ovector_pointer returns a pointer to an invalid ovector.

This was why once a valid search was found everything then started to work.

Both have now been fixed in master.

**Comment by dougmassay** [comment]
Heading home before long. Should be able to check it out soon.

**Comment by dougmassay** [comment]
This definitely corrected the weirdness I was experiencing with my Qt6 build. Thanks! Now I've got some serious thinking to do about how to keep PyQt plugins working with either version of Sigil without some drastic re-writes. I know we're not going to Qt6 yet, but I need a plan. I'm seriously considering a semi-nuclear option.

**Comment by kevinhendricks** [comment]
Hmm ... I did not think of that.  Wouldn't a try handle most of it or am I missing something.

**Comment by kevinhendricks** [comment]
Should we close this and open new issues for the problems as we run into it.

**Comment by dougmassay** [comment]
Makes sense to me!
