### ISSUE TITLE
Used Characters Report doesn't show non-BMP characters

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#658]
Characters outside of BMP are listed as their low surrogates (and the search function doesn't work).

**Comment by kevinhendricks** [comment]
Yes, Checked the code and there is no way a QChar map can store a surrogate pair.  I will need to change it to an unsigned int map, explicitly look for surrogates, and the convert back to a QString.

I will look into that later as work towards porting to Qt6 is my focus now.
Please post a very simple test case that I can use as well as a screen cap of what the correct output should look like.

**Comment by Carmina16** [comment]
[Section0001.xhtml.gz](https://github.com/Sigil-Ebook/Sigil/files/7712551/Section0001.xhtml.gz)

**Comment by kevinhendricks** [comment]
Okay, please try what I just pushed to master to fix this.  I tried with your test case and saw the ipad like image 
I am not sure what you mean by the "search function doesn't work"?  Are you talking about the Filter?

**Comment by kevinhendricks** [comment]
Using Find&Replace to look for that non-BMP char and the change to PCRE2 from PCRE seems to have broken search for non-bmp chars completely.  I will start to look into that.

**Comment by kevinhendricks** [comment]
Do not bother to build as my fix is not working correctly.

**Comment by kevinhendricks** [comment]
This is now fixed in master. Youmay have to modify your system font yo see the actual character.
