### ISSUE TITLE
Support existing PyQt plugins after transitioning to Qt6

### ISSUE THREAD

**Issue by dougmassay** [Sigil-Ebook/Sigil#659]
Leaving this here for conversation. We need a way to make sure that existing plugins using pyqt can still work with Sigil-Qt5 and Sigil-Qt6 without drastic measures and messes.

There's not that many PyQt plugins (indexed on MobileRead anyway) so a lot of work for a few plugins seems counter-intuitive.

My gut is to make a clean break and go to PySide6 (without bundling PyQt5) when Sigil makes the move to Qt6. That way, existing plugins can use something like:

```
python_for_qt = 6
try:
    from PySide6.QtCore import Qt, QByteArray, QCoreApplication, QLibraryInfo, QTimer, QTranslator, qVersion
    from PySide6.QtWidgets import QApplication, QCheckBox, QComboBox, QDialog, QDialogButtonBox
    from PySide6.QtWidgets import QHBoxLayout, QLabel, QLineEdit, QMainWindow, QMessageBox, QPushButton
    from PySide6.QtWidgets import QStyleFactory, QTextEdit, QVBoxLayout, QWidget
    from PySide6.QtGui import QColor, QFont, QIcon, QPalette, QAction
    print('Pyside6')
except ImportError:
    from PyQt5.QtCore import Qt, QByteArray, QCoreApplication, QLibraryInfo, QTimer, QTranslator, qVersion
    from PyQt5.QtWidgets import QApplication, QCheckBox, QComboBox, QDialog, QDialogButtonBox, QAction
    from PyQt5.QtWidgets import QHBoxLayout, QLabel, QLineEdit, QMainWindow, QMessageBox, QPushButton
    from PyQt5.QtWidgets import QStyleFactory, QTextEdit, QVBoxLayout, QWidget
    from PyQt5.QtGui import QColor, QFont, QIcon, QPalette
    print('PyQt5')
    python_for_qt = 5
```

Try PySide6 and then roll to PyQt5 if it's unavailable. Something like that would be fairly easy (with enough lead time) to change existing plugins to support Sigil-qt6 and well as Sigil-qt5, and new plugins could do the same, or make the first Sigil-qt6 release the minimum for their plugins.

Other solutions welcome.

**Comment by kevinhendricks** [comment]
Couldn't we do the same thing with PyQt6 vs PyQt5?

**Comment by kevinhendricks** [comment]
What is the advantage to using PySide6 to PyQt6 here?  Is it easier to get the source?  Is it tied tosip versions like PyQt?

**Comment by dougmassay** [comment]
We could do the same thing with PyQt6 and PyQt5. And I'm certainly not opposed if it's the easier option for all concerned. I'm just looking to kill two birds with one stone, is all. I've always wanted to transition to PySide, and this seemed like an opportunity (without needing to bundle both PySide and PyQt).

There's probably no real advantage from a programming pov, but I just like PySide's availability (both binary and source), and their better documentation for building from source. It's Python for Qt, provided by Qt, downloadable from Qt. I'm no fan of Qt's development habits in general, but I dislike Riverbank Computing's habits even more.  Vague and incomplete build instructions--not to mention missing source downloads for older versions. Then there's the merry-go-round of SIP versions, and the compatibility nightmare each new turn into left field with SIP brings.

To answer your question, PySide doesn't use SIP, but it does have it's own similar generator module called shiboken. There's a build module and a runtime module. And yes, there's still a bit of a balancing act between Python version, Qt version and Shiboken/PySide version, but it's not nearly as cryptic and un-navigable as Riverbank's PyQt stuff has become in my opinion.

**Comment by dougmassay** [comment]
You don't need to build a separate version of Shiboken (SIP equivalent) to build PySide6. It's included and built automatically when building PySide6

**Comment by kevinhendricks** [comment]
Agreed, transitioning to PySide6 sounds like a good idea with Qt6.  Let's do that.

**Comment by kevinhendricks** [comment]
That's even better!

**Comment by dougmassay** [comment]
I need to try and get a Windows build of Qt6 ready so I can experiment with bundling Python/PySide. Do you think KDE will be maintaining their own Qt6, or should I just start with the stock Qt source for now?

**Comment by kevinhendricks** [comment]
That same KDE site did have Qt6 master.  Given Qt 6.2.2 is supposed to be LTS, my guess is they will maintain it in a similar fashion.

**Comment by kevinhendricks** [comment]
That said ... it is probably too early to worry about a LTS version so going with the latest might be for the best.  I think Qt has released a Qt 6.3.0 so perhaps we should stick with the latest official versions for now. 

We should also try and work a couple of our own Qt patches into the build, at least the one that handles h6 in Chromium's part of QtWebEngine.

**Comment by dougmassay** [comment]
I'll probably try with Qt6.3 then. It's not like I won't need the practice compiling Qt on  Windows! :)

Isn't there also hope that 6.3 might work "better" with arm64?

**Comment by kevinhendricks** [comment]
Yes, that is another good reason.  I will try the same for macOS (intel) sometime soon.

I just need to check the minimum macOS useable first.

My guess is I will need to update my laptop since my iMac is stuck on Mojave.

**Comment by kevinhendricks** [comment]
Could not find opensource Qt 6.3 so I am going to try with Qt6.2.2 official source.

**Comment by dougmassay** [comment]
I could be wrong, but I don't think 6.3 has been officially released yet.

I'm going to have to revisit my dark mode stuff before a Qt6 release, too. PySide6 on Arch seems to be picking up theme info from somewhere else. Even when Sigil-qt6 is signaling "light" mode to the plugin framework, there's a dark theme being applied to the PySide widgets. Theming is probably going to be a bit messy in general on Linux where both Qt5 and  Qt6 coexist and look to the same environment variables for style/theme guidance.

**Comment by kevinhendricks** [comment]
Should we close this now given your plugin_utils.py?

**Comment by dougmassay** [comment]
I think so, yes. I've got a few build-related PySide6 kinks to work out on Windows, but there are now valid options for plugin devs to maintain compatibility with PyQt5 and PySide6.
