### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by matkoniecz** [Sigil-Ebook/Sigil#661]
https://github.com/Sigil-Ebook/Sigil/wiki/Linux-Notes claims

> One of Sigil's main developers does maintain an experimental Sigil binary installer (built from official Sigil sources) in his one of his own github repositories.

The latest version available at https://github.com/dougmassay/pkg-sigil/releases 0.9.9 - so I would consider removing this mention or at least past tense.

(updating it also would be nice, but I am not expecting this)

I would make this edit but wiki is closed to general contributors

(I went through docs as I am looking for some way to get more recent Sigil than 1.1.0 on Ubuntu, with hope that it will remember state of Windows that I opened, a I try to use preview as ebook reader)

**Comment by kevinhendricks** [comment]
@matkoniecz All of this is documented in our Mobileread user support site.  Sigil now has actual e-reader plugins that can be used to read a  epub opened in Sigil. Again documented in our MobileRead user support site.
The easist way to use a newer Sigil on an old Linux distribution is to install a newer version of Qt (typically from contributed package archives) and just build it yourself.

**Comment by kevinhendricks** [comment]
Renaming to clarify topic of issue

**Comment by matkoniecz** [comment]
If wiki is fully replaced then maybe delete it or editing pages linking relevant docs on the new site?

#660 had more info about what is outdated on wiki

**Comment by kevinhendricks** [comment]
Yes and if you look here 660 is linked even though closed.

Mobileread is not a new site.  Mobileread has always hosted Sigil's user forums and links to it have been in our README.md here from the very beginning.  In addition, we have a fully updated User Guide as well that is available that has its own repo as well.

See the Links section of the README that lists all available resources.

**Comment by matkoniecz** [comment]
Maybe it is mistake in this case, but I tend to use resources from development website, including github wiki

Wiki is sadly outdated but it is far more accessible than say https://github.com/Sigil-Ebook/sigil-user-guide/releases/tag/2021.10.25 that requires downloading and opening in other software

> Mobileread is not a new site. Mobileread has always hosted Sigil's user forums and links to it have been in our README.md here from the very beginning.

Well, new user who never used this documentation is not aware about such history

**Comment by kevinhendricks** [comment]
As you did not bother to read the README that shows up when you visit this site.  Links to the user guide in epub form are here as well.
pNext time try actually raading the main site ReadMe.

**Comment by matkoniecz** [comment]
I have read readme, wiki was not mentioned explicitly but it is fairly normal to setup it.

Either way it is clear that you do not consider this specific report useful so I will not bother you further.

**Comment by kevinhendricks** [comment]
The Wiki being outdated needs to be addressed eventually.  So we will leave this open to remind us.  That said,  it is very very low priority given we have a Users Forum on Mobileread and an Updated User Guide in epub form to provide people with help.  Github issues is not the place to seek user help.

**Comment by dougmassay** [comment]
> Wiki is sadly outdated but it is far more accessible than say https://github.com/Sigil-Ebook/sigil-user-guide/releases/tag/2021.10.25 that requires downloading and opening in other software.

You DO know that the "other software" you're referring to is Sigil, right? Making the user guide for EPuB creation software in the EPUB format Makes quite a bit of sense.

**Comment by dougmassay** [comment]
The only update to the wiki I have in mind is to replace the the whole thing with one single link: https://sigil-ebook.com

**Comment by eli-schwartz** [comment]
> You DO know that the "other software" you're referring to is Sigil, right? Making the user guide for EPUB creation software in the EPUB format makes quite a bit of sense.

To be fair, Sigil is an epub *editor*, not an epub *reader*, and, um, it's a bit better at the former than it is at the latter...

Personally, I do have both kinds of software installed on my computer. And I'd definitely not think to use Sigil when I want to open a book for *reading*.

As far as either updating or decommissioning the wiki goes:
- what are your thoughts on opening it to public contributions?
- how do you want to solve the bootstrap issue, where you recommend using sigil to read the docs, but the docs include instructions on what to do if sigil crashes instead of opening? Admittedly those are for older versions...

**Comment by dougmassay** [comment]
> To be fair, Sigil is an epub editor, not an epub reader

Too be fair... and epub editor with 3 different _reader_ plugins.

I'm growing bored with this conversation.

**Comment by kevinhendricks** [comment]
Closed because the Wiki has been deleted
