### ISSUE TITLE
Feature Request: Allow to set default HTML / CSS content

### ISSUE THREAD

**Issue by sh2sg** [Sigil-Ebook/Sigil#663]
When opening a new empty epub file, the Section0001.xhtml should contain custom default HTML content.

Add a new context menu under Text: Add Default HTML File

Add a new context menu under Styles: Add Default Stylesheet

**Comment by kevinhendricks** [comment]
Closing.  Issues are not the place to suggest feature requests.  Use our User forums on Mobileread (See the README) so that others can see your suggestions and there is already a thread on future Sigil features.

**Comment by kevinhendricks** [comment]
BTW you can use the template epub plugin or Add Existing as well.
