### ISSUE TITLE
Extremely slow when adding large number of HTML files into epub

### ISSUE THREAD

**Issue by sh2sg** [Sigil-Ebook/Sigil#666]
Sigil 1.8.0
MacBook Pro (late 2013), Big Sur 11.6.2

Opened an empty epub file
"Adding existing files" and selected a huge number of HTML files (eg, 1000+)
It took 10-15 mins to add all files into project
Added an image
Made it as Cover, it took anther 5 mins to complete.

Is there any way to speed it up?

HTML file does not have complicated structure, sample:
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link rel="stylesheet" type="text/css" href="../Styles/main.css"/>
<title>title</title>
</head>
<body>

<div>
<h2>title</h2>
<p>line</p>
<p>line</p>
<p>line</p>
<p>line</p>
<p>line</p>
<p>line</p>
<p>line</p>
<p>around 100 lines in one HTML file</p>
</div>

</body>
</html>
```

**Comment by sh2sg** [comment]
Thanks for the reply. My use case is to assemble serial novel chapters into epub books, the authors usually publish 2-3 chapters every day and last for few years, this easily builds hundreds/thousands of chapters when the story completes. It is not difficult to write a script to fetch the online chapters and save them as local formatted HTML files, then import to Sigil.

It doesn't make sense to merge chapters into one big section as each of them has its own chapter title.

The generated epub files are opened well without any delay by compatible epub reader on mobile device, I am using the app called "Marvin 3" on iOS.

**Comment by kevinhendricks** [comment]
Chapter titles do not prevent merging at all.   Simply use the correct heading tag and precede it with a page break.  Nothing should have to load over 1000 plus files just to get 100 lines of base xhtml.  That makes no sense to me.

Before I could even think about how to optimize loading over 1000 files from a zip and building over 1000 resource objects I would need a valid test case epub.

So please privately post an actual epub that will load and work on an epub reading device (kobo, etc) someplace you have access to and then go to our MobileRead User's site and once registered you can pm (personal mail) "KevinH" (that is me) with the link.  Then only I will be able to read the link.

Please do not post it here or anyplace public unless the epub is in the public domain or you personally own the copyright.

**Comment by kevinhendricks** [comment]
Once I have the test epub and if I can recreate the issue, then I will look into what can be done to speed things up *without* having to completely redesign Sigil, if anything.

**Comment by sh2sg** [comment]
I made a sample epub file, 1185 chapters with all mockup content, please get it at http://www.sh2sg.com/samples/sample.epub

It took 1s to open this epub by the book reader "Marvin 3" on iPhone Xs.
It took few seconds to open the same epub by Sigil on my old MBP, but acceptable.
But it took 14 mins to import original HTML files to Sigil...

**Comment by kevinhendricks** [comment]
This is not the test case I asked for.  

Your mockup provides no evidence that these things actually exist in actual fact, nor whether the files are cross-linked, nor how many images they typically include, if do they share a single css file or if each file includes its own or if it uses style tags in head, if the original files are spaghetti html or xhtml, whether they include metadata in each file, etc. 

Further nothing in your mock-up indicates why you can not just add an hr or p tag with  page-break after always just before the body end tag and merging adjacent files into sets of 10 (or even 100) at a time to easily make realistic sized chapters and not 100 lines per chapter. Sigil has no problems creating either a nav or a ncx or even a html TOC that would allow all chapters to be easily accessible even though merged and the page break after means each new chapter starts on its own page.
 
FYI, using AddExisting does a whole lot more than just copy a file.  It checks each file to make sure it is at least well-formed, it tries to extract metadata from meta elements in head, it looks for linked css files and adds them if possible, it looks for links to image files and adds them if possible, it builds up the opf, all the while maintaining responsiveness in Sigil and the ability to show progress and allow aborting.

That is why I asked for a private copy of an actual web serial epub that you worked on and provided a way for you to get a link to me privately so as to not violate copyright by making such an epub public.

Furthermore, current master already has a number of speedups and improvements in it.  Using current master it took me 1 minute 40 seconds to actually use Add Existing to add all 1185 files on my old MBP.  So I do not really see this getting much faster and still do what AddExisting is supposed to do.

If this is something you do repeatedly, I strongly recommend doing one of the following:

a) merge a normal number of sequential files to form serial groups of some sort adding the appropriate page break just before the body tag during the merge.  This is the best idea for general responsiveness and just common sense.  This can easily be done with a python3 script you run before loading.  Or done just once with new chapters added to the end and merged after building up a requisite set size.

b) write your own Input plugin for Sigil (or pay someone to do it for you) in python3 to take a folder path, build up and sort a list of html files in that folder,  then use gumbo to parse each as html but serialize each to xhtml, and then have it create a bare bones opf (with manifest and spine) entries, mimedata, etc and create a simple zipped "epub" to pass to Sigil.  All of this is easily doable in Sigil's python plugin environment as there are many library support routines to help.  Then you would get an input time of just a few seconds, similarly to how long it takes to load this epub.

c)  do both a) and b) in in a Sigil input plugin to really make things much faster than the 1 minute and 40 seconds it took me with current master.

There are many Sigil plugin devs on the Mobileread website I pointed you at, that can help you create your own Sigil input plugin (including me who would be happy to help or answer coding questions) or if you do not know how to program in python yourself, you might be able to employ someone (not me) there to create the plugin you need.

Sorry, but based on the above, I do not see making any changes to current master's  AddExisting given its current performance and given as this appears to be primarily a "problem" of your own making given your reluctance to actually reformat the input files to something that actually makes sense.

Sorry.

**Comment by sh2sg** [comment]
I misunderstood, I thought you want a sample epub file, if you wanted the web site that I fetched chapter pages from, here is one of them: https://www.txthui.com/16862/ , it is opened to public so everyone can access it. Sorry it is in Chinese, but you can feel how it looks like,  

My script fetches page content, removes all HTML tags except <title>, <p>, adds my own simple HTML <header>, <style>, <h2> and saves it. There are no cross-links required for those files, no embedded images etc. My sample epub shows exactly what I did for real book.

I am trying to keep the original chapters as table of content.

There might be some workarounds by speeding up importing, such as, importing by smaller batches like 100 files at one time. I noticed the progress bar, the import speed was actually good at the first 1/4, then it became slower and slower, the last 1/4 almost took half of total time.

**Comment by kevinhendricks** [comment]
AddExisting speed is nearly constant in Sigil builds from current master.   And the table of contents can be generated from the merged files very quickly as I explained earlier so there is no good reason not to merge the super short files into reasonable sized ones with the appropriate page breaks.  Your script could do that easily.  Your table of contents argument is spurious as file boundaries are not needed for any table of contents.

So do that.  

Sigil master now loads all 1185 files using AddExisting in 1 minute and 30 seconds instead of 14 minutes.  Further speed ups are not needed if you actually merge the files into appropriate sized chunks in your script, or make a specialized input plugin.

So closing this as multiple ways exists to do what you want in a reasonable manner and AddExisting has already been sped up greatly in current master.
