### ISSUE TITLE
Need project folder as alternative to temp cache

### ISSUE THREAD

**Issue by sugenganthos** [Sigil-Ebook/Sigil#667]
Thanks for this marvelous epub editor.
Editing ebook may take several days. However, saving may take long time for rich book. What if use a 'project folder' instead of temp cache. Thus regular saving would take the edited file. Saving to ebook will need 'save project' instead.
Editing xhtml file outside sigil may break the links and anchor index.

**Comment by kevinhendricks** [comment]
You can already set and control where the temp folder is created in Sigil preferences,

You can already use Sigil Checkpoints for fast saves of only changed files.

You can already use FolderIn / FolderOut plugins to interface with an external git repo.

Yes, editing files outside Sigil can break links if you are not careful but that is true of any editor.

Sigil already has Open With to work on files with external editors while book is loaded in Sigil.

Suggestions for improvements do not belong in our github issues.  They are only allowed in our Mobileread User Forums where others can see and comment.

Closing

**Comment by sugenganthos** [comment]
I mean the temp folder gets removed when sigil closed. The project folder stays.
Also i didtn't found yet any apps that keeps link references as good as sigil.

**Comment by kevinhendricks** [comment]
As per above, Sigil only saves and loads epubs.  If you want to leave the files unzipped in a non-epub usable state or if you want to use git to hold the epub files in some intermediate state, use Sigil's FolderIn and FolderOut plugins.
