### ISSUE TITLE
After compiling: symbol lookup error

### ISSUE THREAD

**Issue by dacorsa** [Sigil-Ebook/Sigil#671]
### Bug Description

Hi guys,
i tried to compile Sigil with latest ubuntu and latest code of Sigil, i after sucessefully compiling give me this, when i run:

10:30:01 dacorsa@NanoKDE /home/dacorsa $ /app/Sigil/sigil-build/bin/sigil 
/app/Sigil/sigil-build/bin/sigil: symbol lookup error: /app/Sigil/sigil-build/bin/sigil: undefined symbol: _ZN8Hunspell3addEPKc

any idea?

### Platform (OS)

Linux

### OS Version / Specifics

ubuntu impish

### What version of Sigil are you using?

latest code

**Comment by dougmassay** [comment]
Sigil is not intended to be run from its build directory. It needs to be installed (sudo make install) and run via its launch script in <install prefix>/bin

**Comment by dacorsa** [comment]
Thanks, after make install works well!
Excuse me for the stupid question :)

**Comment by dougmassay** [comment]
No problem. Many programs can be run from their build directory.
