### ISSUE TITLE
Doesn't support windows 7 / 64

### ISSUE THREAD

**Issue by alekssmitt** [Sigil-Ebook/Sigil#674]
### Bug Description

When trying to install Sigil-1.9.2-Windows-x64-Setup on windows 7 / 64 the notification pops up saying:
this program does not support the version of windows your computer is running on

### Platform (OS)

Windows (Default)

### OS Version / Specifics

windows 7 / 64bit

### What version of Sigil are you using?

1.8.0

**Comment by kevinhendricks** [comment]
Not a bug.  Just use the provided Legacy installer.

**Comment by alekssmitt** [comment]
Yes, but Sigil-1.9.2-Windows-Legacy-Setup is for windows 7 / 86 only

**Comment by alekssmitt** [comment]
ok, no need to reply
i see that it's over

**Comment by dougmassay** [comment]
The 32-bit Legacy 1.9.2 will run perfectly fine on Windows 7 -- regardless if your Windows is 64-bit or 32-bit. So it's not "over". I'm just not providing two different legacy versions.
