### ISSUE TITLE
[Bug]: Refuses to install on Windows 7 64bit Home Premium

### ISSUE THREAD

**Issue by dsanalytics** [Sigil-Ebook/Sigil#675]
### Bug Description

Sigil 64bit setup refuses to install on Windows 7 64bit Home Premium - message below. If this is by design, please let me know which version supports Windows 7.

![image](https://user-images.githubusercontent.com/32625394/163918308-b52997c3-d5a8-4c1a-b3a6-d6423b9aab9d.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 7 64bit Home Premium

### What version of Sigil are you using?

1.9.2

**Comment by dougmassay** [comment]
Starting with Sigil 1.9, you must use the legacy sigil installer on Windows 7. The other installers use a version of Python that is incompatible with Windows 7.

**Comment by dougmassay** [comment]
And yes, the 32-bit legacy version will run fine on 64-bit Win7.

**Comment by dsanalytics** [comment]
Legacy worked! Thank you.
