### ISSUE TITLE
[Bug]: Sigil freezes if global conflicting shortcut is used

### ISSUE THREAD

**Issue by dsanalytics** [Sigil-Ebook/Sigil#676]
### Bug Description

I have Ctrl+1, Ctrl+3, Ctrl+3 shortcuts globally mapped to something else, and when I used one of those in Sigil for I forgot about the conflict, it made Sigil freeze, and I had to use Task Manager to close it. Not a big deal for me - just an FYI.

![image](https://user-images.githubusercontent.com/32625394/164397108-8e2efaff-b6f0-408d-8048-7c6d4ce517d8.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 7 64bit SP1 Home Premium

### What version of Sigil are you using?

1.9.2 Legacy

**Comment by kevinhendricks** [comment]
Did Sigil actually hang or did you just change its keyboard input out from under it?

Did you try using Sigil's Preferences Shortcut Manager to remove the Ctrl+1, Ctrl+2, Ctrl+3 shortcuts or change them to prevent the conflict?

**Comment by dsanalytics** [comment]
I did not change any Sigil shortcuts or any other settings - everything was default and the doc was small - I was just plying around with some plain text with no images, no custom style sheet, no fonts, etc. Sigil just hanged after I marked the text and pressed Ctrl-3. Those that do not have conflicts, like Ctrl-7 work just fine. Did not try to change the shortcuts yet - thanks for the tip.

**Comment by kevinhendricks** [comment]
Since neither Qt nor Sigil can detect what specific system level shortcuts are set by an individual user nor what they do, only the user can prevent conflicts by using Sigils Preference to set and unset Bookmarks.  

Changing the keyboard or input method after Qt has started using them is not something Sigil can control.

Closing this.
