### ISSUE TITLE
[FR]: Stop prompting for fixing epub files that are not well formed

### ISSUE THREAD

**Issue by dsanalytics** [Sigil-Ebook/Sigil#679]
### Bug Description

When opening some epub files, Sigil often warns me about not well formed files in it, and then it prompts me to fix it for me. Can this be turned off, as I often open files somebody else created, that are big and I do not want to let Sigil potentially remove things?

![image](https://user-images.githubusercontent.com/32625394/165869803-257f24b3-2d2a-4e26-878e-f7e861160954.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 7 64bit SP1 Home Premium

### What version of Sigil are you using?

1.9.2 Legacy

**Comment by dougmassay** [comment]
Please don't use the bug report template for feature requests. Feature requests should be posted in the Sigil User Forums on MobileRead.com.

**Comment by dsanalytics** [comment]
Ok - did not know that.

**Comment by kevinhendricks** [comment]
And Sigil needs well formed files to work properly so that is not going to happen.  Just let the built in gumbo parser mend the files.  Gumbo is not like old Tidy.  It will not lose code.

**Comment by dsanalytics** [comment]
@kevinhendricks Sometimes I just want to open epub and see one specific thing on the inside and close it, and not work on it or fix it as many of those have not been created by me. Even just to learn how something was done in some epub. But I'm greeted every time with the prompt which is annoying. 

I've let Sigil fix it once or twice, but Sigil does not report, at least as far as I know, what's been changed  - there's no change log. All I need is an option to turn this prompting behavior off.

**Comment by kevinhendricks** [comment]
Again, this is not the place for feature requests.  This is not a bug but designed behaviour.

**Comment by dsanalytics** [comment]
@kevinhendricks I'll post this in a forum as I'm sure many people would agree.

**Comment by kevinhendricks** [comment]
FYI, If you want a log of all changes made, load the epub into Sigil saying "no" when prompted.  Make a Checkpoint.  Run Mend All.  Do a  checkpoint compare to see all changes.

My guess is your files are probably just missing their DOCTYPE which Sigil will fix automatically when allowed to do so.

Please do, this request was made long ago but denied because missing doctypes are easy and safe to fix, and there is no good reason to keep non-well formed xhtml when it can be easily fixed.
