### ISSUE TITLE
[FR]: Option to turn off auto-live preview and have a shortcut to manually refresh live preview

### ISSUE THREAD

**Issue by dsanalytics** [Sigil-Ebook/Sigil#680]
### Bug Description

Can auto live preview be turned off and requested manually to be refreshed through a shortcut? Sometimes I have big files, and live preview is annoying, for as soon as I changed even one character, it triggers it and as I continue typing, it keeps working constantly, etc. I prefer to make several changes and see the result at the end. Thanks. 

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 7 64bit SP1 Home Premium

### What version of Sigil are you using?

1.9.2 Legacy

**Comment by kevinhendricks** [comment]
Have you even tried to read the Sigil User's Guide?  It explains hide Preview using the View menu.  Please do not file bug reports that are not actual bugs but instead are just user questions.

**Comment by dsanalytics** [comment]
I do not want to hide as I need it. So I'd like to have it there but refreshed on demand - is that available?

P.S. Doug Massay explained where to submit FRs.
