### ISSUE TITLE
Sigil's preview is showing blank 

### ISSUE THREAD

**Issue by CarlieM** [Sigil-Ebook/Sigil#681]
### Bug Description

I work on Sigil very often. I use preview to create epubs but recently it stop working, meaning the preview window is always blank, empty, nada. I open any previews epubs I had made and also the preview is blank. I tried creating a new epub from scratch meaning a new html file, and the preview is always blank. How can I fix this so I can preview my files?  

I also tried using older versions of Sigil and the preview in each one is always blank.

### Platform (OS)

macOS

### OS Version / Specifics

Monterrey 12.3.1

### What version of Sigil are you using?

Current - 1.9.2

**Comment by kevinhendricks** [comment]
My guess is a recent update to the your macOS graphics driver is the issue.  Apple has broken a number of graphic drivers with their updates over the years and literally seems to take years before they realize what they did and fix them.

So try the following:

1. Open Sigil
2. Open the Sigil->Preferences menu and navigate to General Settings
3. In General Settings look for Disable GPU Acceleration in QtWebEngine/Preview.  You may have to snoop around in the various tabs in General Settings to find it.
4. Check the box to Disable GPU Acceleration.
5. Exit Preferences
6. Fully shutdown Sigil and Restart it.

Can you now see something in Preview when you load an epub?

**Comment by kevinhendricks** [comment]
Other things to try: 

- unplug any external monitors if you are using more than one
- make sure you have told macOS Settings / Gatekeeper to give Sigil full access
- try disabling any third party antivirus software and restart and try Sigil 
(some "protection" software kills the QtWebEngine render process which is used by Sigil's Preview)
- try running Sigil on a different macOS version / another mac to clarify the issue only happens after the latest update.

**Comment by CarlieM** [comment]
Thank you so much! That did the trick it was the GPU acceleration.

**Comment by kevinhendricks** [comment]
That new Sigil setting should really not be needed for the latest macOS versions.  It was added to help support older macOS versions on systems with older graphics cards.

How old is your mac?  If it is recent (last 3 or 4 years) you  might want to let Apple know they have broken their graphics driver (again).

Glad to hear you got it working!

**Comment by kevinhendricks** [comment]
Try updating to the latest driver for that graphics card.  It may help bring back gpu acceleration.
