### ISSUE TITLE
[Bug]: Styles files are not copied to temp folder for use by Page Edit

### ISSUE THREAD

**Issue by dwhire** [Sigil-Ebook/Sigil#693]
### Bug Description

Styles files are not copied to temp folder for use by Page Edit.
To test: Open Page Edit and see if the desired styles are being applied.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10

### What version of Sigil are you using?

1.9.2 and  1.9.10

### Any backtraces or crash reports

```shell
None needed.
```

**Comment by dwhire** [comment]
Files are copied. I forget to select all file types. However there is still an issue in that Page Edit does not apply the styles. For now I am switching to using Kompozer.

**Comment by kevinhendricks** [comment]
PageEdit applies any properly linked CSS files that have valid css 3 in them.

**Comment by dwhire** [comment]
Thanks Kevin. The problem was mine. Not Page Edit.
