### ISSUE TITLE
"ADD COVER" feature improvement

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#694]
### Improvement description

The "Add Cover..." feature should use data provided by the user: 

- If an image file is already marked as "cover", the file should be automatically selected
- If in meta data the author and title are already provided, they should be put within the "title" element instead of the word "Cover". Alternatively, the title content should be copied from first XHTML file present in the ePub.
Thank you.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10

### What version of Sigil are you using?

current

**Comment by kevinhendricks** [comment]
As explained in this site's README, github issues are not for feature requests. 

```
Please do not use the issue tracker to ask questions or suggest new features. Both of the main developers of Sigil monitor the Sigil Forum at https://www.mobileread.com/forums. All questions and feature requests should be directed there so that other interested users can help or comment.
```
