### ISSUE TITLE
[Bug]: Cannot open Sigil window from background state

### ISSUE THREAD

**Issue by ioudove** [Sigil-Ebook/Sigil#696]
### Bug Description

After launching Sigil, I didn't open any epub files, I just clicked the red close button in the top left corner. At this point, the Sigil software was stuck in the background. Then when I clicked the Sigil icon again, it did not reopen the software. Only when I exit the Sigil software completely and start it again can I reopen it.

### Platform (OS)

macOS

### OS Version / Specifics

12.5.1 (21G83)

### What version of Sigil are you using?

1.9.10

**Comment by kevinhendricks** [comment]
Not a bug. As designed and a long time behaviour of Sigil on macOS.    

You are ignoring the top menu bar. Try clicking on Sigil in your dock and check the top application menu bar.  You should see Sigil's File menu ready to go.

You can also use Sigil icon in the Dock to quit out of Sigil.

**Comment by kevinhendricks** [comment]
Again, post user questions and help requests on our Mobileread User Forums and not here.
