### ISSUE TITLE
[Bug]: opening xhtml files in pageedit from sigil showing blank pages

### ISSUE THREAD

**Issue by muralikodali** [Sigil-Ebook/Sigil#697]
### Bug Description

i have opened a epub file in sigil.

when i tried to open xhtml file from sigil in pageedit, it is shows blank pages. 

![Peek 2022-08-26 12-24](https://user-images.githubusercontent.com/11482766/186841268-1eb351d8-1f19-40f0-9f4a-4c3891f24145.gif)

### Platform (OS)

Linux

### OS Version / Specifics

ArchLinux

### What version of Sigil are you using?

1.9.10

**Comment by dougmassay** [comment]
I've just noticed that Arch's PageEdit package was built with Qt6, but their Sigil package is still Qt5. That _shouldn't_ cause problems, but I'll install the package versions of both to see if I can duplicate this.

In the meantime, can you verify that PageEdit displays epubs correctly without Sigil being in the mix?

**Comment by kevinhendricks** [comment]
I remember seeing something similiar with initial Qt6 PageEdit builds but I can not recreate this with my Manjaro Qt6 builds of PageEdit and Sigil from master but I have not tried mixing them.

**Comment by dougmassay** [comment]
@muralikodali : Can you verify that both PageEdit and Sigil have been installed via pacman, and that PageEdit is the latest version (1.9.10) as well?

**Comment by muralikodali** [comment]
I have got the below info using ```pacman -Qi```

- for sigil

```
$ pacman -Qi sigil
Name            : sigil
Version         : 1.9.10-2
Description     : multi-platform EPUB2/EPUB3 ebook editor
Architecture    : x86_64
URL             : https://sigil-ebook.com
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : hicolor-icon-theme  hunspell  mathjax2  minizip  python-css-parser  python-dulwich  python-lxml  qt5-svg  qt5-webengine
Optional Deps   : hunspell-en_US: for English dictionary support [installed]
                  hyphen-en: for English hyphenation support in plugins [installed]
                  pageedit: external editor to replace BookView [installed]
                  python-html5lib: recommended for plugins [installed]
                  python-chardet: recommended for plugins [installed]
                  python-cssselect: recommended for plugins [installed]
                  python-pillow: recommended for plugins [installed]
                  python-regex: recommended for plugins [installed]
                  python-pyqt5: recommended for plugins [installed]
                  python-pyqt5-webengine: recommended for plugins [installed]
                  tk: recommended for plugins [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 20.93 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Mon 06 Jun 2022 10:09:50 PM IST
Install Date    : Mon 20 Jun 2022 08:41:39 PM IST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```
- for pageedit

```
Name            : pageedit
Version         : 1.9.10-1
Description     : Simple Single Page XHTML Visual Editor, split from Sigil’s BookView
Architecture    : x86_64
URL             : https://github.com/Sigil-Ebook/PageEdit
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : qt6-5compat  qt6-svg  qt6-webengine
Optional Deps   : None
Required By     : None
Optional For    : sigil
Conflicts With  : None
Replaces        : None
Installed Size  : 2.56 MiB
Packager        : Caleb Maclennan <alerque@archlinux.org>
Build Date      : Thu 14 Jul 2022 04:42:58 PM IST
Install Date    : Thu 14 Jul 2022 06:24:43 PM IST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by dougmassay** [comment]
Thanks for the info. I should be able to do some checking this weekend.

**Comment by kevinhendricks** [comment]
I think these are the crucial missing changes since our last release of PageEdit:

https://github.com/Sigil-Ebook/PageEdit/commit/19a77451d62f2657a8d24f754acdc3219fd09db7

and

https://github.com/Sigil-Ebook/PageEdit/commit/b03cc3f1338b2949a8bed3e999d89aa78afd6de4

As I remember, the first one fixes the blank screen one on Linux.  This only happens with Qt6 and PageEdit. With Qt5, this is not an issue.  Since we have not officially released Qt6 versions of either PageEdit or Sigil for any platform, this was not caught earlier.

If you can build PageEdit from master, this issue will go away.

This is really a PageEdit bug not a Sigil one, and one that is already fixed in PageEdit master.

Not sure how to get Arch to build a Qt5 version of PageEdit or add in those two patches before our next release.

**Comment by dougmassay** [comment]
I might be able to beg for a cherry-pick of the commit in an Arch bug report, but I don't really have any history with the new PageEdit/Sigil maintainer.

**Comment by kevinhendricks** [comment]
Alternatively, we could just do a new minor release of both Sigil and PageEdit to force the issue since it has been over 3 months since our last release.

**Comment by dougmassay** [comment]
That's not a terrible idea. There 30 or so commits to Sigil since 1.9.10 are all fairly minor tweaks, right?

**Comment by kevinhendricks** [comment]
Yes, mainly bug fixes with two or three very minor new features related to templating.

What is your schedule like regarding release timing?  I am very flexible.  

I think the base.ts file for translations for Sigil is up to date.  So in a few days I could grab all the new translations.  I think PageEdit's base ts file is good to go since no ui changes have been made.

**Comment by kevinhendricks** [comment]
Actually there were PageEdit UI changes in June.  I will update the PageEdit base ts file for translations now, just in case we decide to go that way.

**Comment by kevinhendricks** [comment]
Just updated the PageEdit ChangeLog and base for translations. So in about a week we should be able to pull in final translations for PageEdit as well.

**Comment by kevinhendricks** [comment]
Closing asthis should be fixed with the upcoming 1.9.20 release of PageEdit.

**Comment by DavidMatuszek** [comment]
I had a similar issue. What finally worked for me was to open Sigil without any external monitors attached.

**Comment by kevinhendricks** [comment]
This issue is unrelated and really has nothing to do with Sigil, and is instead a PageEdit issue that was programmatically fixed in the latest release of PageEdit.
