### ISSUE TITLE
[Bug]: macos 13 source code text size invalid...

### ISSUE THREAD

**Issue by msgi** [Sigil-Ebook/Sigil#701]
### Bug Description

macos 13 source code text size invalid...

### Platform (OS)

macOS

### OS Version / Specifics

13

### What version of Sigil are you using?

1.9.20

### Any backtraces or crash reports

```shell
macos 13 source code text size invalid...
```

**Comment by msgi** [comment]
source code view: only the smallest font size , so I cannot see anything.

**Comment by kevinhendricks** [comment]
Looks fine on all of my macs.  Have you tried adjusting the CodeView font and font size in Sigil Preferences?  That is the way to change that font and or size.  Your sigil.ini file must be corrupted.

**Comment by dougmassay** [comment]
Also make sure you haven't inadvertently changed the zoom factor for Code View to something much less then 100%. 100% is the very middle of the scale.

**Comment by kevinhendricks** [comment]
Could also be the just released Ventura has removed a font file that was previously used with Sigil.  You could try renaming sigil.ini in Sigil Preferences folder to sigil.ini.bak so that a new one is created.

**Comment by msgi** [comment]
I believe this is a macos 13 bug.

**Comment by msgi** [comment]
> 

This fixed my problem, thank you very much!

**Comment by dougmassay** [comment]
Several suggestions were given. Can you say which was the "this" that fixed your issue? It might help someone in the future to know. Thanks.
