### ISSUE TITLE
[Bug]: build on macos 13 error.

### ISSUE THREAD

**Issue by msgi** [Sigil-Ebook/Sigil#702]
### Bug Description

Hi, I build sigil on my macbook with macos 13.

Not supported or?

### Platform (OS)

macOS

### OS Version / Specifics

13

### What version of Sigil are you using?

current

### Any backtraces or crash reports

```shell
Hi, I want to build sigil on my macbook with macos 13. And I followed the docs and starded by building qt6 on my mac. And error occured.

[6569/14968] Building OBJCXX object qtbase/src/p...keFiles/QCocoaIntegrationPlugin.dir/qnsview.mm.o
ninja: build stopped: subcommand failed.

Not supported or?
```

**Comment by kevinhendricks** [comment]
Building on macOS on intel based macs works just fine with Qt 5.12, Qt 5.15, and Qt 6.2.4,  Building on macOS on arm64 works just fine with Qt 6.2.4.  Make sure you set the target build platform as explained in the instructions.

Is this intel or arm64?  Which specific Qt version are you using?

As for Qt build issues, you should file your bug report with Qt, not Sigil as it is not Sigil specific.

**Comment by kevinhendricks** [comment]
Also, ninja is a parallel build and the last file before it errors is not necessarily the problem one.  What was the exact build error from the compiler?

**Comment by msgi** [comment]
It it intel, and I was using Qt6.2.4 just like the doc guided.

**Comment by msgi** [comment]
Because I built it with the doc in you docs. So I wonder if you guys met with this problem before.

**Comment by kevinhendricks** [comment]
The exact true compiler error message would help.

**Comment by kevinhendricks** [comment]
The Sigil build Qt6 on macOS docs are for Qt6.2.2 not Qt 6.2.4 but I have built out of the box from Qt 6.2.4 source as well.  So if you are running into trouble then my guess is it is the macOS compiler SDK changes in headers  that are impacting you.

If so, you should file a bug report with Qt building on Ventura as Q builds out of the box with earlier macOS versions / SDKs.  Perhaps downloading and using an earlier XCode SDK/compiler freely available from the Apple developer website until building Qt is fixed.

Things like this are why I never update my developer machines to the latest macOS and XCode until much much later in their OS release cycle as macOS updates constantly are breaking / moving headers.

Again the actual compiler error message would help.

**Comment by msgi** [comment]
Building CXX object qtbase/src...keFiles/QICOPlugin.dir/qicohandler.cpp.o
/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/imageformats/ico/qicohandler.cpp:211:20: warning: variable 'readBytes' set but not used [-Wunused-but-set-variable]
            qint64 readBytes = ICONDIR_SIZE;
                   ^
1 warning generated.
[52/9877] Building OBJCXX object qtbase/...Plugin.dir/qiosurfacegraphicsbuffer.mm.o
FAILED: qtbase/src/plugins/platforms/cocoa/CMakeFiles/QCocoaIntegrationPlugin.dir/qiosurfacegraphicsbuffer.mm.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DGL_SILENCE_DEPRECATION -DQCocoaIntegrationPlugin_EXPORTS -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_PLUGIN -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/Users/msgi/sigil/build624/qtbase/src/plugins/platforms/cocoa/QCocoaIntegrationPlugin_autogen/include -I/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa -I/Users/msgi/sigil/build624/qtbase/src/plugins/platforms/cocoa -I/Users/msgi/sigil/build624/qtbase/include -I/Users/msgi/sigil/build624/qtbase/include/QtCore -I/Users/msgi/sigil/build624/qtbase/lib/QtCore.framework/Headers -I/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/mkspecs/macx-clang -I/Users/msgi/sigil/build624/qtbase/src/corelib -I/Users/msgi/sigil/build624/qtbase/include/QtCore/6.2.4 -I/Users/msgi/sigil/build624/qtbase/include/QtCore/6.2.4/QtCore -I/Users/msgi/sigil/build624/qtbase/include/QtGui -I/Users/msgi/sigil/build624/qtbase/lib/QtGui.framework/Headers -I/Users/msgi/sigil/build624/qtbase/src/gui -I/Users/msgi/sigil/build624/qtbase/include/QtGui/6.2.4 -I/Users/msgi/sigil/build624/qtbase/include/QtGui/6.2.4/QtGui -x objective-c++ -DNDEBUG -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -fPIC -std=c++17 -MD -MT qtbase/src/plugins/platforms/cocoa/CMakeFiles/QCocoaIntegrationPlugin.dir/qiosurfacegraphicsbuffer.mm.o -MF qtbase/src/plugins/platforms/cocoa/CMakeFiles/QCocoaIntegrationPlugin.dir/qiosurfacegraphicsbuffer.mm.o.d -o qtbase/src/plugins/platforms/cocoa/CMakeFiles/QCocoaIntegrationPlugin.dir/qiosurfacegraphicsbuffer.mm.o -c /Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm
In file included from /Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:40:
/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:32: error: unknown type name 'CGColorSpaceRef'; did you mean 'QColorSpace'?
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                               ^~~~~~~~~~~~~~~
                               QColorSpace
/Users/msgi/sigil/build624/qtbase/include/QtCore/../../../../qt-everywhere-src-6.2.4/qtbase/src/corelib/kernel/qmetatype.h:1410:1: note: 'QColorSpace' declared here
QT_FOR_EACH_STATIC_GUI_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/Users/msgi/sigil/build624/qtbase/include/QtCore/../../../../qt-everywhere-src-6.2.4/qtbase/src/corelib/kernel/qmetatype.h:199:28: note: expanded from macro 'QT_FOR_EACH_STATIC_GUI_CLASS'
    F(QColorSpace, 0x1017, QColorSpace) \
                           ^
/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.mm:90:32: error: out-of-line definition of 'setColorSpace' does not match any declaration in 'QIOSurfaceGraphicsBuffer'
void QIOSurfaceGraphicsBuffer::setColorSpace(QCFType<CGColorSpaceRef> colorSpace)
                               ^~~~~~~~~~~~~
/Users/msgi/sigil/qt-everywhere-src-6.2.4/qtbase/src/plugins/platforms/cocoa/qiosurfacegraphicsbuffer.h:54:24: note: type of 1st parameter of member declaration does not match definition ('QCFType<QColorSpace>' vs 'QCFType<CGColorSpaceRef>')
    void setColorSpace(QCFType<CGColorSpaceRef> colorSpace);
                       ^
2 errors generated.
[65/9877] Building OBJCXX object qtbase/...rintSupport.dir/cmake_pch.objcxx.hxx.pch
ninja: build stopped: subcommand failed.

**Comment by msgi** [comment]
Well, I am regret about upgrading to the newest macos now. So stupid.

**Comment by dougmassay** [comment]
We patch qiosurfacegraphicsbuffer.h with qt622_fix_qiosurfacegraphicsbuffer.h.patch in our Qt6 build instructions. Did you apply that patch? If so, perhaps it's no longer applicable with MacOS 13?

**Comment by msgi** [comment]
Yes, I applied that patch. And I tried it many times, it worked. But, as I build sigil, some errors occured. So I just try Qt5 and give it a try.

**Comment by msgi** [comment]
Maybe it's time for me to just quit.

**Comment by dougmassay** [comment]
My point was that perhaps that patch needs changed, or even left out on the latest macOS.

**Comment by msgi** [comment]
CMake Error at src/qt6sigil.cmake:24 (find_package):
  Found package configuration file:

    /Users/msgi/sigil/QT624/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "WebEngineCore".

  Expected Config file at
  "/Users/msgi/sigil/QT624/lib/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake"
  does NOT exist

  Failed to find Qt component "WebEngineWidgets".

  Expected Config file at
  "/Users/msgi/sigil/QT624/lib/cmake/Qt6WebEngineWidgets/Qt6WebEngineWidgetsConfig.cmake"
  does NOT exist



Call Stack (most recent call first):
  src/CMakeLists.txt:657 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/msgi/sigil/build/CMakeFiles/CMakeOutput.log".
See also "/Users/msgi/sigil/build/CMakeFiles/CMakeError.log".

**Comment by msgi** [comment]
It seems that patch worked and I built Qt6 successfully. Now when I build sigil, errors like up occured.

**Comment by dougmassay** [comment]
It doesn't sound like QtWebEngine was built. Did you check the output of the initial configure command when building Qt6? It would end with a summary of which Qt modules would be built, and which would not.

**Comment by msgi** [comment]
Then why was not  QtWebEngine  built? I am so confused.
Something needs python2?

**Comment by dougmassay** [comment]
As I did not see the summary output of the configure command, I don't know why webengine didn't build.

**Comment by msgi** [comment]
I will try to build QT6 once more.

**Comment by msgi** [comment]
WARNING: QtWebEngine won't be built. Python2 version 2.7.5 or later is required.
WARNING: QtPdf won't be built. Python2 version 2.7.5 or later is required.

**Comment by msgi** [comment]
Does this make any sense?

**Comment by msgi** [comment]
Well, I will use python2 and give it one more try.

**Comment by dougmassay** [comment]
The python requirement for QtWebEngine has not changed from earlier macOS versions to my knowledge. Perhaps the latest macOS doesn't come with Python2 like previous versions?

**Comment by kevinhendricks** [comment]
Checked the qt 6.2.4 source and the qt622_fix_qiosurfacegraphicsbuffer.h.patch is not needed for qt 6.2.4, just qt 6.2.2.  So if you try to apply that patch to 6.2.3 source it should fail (or ask you if you want to reverse it (you should not).

I did not know macOS python 2.75 was dropped from Ventura.  That said  I have no idea why building QtWebEngine would still require an old outdated python 2 to build.  Qt really needs to fix that.

**Comment by kevinhendricks** [comment]
Checked Qt site but they point to this issue filed for Chromium:

https://chromium.googlesource.com/chromium/src/+/HEAD/docs/python3_migration.md

but that issue still has a handful of blocking issues.

**Comment by msgi** [comment]
I installed conda on my Mac so it uses my configured python version which is python3.9.

Actually I wondered if you could pre compile a Mac version of qt so I can just build sigil with it.

**Comment by dougmassay** [comment]
The newest versions of Qt 6 now require the html5lib python module and nodejs (on all platforms) as well.

For compiling, I mean.

**Comment by msgi** [comment]
Omg, so could you please offer one pre compiled version?

**Comment by kevinhendricks** [comment]
There already is one. See https://github.com/kevinhendricks/BuildSigilOnMac

It is a prebuilt python3 and a prebuilt Qt 5.12.x with all patches in place.

But why not just download and install our macOS release binary from:

https://github.com/Sigil-Ebook/Sigil/releases

since you are using an intel mac, there really is no benefit from compiling yourself.

**Comment by kevinhendricks** [comment]
I would much rather see a detailed crash log from macOS if you see ever see a released build of Sigil on macOS crash.  If only your own builds crash, we may not be able to match your build environment.  So crash reports from released builds are very very important.

Right now we have no outstanding crash reports on macOS or otherwise.

**Comment by kevinhendricks** [comment]
And what do you mean by big epubs?  Are you talking about epubs that are really just one big html file (poorly built) or epubs with hundreds and hundreds of chapters? 

Again, posting problem epubs that have reproducible crashes would be quite valuable.

Unless you are a C++ developer with experience with Qt, you may find the Sigil source to be hard to fathom.

**Comment by msgi** [comment]
Great work, by the way!

**Comment by kevinhendricks** [comment]
Thousands of files is NOT a typical use case for epub.  Unless you know C++ and are familiar with Qt's Concurrent framework, speeding anything up to work at that scale would require a complete redesign of Sigil that frankly we would never incorporate.  Try turning off spellcheck and Preview when working on epubs with thousands of files.
