### ISSUE TITLE
[Bug]: When using an unlisted language code, Metadata Editor won’t keep the code

### ISSUE THREAD

**Issue by Aunst** [Sigil-Ebook/Sigil#705]
### Bug Description

When changing the book's language code to an unlisted code (like [Literary Chinese](https://en.wikipedia.org/wiki/Classical_Chinese) `lzh`) in `content.opf`, then open the metadata editor and click "OK", the language code in `content.opf` will disappear.

This will cause a Python error when opening Metadata Editor the second time.

I think if a language code is unlisted, Metadata Editor should show it directly and keep it when saving.

![content.pdf's source code, highlight on &lt;dc:language&gt;lzh&lt;/dc:language&gt;](https://user-images.githubusercontent.com/58869551/210122843-cd15f7f2-1ef1-432e-b2c3-276194fd246e.png)

![Metadata Editor](https://user-images.githubusercontent.com/58869551/210122923-0b7f9f63-8cf5-4f05-86b5-3da677bbc1e5.png)

![content.pdf's source code, after click Metadata Editor's OK button, language code disappears (&lt;dc:language&gt;&lt;/dc:language&gt;)](https://user-images.githubusercontent.com/58869551/210122938-abbb7ca4-b411-4744-99c2-a241bca8ba23.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 22H2

### What version of Sigil are you using?

1.9.20

**Comment by kevinhendricks** [comment]
Sigil does not support unlisted language codes and will not. The bug with metadata editor failing with empty language code field has already been fixed in master.  The fix will appear in the next release of Sigil.

**Comment by kevinhendricks** [comment]
The iso-693-3 is the only list I can find that lists "lzh" and that version of the 693 language codes is simply too large to be fully support (and includes too many dead languages).  Sigil implements and supports  ISO-693-1 and ISO-693-2 language codes.

That said ... a Pull Request adding support for specific 3 digit language codes to Sigil/src/Misc/Language.cpp where an argument can be made for their popular use in epubs, would be considered.

**Comment by kevinhendricks** [comment]
I will reopen this in case you want to generate a pr and argument for lzh inclusion into Sigil.

**Comment by Aunst** [comment]
Well, but what I want to say is unlisted language codes should be kept by Metadata Editor. Somebody may use the code to mark scripts. For example:
* Chinese characters have simplified and traditional forms, sometimes that can't simply classify by region. Thus, people may use `zh-Hans` (simplified) or `zh-Hant` (traditional).
* Serbian uses both Latin and Cyrillic script , maybe people want to mark a script in code (like `sr-Latn` or `sr-Cyrl`).
* Mongolian also uses Cyrillic `mn-Cyrl` and traditional Mongolian script `mn-Mong`.

And the script code also can be combined with the region code, listing all situations is almost impossible.

> I think if a language code is unlisted, Metadata Editor should show it directly and keep it when saving.

Would you consider this again?

**Comment by kevinhendricks** [comment]
Original epub spec called for iso 693-2 language code and that is what Sigil implements.  That language code is used for dictionary matching as well.  The design of the metaeditor is to use translated language names with menu pulldowns to select language so open ended non-translated language codes are not possible.

**Comment by Aunst** [comment]
Thanks for explaining, I get it.

**Comment by kevinhendricks** [comment]
I can try to leave it alone until the user tries to edit it, but if it is not listed, it can not be part of the choice set for new language additions nor an option when editing the current language.  I will see if that is doable.

The iso-693-3 list is just huge with way way too many dead languages in it to ever be viable for epub.  

So again the best solution for Sigil would be to add *selected* 3 letter codes from the iso-693-3 list that are actively used language codes for epub publishing.  Then it simply all works as is.

Alternatively, the user can always directly edit the opf to make the language code whatever they want.

**Comment by kevinhendricks** [comment]
BTW: zh-Hant is not even part of the iso-693-3 huge spec.  How does it differ from zh-TW and the one you wanted,  lzh?  I thought both were traditional, not simplified.

**Comment by kevinhendricks** [comment]
The changes needed to support allowing an unknown language code to just pass through the MetaEditor and survive (as long as the user does not click on it to edit the language value) turned out to be trivial and so I pushed them to master.

That said, if the user decides to click on the unknown language code inside the MetaEditor to edit it,  that value will be lost and replaced by the pull down menu selection of known language codes (iso-696-2 list).

Hope this helps.

**Comment by Aunst** [comment]
> BTW: zh-Hant is not even part of the iso-693-3 huge spec. How does it differ from zh-TW and the one you wanted, lzh? I thought both were traditional, not simplified.

These script codes were defined in [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924). In [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) (BCP 47), these codes can be combined with ISO-639 code to specify this language's writing system.

[`Hant`](https://en.wikipedia.org/wiki/Traditional_Chinese_characters) and [`Hans`](https://en.wikipedia.org/wiki/Simplified_Chinese_characters) are two different **written forms** of Chinese characters. Here is a character in different forms: “达”(Hans) and “達”(Hant).

zh-TW like en-GB, which just represents the language's region variety. For example, the word “network” in Hong Kong Chinese (`zh-HK`) is “網絡”, and in Taiwan Chinese (`zh-TW`) is “網路”, all of these are written in Traditional Chinese (`zh-Hant`).
Imagine if English can be written in Cyrillic script, British English is still British English, writing system hasn't affected the language. (Most times `zh-TW` is written in `Hant`, but `Hans` isn't unacceptable.)

Literary Chinese `lzh` like Old English, is an old, literary, terse Chinese variety, also can be written in `Hans` or `Hant`.

> The changes needed to support allowing an unknown language code to just pass through the MetaEditor and survive (as long as the user does not click on it to edit that language value) turned out to be trivial and so I pushed them to master.
> 
> That said, if the user decides to click on the unknown language code inside the MetaEditor to edit it, that value will be lost and replaced by the pull down menu selection of known language codes (iso-696-2 list).
> 
> True support for specific iso-693-3 language codes in Sigil really needs to added based on user supplied statistical data that shows that code is commonly used in epubs and has no equivalent in the iso-693-1 and iso-693-2 lists.
> 
> Hope this helps.

That is what I want, a huge thanks to you!

**Comment by kevinhendricks** [comment]
Thank you for your bug report.  
One final question if you have a free moment:

Wouldn't the form of the character (Hans vs Hant) be determined by the font chosen to represent the characters of the word?  Or am I misunderstanding what you mean by "writing system" and "script"?

**Comment by kevinhendricks** [comment]
Closed as fixed in master.
