### ISSUE TITLE
[Bug]: Forgets history when saved

### ISSUE THREAD

**Issue by LinAGKar** [Sigil-Ebook/Sigil#714]
### Bug Description

As soon as you save the book, the undo history gets wiped. This pretty much renders the undo button unusable, since most of the time the undo history is gonna be completely empty.

### Platform (OS)

Linux

### OS Version / Specifics

OpenSUSE Tumbleweed

### What version of Sigil are you using?

1.9.30

**Comment by dougmassay** [comment]
The undo history is not to be relied upon for much other than an quick accidental deletion. Use the Checkpoint Feature if you need a more reliable, robust way to undo changes (including after saves).
