### ISSUE TITLE
[Bug]: Sigil for Mac, problem in configuration of ePub3

### ISSUE THREAD

**Issue by webpresario** [Sigil-Ebook/Sigil#718]
@BeckyDTP @user-none @kevinhendricks  ### Bug Description

I am working on Sigil for Mac in a technical book. It has some stylesheets. In the Sigil interface, it looks ok. However, when I save as ePub3 it looks desconfigurated. Can you help me to check this issue and maybe fix it, please. Thanks.

I send the repo of the ePub file:

www.librosparakindle.com/bookstore/success/prueba_estadistica/estadisticapreliminar2.epub

### Platform (OS)

macOS

### OS Version / Specifics

High Sierra

### What version of Sigil are you using?

1.9.30

**Comment by kevinhendricks** [comment]
I need more information.  It looks "disconfigurated"  in what way?  With what epub3 e-reader?  Are you using a good epub3 reader?  Many epub2 only e-readers will not understand css3? Some epub e-readers will ignore css if it detects anything it does not understand.  Have you validated your epub with epubcheck?  Have you validated your epub's css? Why do you think this is some type of Sigil bug when Sigil itself shows it as you expect?  It is most likely the fault of a poor or epub2 only e-reader that does not follow the epub3 spec

Getting  help with your epub projects is what our Sigil User forum on Mobileread is all about. You really should be posting your how-to questions there.  The real epub experts are there.  See this site's README..md for the proper urls for Mobileread to get help.
