### ISSUE TITLE
[Bug]: Menus do not reappear after closing certain modal windows

### ISSUE THREAD

**Issue by chrisridd** [Sigil-Ebook/Sigil#724]
### Bug Description

1. Start with no windows open
2. Choose File > New to create a new document
3. Choose Tools > Delete unused media files
4. (Note most menus disappear, only Sigil and File remain)
5. Close the modal window that says "There are no unused image, video or audio files to delete." by pressing "OK"
6. (Note that menus have not changed or reappeared)
7. Click on the document window
8. (Note that menus have reappeared)

This occurs with "Delete unused stylesheet selectors" and possibly others.

It doesn't occur with Plugins > Output > epub3-itizer though, but that opens a different looking window.

### Platform (OS)

macOS

### OS Version / Specifics

13.5 on M1

### What version of Sigil are you using?

2.0.1

**Comment by chrisridd** [comment]
I think this is a regression from Sigil 1.x

**Comment by kevinhendricks** [comment]
This is a known Qt 6.5.2 bug.  I will see if they have a solution for this issue yet.

**Comment by kevinhendricks** [comment]
It does not lose menu items.  Instead it is returning focus back to the main application default menubar and not to the MainWindow.  Still not sure what in Qt causes this.

But I can recreate this issue. 

Luckily, making the MainWindow active is just a single click away which will bring back that's MainWindow's menubar and not the application's default menubar.

So only annoying with no corruption.  

I may try to workaround this in Sigil code to force activate the current MainWindow but waiting for Qt to fix their bug in a future release is probably safer.

Thank you for your bug report.

**Comment by chrisridd** [comment]
Thanks for raising a JIRA with the Qt folks. Waiting to see what they come back with is probably the best approach.

**Comment by kevinhendricks** [comment]
There are actually over 33 places in Sigil that use QMessageBox it a way that is impacted by this bug in Qt.

So I have prepared a wrapper patch tor all these instances.

I will only apply it just before the next release in the eventuality that a proper fix from Qt is not forthcoming by that time.  I have tested it locally on macOS under both arm64 and x86_64 and it prevents the problem and works well.

I will leave this issue open until then to remind me.

**Comment by kevinhendricks** [comment]
As it turns out changes meant for Qt 6.5.3 close on September 5 and since this bug has still not been triaged, it stands no chance of being fixed in the upcoming Qt 6.5.3 unless a miracle happens.

So ai just committed my workaround fix to Sigil master.  So closing this as fixed.

Thank you for your bug report!

**Comment by chrisridd** [comment]
It looks like the underlying bug was fixed in Qt 6.5.4 - is it worth revving Sigil's Qt version and removing Sigil's workaround? Less code is always good (if it works!)

**Comment by kevinhendricks** [comment]
Qt 6.5.4 is not opensource so using it in a Sigil build is not allowed.  If we release a version of Sigil, we would have to release the source to the Qt version which we do not have.

That said, I was able to backport from opensource dev the fixes and will include them in a future release of our patches for Qt 6.5.3.

There is no need remove the work around code as it hurts nothing.p and does its job.  Collecting their use into our Utility.cpp actually makes goo sense and not everyone who uses Sigil can compile their own Qt easily or uses the latest version of Qt.
