### ISSUE TITLE
[Bug]: OSX 10.14.6 

### ISSUE THREAD

**Issue by profjens** [Sigil-Ebook/Sigil#729]
### Bug Description

Won´t start. "on your computer 10.14.6 is installed. However you need at least 10.9.6

### Platform (OS)

macOS

### OS Version / Specifics

10.14.6.

### What version of Sigil are you using?

2.0.1

### Any backtraces or crash reports

```shell
Auf deinem Computer ist macOS 10.14.6 installiert. Das Programm erfordert macOS 10.9.5 oder neuer.
```

**Comment by profjens** [comment]
closed mac os 11 need message is wrong.

**Comment by kevinhendricks** [comment]
Which message is wrong?  From where?

**Comment by profjens** [comment]
I closed the issue. I am at 10.14.6
When I Start SIGIL the following message is generated:

Regards



____________________________________________________________
Prof. Dr. Jens Schulze
Marketing & Vertrieb
Münsterstrasse 265		www.profjens.de <http://www.profjens.de/>
46397 Bocholt				***@***.*** ***@***.***>
02871-2155 864			***@***.*** ***@***.***>.de ***@***.***>
____________________________________________________________

**Comment by kevinhendricks** [comment]
Fixed by update to Sigil master for the next release.
Thank you for your bug report.
