### ISSUE TITLE
[Bug]: Norton Blocking install of Sigil-2.0.2-Windows-x64-Setup.exe

### ISSUE THREAD

**Issue by stuartjmu** [Sigil-Ebook/Sigil#732]
### Bug Description

![image](https://github.com/Sigil-Ebook/Sigil/assets/149164315/f38f32b5-6b1f-4884-9f33-3943019a26ec)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

windows

### What version of Sigil are you using?

2.0.1

**Comment by dougmassay** [comment]
The Windows Sigil installer has ALWAYS deleted certain files from Sigil's own program directory before installing. I have no idea why Norton has suddenly decided this is a problem. Nor do I much care. If Sigil were dangerous, it would not pass muster for winget or chocolatey (which both scrutinize Sigil's installer before accepting each new update). I'm also quite confident that nothing has changed in the way that 2.0.2 installs Sigil compared to past Sigil versions on Windows. Norton is being paranoid IMO.

**Comment by dougmassay** [comment]
If it concerns you overly, uninstall Sigil manually (making sure its program directory is empy) before updating to a newer version of Sigil (no settings will be lost). Then Norton should find nothing to complain about.

For the record: the Lib directory has always been removed prior to installation to avoid problems whenever Sigil's Python gets updated. The content that has always been removed from Sigil's program directory can be viewed in the in last up script that's used to create the Windows installer: https://github.com/Sigil-Ebook/Sigil/blob/master/installer/Sigil.iss#L89

**Comment by dougmassay** [comment]
Seems very silly to me that Norton would ding an installer for diddling files in a program's own directory during an in-place upgrade (using a standard method that Inno provides, no less). But then I gave up using third-party anti-malware software on Windows a long time ago.
