### ISSUE TITLE
[Bug]: Build fails when Qt6 GLESv2 is used because of unneeded cmake files in cmake_extras/

### ISSUE THREAD

**Issue by ggardet** [Sigil-Ebook/Sigil#740]
### Bug Description

Build fails on openSUSE Tumbleweed aarch64 when Qt6 GLESv2 is used because of unneeded cmake files in `cmake_extras/`.
I needed to remove some of them:
```
rm cmake_extras/FindPackageHandleStandardArgs.cmake
rm cmake_extras/FindPython*.cmake
```
Since current cmake provides the required files.

### Platform (OS)

Linux

### OS Version / Specifics

openSUSE Tumbleweed aarch64

### What version of Sigil are you using?

2.0.2

### Any backtraces or crash reports

```shell
[   58s] -- Found GLESv2: /usr/include  
[   58s] CMake Warning at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
[   58s]   Found package configuration file:
[   58s] 
[   58s]     /usr/lib64/cmake/Qt6Gui/Qt6GuiConfig.cmake
[   58s] 
[   58s]   but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
[   58s]   NOT FOUND.  Reason given by package:
[   58s] 
[   58s]   Qt6Gui could not be found because dependency GLESv2 could not be found.
[   58s] 
[   58s]   Configuring with --debug-find-pkg=GLESv2 might reveal details why the
[   58s]   package was not found.
[   58s] 
[   58s]   Configuring with -DQT_DEBUG_FIND_PACKAGE=ON will print the values of some
[   58s]   of the path variables that find_package uses to try and find the package.
[   58s] 
[   58s] Call Stack (most recent call first):
[   58s]   /usr/lib64/cmake/Qt6/QtPublicDependencyHelpers.cmake:111 (find_dependency)
[   58s]   /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreDependencies.cmake:39 (_qt_internal_find_qt_dependencies)
[   58s]   /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake:50 (include)
[   58s]   /usr/lib64/cmake/Qt6/Qt6Config.cmake:174 (find_package)
[   58s]   src/qt6sigil.cmake:27 (find_package)
[   58s]   src/CMakeLists.txt:685 (include)
[   58s] 
[   58s] 
[   58s] CMake Warning at /usr/lib64/cmake/Qt6/Qt6Config.cmake:174 (find_package):
[   58s]   Found package configuration file:
[   58s] 
[   58s]     /usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake
[   58s] 
[   58s]   but it set Qt6WebEngineCore_FOUND to FALSE so package "Qt6WebEngineCore" is
[   58s]   considered to be NOT FOUND.  Reason given by package:
[   58s] 
[   58s]   Qt6WebEngineCore could not be found because dependency Qt6Gui could not be
[   58s]   found.
[   58s] 
[   58s]   Configuring with --debug-find-pkg=Qt6Gui might reveal details why the
[   58s]   package was not found.
[   58s] 
[   58s]   Configuring with -DQT_DEBUG_FIND_PACKAGE=ON will print the values of some
[   58s]   of the path variables that find_package uses to try and find the package.
[   58s] 
[   58s] Call Stack (most recent call first):
[   58s]   src/qt6sigil.cmake:27 (find_package)
[   58s]   src/CMakeLists.txt:685 (include)
[   58s] 
[   58s] 
[   58s] CMake Error at src/qt6sigil.cmake:27 (find_package):
[   58s]   Found package configuration file:
[   58s] 
[   58s]     /usr/lib64/cmake/Qt6/Qt6Config.cmake
[   58s] 
[   58s]   but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
[   58s]   FOUND.  Reason given by package:
[   58s] 
[   58s]   Failed to find required Qt component "WebEngineCore".
[   58s] 
[   58s]   Expected Config file at
[   58s]   "/usr/lib64/cmake/Qt6WebEngineCore/Qt6WebEngineCoreConfig.cmake" exists
[   58s] 
[   58s] 
[   58s] 
[   58s]   Configuring with --debug-find-pkg=Qt6WebEngineCore might reveal details why
[   58s]   the package was not found.
[   58s] 
[   58s]   Configuring with -DQT_DEBUG_FIND_PACKAGE=ON will print the values of some
[   58s]   of the path variables that find_package uses to try and find the package.
[   58s] 
[   58s] Call Stack (most recent call first):
[   58s]   src/CMakeLists.txt:685 (include)
[   58s] 
[   58s] 
[   58s] -- Configuring incomplete, errors occurred!
[   58s] error: Bad exit status from /var/tmp/rpm-tmp.00LiTK (%build)
```

**Comment by dougmassay** [comment]
I have zero experience building anything on aarch64, let alone Sigil. However... Arch Linux seems to provide aarch64 builds of Sigil without any major patching.

So did your build work after that? The error log you posted doesn't really have any relation to the cmake_extras files you removed.

**Comment by kevinhendricks** [comment]
I can see no relation to the requested change.  Your real issue is here:

58s] 
[   58s]   Qt6Gui could not be found because dependency GLESv2 could not be found.

It found the headers but not the lib so no gui which leads to cmake failure.

**Comment by dougmassay** [comment]
I guess it's within the realm of possibility that a newer FindPackageHandleStandardArgs that comes with the distro-supplied cmake for arm64 might find the Qt6 modules Sigil's needs. But I don't think we can rely upon all distros/archhitectures having the proper cmake_extras.

More likely, the user simply needs to provide the -DQt6_Dir location (as described in the build instructions) to properly find the Qt6 pieces needed.

**Comment by dougmassay** [comment]
I'm also unclear on what the FindPython extra has to do with the errors provided??

**Comment by ggardet** [comment]
> I'm also unclear on what the FindPython extra has to do with the errors provided??

This is needed as additional fixes as I had further errors after fixing the 1st issue.

> I can see no relation to the requested change. Your real issue is here:
> 
> 58s] [ 58s] Qt6Gui could not be found because dependency GLESv2 could not be found.
> 
> It found the headers but not the lib so no gui which leads to cmake failure.

There is a mismatch between GLESv2 and GLESV2 in the detection. With current cmake, there is no reason to provide *.cmake overlays, especially, when they are broken. Using the ones from cmake itself just works.

https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html

**Comment by dougmassay** [comment]
But we support versions of cmake (as well as platforms) that don't always
provide these extras. To say they're not needed is to say they might not be
needed by you. Not everyone is using a cutting edge system like Tumbleweed
or Arch.

**Comment by dougmassay** [comment]
I'm also guessing that you could have used the -DTRY_NEWER_FINDPYTHON3=1 directive (found at the end of the Linux build instructions) when initially configuring cmake to avoid whatever errors you were getting in that regard. It doesn't use the one in cmake_extras/.

**Comment by kevinhendricks** [comment]
And that Find_Python cmake I believe was specifically modified to find a suitable python within your PATH.  If that causes "issues" later on, you need to adjust your path or its order accordingly.  Not remove it as it is needed in other platforms.The issue for you is the case difference between GLESV2 and GLESv2? Is that correct?On Feb 26, 2024, at 10:24 AM, Doug Massay ***@***.***> wrote:﻿
But we support versions of cmake (as well as platforms) that don't always

provide these extras. To say they're not needed is to say they might not be

needed by you. Not everyone is using a cutting edge system like Tumbleweed

or Arch.

**Comment by kevinhendricks** [comment]
If so, and as long as the newer FindPackageHandleStandardArgs from cmake works in cmake 3.0.5 and hopefully earlier, we could pull it or case comparison related fixes from it into our internal cmake_extras build.

**Comment by dougmassay** [comment]
I agree that removing the extra cmake files should be unnecessary. The PythonFind can definitely be overridden with configure options already. If there's a simple casing issue with GLESv2, we can fix that (unless it breaks compatibility with older versions of Qt5/CMake on certain platforms).

**Comment by kevinhendricks** [comment]
@dougmassay, 
Do you want me to update our version of FindPackageHandleStandardArgs.cmake to match the version in cmake-3.22?
It should not impact our minimum supported cmake version to build Sigil.   It may not solve his build issue but should not hurt anything either afaict.

**Comment by ggardet** [comment]
Adding https://github.com/Sigil-Ebook/Sigil/commit/12701ca7f40e90769515729717a8bf107bda22fc on top of release 2.0.2 + `-DTRY_NEWER_FINDPYTHON3=1` resolves my problem. Thanks!

**Comment by kevinhendricks** [comment]
Thank you for your bug report and testing.
