### ISSUE TITLE
[Bug]: Windows 11 pro - Sigil closed

### ISSUE THREAD

**Issue by vanessamartins002** [Sigil-Ebook/Sigil#743]
### Bug Description

Hello!
I have a problem with the latest versions of Sigil (2.0.1, 2.0.2, 2.0.0). My machine is Windows 11 Pro. I open Sigil and when I try to open an already finished epub, it closes the program. Does anyone know what can it be?

Thanks!

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 11 Pro

### What version of Sigil are you using?

2.0.1, 2.0.2, 2.0.0

**Comment by dougmassay** [comment]
It almost certainly has to be something wrong with the epub(s). We don't ever want Sigil to crash, but we can't always foresee all the ways someone might create non-compliant epubs. Can you check one of the epubs that causes Sigil to close with an online version of  EpubCheck (and report any errors)?

https://draft2digital.com/book/epubcheck/upload

**Comment by dougmassay** [comment]
You also might have 3rd-party File Explorer extensions installed that are notorious for crashing some programs. Are you opening Sigil first and then using File->Open? Or are you double-clicking on an epub file in the file explorer?

**Comment by vanessamartins002** [comment]
Hello, Doug.  The epubs open in Sigil on another computer.  I'm opening Sigil and asking to open the Epub there, going to files, open...

**Comment by kevinhendricks** [comment]
Perhaps it is an issue with your graphics card driver.  You could try going to Sigil's Preferences and turn off the graphics accelerator, then restart Sigil to see if that allows you to open the epub.

**Comment by vanessamartins002** [comment]
Hi, Kevin. Thanks for your help. I'm turn off the graphics accelerator e still with the same problem. =/

**Comment by kevinhendricks** [comment]
Is it just one specific epub?  Perhaps it is tickling a platform specific Qt bug.  Is the problem epub in the public domain that you could point us to?

Is the machine that runs Sigil that works on Windows 11 too?

**Comment by vanessamartins002** [comment]
These are all the e-pubs that I try to open in it. 

They have been validated in epubchecker and open on another computer (which has Windows 11 Home). 

Therefore, I believe the problem is with the Windows version (the computer causing the problem is Windows 11 Pro, version 23H2, pack 100-0.22687.1000.0).

**Comment by dougmassay** [comment]
Have you tried exempting the Sigil executable and program folder from any antivmalware programs (including the built-in Windows Defender).

You could also try backing up and deleting Sigil's preferences folder to see if there's some kind of corruption there. I don't have access to any Windows 11 machines to help debug unfortunately.

**Comment by kevinhendricks** [comment]
But Sigil itself opens and sets up an empty epub just fine.  Then using file open on any epub it then fails.  Is that correct?

**Comment by vanessamartins002** [comment]
Sigil opens a new epub, opens files alone in HTML. It just doesn't open files with the .epub extension.

**Comment by kevinhendricks** [comment]
Sounds like a bad third party os system extension that is probably trying to show a preview the epub is causing Sigil to crash.  Try rebooting your machine into safe mode and run Sigil and open that epub.  If that works then it is a bad os extension.  There are tools that can help narrow down the broken extension.

**Comment by kevinhendricks** [comment]
An epub file is nothing more then a specially constructed zip file.  So something is trying to unzip it and causing the crash.

**Comment by dougmassay** [comment]
Perhaps the .epub extension has mistakenly been flagged as a security risk on that machine?

A problematic third-party file explorer extension is more likely, though.

**Comment by vanessamartins002** [comment]
Faced with the problem, I installed other Windows on the computer (Windows 11, 10...) and it didn't solve the problem.

According to the error log, the Path of the failed module is C:\Program Files\Sigil\Qt6Gui.dll

The machine I'm using is this: https://www.br.vaio.com/vaio-fh15-vjfh52f11x-bsku382-3343876/p
[log.txt](https://github.com/Sigil-Ebook/Sigil/files/14603409/log.txt)

**Comment by kevinhendricks** [comment]
I very much doubt that the version of Windows is the issue. The problem is typically third party system extensions that are many times bundled with Windows by the computer manufacturer.  Some of these use old Qt versions dynamically loaded that cause conflict with newer versions of Qt.

So please read up on how to reboot your computer in safe mode and then launch Sigil and load your epub.  That will tell us if the problem software is a system extension loaded by the computer maker.

**Comment by dougmassay** [comment]
It could still be video card driver-related. Laptop manufacturers often use
their own drivers rather than the OEM card manufacturer's.

**Comment by vanessamartins002** [comment]
Now I discovered that this only happens with some epubs. The same epub opens on a computer but does not open on a notebook. I don't know what could be wrong, epubs pass the validator and go up to reading platforms (like Amazon and iBooks) without any errors.

**Comment by kevinhendricks** [comment]
Again, please reboot into safe-mode on your computer and test Sigil and report back.

**Comment by vanessamartins002** [comment]
Even doing it in safe mode, it closes Sigil when I try to open the epubs.

**Comment by kevinhendricks** [comment]
Must then be graphics card or driver (perhaps opengl driver?) related.  I assumed you have already told your Anti-virus/Defender to leave Sigil alone (trust it)

**Comment by dougmassay** [comment]
> Faced with the problem, I installed other Windows on the computer (Windows 11, 10...) and it didn't solve the problem.

Just to make sure I understand correctly: you have multiple versions of Windows installed on the same laptop? Is it a multi-boot situation, or are you running virtual Windows machines and installing Sigil on them?

**Comment by vanessamartins002** [comment]
Yes, I already told the antivirus to leave it alone! 
But even so, I still have the problem. 
As I believed the problem was with Windows, I installed another version to test. however, the same error occurred.
The issue now is that only the epubs files that I created do not open. But these files are already validated and running perfectly, they just won't open on this computer.

**Comment by vanessamartins002** [comment]
Thank you everyone for your help. 

 I discovered that the issue is only with woff fonts.  When I try to add a woff font to epub or a file epub that has woff fonts, Sigil stops working.
According to the crash log, the error occurs in the Qt6Gui.dll file. I've already tried using Windows Safe Mode, and the same thing happens.
All other computers open the epub files that have the woff fonts without any problems, it's just this new one that doesn't open. I put several Windows to test (10, 11 home, 11 pro) and none of them worked, so I believe the problem is not in Windows

**Comment by dougmassay** [comment]
You've still not explained how exactly your putting "several Windows to test" on this one computer.

**Comment by dougmassay** [comment]
I'm trying to eliminate the possibility that you're using virtual machines (and thus virtual video drivers).

**Comment by kevinhendricks** [comment]
And woff fonts have no recent bugs related to it in the Qt bug database over the last couple years. So this is not an issue reported to Qt.  Qt should just fine with epubs with woff fonts.  It has to be an issue with how your specific machine s set up.  

Perhaps something specific to a font previewer?  Please run those specific woff fonts through a font validator to make sure they are not corrupted.

**Comment by kevinhendricks** [comment]
I noticed that later versions of Windows 10 and Windows 11 now has a setting that controls blocking or unblocking use of untrusted fonts:

https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/feature-to-block-untrusted-fonts

You should make sure your problem computer does NOT block untrusted fonts as woff fonts are not native to Windows.

Please verify this feature to block untrusted fints is not enabled, reboot and re-run the test.

**Comment by kevinhendricks** [comment]
Okay, based on the discusion in our MobileRead forum, we now have a testy build that should prevent the Qt bug with woff and woff2 fonts.

See: https://github.com/kevinhendricks/BuildSigilOnMac/releases/

Download: Sigil-2.1.0-Windows-x64-Setup.exe

Please download and install this version and verify it fixes your issue and let us know the outcome.  

Assuming it works for you  we can go ahead and close this issue as fixed.  The fix will appear in our upcoming release after the holiday (after the end of March).

**Comment by vanessamartins002** [comment]
> Ok, com base na discussão em nosso fórum MobileRead, agora temos uma versão de teste que deve evitar o bug do Qt com fontes woff e woff2.
> 
> Veja: https://github.com/kevinhendricks/BuildSigilOnMac/releases/
> 
> Baixar: Sigil-2.1.0-Windows-x64-Setup.exe
> 
> Baixe e instale esta versão e verifique se ela corrige seu problema e informe-nos o resultado.
> 
> Supondo que funcione para você, podemos prosseguir e encerrar o problema como corrigido. A correção aparecerá em nosso próximo lançamento após o feriado (após o final de março).

Thank you so much, Kevin!

Here, with this version, I was able to open all epubs with the woff font.
