### ISSUE TITLE
[Bug]:  Crash on Print Preview When Margins are Changed 

### ISSUE THREAD

**Issue by Noryub** [Sigil-Ebook/Sigil#744]
### Bug Description

Title says everything.
Crash happens even if there is no text and the page is empty.

Unfortunately I don't know how to get backtraces or crash reports from Sigil, everything I get is [Segmentation Fault] from the terminal.

However, this error should be easy to reproduce.

No plugins or complements installed.

### Platform (OS)

Linux

### OS Version / Specifics

Debian 12 Bookworm Stable

### What version of Sigil are you using?

2.0.2 Qt6 6.4.2

**Comment by Noryub** [comment]
**Correction**: Crash happens inside Page Setup Window just after clicking "Ok", no need to change margins.

**Comment by dougmassay** [comment]
I'd need to set up a virtual Debian machine it doesn't crash with with Qt6.5 or Qt6.6 on Arch. I do remember Qt6.4 being pretty polluted with crash-related widget stuff, though.

**Comment by dougmassay** [comment]
Are you building Sigil yourself, or are those the packages/versions of Sigil/Qt6 provided by your distro's repositories?

**Comment by Noryub** [comment]
> Are you building Sigil yourself, or are those the packages/versions of Sigil/Qt6 provided by your distro's repositories?

I build Sigil myself.
The libraries of Qt6 came from Debian official repositories.
Optional libraries where installed too. 

[I saw that Qt6.4 was ok in the instructions](https://github.com/Sigil-Ebook/Sigil/blob/master/docs/Building_on_Linux.md#general-overview) and I went with that, curious that [PageEdit recommends Qt6.6](https://github.com/Sigil-Ebook/PageEdit?tab=readme-ov-file#on-linux)

Maybe I should rebuild with Qt5 and stick with that? Qt6.6 will not do on Debian Stable.

**Comment by kevinhendricks** [comment]
Our next release builds of Sigil and PageEdit will both be based on Qt 6.6.2 for Windows and Mac.   We both test on Linux with Arch and on Manjaro which both have access to Qt 6.6.x.

Previous releases of Qt 6.5.x, and Qt 6.4.x have a large number of crashing bugs reported to Qt.  This is why we are moving to Qt 6.6.2 or later.

You can still build both Sigil and PageEdit with Qt 5.15.x or later with the correct build flags.

**Comment by kevinhendricks** [comment]
FWIW, Qt 6.6.2 is available in experimental for Debian.

https://packages.debian.org/source/experimental/qt6-base

**Comment by Noryub** [comment]
> Our next release builds of Sigil and PageEdit will both be based on Qt 6.6.2 for Windows and Mac. We both test on Linux with Arch and on Manjaro which both have access to Qt 6.6.x.
> 
> Previous releases of Qt 6.5.x, and Qt 6.4.x have a large number of crashing bugs reported to Qt. This is why we are moving to Qt 6.6.2 or later.
> 
> You can still build both Sigil and PageEdit with Qt 5.15.x or later with the correct build flags.

> FWIW, Qt 6.6.2 is available in experimental for Debian.
> 
> https://packages.debian.org/source/experimental/qt6-base

Will try it.
I will close the issue, after all, is not related to Sigil.

Thanks for helping me.

**Comment by dougmassay** [comment]
If this can be reproduced and worked around easily enough, I'd still like to diagnose/fix it if possible. But I have a Debian 12 Bookworm Virtual machine with Qt6.4.2 and I can't get get Sigil 2.0.2 to crash when using the Print Preview as you describe. What are you using for Sigil source code? The very latest Github HEAD or a certain tagged version?

**Comment by dougmassay** [comment]
For the record: I've tried both the Sigil 2.0.2 tagged source and the latest Github HEAD and can't reproduce the crash on Debian 12 Bookworm with the system-supplied Qt6.4.2. This is on a Gnome DE.

**Comment by dougmassay** [comment]
Another thing to consider is that I have no quick way of setting up a physical printer on this virtual machine. The default printer is the system provided Print To PDF Printer. If you have a physical default printer set up, that could possibly change things.
