### ISSUE TITLE
[Bug]: Reformatting of html converts small non-breaking space

### ISSUE THREAD

**Issue by plastikschnitzer** [Sigil-Ebook/Sigil#745]
### Bug Description

Steps to reproduce:

put a narrow non-breaking space into the code with `&#x202f;`
go to tools -> reformat and clean html
see conversion of narrow non-breaking spaces to a character that just shows an underscore

Expected behavior:

Narrow non breaking space should be untouched like normal non-breaking space

### Platform (OS)

Linux

### OS Version / Specifics

Ubuntu 22.04

### What version of Sigil are you using?

1.9.2

**Comment by dougmassay** [comment]
You'll find a setting in Sigil Preferences call Preserve Entities where you'll need to add the list of entities you want to preserve. Note, however, that the narrow non-breaking space entity is currently being converted to a narrow non-breaking space character.

**Comment by dougmassay** [comment]
The underscore is to let you know that there's a special invisible character there. In this case, a narrow non-breaking space character. 

This is not a bug. Sigil is operating as expected. Protect the entities you wish to preserve (as entities) by adding them to the Preserve Entities list in preferences.
