### ISSUE TITLE
[Bug]: Icon Doesn’t blend with MacOS.

### ISSUE THREAD

**Issue by Lululalu** [Sigil-Ebook/Sigil#746]
### Bug Description

It's simple, just to add a custom icon to MacOS version.
There are two options on the zip below.

[SigilMacIcons.zip](https://github.com/Sigil-Ebook/Sigil/files/14846790/SigilMacIcons.zip)

### Platform (OS)

macOS

### OS Version / Specifics

Sonoma

### What version of Sigil are you using?

2.1.0

**Comment by dougmassay** [comment]
Please don't use Sigil's bug report system to ask for aesthetic changes. Non-bug reports will be closed.
