### ISSUE TITLE
[Bug]: font appears blurry in wayland environment preview

### ISSUE THREAD

**Issue by douglarek** [Sigil-Ebook/Sigil#752]
### Bug Description

In wayland environment, the font appears very blurry when previewing the page. there is no issue in the X11 environment.

![image](https://github.com/Sigil-Ebook/Sigil/assets/1488134/757d376d-0c30-4e80-af97-103564626f27)

test file: [sjsjz.tar.gz](https://github.com/Sigil-Ebook/Sigil/files/15013259/sjsjz.tar.gz)

### Platform (OS)

Linux

### OS Version / Specifics

Manjaro/KDE 6.0.4

### What version of Sigil are you using?

2.1.0

**Comment by kevinhendricks** [comment]
We changed nothing font related that would cause fuzziness.  Perhaps a Qt version issue?  Or a Wayland issue? Bad Anti-aliasing issue?

Use Sigil's About menu to see which Qt Version you are using and report it here.

I will run your test case on macOS and my Manjaro KDE X11 box to see what it shows?

**Comment by dougmassay** [comment]
I'm not seeing anything particularly blurry in the screenshot. But then I
don't know how that font appears outside of Sigil's Preview. I also have no
machines with distros that support Wayland to test on.

**Comment by kevinhendricks** [comment]
It looks just fine on macOS and on Manjaro Linux KDE X11.  I stay far away from wayland so I have nothing that will work using it.

My guess is it is one of the hundreds of wayland bugs dealing with either fonts or fractional scaling that have ben reported over the last couple of years.  It could also be a Qt bug but I searched Qt's All Issues with wayland and nothing obvious jumped out.

I am sorry but we have no way to recreate what you are seeing.  Can you try running Sigil within XWayland and see if the problem persists?  Alternatively change your display to not use fractional scaling (use 100% or 200% not say 125%) and see if the problem persists.

There is no code inside the Sigil project itself that can cause this issue.  Preview is simply a QtWebEngineView widget.

It does not appear to be an embedded font issue unless it is an interaction of font and fontengine.  Again neither of which Sigil controls.

**Comment by dougmassay** [comment]
They all use Qt's implementation of Google's WebEngine to render (x)html.

**Comment by kevinhendricks** [comment]
I am going to close this as the bug is not in Sigil code but instead in wayland or Qt.
So I would strongly recommend making a bug report with Qt if you want to get anything fixed.   They will ask for a sample program to illustrate the bug.  I have one I used for earlier Qt font bugs that could be easily modified to load your font in  QWebEngineView (the widget we use for Preview). I can post it here for you if you want.

Just let me know.
