### ISSUE TITLE
Adding clip to a piece of text containing angular brackets breaks escape

### ISSUE THREAD

**Issue by bogdane** [Sigil-Ebook/Sigil#76]
Hi.
First I would like to thank you for the wonderful software you are developing.

I encountered an (unexpected) bug today, using Sigil 0.8.6, in Book View. How to reproduce:
1. In a new file, write a text containing angle brackets < and >, for example: "You may embed a video in html using the <embed> tag". Sigil properly escapes the angular brackets as &lt; and &gt;, as expected.
2. Create a new clip, with a content like "<span class="code">\1</span>". Apply the clip to the "<embed>" part of the written text. It vanishes. Looking at Code View, I see Sigil has changed back the escaped angular brackets to real angular brackets, thus inserting a html entity.

**Comment by bogdane** [comment]
<embed> tag. I see GitHub is eating my text...

**Comment by bogdane** [comment]
1. In a new file, write a text containing angle brackets < and >, for example: "You may embed a video in html using the \<embed> tag". Sigil properly escapes the angular brackets, as expected.
2. Create a new clip, with a content like \<span class="code">\1\</span>.
3. Apply the clip to the "\<embed>" part of the written text. It vanishes. Looking at Code View, I see Sigil has changed back the escaped angular brackets to real angular brackets, thus inserting a html entity.

**Comment by user-none** [comment]
Looks like what's happening is the clips are converting entities to characters before outputting the final clip.

**Comment by bogdane** [comment]
Yes, something along that line. I observed something right now: it only happens if I use Book View. In Code View it is working ok.

**Comment by kevinhendricks** [comment]
Closing this as BookView has been removed from Sigil and my testing shows this works properly in CodeView.

Sorry it took so long on this.
