### ISSUE TITLE
[Bug]: Item id does not change with the file's name anymore

### ISSUE THREAD

**Issue by theoguedes** [Sigil-Ebook/Sigil#760]
### Bug Description

When a file's name is changed the <item> id on the content.opf remains as the previous file's name.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10

### What version of Sigil are you using?

2.2.1

**Comment by kevinhendricks** [comment]
Not an bug.  It is working as designed.  See this discussion in our user Forum on Mobileread:

https://www.mobileread.com/forums/showpost.php?p=4432981&postcount=52

and 

https://www.mobileread.com/forums/showpost.php?p=4432997&postcount=53

and then

https://www.mobileread.com/forums/showpost.php?p=4433098&postcount=56

We are looking at adding a new tool to the Sigil tool menu to rebase all manifest ids on current names for people who think this matters (it does not - a valid unique id is a valid unique id - there is no spec to base this off the file name just a habit/expedient Sigil used to use) but it is still in the development stage and will not appear until a future release sometime.

**Comment by kevinhendricks** [comment]
If you are okay with command line tools and using python, see this post for a developmental routine to take an opf and update all manifest item ids to be based on file names:

https://www.mobileread.com/forums/showpost.php?p=4433568&postcount=58

It will probably form the basis of a future Sigil tool  called something along the lines of "Rebase Manifest Ids on Filenames" or "Update Manifest Ids using Filenames".

**Comment by kevinhendricks** [comment]
The Rebase OPF Manifest IDs based on Current Filenames has now been added to Sigil in Sigil-2.3.0 and later.

**Comment by theoguedes** [comment]
> The Rebase OPF Manifest IDs based on Current Filenames has now been added to Sigil in Sigil-2.3.0 and later.

I saw it today <3
Already updated!
Thanks a lot!

**Comment by kevinhendricks** [comment]
If you do a lot of renaming, you can wait and run this tool once after you are happy with all your filenames.p (or multiple times as desired).
