### ISSUE TITLE
Ransonware activity

### ISSUE THREAD

**Issue by BethAnn47** [Sigil-Ebook/Sigil#761]
### Bug Description

I get an intermittent warning from Trend Micro of an attempted Ransonware attack. Is there a fix for that?

I can't get the full name of the files, but they're in [user]/appdata

### Platform (OS)

Windows (Default)

### OS Version / Specifics

11

### What version of Sigil are you using?

2.2.0

**Comment by dougmassay** [comment]
It's a false positive. We can't fix their dumb for them. Our code is
opensource--reviewable by anyone. So you can trust it and install anyway,
or install via the winget or Chocolatey repositories. They verify the
installers. Or you can wait until there's more downloads of the installer,
and it will stop warning you.

**Comment by BethAnn47** [comment]
Sorry to waste your time, but thank you.

**Comment by dougmassay** [comment]
Sorry. I didn't mean to imply you were wasting my time. I just grow weary
of 3rd-party Windows anti-malware (and often Windows itself) popping
warnings intended to scare people away from opensource software (and trying
to force opensource developers into paying to have their software
whitelisted.

You're fine. It's me that's jaded. :)
