### ISSUE TITLE
[Bug]: Unable to manage epub3 with fixed layout

### ISSUE THREAD

**Issue by GEORGEJUNGCOCAINE** [Sigil-Ebook/Sigil#785]
### Bug Description

Unable to manage epub3 with fixed layout.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows10

### What version of Sigil are you using?

Current

**Comment by dougmassay** [comment]
So far as I know, you can edit fixed-layout epubs to your heart's content with Sigil. Preview isn't likely to show them properly, but that's not a bug. It's an unsupported feature.

**Comment by GEORGEJUNGCOCAINE** [comment]
> that's not a bug. It's an unsupported feature.

Shoujld I report it in a different thread then?
Thnx

**Comment by dougmassay** [comment]
Feature requests should be made in Sigil's user support forums at MobileRead.com. The GitHub issue database is reserved for bugs. The main README has all the details/links for asking questions, or suggesting new features.

**Comment by kevinhendricks** [comment]
Yes support for viewing fixed layout in a Preview window that can be any size and easily changed in size is not on our agenda.  Fixed layout epubs are inferior to existing pdf technology and really not something we plan to ever spend any time on supporting in Preview in Sigil.

That said, if you detach Preview into its own window, you may be able to manually resize it to work with your fixed layout size but support for Preview of facing pages and rotations would still not exist as those are reader implemented and dependent.
