### ISSUE TITLE
[Bug]: Dry Run Replace All table doesnt memorize the last column width 

### ISSUE THREAD

**Issue by Palloxin** [Sigil-Ebook/Sigil#787]
### Bug Description

![ne](https://github.com/user-attachments/assets/dd9e51d7-e2f0-4dba-9885-605d0aac316a)
These columns. Every time i open the Dry Run Replace All table the column widths go back to deafult size and I have to re-adjust them. It should be memorized.

How to reproduce:
1. input a regex, trigger the dry run by keeping pressed SHIFT and then this(image below)
![ine](https://github.com/user-attachments/assets/212d1ed5-4a65-4f49-9fc5-fa715f0cea65)
2. custom the columns width
3. close the dry run table.
4. re-open the dry run table.

The width return to default, it should memorize what I set last time I changed it.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10 

### What version of Sigil are you using?

2.3.1

**Comment by kevinhendricks** [comment]
Why?  They are auto-sized for the column contents.  Each time you start Dry Run Replace you have different regex p, different before and after contents.  Using the previous column size is guaranteed not to be correct.

So auto-sizing the columns based on current contents is the right option here.  So not a bug.

**Comment by Palloxin** [comment]
1. my screen is small.
2. The dry run table was used tp compare changes from another epub, so i had to divide the screen between these two. It would be cool to have a checkbow to say "keep column width modifications"

Thank you for your patience.

**Comment by kevinhendricks** [comment]
That was not the design for that Dialog.  If you have two versions of the same epub, simply Checkpoint the first then load the second and use the Checkpoint cmpare to see all changes.

**Comment by kevinhendricks** [comment]
You do know that the context pulldown (ie. 10, 20, 30, etc) basically contols the width of the Before and After columns, right?

But we are *not* going to be adding features or controls to enable misusing this dialog simpler for one user.

That said... if you build your own Sigil from source you can of course change anything you want, that is the power of open source.
