### ISSUE TITLE
[Bug]: Error Python in ubuntu 24.04

### ISSUE THREAD

**Issue by dacorsa** [Sigil-Ebook/Sigil#788]
### Bug Description

Ho guys i compile well Sigil but when i run i have this:
Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/usr/local/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 17, in <module>
    from lxml import etree

ModuleNotFoundError: No module named 'lxml'

### Platform (OS)

Linux

### OS Version / Specifics

ubuntu 24.04

### What version of Sigil are you using?

latest code

**Comment by dacorsa** [comment]
It's already installed this:
python3-dev python3-pip python3-lxml python3-six python3-css-parser python3-dulwich python3-pil.imagetk python3-html5lib python3-regex python3-pillow python3-cssselect python3-chardet

**Comment by dacorsa** [comment]
same error :
Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/usr/local/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 17, in <module>
    from lxml import etree

ModuleNotFoundError: No module named 'lxml'

**Comment by dougmassay** [comment]
Then your distro has installed those modules in a location that Sigil's embedded python cannot find them. Were they installed using sudo as per the instructions?

Also verify that you are launching Sigil via the /usr/local/bin/sigil script and not something else.

**Comment by kevinhendricks** [comment]
Could your system have more than one version of python installed?

**Comment by dacorsa** [comment]
same error :
Traceback (most recent call last):

  File "/usr/local/share/sigil/python3lib/xmlprocessor.py", line 6, in <module>
    from sigil_bs4.builder._lxml import LXMLTreeBuilderForXML

  File "/usr/local/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 17, in <module>
    from lxml import etree

ModuleNotFoundError: No module named 'lxml'

**Comment by dacorsa** [comment]
> Could your system have more than one version of python installed?

yes python3.12 and python3.13

**Comment by kevinhendricks** [comment]
Then that is your problem.  Sigil is finding one of them but the other is the one with lxml module installed in it.

You need to figure out which one has all the modules you installed (ie the system one) that are needed by Sigil and remove the other completely.

**Comment by dougmassay** [comment]
The cmake configure command should output the version of the Python it found to use.

But yes, whether it defaulted to the older or newer Python, you'll have to make sure the modules are installed to the same version that Sigil is compiled against.

The build instructions also have notes on how to force Sigil to be built against a specific Python version.

**Comment by dacorsa** [comment]
> Could your system have more than one version of python installed?

yes python3.12 and python3.13

**Comment by dacorsa** [comment]
> Then that is your problem. Sigil is finding one of them but the other is the one with lxml module installed in it.
> 
> You need to figure out which one has all the modules you installed (ie the official ubuntu system one) that are needed by Sigil and remove the other completely.
> 
> Or install all the required modules in both.
> 
> Or temporarily hide one completely (hide all its .so files and executables) and rebuild Sigil against the official system one after making sure it has the proper modules.

yes removed the python3.13 and works, thanks, but why Sigil not use the default python instead the newer?

i have the symbol link python3 -> python3.12 not 3.13

Thanks, best regards

**Comment by dacorsa** [comment]
it's possible to modify Sigil code to use the default version of python (symbol link in /usr/bin/python3)

**Comment by dougmassay** [comment]
As I mentioned earlier: there are cmake defines in the advanced section of Sigil's build instructions that allow you to target a specific version of Python on your system. The cmake find_python module used by Sigil's build process behaves differently on different platforms. On Linux, the default behavior seems to be to find/use the most recent version of Python. When multiple versions of Python 3 exist on your system, the best way to handle it to use the cmake definites I mentioned.

https://github.com/Sigil-Ebook/Sigil/blob/master/docs/Building_on_Linux.md#cmake-options

> The following three cmake options are used to manually specify which Python3 you want to use when building Sigil instead of relying on the included cmake utilities to try and automatically find a suitable version.

**Comment by dougmassay** [comment]
Glad you got it working. I''m going to close this issue as the way to avoid this is explained in the build instructions.

**Comment by dacorsa** [comment]
ok thanks !
