### ISSUE TITLE
Generated TOC not showing in iBooks

### ISSUE THREAD

**Issue by gudh** [Sigil-Ebook/Sigil#79]
Hi, thanks for the amazing tool!

However, I came across a problem:

I generated TOC (Table of Contents) successfully with the help of [this video](https://www.youtube.com/watch?v=4SC10eTkaTk), and I am using latest 0.8.6 on a Mac

However, the table of content fail to show up in iBooks

Any ideas?

**Comment by kevinhendricks** [comment]
This is not a Sigil issue.  File an issue with iBooks

**Comment by daniel-j** [comment]
@gudh Please try the Sigil plugin I made that fixes the toc for the broken iBooks on iOS: https://github.com/daniel-j/sigil-plugin-ibooksfix
