### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by bumblebritches57** [Sigil-Ebook/Sigil#80]
Currently Sigil removes the OEPBS folder, and moves content to different folders depending on content (such as Text) can this be changed to put Text, Fonts, etc under the OEPBS folder?

Also, this is a totally separate issue but I was wondering if you guys could keep Sigil from moving around the iTunes added files like iTunesArtwork, iTunesMetadata.plist, because they HAVE to be in the root folder for iTunes, and iBooks to find them.

**Comment by kevinhendricks** [comment]
Hi,
Sigil does not remove the OEBPS folder.  It should be creating Text, Images, Fonts folder inside of it.

Which version of Sigil and whose build are you using?

Kevin

**Comment by bumblebritches57** [comment]
Just the standard build available on the website, I used it a couple months ago, but it completely removed the OEPBS folder and replaced it with text, etc. I can upload an epub I used it on if you want to see for yourself.

**Comment by kevinhendricks** [comment]
Hi,

Please don’t confuse the folders showing in the left side of the Sigil screen with how the epub is exactly laid out.  All of those folders are in fact written into an OEBPS folder inside the created epub.  Simply rename any epub created by Sigil from .epub to .zip and use any unzip tool to open the epub itself and see the exact folder structure.

Kevin

**Comment by bumblebritches57** [comment]
No no no, I opened the output epub with 7-zip and examined it's contents myself, there is no OEPBS folder.

**Comment by kevinhendricks** [comment]
If you are 100% positive this epub was generated by a Save-As done in Sigil 0.8.6 or later, then please post a link to it.

**Comment by kevinhendricks** [comment]
Closing as can't recreate this in any version of Sigil on any platform.
