### ISSUE TITLE
Feature Request: Warn if an EPUB3 is openend with Sigil

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#81]
As Sigil is my main tool for working/updating a huge catalogue of EPUB. A small portion of these are EPUB3 files. As sigil opens them without complaint I often are unaware of my mistake and sigil rewrites/destroys the EPUB3 on save.
I'd be great to have Sigil refuse to open an EPUB3 as long as it is not really aware of the Format.

Thanks alot! 
Georg

**Comment by kevinhendricks** [comment]
Hi,
Sigil 0.8.x and earlier is an epub2 editor.  That said, current master should allow Sigil to load an epub3 with no harm.  At least theoretically!  Some of the automated tools such as Metadata editing still require some work to prevent epub3 info from being lost.  Support for loading and saving epub3 is my goal for the first Sigil 0.9 release when it happens.  There is still much work to be done in that regards.  The Sigil 0.8.7 release is the final stable release for that series.

Your only workaround now is to use a simple python or other script to identify and filter your epubs by type until we reach that point. 

Thanks,

KevinH

**Comment by shorshe** [comment]
Thanks!
And great News about Sigil 0.9.
