### ISSUE TITLE
Middle click to close tab

### ISSUE THREAD

**Issue by DanRya** [Sigil-Ebook/Sigil#82]
Please implement the following behaviour which is common in web browsers and many other applications.

When using the middle mouse button and clicking on an open tab then close the tab. If it helps I'm running Windows 8 x64.

Many thanks for your fantastic software. I use it for my work (and have made a small donation* in the past due to how useful it is!)

*Please note I'm not mentioning this to get any preferential treatment. I understand if you don't have the time / don't feel this is worth doing. Would just be quite handy!

**Comment by kevinhendricks** [comment]
This is not standard behaviour on all browsers or even all software that uses tabs (especially on Mac OS X) but I can see its usefulness.  That said this really should be a Qt feature request. And I think it already is.  Perhaps a future release of Qt will include it out of the box.

**Comment by DanRya** [comment]
Ah that makes a lot of sense. I didn't realise it was a missing feature of
the UI framework. I thought it might have just been an option for you to
configure, but since it isn't it certainly doesn't make sense to hack
something in like you say.

Thanks for taking a look and explaining!

**Comment by phineas-pta** [comment]
hi @kevinhendricks, is the middle click supported in qt yet ? it's already 2026 i think it should be

**Comment by kevinhendricks** [comment]
If it is, that shortcut would naturally be part of Sigil since we automatically get Qt's built-in shortcuts.  So try it on Sigil 2.8.0.  But again, using a middle click button to close tabs is certainly not a thing on MacOX and possibly other platforms.  And since Qt is a cross-platform app, they may not have put much emphasis on that feature request.

**Comment by phineas-pta** [comment]
i tested on windows and it doesnt work

but i'm not sure if that feature is something built into qt

should it be a feature to be implemented in each app ?

in case u dont want to do it, it's totally understandable

**Comment by kevinhendricks** [comment]
Qt includes the built-in shortcuts for most things in Sigil but closing a Tab is just obviously not one of them if you tried it and it did not work.    There is already a keyboard shortcut and of course the close button on the tab itself.  So it is certainly not high priority for Qt or Sigil.  Sorry.
