### ISSUE TITLE
Insert Split Marker adds two markers

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#83]
"Insert -> Split marker" and "Ctrl+Shift+Return" both insert two markers instead of the expected one marker.

OS: Windows 7 SP1 64-bit
Sigil-0.8.7-Windows-x64-Setup.exe. Build version 2015.06.15 04:45:21 UTC

**Comment by mrprobert** [comment]
The error seems to only happen in a newly created document.

**Comment by kevinhendricks** [comment]
I just tried this and can not recreate this at all.  If I insert a split marker I get just one of the expected <hr> rules.  Does Sigil 0.8.6 exhibit the same issue on your platform?

**Comment by mrprobert** [comment]
I have not seen the issue on 0.8.6 with which I edited several hundred
ebooks. I just did an uninstall of 0.8.7 and installed 0.8.6 64-bit and
could not repeat the issue. I reinstalled 0.8.7 64-bit and the issue
returned.

Next I did another uninstall and installed 0.8.7 32-bit on my 64-bit
Windows box and the issue was again present.

My installed VC++ libraries:

[image: Inline image 1]

**Comment by kevinhendricks** [comment]
Thanks for confirming that.  This is just a symptom of the same change that disabled the italics, subscript, etc gui buttons.
A fix for this has already been comitted to master.  Please revert to Sigil 0.8.6 until a new release build is made.  There were no other functional  changes from 0.8.6 to 0.8.7.

Thanks for the bug report.
