### ISSUE TITLE
Edit tools ERROR

### ISSUE THREAD

**Issue by openiurismx** [Sigil-Ebook/Sigil#84]
[version sigil .0.8.7] bold, italic, sub, sup do not work properly, why?

When I write and select the text, I start to edit the text but does not change any element aforementioned

**Comment by kevinhendricks** [comment]
Which platform?  User-none quickly produced Sigil 0.8.7 but with a new version of the clang compiler on Mac OS X, and this has changed things on that platform.  I strongly recommend sticking with Sigil 0.8.6 until I release a new version.  No other changes were made from Sigil 0.8.6 to Sigil 0.8.7.

**Comment by kevinhendricks** [comment]
Yes, revert to Sigil 0.8.6.  A change to workaround a compiler optimization issue is the culprit.  This is now fixed in master.
