### ISSUE TITLE
Windows 8.1: high contrast theme is incorrectly applied

### ISSUE THREAD

**Issue by HenningJW** [Sigil-Ebook/Sigil#86]
Hello,
when using the high contrast theme on Windows 8.1 the background and the text colour of the WYSIWYG preview is black. You can only see the text when selecting it. The HTML view is better due to syntax highlighting, but not without errors.

I attached pictures for clarity:

![image](https://cloud.githubusercontent.com/assets/12969339/8655238/281ff68a-2990-11e5-9f37-f2a300d2e715.png)

![image](https://cloud.githubusercontent.com/assets/12969339/8655246/356a6aaa-2990-11e5-8fb2-53ae2f46eab1.png)

**Comment by kevinhendricks** [comment]
Hi,

Thank you for your bug report.  As a work around, have you thought about adding the proper css to your document to set the background colour and font colour.

Kevin

**Comment by HenningJW** [comment]
I was just trying out themes, so this doesn't affect me anymore, but thanks for caring. There seems to be some added work for those dark themes in lots of tools, Eclipse sends out a message if you set the high contrast theme and wants to restars itself and both these programs were not the only ones with problems afaik.

**Comment by kevinhendricks** [comment]
Hi,

Understood.  You can actually set the background and foreground colours and text colours fore CodeView by using Sigil->Preferences->Appearance.  And of course you can use css to control pretty much anything inside BookView and Preview.  That said, this might be more a Qt issue as Qt webkit is used as the viewer for both BookView and Preview.  It must have default setting that can be configured.

I am going to keep this bug open as a reminder for me to look more into this.  Right now almost all of my time is spent on getting Sigil to work and play nice with epub3 without giving up on epub2.

Thanks again for your bug report.

Kevin

**Comment by kevinhendricks** [comment]
I have looked at this and the author of the ebook (ie. you) can control exactly what fonts are used for display inside the ebook itself and what if any colours are chosen for foreground and background of text.  So I am not sure how this is a Sigil issue.  Sigil is not an ebook reader.  It is an ebook editor.    If you are editing your e-book and want to control those colours in Preview and Codeview you can do so with css.  If you want to control them for CodeView, we have preference settings.

**Comment by HenningJW** [comment]
The problem is when there are no colours set in the epub (like in my case), Sigil uses black for the text and system colours for the background in the preview. In my opinion this is inconsistent and a issue of Sigil. Editing the colour of the font inside the epub (that will probably make it useless on most eink readers) shouldn't be a workaround.

But again, this affects probably a very small minority of users and might even be a QT problem.
