### ISSUE TITLE
Entering Unicode chars with keyboard

### ISSUE THREAD

**Issue by celiapgt** [Sigil-Ebook/Sigil#89]
I'm using Sigil since a long time ago. I'm very happy and greatful for it.

I respectfully ask for a feature: to insert Unicode characters using the keyboard, not the Special codes palette (which inserts entities, by the way, I know). It will be easier to enter many more characters this way.

**Comment by dougmassay** [comment]
The entering of unicode characters via keyboard shortcuts (or directly for keyboards that support it) is already supported. With the exception of the non-breaking space character (and maybe a few of the unicode space variants), no entities need to be used if you don't want to use them.
