### ISSUE TITLE
File already exists dialog with "keep decision" button

### ISSUE THREAD

**Issue by JulesDoe** [Sigil-Ebook/Sigil#99]
I often replace multiple images at once in E-Pub files. It would be a nice feature if the alert box would give me an option to keep my decision to replace the image for the following images.
chears

**Comment by kevinhendricks** [comment]
Just added buttons YesToAll and NoToAll to this dialog.  Sorry it took so long but we have been very very busy with getting Sigil to 1.0 state and after and this was very low priority.
This change will appear in the next release.

**Comment by JulesDoe** [comment]
hahaha totaly fine with me :D i changed Jobs years ago.
Thank you for your awesome work though (and all the others contributors of course). Without Sigil it would have been souch a pain to create Epubs. I hope for you all this ecosystem got a little more consistent by now...
